### ISSUE TITLE
Colab 7_SAC_minitaur_tutorial.ipynb "NameError: name 'video' is not defined"

### ISSUE THREAD

**Issue by ivarsg** [tensorflow/agents#101]
Hi,

It looks like the code in the last cell mises a code-line like "with imageio.get_writer(video_filename, fps=60) as video:", since "video.append_data(eval_py_env.render())" ends with "NameError: name 'video' is not defined".

**Comment by oars** [comment]
Thanks! I'll submit a fix today. Video generation is different internally for us and I missed that in last minute changes.
