### ISSUE TITLE
value_pred_loss_coef

### ISSUE THREAD

**Issue by mattinjersey** [tensorflow/agents#102]
I reduced this value value_pred_loss_coef because in Tensorboard, the value_estimation_loss was much higher than policy_loss.
But even though I reduced it, the value_estimation_loss did not change.
Using PPOAgent.
?

**Comment by mattinjersey** [comment]
no I see, it is my mistake.  I did not change the parameter in the right place in the code.

**Comment by mattinjersey** [comment]
is it recommended to change this value_pred_loss_coef so that the value loss is comparable to the policy loss?

**Comment by sguada** [comment]
The specific tuning of parameters is problem specific. PPO requires careful tuning of parameters.

After changing the `value_pred_loss_coef` the  `value_estimation_loss` should change too. If you are not seeing changes, let us know
