### ISSUE TITLE
Proper way to write action space

### ISSUE THREAD

**Issue by evanatyourservice** [tensorflow/agents#105]
Hello,

I am wanting to code a continuous action space that has two elements but can't seem to get it working. What would be the proper way to write this action space?

A couple examples of what I've tried:

`self._action_spec = [array_spec.BoundedArraySpec(shape=(1,), dtype=np.float32,
                                                       minimum=-1, maximum=2,
                                                       name='action'),
                           array_spec.BoundedArraySpec(shape=(1,), dtype=np.float32,
                                                       minimum=0.0002, maximum=1,
                                                       name='action')]`

`self._action_spec = array_spec.BoundedArraySpec(shape=(2,), dtype=np.float32,
                                                       minimum=np.array([-1.0, 0.0002]), maximum=np.array([2.0, 1.0]),
                                                       name='action')`

Thank you,
Evan

**Comment by evanatyourservice** [comment]
Ah after a second look it seems the top one will indeed work, but I was trying to use it in the DQN example.

**Comment by sguada** [comment]
Yeah DQN requires discrete action spaces, you could use [ActionDiscretizeWrapper](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/wrappers.py#L197) if you want to use an environment with continuous actions with DQN

**Comment by evanatyourservice** [comment]
Thanks sguada
