### ISSUE TITLE
Can't run examples without getting errors. What TF versions are we to use?

### ISSUE THREAD

**Issue by jarlva** [tensorflow/agents#119]
Running  `tf_agents/agents/dqn/examples/v1/train_eval_gym.py` spits all kinds of errors (depending on the TF versions/combo I tried). Since this is a dynamic environment and tensorflow itself is a moving target, as this projects progresses it would be very helpful for everyone to detail in the main project page/install section:  

1. The recommended versions of TF/TB/TFP,
2. Environment: Windows/Linux/Mac, Python versions,
3. Anything else that can smooth the project's adoption

This is a low hanging fruit that can save everyone many frustrating hours..

I tried TF2-nightly, TF-nightly, TF (1.13.1). Running on Windows10 , Ubuntu 18.04, Python 3.6.8.

**Comment by tagomatech** [comment]
Did you try out with [tf-agents-nightly](https://github.com/tensorflow/agents)?

```
# Installing with the `--upgrade` flag ensures you'll get the latest version.
pip install --user --upgrade tf-agents-nightly  # depends on tf-nightly
```

**Comment by jarlva** [comment]
Yap. that what I did

**Comment by tagomatech** [comment]
> I tried TF2-nightly, TF-nightly, TF (1.13.1). Running on Windows10 , Ubuntu 18.04, Python 3.6.8.

Ok you seem to have tested several combinations of library on both Windows and Linux.
Can you provide with the error traceback/error message say for a specific config?

**Comment by jarlva** [comment]
Pardon me but since I tried various versions and each one gave a different error I believe it would be more constructive, not just for me, to first answer the following and take it from there.
1.  The recommended versions of TF/TB/TFP,
2.     Environment: Windows/Linux/Mac, Python versions,
3.     Anything else that can smooth the project's adoption

**Comment by jarlva** [comment]
Can someone please solve the mystery?
What versions of tensorflow and what OS' and Python versions are known to work with agents??
If we can't find this basic information we can't benefit and use the project.

**Comment by oars** [comment]
You need nightly versions. See for example: https://www.endtoend.ai/gsoc/1 where the environment was setup through conda which you should be able to use with any OS.
