### ISSUE TITLE
Is gym.timestep_limit deprecated?

### ISSUE THREAD

**Issue by tagomatech** [tensorflow/agents#122]
I 'm getting the following message while loading a gym environment, e.g. **CartPole-v0**:

```
from tf_agents.environments import suite_gym
env = suite_gym.load('CartPole-v0')


AttributeError                            Traceback (most recent call last)
<ipython-input-2-3d9a4ddbdf04> in <module>
----> 1 env = suite_gym.load('CartPole-v0')

c:\program files\python36\lib\site-packages\gin\config.py in wrapper(*args, **kwargs)
   1030         scope_info = " in scope '{}'".format(scope_str) if scope_str else ''
   1031         err_str = err_str.format(name, fn, scope_info)
-> 1032         utils.augment_exception_message_and_reraise(e, err_str)
   1033 
   1034     return wrapper

c:\program files\python36\lib\site-packages\gin\utils.py in augment_exception_message_and_reraise(exception, message)
     47   if six.PY3:
     48     ExceptionProxy.__qualname__ = type(exception).__qualname__
---> 49     six.raise_from(proxy.with_traceback(exception.__traceback__), None)
     50   else:
     51     six.reraise(proxy, None, sys.exc_info()[2])

c:\program files\python36\lib\site-packages\six.py in raise_from(value, from_value)

c:\program files\python36\lib\site-packages\gin\config.py in wrapper(*args, **kwargs)
   1007 
   1008       try:
-> 1009         return fn(*new_args, **new_kwargs)
   1010       except Exception as e:  # pylint: disable=broad-except
   1011         err_str = ''

c:\program files\python36\lib\site-packages\tf_agents\environments\suite_gym.py in load(environment_name, discount, max_episode_steps, gym_env_wrappers, env_wrappers, spec_dtype_map)
     64   gym_env = gym_spec.make()
     65 
---> 66   if max_episode_steps is None and gym_spec.timestep_limit is not None:
     67   #if max_episode_steps is None:
     68     max_episode_steps = gym_spec.max_episode_steps

AttributeError: 'EnvSpec' object has no attribute 'timestep_limit'
  In call to configurable 'load' (<function load at 0x000001BA9A44A488>)
```

Looking into gym library code, I couldn't find anything related to  **max_episode_steps**.

Now, simply replacing:

`if max_episode_steps is None and gym_spec.timestep_limit is not None:`

with:

`if max_episode_steps is None:`

in  **tf_agents\environments\suite_gym.py** does the trick. But at this stage, I'm not sure of all the consequences of discarding **timestep_limit**.

Can you please throw the light on this for me?

Thank you.

(Windows10, TF2.0.0-dev20190518, tf-agents-nightly, gym0.12.4)

**Comment by ageron** [comment]
For what it's worth, I got the same issue, I worked around it by downgrading to gym==0.12.1.

**Comment by julianstastny** [comment]
[Here](https://github.com/openai/gym/blob/master/gym/envs/registration.py) you can find max_episode_steps. I was confused too but found out that they just forgot to include max_episode_steps in the description (which is now fixed).

**Comment by oars** [comment]
Gym updated with https://github.com/tensorflow/agents/commit/96e7b31d71023217ffe9e7febff2ef2c5db88513 which should fix this.

**Comment by mariuhbr** [comment]
> For what it's worth, I got the same issue, I worked around it by downgrading to gym==0.12.1.

thanks, this solved my problem.
