### ISSUE TITLE
How to seed environments belonging to a ParallelPyEnvironment

### ISSUE THREAD

**Issue by diegoferigo** [tensorflow/agents#126]
I am able to seed a `PyEnvironment` as follows:

```python
seed = 42
env = suite_gym.load("CartPole-v1", max_episode_steps=500)
env.wrapped_env().gym.seed(seed)
```

However, I didn't find a way to do the same with a `ParallelPyEnvironment`. With all the inception of envs and wrappers I couldn't find any way to access individually the environments instantiated which are part of the parallel batch.

**Comment by oars** [comment]
The issue is that the parallel_py_environment is not exposing a seed method.

Adding something like:

```
  def seed(self, seeds):                                                        
    if len(seeds) != len(self._envs):                                           
      raise ValueError(                                                         
          'Number of seeds should match the number of parallel_envs.')          
                                                                                
    promises = [env.call('seed', seed) for seed, env in zip(seeds, self._envs)] 
    # Block until all envs are seeded.                                          
    return [promise() for promise in promises]
```

to the parallel_py_env will make the seed method work. Note `seed` is not currently a method in the base py env. so we'll have to add that too.

**Comment by diegoferigo** [comment]
@oars Exactly, the current APIs was not covering this usage. Having a seed method as you proposed is a valid solution. Thanks for taking care of it :+1:
