### ISSUE TITLE
Update TFUniformReplayBuffer to use TF2.0

### ISSUE THREAD

**Issue by zh4ngx** [tensorflow/agents#128]
I believe the TF2.0 Alpha API (that the TF Agents nightly is targeting) does not have `tf.math.mod()`. Therefore, a line like this would break:

```python
                    rows_to_get = tf.math.mod(ids, self._capacity)
```

It should be a relatively small fix:
```python
                    rows_to_get = tf.mod(ids, self._capacity)
```

Happy to do it and submit a PR

**Comment by oars** [comment]
`tf.math.mod` is available in TF2.0. See the aliases for floormod:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/floormod

We run all our tests against both tf-nightly and the preview builds.
