### ISSUE TITLE
Custom tf.Environment parallelization

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#129]
Hello Team, 
is it possible to parallelize custom tf.env ?
In the colabs/examples I found only this lines of code as reference to create parallels environments.

env = parallel_py_environment.ParallelPyEnvironment([env] * num_parallel_environments)
env = tf_py_environment.TFPyEnvironment(env)

but this only applies to py_environments.

**Comment by oars** [comment]
The tf_env generates and takes batched observations/actions, given the nature of TF if you already have a TF env and there are no dependencies between the ops it will parallelize it for you. You will however have to setup your custom tf_env to generate these batches though.
