### ISSUE TITLE
TD3 support for discrete action space

### ISSUE THREAD

**Issue by redknightlois** [tensorflow/agents#132]
I was looking to try the TD3 agent on but the collect policy is being hardcoded to use a Gaussian Distribution, therefore, it won't work.
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/td3/td3_agent.py#L147

Error is the following:
```
  File "S:\Source\trendstone.git\include\tf_agents\tf_agents\agents\td3\td3_agent.py", line 150, in __init__
    clip=True)
  File "S:\Source\trendstone.git\include\tf_agents\tf_agents\policies\gaussian_policy.py", line 54, in __init__
    tf.nest.map_structure(_validate_action_spec, wrapped_policy.action_spec)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 527, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 527, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "S:\Source\trendstone.git\include\tf_agents\tf_agents\policies\gaussian_policy.py", line 52, in _validate_action_spec
    'Gaussian Noise is applicable only to continuous actions.')
ValueError: Gaussian Noise is applicable only to continuous actions.
```

Shouldn't the exploration policy be supplied as a parameter or as part of an abstract method in order to support discrete actions?

EDIT: I was looking into other agents too and the hardcoding of the exploration policy seems to be a recurring theme, probably a more general approach is necessary. 

EDIT2: Ohh, I see that this version of TD3 does not support discrete action space at all.

**Comment by sguada** [comment]
TD3 is based on DDPG so it is only intended to work with continuous actions.

**Comment by redknightlois** [comment]
True, algorithms topology is a mess. Technically, either DQN with clipped double-Q learning, delayed policy updates and target policy smoothing (which I've seen in some places being called TD3 too) or TD3 with Wolpertinger based training. Probably  I should change the name of the title of the issue.

**Comment by sguada** [comment]
In our case TD3 is referring this paper "Addressing Function Approximation Error in Actor-Critic Methods" by Fujimoto et al. https://arxiv.org/abs/1802.09477.

Although some ideas can be used in other algorithms.

**Comment by Strateus** [comment]
Is there any other solution for this? I want to use 2 critic and 1 actor network in a stochastic env, to avoid Q-learning overestimation, but cannot find any suitable agent for this.

**Comment by sguada** [comment]
You can build a dedicated agent that has 2 critics and use the TD3 trick to avoid overstimulation, but you cannot directly propagate the gradients from the critics to the actor, unless the actor uses a continuous space, your will need to use re-parametrization tricks.

**Comment by Strateus** [comment]
Thanks, been trying to do it, but cannot understand how and where should i reparameterize.  Modified both TD3Agent and CriticNetwork in different ways, but i am probably getting the idea incorrectly:
1. for TD3Agent i removed two policies, keeping ActorPolicy with int32 spect and clip=True
2. removed add_noise_to_action from critic_loss
3. as i understand CriticNetwork should transform actions through RelaxedOneHotCategorical, but i am failing to understand where and how, getting different errors.

Could you please help with it?

**Comment by Strateus** [comment]
I had a SAC example (here: https://github.com/kengz/SLM-Lab/blob/master/slm_lab/agent/algorithm/sac.py) and still it fails. I added this to `_actions_and_log_probs`:
```
        if reparameterize:
            actions, log_pi = self._gumbel(action_distribution)
        else:
            actions = tf.nest.map_structure(lambda d: d.sample(), action_distribution)
            log_pi = common.log_probability(action_distribution, actions, self.action_spec)
```
where `_gumbel` is:
```
    def _gumbel(self, action_distribution):
        dist = tfp.distributions.RelaxedOneHotCategorical(0.01, logits=action_distribution.logits_parameter())
        return dist.sample(), dist.log_prob(action_distribution.sample())
```
and added this to `actor_loss`:
```
actions, log_pi = self._actions_and_log_probs(time_steps, reparameterize=True)
```

I tried different combinations of parameters (for example i passed actions instead of action distribution), but it was failing with very different reasons (one reason for example was that it did not want to take my action integers). I clearly miss the point of how i can do it, any suggestions?
