### ISSUE TITLE
DQN Tutorial has import errors

### ISSUE THREAD

**Issue by pdenboef** [tensorflow/agents#133]
**Problem**
I cannot run the DQN Tutorial notebook, due to import errors.

**Steps to reproduce**

1. Open `tf-agents/colabs/1_dqn_tutorial.ipynb` in a hosted Colab runtime.
2. Run the first two code cells of the notebook. 

**Further  details**
Here is the error message that I received (Python 3 runtime): 

```bash
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-d94cd7c61173> in <module>()
     13 import tensorflow as tf
     14 
---> 15 from tf_agents.agents.dqn import dqn_agent
     16 from tf_agents.drivers import dynamic_step_driver
     17 from tf_agents.environments import suite_gym

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/absolute_value.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 import tensorflow.compat.v2 as tf
     22 
     23 from tensorflow_probability.python.bijectors import bijector

ModuleNotFoundError: No module named 'tensorflow.compat'
```

**Comment by sguada** [comment]
Can you check your version of TF, currently TF-Agents requires the latest tf-nightly.

**Comment by djbyrne** [comment]
I have a similar problem. I upgraded tensorflow to latest version of tf-night( tf-nightly 1.14.1.dev20190607 )

Now I have a new error

```
 ImportError                               Traceback (most recent call last)
<ipython-input-11-a2d96ed003da> in <module>()
     13 import tensorflow as tf
     14 
---> 15 from tf_agents.agents.dqn import dqn_agent
     16 from tf_agents.drivers import dynamic_step_driver
     17 from tf_agents.environments import suite_gym

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/internal/tensor_tuple.py in <module>()
     22 
     23 from tensorflow.python.framework import composite_tensor  # pylint: disable=g-direct-tensorflow-import
---> 24 from tensorflow.python.framework import type_spec  # pylint: disable=g-direct-tensorflow-import
     25 
     26 

ImportError: cannot import name 'type_spec' 
```

**Comment by pdenboef** [comment]
The version of `tensorflow`is `1.14.1-dev20190607`.

I have tried again after resetting my runtime, now I am getting the following error message:

```bash
ImportErrorTraceback (most recent call last)
<ipython-input-7-d94cd7c61173> in <module>()
     13 import tensorflow as tf
     14 
---> 15 from tf_agents.agents.dqn import dqn_agent
     16 from tf_agents.drivers import dynamic_step_driver
     17 from tf_agents.environments import suite_gym

2 frames
/usr/local/lib/python2.7/dist-packages/tf_agents/trajectories/__init__.py in <module>()
     16 """Trajectories module."""
     17 
---> 18 from tf_agents.trajectories import policy_step
     19 from tf_agents.trajectories import time_step
     20 from tf_agents.trajectories import trajectory

ImportError: cannot import name policy_step
```

**Comment by pdenboef** [comment]
The errors have disappeared with the release of `1.14.1-dev20190608`.

**Comment by MarcTolkmitt** [comment]
It is still not working on a home-pc - we have 2022 now. The old nightly should be real by now and it  is still not working. Why are you forced to use 'Colab' online - which software could be done at home ? This is not the first tutorial that is not taking care of that ...
ImportError                               Traceback (most recent call last)
---> 15 from tf_agents.agents import dqn_agent
18 # TODO(b/130564501): Do not import classes directly, only expose modules.

**Comment by grizzlybearg** [comment]
> It is still not working on a home-pc - we have 2022 now. The old nightly should be real by now and it  is still not working. Why are you forced to use 'Colab' online - which software could be done at home ? This is not the first tutorial that is not taking care of that ...
> ImportError                               Traceback (most recent call last)
> ---> 15 from tf_agents.agents import dqn_agent
> 18 # TODO(b/130564501): Do not import classes directly, only expose modules.

4 years later, problem still exist
