### ISSUE TITLE
Request: Exploration by Random Network Distillation (modified PPO)

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/agents#139]
A gentle request for a TF-Agents implementation of a modified PPO with an exploration bonus - for testing on Montezuma's Revenge.

Paper: [Exploration by Random Network Distillation](https://arxiv.org/abs/1810.12894) - Burda et al (OpenAI, University of Edinburgh).

> "...exploration bonus with the extrinsic rewards we introduce a modification of Proximal Policy Optimization (PPO, Schulman et al. (2017)) that uses two value heads for the two reward streams. This allows the use of different discount rates for the different rewards, and combining episodic and non-episodic returns."

Code (TF 1.x): https://github.com/openai/random-network-distillation/tree/master/policies

**Comment by oars** [comment]
@seungjaeryanlee is working on this as part of a Google Summer of Code project. See his blog for progress: https://www.endtoend.ai/tags/gsoc/

**Comment by robodhruv** [comment]
Is there an update on this? Is it up for release soon / is there an early tested version ready for use?
