### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_agents'

### ISSUE THREAD

**Issue by Bhaney44** [tensorflow/agents#140]
I am trying to run the example test code below:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

from tf_agents.networks import network

class DummyNet(network.Network):
    #Dummy Network for Testing
    def __init__(self, unused_observation_spec, action_spec, name=None):
        super(DummyNet, self).__init__(
                unused_observation_spec, state_space=(), name=name)
        action_spec = tf.nest.flatten(action_spec)[0]
        num_action = action_spec.maximum - action_spec.minimum + 1
        self._layers.append(
                tf.keras.layers.Dense(
                        num_actions,
                        kernel_initializer=tf.compat.v1.initializers.constant([[2, 1],
                                                                               [1, 1]]),
                        bias_intializer=tf.compat.v1.initializers.constant([[1], [1]]),
                        dtype=tf.float32))
    
    def call(self, inputs, unused_step_type=None, network_state=()):
        inputs = tf.cast(inputs, tf.float32)
        for layer in self.layers:
            inputs = layer(inputs)
        return inputs, network_state
```

I downloaded the required dependencies from the command line as described in the [DQN Tutorial](https://colab.research.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/1_dqn_tutorial.ipynb). The code returns the following error:

`ModuleNotFoundError: No module named 'tf_agents'`

In short, I am  not sure why my machine would be unable to locate the tf_agents module. I am running the code from the Idle interpreter. I would appreciate any suggestions on where to look on my hard drive, what dependencies to install, or any general advice on how to proceed.

With thanks,

Brian

**Comment by sguada** [comment]
It seems you don't have TF-Agents installed, try the following
```
pip install tf-agents-nightly
```

**Comment by Bhaney44** [comment]
I re-installed and ran it from the command line and it worked. However, it still doesn't work directly from the interpreter. Thanks for your help.

**Comment by tfboyd** [comment]
Closing as stale.

**Comment by kapilrathore42** [comment]
i have same issue but nothing works

**Comment by Bhaney44** [comment]
Hi @kapilrathore42 I haven't looked at this since June 18, 2019. As I mentioned in my previous post, I had more success running from the command line than in the Idle interpreter. But overall, I never explored Agents or TensorFlow further. The main reason is because there are too many dependencies and updates, which makes it more efficient to simply write code from scratch yourself. Moreover, the TF models are not flexible for fitting to new data. With that said, the programmers at TensorFlow are really great and may be able to offer more specific guidance for running and installing Agents.
