### ISSUE TITLE
Add policy saving to 7_SAC_minitaur_tutorial.ipynb

### ISSUE THREAD

**Issue by hwiedPro** [tensorflow/agents#146]
Hey,
could you please add an example on how to save a policy to the 7_SAC_minitaur_tutorial.ipynb colab?
That would be really nice! Thanks in advance. :)

**Comment by oars** [comment]
Sample code that would need to be integrated:

Training:
```
from tf_agents.policies import policy_saver
saver = policy_saver.PolicySaver(policy, batch_size=None)
...
train
...

saver.save('/tmp/sac/policy_%d' % global_step)
```

Deploy/Eval:
```
saved_policy = tf.compat.v2.saved_model.load('policy_0')
policy_state = saved_policy.get_initial_state(batch_size=3)
time_step = tf_env.reset()
while True:
  policy_step = saved_policy.action(time_step, policy_state)
  policy_state = policy_step.state
  time_step = tf_env.step(policy_step.action)
```

**Comment by hwiedPro** [comment]
Hi,
I integrated it on my fork into the colab and it runs without any errors (35cb6d53a679789440afb79ea5c2d04de0d4f6cc). Unfortunately the policy doesn't return the same results as before saving. Any ideas?
Thanks in advance!

**Comment by oars** [comment]
When you say not the same results, what do you mean? Note that SAC's actions come from a distribution that is sampled everytime the action is generated.

You can add a seed to the saver, along with the `train_step` to verify it is loading correctly:

```
>>> saver = policy_saver.PolicySaver(tf_agent.policy, batch_size=None, train_step=global_step, seed=5)
>>> saved_policy = tf.compat.v2.saved_model.load(saved_policy_path)
>>> policy_state = saved_policy.get_initial_state(batch_size=batch_size)
>>> tf_agent.policy.action(time_step, seed=5)
PolicyStep(action=<tf.Tensor: id=6776823, shape=(1, 8), dtype=float32, numpy=
array([[-0.90369   , -0.25899497, -0.8079079 , -0.49438488,  0.4417963 ,
        -0.6404904 , -0.6801764 , -0.8823163 ]], dtype=float32)>, state=(), info=())

>>> saved_policy.action(time_step)
PolicyStep(action=<tf.Tensor: id=6776842, shape=(1, 8), dtype=float32, numpy=
array([[-0.90369   , -0.25899497, -0.8079079 , -0.49438488,  0.4417963 ,
        -0.6404904 , -0.6801764 , -0.8823163 ]], dtype=float32)>, state=(), info=())
```

**Comment by hwiedPro** [comment]
I generate a video to both policy the one saved and the one loaded. In the first one the robot performs some kind of crawling without falling. In the loaded one the robot falls immediately. I wouldn't expect the robot to do *exactly* the same, but at least to do something similar successful.

I will have a try using the seed, and see if it's just a random nonsense action.
Thanks for your help! :)

**Comment by hwiedPro** [comment]
Ok, I have tried it. Unfortunately nothing changed.
I have pushed the executed notebook to my fork: https://github.com/hwiedDFKI/agents/blob/saving_sac_policy/tf_agents/colabs/7_SAC_minitaur_tutorial-run-through.ipynb
This is the video of the policy after learning:
https://raw.githubusercontent.com/hwiedDFKI/agents/saving_sac_policy/tf_agents/colabs/sac_minitaur.mp4
And this after loading the saved policy:
https://raw.githubusercontent.com/hwiedDFKI/agents/saving_sac_policy/tf_agents/colabs/loaded_sac_minitaur.mp4

**Comment by JCMiles** [comment]
Hi team,
there is any diff in doing this (as mentioned in sac agent tutorial v2),
instead of what you propose here?

    policy_checkpointer = common.Checkpointer(
        ckpt_dir=os.path.join(train_dir, 'policy'),
        policy=eval_policy,
        global_step=global_step)

and what's the purpose of setting batch_size=None while training (makes sense)

    saver = policy_saver.PolicySaver(policy, batch_size=None)

and than using batch_size=3 for Deploy/Eval:

    policy_state = saved_policy.get_initial_state(batch_size=3).

I'm a little bit confused so if  you can clarify what is the best practice here it would be very appreciated.
thx

**Comment by oars** [comment]
@JCMiles Thanks for catching the errand `batch_size=3` the batch size should match that of the environment being evaluated.

The `batch_size` used when saving is used in the tracing of the tf_function.

@hwiedDFKI The other thing I noticed thankes to JCMiles's comment, in the colab I believe you are comparing the eval_policy to the agent's regular policy. Note that the eval_policy is Greedy. You could change the policy_saver initialization to save the eval_policy instead. I think it should give you the correct behavior then.

**Comment by JCMiles** [comment]
thx @Oars for the clarification regarding the  batch_size now everything's clear.
One last thing, can you confirm please that calling

    saver = common.Checkpointer(
        policy=agent.policy,
        batch_size=env.batch_size)

is equal to 

    saver = policy_saver.PolicySaver(agent.policy, batch_size=env.batch_size)

thx

**Comment by oars** [comment]
@JCMiles  sorry, forgot to go into details on the difference. They are two different interfaces that create different types of "checkpoints".

Checkpointer uses [tf.train.Checkpoint](https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint) which will save any object attributes that are trackable. In order to restore the checkpoint you must first recreate the Checkpointable object with the same attributes, and the state in those will be restored when the checkpoint is loaded. This works and is useful for situations where you for example want to restore and continue training, but has the downside that you need to recreate the whole agent before you can load the checkpoint. 

The PolicySaver on the other hand exports a [SavedModel](https://www.tensorflow.org/beta/guide/saved_model) of the policy only exposing the action method. This saved model can be loaded directly without requiring any knowledge of what kind of policy or from which agent the saved policy came from. This is really useful when you have to deploy or serve policies.

**Comment by JCMiles** [comment]
and that's exactly what I was expecting.
Thx @oars for the quickly and coincisive response and also for the great work you are doing guys.

**Comment by hwiedPro** [comment]
Hi guys,
thanks for your replies. 

**Regarding the eval_policy thing:**
I generate the video of the current policy by using `action_step = tf_agent.policy.action(time_step, seed=seed)` and for the evaluation video of the loaded policy I use `policy_step = saved_policy.action(time_step, policy_state)` while I configured the `saver` with `saver = policy_saver.PolicySaver(eval_policy, batch_size=None, seed=seed)`. The eval_policy is no where around, it's only used during training in `compute_avg_return(...)`.
Or does `GreedyPolicy()` in  `eval_policy = greedy_policy.GreedyPolicy(tf_agent.policy)` influence `tf_agent.policy` as well?

**Regarding the Checkpoint, SavedModel thing:**
If I want to resume training a saved model, I guess I have to use the Checkpointer, correct?

**Comment by JCMiles** [comment]
@oars I came across this error while trying to save my policy as discussed before.

I'm runnning a SAC agent so my save step looks like:

     policy_saver.PolicySaver(agent.policy, batch_size=1, seed=None)

  File "C:\Users\shock\Desktop\workspace\TestAgent\core\model.py", line 441, in evaluate
    save_dir, 'PolicyCheckpoint.%d' % global_step))
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tf_agents\policies\policy_saver.py", line 279, in save
    self._policy, export_dir, signatures=self._signatures)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tensorflow\python\saved_model\save.py", line 849, in save
    saveable_view, asset_info.asset_index)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tensorflow\python\saved_model\save.py", line 604, in _serialize_object_graph
    _write_object_proto(obj, obj_proto, asset_file_def_index)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tensorflow\python\saved_model\save.py", line 643, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2198, in _tracking_metadata
    return json.dumps(metadata, default=serialization.get_json_type)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\shock\Anaconda3\envs\agent-dev\lib\site-packages\tensorflow\python\util\serialization.py", line 70, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', tf.float32)

**Comment by kbanoop** [comment]
We are planning to add a colab for policy saving, so I'm closing this issue in favor of #186.

I'll add a reference to this from #186.
