### ISSUE TITLE
TF Agents & Dopamine

### ISSUE THREAD

**Issue by abdel** [tensorflow/agents#15]
There seems to be a lot of overlap between objectives of TF Agents and the [Dopamine framework](https://github.com/google/dopamine), are there any plans to share or combine these frameworks, or are they intentionally made separate?

**Comment by alaterre** [comment]
I agree with @abdel, it seems that Dopamine and TF-Agent strongly overlap. Although dopamine aims at being used for fast prototyping and benchmarking as the reproducibility has been put at the core of the project, whereas TF-Agent would be more used for production-level reinforcement learning algorithms. I would love seeing the two frameworks merging or at least having strong compatibilities to facilitate the move from prototyping to production-level code.

**Comment by ebrevdo** [comment]
@psc-g fyi; we could have a discussion about this as a long term goal.

**Comment by psc-g** [comment]
yeah, i think this would be a great thing to have. i imagine the use-case
would almost exclusively be dopamine -> tf-agents, so we could focus on
that without necessarily worrying about supporting the tf-agents ->
dopamine direction.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if we need to track this actively or if you have further questions.
