### ISSUE TITLE
Error in environment validation

### ISSUE THREAD

**Issue by marconardelli** [tensorflow/agents#152]
Hi, I have defined the following BoundedArraySpec for my actions:

`self._action_spec = array_spec.BoundedArraySpec(shape=(1, 3), dtype=np.int32, minimum=[1, 1, 0], maximum=[ord_rows, max(vend_rows, mach_rows), 1])`

When I try to validate the environment, the validation process return the following error:

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

this is raised because in array_spec.py there is a function sample_bounded_spec() that has the following check on line 61.

```
    if high < tf_dtype.max:
      high = high + 1  # pylint: disable=g-no-augmented-assignment
```
I don't know if I'm doing something wrong or there is a bug there.

**Comment by oars** [comment]
Issue is in the array_spec sampling.
