### ISSUE TITLE
Using TF-agents as a dependency

### ISSUE THREAD

**Issue by alexlee-gk** [tensorflow/agents#153]
I have a project that uses the TF-agents library: [SLAC](https://arxiv.org/abs/1907.00953). We have been using our own fork, but we would like to refactor our implementation to a separate repo and use TF-agents as an external dependency. What's the recommended way to use TF-agents as a dependency and keep up with any breaking changes? Are there guidelines or a mailing list for this?

**Comment by sguada** [comment]
Probably the easiest is to add tf-agents-nightly as a python requirement until the tf-agents stable version is out.

**Comment by alexlee-gk** [comment]
Thanks Sergio!
