### ISSUE TITLE
train_eval.py for PPO is stuck

### ISSUE THREAD

**Issue by pratham751** [tensorflow/agents#154]
So I start train_eval.py from my anaconda console with this command:

`python train_eval.py --root_dir=E:\Github\agents\tf_agents\agents\ppo\examples\v1\HalfCheetah-v2 --alsologtostderr`

Then the program starts to run and shows some messages:
`W0703 21:50:25.094830 39804 deprecation.py:506] From E:\Application\Anaconda\envs\tens_agent\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1624: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[2019-07-03 21:50:25,094] From E:\Application\Anaconda\envs\tens_agent\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1624: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
I0703 21:50:25.103328 39804 parallel_py_environment.py:81] Spawning all processes.
[2019-07-03 21:50:25,103] Spawning all processes.`

After this, the program doesn't output anything and also when I look at the task manager, it shows that both the GPUs are free and the CPU is not running on its max capacity as well, like 10% utilization.

So I stop running the program with Ctrl+C and it shows me this message:

`forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01113B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF402656FD  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF406D4034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF432A3691  Unknown               Unknown  Unknown
Traceback (most recent call last):
  File "E:\Application\Anaconda\envs\tens_agent\lib\multiprocessing\spawn.py", line 113, in _main
    preparation_data = reduction.pickle.load(from_parent)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Application\Anaconda\envs\tens_agent\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Application\Anaconda\envs\tens_agent\lib\multiprocessing\spawn.py", line 113, in _main
    preparation_data = reduction.pickle.load(from_parent)
KeyboardInterrupt`

Now, I think this is because I am using this on tensorflow 1 not 2.0 but if tensroflow 2.0 was necessary, wouldn't it give me an error because I don't have that installed??

Thank you for reading my issue.

**Comment by ichisadashioko** [comment]
I suggest that you should switch to a Ubuntu (Linux) machine because I saw this instruction in the script:

```bash
tensorboard --logdir $HOME/tmp/ppo_v1/gym/HalfCheetah-v2/ --port 2223 &

python tf_agents/agents/ppo/examples/v1/train_eval.py \
  --root_dir=$HOME/tmp/ppo_v1/gym/HalfCheetah-v2/ \
  --alsologtostderr
```

**Comment by pratham751** [comment]
Ohh thanks for the suggestion but I think it will take a lot of time to install that

**Comment by sguada** [comment]
Try running replacing `parallel_py_environment.ParallelPyEnvironment` with `batched_py_environment.BatchedPyEnvironment` to avoid using multi-process and use multi-thread instead. Although it would be slower.

**Comment by pratham751** [comment]
Thank you for that will definitely give that a try

**Comment by kbanoop** [comment]
Closing this, please reopen if it's still an issue.
