### ISSUE TITLE
SAC should only apply gradients to trainable variables

### ISSUE THREAD

**Issue by pyetras** [tensorflow/agents#158]
During SAC optimisation step gradients are being applied to all variables instead of just trainable variables. This causes undesirable behaviour if the nets contain a shared encoder layer with fixed weights - a use case suggested in [Learning to drive in a day](https://arxiv.org/abs/1807.00412) article.

**Comment by kuanghuei** [comment]
Thanks for raising this! It looks like this issue exists in a few of the agents. We have fixed it in SAC. Feel free to comment again or reopen if you have further questions.

**Comment by sguada** [comment]
@kuanghuei next time write in the description of the fix, so it would marked as fixed.
Fixes #158
