### ISSUE TITLE
tf-agents-nightly not automatically updated nightly

### ISSUE THREAD

**Issue by andreas-repp** [tensorflow/agents#159]
In the readme of this project it states that you should install the tf-agents-nightly pip package. However, this package is not updated nightly, as the name suggests, but seems to be totally outdated (last updated on May 28th 2019). 

Why is the nightly package not updated nightly? If there is a reason for it, please, at least highlight it in the readme.

I just spent hours searching a bug in tf_agents that was fixed months ago, simply because I assumed the repository code would be in the nightly package.

**Comment by sguada** [comment]
Sorry for the troubles, we are having some issues with the automatic push of pip packages.
I just pushed a new nightly version up to date. Let me know if you have any further problems.
Will update this issue as soon as we fix the automatic pushes.

**Comment by andreas-repp** [comment]
@sguada: Many thanks for the fast response!

**Comment by andreas-repp** [comment]
@sguada: From looking at the releases on pypi, it looks like you guys fixed this one. Therefore, I think this issue is resolved.
