### ISSUE TITLE
Correct way of setting Atari environment for PPO?

### ISSUE THREAD

**Issue by seungjaeryanlee** [tensorflow/agents#160]
What is the correct way to set an Atari environment for TF-Agents?

I am trying to run PPO on Venture, and this is the setup I am using currently:
```python
env_name = "VentureNoFrameskip-v0"
eval_tf_env = tf_py_environment.TFPyEnvironment(env_load_fn(env_name, gym_env_wrappers=(FrameStack4, AtariPreprocessing)))
    tf_env = tf_py_environment.TFPyEnvironment(
        parallel_py_environment.ParallelPyEnvironment(
            [lambda: env_load_fn(env_name, gym_env_wrappers=(FrameStack4, AtariPreprocessing))] * num_parallel_environments))
```

Am I missing some environment wrappers or using the wrong variant?

**Comment by andreas-repp** [comment]
I use the following and it seems to work (still in training):

I call the `train_eval` method of the [PPO v2 example](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py) with the following parameters:

```
def main(_):
	tf.compat.v1.enable_v2_behavior()
	logging.set_verbosity(logging.INFO)

	train_eval(
		root_dir=FLAGS.root_dir,
		env_name=FLAGS.env_name,
		env_load_fn=suite_atari.load)
```

**Comment by seungjaeryanlee** [comment]
@andreas-eberle Oh didn't know `suite_atari` existed. Thank you :D

What did you set `FLAGS.env_name` to? Curious which mode ('', 'NoFrameskip', 'Deterministic') and version ('v0', 'v4') you are using.

**Comment by andreas-repp** [comment]
As of yet, I only used "Pong-v0" and "Breakout-v0". However, the other Atari games should (hopefully ;) ) behave the same.

**Comment by seungjaeryanlee** [comment]
I see. My agents are stuck in initialization when I use 'v4' version, so I was wondering if the issue was on me or in the repo.

**Comment by oars** [comment]
Do the v0 ones work for you?

**Comment by seungjaeryanlee** [comment]
@oars They do! `Venture-v0`, `VentureNoFrameskip-v0`, `VentureDeterministic-v0` all work for me.

**Comment by sguada** [comment]
I would recommend trying
```
tf_env = suite_atari.load(
          env_name,
          max_episode_steps=max_episode_frames / ATARI_FRAME_SKIP,
          gym_env_wrappers=suite_atari.DEFAULT_ATARI_GYM_WRAPPERS_WITH_STACKING)
```

**Comment by seungjaeryanlee** [comment]
@sguada Thank you for the suggestion!

Just to make sure, am I correct that TF-Agents currently does not have a wrapper that normalizes observation to be from [0, 255] to [0,1]?

**Comment by seungjaeryanlee** [comment]
Quoting @oars from https://github.com/seungjaeryanlee/agents/pull/9:

> v4 envs are registered with max_episode_steps = 100000 which is 10x v0, this means it will take a long time to finish the episodes. Also the replay buffer capacity required goes up by 10x

This seems like the reason! Thank you.

**Comment by andreas-repp** [comment]
@seungjaeryanlee: TF-Agents' PPO has a `normalize_observations` parameter, which defaults to true. Therefore, the observations are normalized with a `StreamingTensorNormalizer` by default. So they should be normalized with mean and std.

**Comment by sguada** [comment]
For DQN Instead of normalizing the observations from [0, 255] to [0.0, 1.0] in the environment we do it in the [Network](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v1/train_eval_atari.py#L115), this avoid storing float32 (4 bytes) instead of unit8 (1 byte) in the replay buffer.
PPO does its own observation normalization.

**Comment by seungjaeryanlee** [comment]
@andreas-eberle @sguada Thank you for the reply! I am trying to implement Random Network Distillation which does both the divide-by-255 and streaming normalization, so it looks like I will have to implement the former.
