### ISSUE TITLE
ImageData' object has no attribute 'data'

### ISSUE THREAD

**Issue by dp6000** [tensorflow/agents#163]
I ran the colab tutorial, '1_dqn_tutorial.ipynb' without making any changes. When running the code, 

env.reset()
PIL.Image.fromarray(env.render())

The following error is reported:

AttributeErrorTraceback (most recent call last)
<ipython-input-6-4ef82062fab5> in <module>()
      1 env.reset()
----> 2 PIL.Image.fromarray(env.render())

3 frames
/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.pyc in render(self, return_rgb_array)
     94             buffer = pyglet.image.get_buffer_manager().get_color_buffer()
     95             image_data = buffer.get_image_data()
---> 96             arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
AttributeErrorTraceback (most recent call last)
<ipython-input-6-4ef82062fab5> in <module>()
      1 env.reset()
----> 2 PIL.Image.fromarray(env.render())

3 frames
/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.pyc in render(self, return_rgb_array)
     94             buffer = pyglet.image.get_buffer_manager().get_color_buffer()
     95             image_data = buffer.get_image_data()
---> 96             arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
     97             # In https://github.com/openai/gym-http-api/issues/2, we
     98             # discovered that someone using Xmonad on Arch was having

**AttributeError: 'ImageData' object has no attribute 'data'**

**Comment by kuanghuei** [comment]
It looks like a recent release of pyglet breaks gym. I downgraded pyglet to 1.3.2 for the colabs, and it should work now.

Thanks.
