### ISSUE TITLE
Reward Normalizer not updated in PPO?

### ISSUE THREAD

**Issue by seungjaeryanlee** [tensorflow/agents#164]
In `PPOAgent`, it seems like when observation is normalized, the reward normalizer is never updated. Is there a reason behind this?

```python
    if self._observation_normalizer:
      self._observation_normalizer.update(
          time_steps.observation, outer_dims=[0, 1])
    else:
      # TODO(b/127661780): Verify performance of reward_normalizer when obs are
      #                    not normalized
      if self._reward_normalizer:
        self._reward_normalizer.update(next_time_steps.reward,
                                       outer_dims=[0, 1])
```

For reference, [here is the link to the full code.](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/ppo_agent.py#L565)

**Comment by sguada** [comment]
It seems we still have to verify that the reward_normalization performs well when there is no observation normalization.

**Comment by tfboyd** [comment]
This bug is no longer listed in the code. It may still exist. I only searched to see if the bug number existed in the code.  Closing issue as stale.
