### ISSUE TITLE
trouble converting a custom PyEnvironment into TFPyEnvironment

### ISSUE THREAD

**Issue by basvanopheusden** [tensorflow/agents#165]
I'm having trouble converting a custom PyEnvironment into a TFPyEnvironment. My environment has observations consisting of a list of 2 matrices, each 20x5 (one non-negative, the other unconstrained), which I specify like this:

`self._observation_spec = [array_spec.ArraySpec(shape=(20,5), dtype=np.float64,name='observation'),
array_spec.BoundedArraySpec(shape=(20,5), dtype=np.float64, minimum=0, name='observation')]
`

When I create the environment and run `utils.validate_py_environment(env)` it produces no errors or warnings. However, when I convert this environment to a TFPyEnvironment using 

`tf_env = tf_py_environment.TFPyEnvironment(env)`

and run `utils.validate_py_environment(tf_env)`, I do get an error "Given \`time_step\` does not match expected \`time_step_spec\`", which seems to be because `tf_env.reset()` creates a TimeStep with the 2 matrices encoded as 1x20x5 tensors, whereas `tf_env.time_step_spec()` expects 20x5 tensors. 

Any help appreciated!

**Comment by oars** [comment]
The validate tool will only work for the `py_environment`, once you've wrapped it through `tf_py_environment.TFPyEnvironment` it will not work.

If the validation passed on your py env you should be good to go.

Note issue: #161 though be careful with the dtype of your network, consider moving to float32 observations in your env.

Feel free to re-open if you hit issues when using the tf_env for training.

**Comment by basvanopheusden** [comment]
Ok, thanks a lot!
