### ISSUE TITLE
How to use tensor_spec to get embedding

### ISSUE THREAD

**Issue by YankeeLiu** [tensorflow/agents#175]
When i try to build my own network, the input_tensor_spec looks like this
[BoundedTensorSpec(shape=(10,), dtype=tf.int32, name='n_h', minimum=array(0, dtype=int32), maximum=array(2147483647, dtype=int32)), BoundedTensorSpec(shape=(10,), dtype=tf.int32, name='p_h', minimum=array(0, dtype=int32), maximum=array(2147483647, dtype=int32))]
how can i use this to get embedding vector, I tried tf.nn.embedding_lookup(), treated the input_tensor_spec as normal tensor, but tf raised an error said
"TypeError: Failed to convert object of type <class 'tensorflow.python.framework.tensor_spec.BoundedTensorSpec'> to Tensor. Contents: BoundedTensorSpec(shape=(10,), dtype=tf.int32, name='n_h', minimum=array(0, dtype=int32), maximum=array(2147483647, dtype=int32)). Consider casting elements to a supported type."
What should i do?

**Comment by kbanoop** [comment]
You can sample from the spec to generate an appropriately shaped Tensor that you can pass to the network, e.g.  https://github.com/tensorflow/agents/blob/e31a1c6dfb744c688deda7a9024bb19631d5bce0/tf_agents/networks/network.py#L142
