### ISSUE TITLE
DQN tutorial: collect_steps_per_iteration = 1 ? dynamic_step_driver ?

### ISSUE THREAD

**Issue by christianhidber** [tensorflow/agents#178]
Looking at the dqn tutorial I was wondering about the following points:

o collect_steps_per_iteration is set to 1, thus we get only 1 additional step in the replay buffer per iteration (and tf_agent.train call): wouldn't it be more "natural" to have collect_steps_per_iteration set to 100 or 1000 and num_iterations set to a lower value ?

o the replay buffer is filled "manually" using the collect_step function: is there a particular reason for not using dynamic_step_driver ?

**Comment by oars** [comment]
`collect_steps_per_iteration` is set to 1 as it is how it is presented in the original paper, 1 step of collect per training step. I'm not sure what you mean by "natural" but you can definitely collect for example a whole episode, and then train for n steps. Finding hyper-parameters for these values for a given environment can be tricky.

The only reason it is done  manually is to avoid having to introduce too many concepts at once.

**Comment by christianhidber** [comment]
Great. Thank you !
