### ISSUE TITLE
Learning the opposite behavior

### ISSUE THREAD

**Issue by DaveOuds** [tensorflow/agents#182]
I'm creating a training system that, instead of a environment, uses a simulation software.
The agent needs to learn it's behavior depending on the status that the simulation software returns. The statuses are given as an integer (0-4) and are used in a reward determiner (basically a switch case). **The lower the status, the better the behavior (0 best, 4 worst).**

See code below as example.

```
if status == 0: 
  reward += 100
elif status == 1: 
  reward += 100
elif status == 2: 
  reward += 0 
elif status == 3:
  reward -= 5
elif status == 4: 
  reward -= 1000
elif status == 5: 
  reward -= 2000

ts.TimeStep(            
  step_type=tf.convert_to_tensor([type], dtype=np.int32), 
  reward=tf.convert_to_tensor([reward], dtype=np.float32), 
  discount=tf.convert_to_tensor([1.], dtype=np.float32), 
  observation=tf.convert_to_tensor([observation], dtype=np.int32)
)
```

However, this is were things get interesting. The agent seems to be learning the opposite behavior. Meaning that when status 0 gets the most points and status 4 the least (negative rewards even), the agent learns to "acquire" status 4.

When I invert the reward determiner (so status 0 get negative rewards and status 4 positive) it learns the desired behavior.

```
if status == 0:
  reward -= 2000
elif status == 1:
  reward -= 1000
elif status == 2:
  reward -= 5
elif status == 3:
  reward += 0
elif status == 4:
  reward += 100
elif status == 5:
  reward += 100
```
Am I doing something wrong, or is this just how environments are normally implemented?

**Comment by sguada** [comment]
Given this little details is hard to know what is going wrong, I will recommend evaluating a random policy and validate the environment.

**Comment by kbanoop** [comment]
Yes you are right, the agent learns to maximize the reward from the environment, so if your simulator behaves the opposite way, you will have to implement an environment that reverses this.
