### ISSUE TITLE
Untracked object tensor error in PolicySaver.save

### ISSUE THREAD

**Issue by schmittjoh** [tensorflow/agents#183]
After updating to latest versions of tf-nightly-gpu and tf-agents-nightly, it seems like the PolicySaver.save method is not working anymore.

It now raises the following error:

```
AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_28:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```

This might be similar to tensorflow/tensorflow#31300.

**Comment by oars** [comment]
Do you have a specific agent's policy where this is happening? Is it with a custom network of yours, or one of the example ones?

**Comment by schmittjoh** [comment]
I'm using the PPO example v2 (https://github.com/tensorflow/agents/blob/bd448c215281e7ffe8ca4b6d472c82425ce03202/tf_agents/agents/ppo/examples/v2/train_eval.py) with use_rnns=True.

**Comment by schmittjoh** [comment]
Some further investigation shows that this error happens when introducing a custom environment where the spaces contains a `gym.spaces.Tuple`, i.e.

```
class MyEnv(gym.Env):
    def __init__(self):
        self.observation_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(700,))
        self.action_space = gym.spaces.Tuple((
            gym.spaces.Discrete(3),
            gym.spaces.Discrete(4),
        ))
```

and updating `train_eval.py` to use the new environment:

```
tf_env = tf_py_environment.TFPyEnvironment(
        parallel_py_environment.ParallelPyEnvironment(
            [lambda: GymWrapper(MyEnv()) for i in range(num_parallel_environments)]))
```

As a workaround it seems to be possible to use a `gym.spaces.Dict` instead:

```
class MyEnv(gym.Env):
    def __init__(self):
        self.observation_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(700,))
        self.action_space = gym.spaces.Dict({
            'a': gym.spaces.Discrete(3),
            'b': gym.spaces.Discrete(4),
        })
```
