### ISSUE TITLE
Reward Assignments After One Epoch

### ISSUE THREAD

**Issue by sawsanq** [tensorflow/agents#185]
I am wondering if I can re-write the reward scores for all steps when one epoch/round is completed (one pass for all words in text). I need to use a reward that cannot be computed unless all decisions are made for all words; then different scores can be assigned for each word. 

Would there be any way to do this using this library?

**Comment by oars** [comment]
You can put in a custom driver and avoid passing data to observers until you've recalculated the rewards. Look at the python driver as it should be easier for you to modify.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if you still need help.
