### ISSUE TITLE
Tutorial request - How does saving work?

### ISSUE THREAD

**Issue by Taxel** [tensorflow/agents#186]
After several different tries of saving and loading my PPO networks and/or policies I have to ask:

What is the intended way of serializing and restoring networks with tf-agents?

What I want to do: 

- Save the complete network so I can resume the training
- Use the actor distribution network to predict an action based on state

What I tried:

- Saving the actor_net and value_net as a SavedModel via the .save() function - I ran into [this issue](https://github.com/tensorflow/agents/issues/136) first, after saving with include_optimizer=False I succeeded in loading, but then could not pass the loaded model to my PPOAgent (because it is not an ActorDistributionNetwork but a SavedModel)
- Saving only the weights via save_weights() - not possible since it is a subclassed model or some other error
- Saving the policy only: This seemed to work at first but when trying to use PolicySaver again after training with the loaded policy, I get `TypeError: policy is not a TFPolicy`. Also, I can't get the prediction to work because the timestamps I create manually from the state do not exactly fit the saved function's parameters (see [this stackoverflow question](https://stackoverflow.com/questions/57565249/loaded-tf-agents-policy-cant-manually-construct-timestep) )

Any of these approaches might be the correct one or maybe I am missing something completely, but after scrolling through the issues here a bit, there seem to be a few about saving and loading, which means to me that this matter is unclear to several other people. Could you please explain the intended way to achieve the top two bullet points to me and in the future incorporate this into one of the colab tutorials so others won't have to struggle with this?

**Comment by Taxel** [comment]
At least for Tensorflow 2.0 I have found a working solution, which is most likely how one is intended to serialize and restore models, as well as predict using an existing model:

**Continuing training**
In order to save the model and continue training, the Tensorflow 2.0 solution is called `Checkpoints`.
So you do not call the `.save()` function on your model, which saves it as a `SavedModel` that can't easily be loaded for further training, but instead do something like this

```
checkpoint = tf.train.Checkpoint(
            actor_net=actor_net, value_net=value_net)
```
To save and restore the model, take a look at [the Checkpoint docs](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/train/Checkpoint)

**Prediction using a trained model**

For prediction you need the `policy` (`eval_policy`). In order to save this, `tf-agents` provides its `PolicySaver` class. 
Example code:
```
# save policy
PolicySaver(eval_policy).save(model_dir + 'eval_policy')
...
# load policy
policy = tf.saved_model.load(model_path)
action = policy.action(timestep)
```

I hope this helps to clear up misunderstandings.
If any of the devs want to close this issue, that's fine. I am leaving it open because the question got several upvotes, which in my eyes would merit a short section about this issue in one of the tutorial colab files.

**Comment by kbanoop** [comment]
Also see #146 and #136

**Comment by mirdones** [comment]
Any news on the colab?
I am training a C51 agent using the c51_tutorial as a base and I would like to save it during training and later use it on production.

**Comment by qw245roar** [comment]
Any updates on this?

**Comment by Strateus** [comment]
I used `save_weights` for each network separately, which worked prior to 2.3 upgrade, but not anymore

**Comment by tfboyd** [comment]
I know a ton of time has passed.  I think the SAC example is very good as far as showing how to save checkpoints. https://github.com/tensorflow/agents/blob/master/tf_agents/experimental/examples/sac/haarnoja18/sac_train_eval.py  I am closing as this issue/questions is stale.  If you come across this issue and are still having an issue with checkpoints please open a new issue with the specific use case and we can take another shot.

**Comment by ghost** [comment]
> I used `save_weights` for each network separately, which worked prior to 2.3 upgrade, but not anymore

Can you explain how that worked for you? I am unable to get the weights for the networks through SavedModel, and not able to use save_weights(), coz the networks are not keras.layers but apparently from the network.Networks class.
