### ISSUE TITLE
Can not develop on case-insensitive file system (Mac OS)

### ISSUE THREAD

**Issue by jurgisp** [tensorflow/agents#187]
I'd like to contribute to TF-Agents, but there is a git problem that I encounter on Mac OS X. There are two files that only differ by case:

- https://github.com/tensorflow/agents/blob/master/tf_agents/docs/python/tf_agents/utils/common/Periodically.md
- https://github.com/tensorflow/agents/blob/master/tf_agents/docs/python/tf_agents/utils/common/periodically.md

Since Mac OS file system is case-insensitive, I get only one of those files on disk, and git is always showing dirty working directory because of the "deleted" other file.

Could we rename one of those files?

**Comment by kbanoop** [comment]
@MarkDaoust is there a way to fix this in the auto doc gen tool?

**Comment by MarkDaoust** [comment]
lots of the tooling relies on file names matching their api path.

Probably the simplest fix would be to move the docs to tensorflow.org, so they're not part of the git checkout.

WDYT?

+@adammichaelwood

**Comment by adammichaelwood** [comment]
Wouldn't that just make them part of a different git checkout?

**Comment by adammichaelwood** [comment]
You're suggesting building the API docs from the source in this repo and not checking them in, but publishing them the same way we do the core docs?

Yes. We should do that.

The reason for the holdup on moving docs to a subsite was a stable release from Agents. I don't mind moving ahead with the subsite ahead of that release, but ultimately that decision is above my pay grade.

**Comment by MarkDaoust** [comment]
> building the API docs from the source in this repo and not checking them in.

Yes, we have it setup so we can do that now.
It wouldl be one way to get this problem solved.

**Comment by tfboyd** [comment]
This happened. Those files are no longer in the github tree.
