### ISSUE TITLE
module 'tensorflow' has no attribute 'TypeSpec'

### ISSUE THREAD

**Issue by marconardelli** [tensorflow/agents#188]
Hello,
I updated to the latest tf-agents code in the morning, and I've got the following error in a previously working project:

the file where the error is returned is time_step.py

   301   first_observation_spec = tf.nest.flatten(observation_spec)[0]
    302   if isinstance(first_observation_spec,
--> 303                 (tf.TypeSpec, tensor_spec.TensorSpec,
    304                  tensor_spec.BoundedTensorSpec)):
    305     return TimeStep(

AttributeError: module 'tensorflow' has no attribute 'TypeSpec'
  In call to configurable 'BatchedPyEnvironment' (<function BatchedPyEnvironment.__init__ at 0x7fbc731d5510>)
  In call to configurable 'TFPyEnvironment' (<function TFPyEnvironment.__init__ at 0x7fbc72a76bf8>)

**Comment by marconardelli** [comment]
Nevermind, tf update solved the issue

**Comment by junhuang-ifast** [comment]
> Nevermind, tf update solved the issue

Hi @marconardelli , may I know which tf version solved this issue?

**Comment by kushantp58** [comment]
can you please let me know which tf version solved this issue.... I'm facing this issue and I did update my tf but it doesn't seem to solve it

**Comment by sunsibar** [comment]
If you are using TF 1, the updated version might be 1.15.0. I got the error with 1.14.?, and updating to 1.15.0 seems to have solved it.
