### ISSUE TITLE
tf.function throws error when used in PP0 TF2.0 GPU example

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#19]
I get the following error  when setting `use_tf_functions = True`  in the PPO v2 example.
This error appears in the line
```
collect_driver.run = common.function(collect_driver.run, autograph=False)
```
with TF2.0 GPU installed with `tf-nightly-gpu-2.0-preview` : 

```
Cannot place the graph because a reference or resource edge connects colocation groups with incompatible assigned
 devices: /job:localhost/replica:0/task:0/device:CPU:0 vs /job:localhost/replica:0/task:0/device:GPU:0. The edge src node is driver_loop/exit/_130 , and the dst node is driver
_loop [Op:__inference_run_5502]
```

**Comment by jrabary** [comment]
Setting `tf.config.set_soft_device_placement(True)` seems to solve this problem.

**Comment by sguada** [comment]
Thanks for the report, if you want to add the `tf.config.set_soft_device_placement(True)` to the example please send a PR.

**Comment by jrabary** [comment]
Finally `tf.config.set_soft_device_placement(True)` doesn't solve this problem!
Maybe, it has to do with the fact that I'm using TFPyEnvironment with parallel_py_environment.

**Comment by ebrevdo** [comment]
Sadly, this issue has gotten quite old. We've moved to using eager mode to collect data by default. But please let me know if this is not obsolete.
