### ISSUE TITLE
Loaded policy can't be used for prediction (TimeStep does not match SavedModel's expected arguments)

### ISSUE THREAD

**Issue by Taxel** [tensorflow/agents#190]
I am saving my PPO policy using 
```
    try:
        PolicySaver(collect_policy).save(model_dir + 'collect_policy')
    except TypeError:
        tf.saved_model.save(collect_policy, model_dir + 'collect_policy')
    try:
        PolicySaver(eval_policy).save(model_dir + 'eval_policy')
    except TypeError:
        tf.saved_model.save(eval_policy, model_dir + 'eval_policy')
```

Now I want to load it again and use a `timestep` I am creating myself to predict using this policy. I have tried it like this:
```
self.policy = tf.saved_model.load(model_dir + 'eval_policy')
state = table.getState()
step_type = tf.convert_to_tensor(
            [0], dtype=tf.int32, name='step_type')
reward= tf.convert_to_tensor(
            [0], dtype=tf.float32, name='reward')
discount= tf.convert_to_tensor(
            [1], dtype=tf.float32, name='discount')
observations= tf.convert_to_tensor(
            [state], dtype=tf.float32, name='observations')
timestep = ts.TimeStep(step_type, reward, discount, observations)

prediction = self.policy.action(timestep)
```
But this leads to the following error, having to do with the timestep:

> Traceback (most recent call last):
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\test_player.py", line 31, in test_ai
>     t.reset()
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\table.py", line 141, in reset
>     return self.runUntilChoice()
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\table.py", line 230, in runUntilChoice
>     ret = self.bettingRoundInterrupted(self.button + 3)
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\table.py", line 341, in bettingRoundInterrupted
>     choice, info = p.decide(self)
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\ai_player.py", line 61, in decide
>     prediction = self.policy.action(timestep)
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 416, in __call__
>     self._initialize(args, kwds, add_initializers_to=initializer_map)
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 359, in _initialize
>     *args, **kwds))
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1360, in _get_concrete_function_internal_garbage_collected
>     graph_function, _, _ = self._maybe_define_function(args, kwargs)
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1648, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1541, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "C:\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py", line 716, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 309, in wrapped_fn
>     return weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "C:\Python37\lib\site-packages\tensorflow\python\saved_model\function_deserialization.py", line 256, in restored_function_body
>     "\n\n".join(signature_descriptions)))
> **ValueError: Could not find matching function to call loaded from the SavedModel. Got:
>    Positional arguments (2 total):
>     * TimeStep(step_type=<tf.Tensor 'time_step:0' shape=(1,) dtype=int32>, reward=<tf.Tensor 'time_step_1:0' shape=(1,) dtype=float32>, discount=<tf.Tensor 'time_step_2:0' shape=(1,) dtype=float32>, observation=<tf.Tensor 'time_step_3:0' shape=(1, 79) dtype=float32>)
>     * ()
>   Keyword arguments: {}**
> 
> Expected these arguments to match one of the following 2 option(s):
> 
> Option 1:
>   Positional arguments (2 total):
>     * TimeStep(step_type=TensorSpec(shape=(None,), dtype=tf.int32, name='time_step/step_type'), reward=TensorSpec(shape=(None,), dtype=tf.float32, name='time_step/reward'), discount=TensorSpec(shape=(None,),
> dtype=tf.float32, name='time_step/discount'), observation=TensorSpec(shape=(None, 79), dtype=tf.float64, name='time_step/observation'))
>     * ()
>   Keyword arguments: {}
> 
> Option 2:
>   Positional arguments (2 total):
>     * TimeStep(step_type=TensorSpec(shape=(None,), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(None,), dtype=tf.float32, name='reward'), discount=TensorSpec(shape=(None,), dtype=tf.float32, name='discount'), observation=TensorSpec(shape=(None, 79), dtype=tf.float64, name='observation'))
>     * ()
>   Keyword arguments: {}

As you can see, there are a few differences between the timestep I am passing to the function and the one it is expecting:

 - The shapes in my tensor look like (1,) while the expected ones are written out as (None, ) -This should match afaik
 - The names are different
 - The function expects TensorSpecs but gets tf.Tensors
 - the dtypes are not as expected: tf.float32 vs float32

How can I fix this to get this prediction to work? Is it correct that I want to use the policy for prediction?

**Comment by Taxel** [comment]
I've played around with the function `TfPyEnvironment._set_names_and_shapes` to see if `TFPyEnvironment` somehow changes the `TimeStep` it returns but to no avail. 
I did, however, find out that I need to pass the `step_type`, `reward`, and `discount` as lists because they need to be arrays with a length equal to the step size 1. I have updated my question above.
Unfortunately, it still does not work. Even though I am setting the tensor names and dtypes manually using `tf.convert_to_tensor()`, the error message does not change -.-

**Comment by sguada** [comment]
TensorSpecs are just specifications of the expected Tensors, so that is correct. It seems the shapes are correct but the dtypes are not.
It seems that when you saved the policy the observations were tf.float64 not tf.float32. Try
`observations= tf.convert_to_tensor(
            [state], dtype=tf.float64, name='observations')`

**Comment by Taxel** [comment]
Thanks, I did not see that I used this dtype incorrectly.
Solved.

**Comment by dalvaren** [comment]
Thank you! I've ran over the same situation and my problem was not setting the values as lists (I was using np.array), so now it is working.
