### ISSUE TITLE
ParallelPyEnvironment fails silently (threads do not start)

### ISSUE THREAD

**Issue by Taxel** [tensorflow/agents#191]
I am trying to execute my custom `PyEnvironment` in parallel, but it does not work.

```
train_env = tf_py_environment.TFPyEnvironment(
    ParallelPyEnvironment(
        [CardGameEnv()] * hparams['parallel_environments']
    )
)
# this works perfectly:
eval_env = tf_py_environment.TFPyEnvironment(CardGameEnv(debug=True))

```
Everything runs smoothly when just wrapping the environment in a `TFPyEnvironment`, but when I use `ParallelPyEnvironment` to instantiate multiple envs, the program stops at the line where it is called indefinitely. When I terminate the program with `CTRL+C`, this is the error message:

> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\train.py", line 229, in <module>
>   File "<string>", line 1, in <module>
>     train(model_num=3)
>   File "C:\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
>   File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\poker_logic\train.py", line 64, in train
>     [CardGameEnv()] * hparams['parallel_environments']
>     exitcode = _main(fd)
>   File "E:\Users\tmp\AppData\Roaming\Python\Python37\site-packages\gin\config.py", line 1009, in wrapper
>   File "C:\Python37\lib\multiprocessing\spawn.py", line 113, in _main
>     preparation_data = reduction.pickle.load(from_parent)
> KeyboardInterrupt
>     return fn(*new_args, **new_kwargs)
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 70, in __init__
>     self.start()
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 83, in start
>     env.start(wait_to_start=self._start_serially)
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 223, in start
>     self._process.start()
>   File "C:\Python37\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Python37\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Python37\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 264, in __getattr__
>     return self._receive()
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 333, in _receive
>     message, payload = self._conn.recv()
>   File "C:\Python37\lib\multiprocessing\connection.py", line 250, in recv
>     buf = self._recv_bytes()
>   File "C:\Python37\lib\multiprocessing\connection.py", line 306, in _recv_bytes
>     [ov.event], False, INFINITE)
> KeyboardInterrupt
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 289, in close
>     self._process.join(5)
>   File "C:\Python37\lib\multiprocessing\process.py", line 139, in join
>     assert self._popen is not None, 'can only join a started process'
> AssertionError: can only join a started process

Am I using ParallelPyEnvironment correctly?

**Comment by sguada** [comment]
You need to pass a [callables not instances](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/parallel_py_environment.py#L55), since ParallelPyEnvironment need to build them in the appropriate processes.

```
train_env = tf_py_environment.TFPyEnvironment(
    ParallelPyEnvironment(
        [CardGameEnv] * hparams['parallel_environments']
    )
)
```

**Comment by Taxel** [comment]
Sorry for resurrecting this @sguada  but passing a callable does not fix the problem.
For debugging purposes, I manually instantiated a `ProcessPyEnvironment`, which is used internally by `ParallelPyEnvironment`. I am using the following code to try and step through the env:

            process_env = ProcessPyEnvironment(lambda: PokerEnvironment(
                players=pls, debug=True, model_to_train=-1, resetWhenAIPlayerOut=False))
            print("Starting process py env")
            process_env.start(wait_to_start=True)
            print("Resetting process py env")
            process_env.reset(blocking=True)
            print("Stepping process py env")
            process_env.step(0, blocking=True)
            print("Closing process py env")
            process_env.close()

I am pretty sure I am calling everything correctly this time, the lambda provides the possibility of calling the constructor with arguments and passing a callable at the same time.
When I execute the code above, I just get the console output

> Starting process py env

When I terminate it with ctrl+c, this is what happens:

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\write_league.py", line 150, in <module>
  File "<string>", line 1, in <module>
    write_out()  File "C:\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main

  File "E:\Users\tmp\Documents\Programming\Neural Nets\Poker_AI\write_league.py", line 80, in write_out
    exitcode = _main(fd)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 113, in _main
    process_env.start(wait_to_start=True)    preparation_data = reduction.pickle.load(from_parent)

KeyboardInterrupt
  File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 224, in start
    self._process.start()
  File "C:\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 265, in __getattr__
    return self._receive()
  File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 334, in _receive
    message, payload = self._conn.recv()
  File "C:\Python37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Python37\lib\multiprocessing\connection.py", line 306, in _recv_bytes
    [ov.event], False, INFINITE)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 290, in close
    self._process.join(5)
  File "C:\Python37\lib\multiprocessing\process.py", line 139, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
```

I currently have the suspicion this might have something to do with the players array I am passing in:
Each player instance in this array inherits from AbstractBaseClass Player, which implements most of the methods. Every type of player (RandomPlayer, HumanPlayer, AIPlayer) has its own `decide` function which for the AIPlayer just calls `self.policy.action` for a policy that was loaded during construction of the object.
Is it possible that the pickling during process startup fails because I am passing in an object that contains a loaded policy?

**Comment by sguada** [comment]
Yeah maybe some of the objects you are passing a not pickable, or the Environment is not being created properly.
