### ISSUE TITLE
Layer weights initialization

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#193]
Hi, I have a question regarding layer weights initialization. There seems to be multiple ways to initialize weights in the current code base. (e.g. difference between `actor_network` and `actor_distribution_network`, between `critic_network` and `value_network`, between `encoding_network` and `actor_network`).

Is there some intuition behind these differences? Do different initializations affect policy performance by a lot? Thanks a lot! 

https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/networks/encoding_network.py#L204-L206
https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/networks/actor_distribution_network.py#L124-L125
https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/agents/ddpg/actor_network.py#L88-L103

**Comment by kuanghuei** [comment]
`ddpg/actor_network` is a legacy which predicts deterministic action. It is possible to use `actor_distribution_network` instead.
`ddpg/critic_network` predicts Q-value Q(s, a). value_network predicts value V(s).
`encoding_network` just produces a (ConvNet +) MLP.

**Comment by ChengshuLi** [comment]
Thank you for your answer. 

I understand the different purposes / meanings of these networks. 

I am wondering whether it is necessary to initialize the weights of these networks in different ways, as the current code base does. Is there any intuition behind these different weight initializations? If we initialize them the same way, say `tf.compat.v1.keras.initializers.glorot_uniform()`, would there be a significant performance drop?

Thanks a lot!
@kuanghuei

**Comment by kuanghuei** [comment]
I don't think the results would be significant different, but you can try playing with it. Sometimes we just follow the original paper to use a different initialization.
