### ISSUE TITLE
Rename actor_fc_layers to policy_fc_layers?

### ISSUE THREAD

**Issue by seungjaeryanlee** [tensorflow/agents#194]
There are a few TODOs in train_eval example scripts that ask for renaming `actor_fc_layers` to `policy_fc_layers`. Before fixing it, I wanted to ask if this is still relevant, since the rest of the code seems to use the word "Actor" rather than "Policy". (For example, the network is called `ActorDistributionNetwork`)

https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/agents/ppo/examples/v1/train_eval.py#L93

https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/agents/ppo/examples/v2/train_eval.py#L87

https://github.com/tensorflow/agents/blob/a614c5b699ab08f6ac501c1d2bfc520d0a46572f/tf_agents/agents/reinforce/examples/v1/train_eval.py#L67

**Comment by kbanoop** [comment]
Yes I think it is probably better to keep it Actor since it fits better with the rest of the codebase. And we can remove the TODO.
