### ISSUE TITLE
Trouble testing a environment using utils.validate_py_environment

### ISSUE THREAD

**Issue by Cjaimesg** [tensorflow/agents#201]
I am trying to develop my own environment in colab 

` 
INITIAL_ACCOUNT_BALANCE = 10000
MAX_NUM_SHARES = 2147483647
look_back = 15
commission = 0.00075 

class StockTradingEnv(py_environment.PyEnvironment):

  def __init__(self, df):
    
    self.df = df
    
    self._action_spec = array_spec.BoundedArraySpec(shape=(2, 1), dtype=np.float32, minimum=-1, maximum=1, name='action')
    self._observation_spec = array_spec.BoundedArraySpec(shape=(look_back+1, 10) , dtype=np.float32, minimum=0, name='observation')
    
    self._time_step_spec = array_spec.BoundedArraySpec(shape = (),dtype = np.int32, name="step_type")
    
    self.current_step = random.randint(look_back + 1, len(self.df.loc[:, 'Open'].values))
    
    self.frame = np.array(
            [
            self.df.loc[self.current_step - look_back : self.current_step, 'Open'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'High'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Low'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Close'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Volume'].values / MAX_NUM_SHARES,
        ]
        )
        
    self.net_worth = INITIAL_ACCOUNT_BALANCE
    
    self.account_history = np.repeat([[self.net_worth],
                                          [0],
                                          [0],
                                          [0],
                                          [0]], look_back + 1, axis=1)
    

    self._state = np.append(self.frame, self.account_history[:, - look_back - 1 :], axis=0).T                  
                                     
    self._episode_ended = False

  def action_spec(self):
    return self._action_spec

  def observation_spec(self):
    return self._observation_spec
  
  def _reset(self):
    
    self.balance = INITIAL_ACCOUNT_BALANCE
    self.net_worth = INITIAL_ACCOUNT_BALANCE
    self.max_net_worth = INITIAL_ACCOUNT_BALANCE
    self.shares_held = 0
    self.cost_basis = 0
    self.total_shares_sold = 0
    self.total_sales_value = 0
    
    self.current_step = random.randint(look_back + 1, len(self.df.loc[:, 'Open'].values))
    
    self.frame = np.array(
            [
            self.df.loc[self.current_step - look_back : self.current_step, 'Open'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'High'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Low'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Close'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Volume'].values / MAX_NUM_SHARES,
        ]
        )
        
    self.net_worth = INITIAL_ACCOUNT_BALANCE
    
    self.account_history = np.repeat([[self.net_worth],
                                          [0],
                                          [0],
                                          [0],
                                          [0]], look_back + 1, axis=1)
    

    self._state = np.append(self.frame, self.account_history[:, - look_back - 1 :], axis=0).T
    
    self._episode_ended = False
    
    return ts.restart(np.array(self._state, dtype=np.float32)) #ts.restart(np.array([self._state], dtype=np.float32))

  def _step(self, action):

    if self._episode_ended:
      # The last action ended the episode. Ignore the current action and start
      # a new episode.
      return self.reset()
    
    current_price = random.uniform(self.df.loc[self.current_step, "Open"], self.df.loc[self.current_step, "Close"])

    action_type = action[0]
    amount = action[1]
    
    shares_bought = 0
    shares_sold = 0
    sales = 0
    additional_cost = 0
    
    if (action_type >= -1) & (action_type <= -0.3333) :
      # Buy amount % of balance in shares
      total_possible = int(self.balance / current_price)
      shares_bought = int(total_possible * amount)
      print("total possible", total_possible)
      print("cantidad", amount)
      print("shares_bought", shares_bought, "--", int(total_possible * amount))
      prev_cost = self.cost_basis * self.shares_held
      additional_cost = shares_bought * current_price * (1 + commission)

      self.balance -= additional_cost
      self.cost_basis = (prev_cost + additional_cost) / (self.shares_held + shares_bought)
      self.shares_held += shares_bought
      
    if (action_type <= 1) & (action_type >= 0.3333):
      # Sell amount % of shares held
      shares_sold = int(self.shares_held * amount)
      sales = shares_sold * current_price * (1 - commission)
      self.balance += sales
      self.shares_held -= shares_sold
      self.total_shares_sold += shares_sold
      self.total_sales_value += shares_sold * current_price
    
    self.net_worth = self.balance + self.shares_held * current_price
    
    if self.net_worth > self.max_net_worth:
      self.max_net_worth = self.net_worth

    if self.shares_held == 0:
      self.cost_basis = 0
            
    self.account_history = np.append(self.account_history, [[self.net_worth],
                                                            [shares_bought],
                                                            [additional_cost],
                                                            [shares_sold],
                                                            [sales]], axis=1)
    
    self.current_step += 1
    
    if self.current_step >= len(self.df.loc[:, 'Open'].values):
      self.current_step = look_back + 1
    
    self.frame = np.array(
            [
            self.df.loc[self.current_step - look_back : self.current_step, 'Open'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'High'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Low'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Close'].values,
            self.df.loc[self.current_step - look_back : self.current_step, 'Volume'].values / MAX_NUM_SHARES,
        ]
        )
    
    self._state = np.append(self.frame, self.account_history[:, - look_back - 1 :], axis=0).T
    
    
    reward_final = self.balance
    
    if self._episode_ended or self.net_worth <= 0:
      reward = reward_final if self.net_worth >= 0 else -10000
      return ts.termination(np.array(self._state, dtype=np.float32), reward)
    else :
      return ts.transition(np.array(self._state, dtype=np.float32), reward=reward_final, discount=1.0)
`
When I test the enviorment i have the next error:

`environment = StockTradingEnv(df)
utils.validate_py_environment(environment)`

`ValueError                                Traceback (most recent call last)
<ipython-input-7-a425415c85a0> in <module>()
      1 environment = StockTradingEnv(df)
----> 2 utils.validate_py_environment(environment)
      3 
      4 time_step = environment.step([-0.5, 0.5])

/usr/local/lib/python3.6/dist-packages/tf_agents/environments/utils.py in validate_py_environment(environment, episodes)
     58       raise ValueError(
     59           'Given `time_step`: %r does not match expected `time_step_spec`: %r' %
---> 60           (time_step, time_step_spec))
     61 
     62     action = random_policy.action(time_step).action

ValueError: Given `time_step`: TimeStep(step_type=array(1, dtype=int32), reward=array(17526.9, dtype=float32), discount=array(1., dtype=float32), observation=array([[ 1.5510000e+01,  1.5550000e+01,  1.5010000e+01,  1.5190000e+01,
         1.2418255e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.5140000e+01,  1.5150000e+01,  1.4650000e+01,  1.4790000e+01,
         1.3702083e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4810000e+01,  1.5100000e+01,  1.4610000e+01,  1.4850000e+01,
         2.0923559e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4850000e+01,  1.5190000e+01,  1.4660000e+01,  1.5080000e+01,
         1.8515158e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4800000e+01,  1.4860000e+01,  1.4500000e+01,  1.4570000e+01,
         1.2531411e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4530000e+01,  1.4920000e+01,  1.4100000e+01,  1.4200000e+01,
         2.8897543e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4290000e+01,  1.4560000e+01,  1.3780000e+01,  1.4140000e+01,
         2.6450958e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4160000e+01,  1.4550000e+01,  1.4120000e+01,  1.4490000e+01,
         1.0462943e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4440000e+01,  1.4470000e+01,  1.4300000e+01,  1.4360000e+01,
         3.2712705e-04,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4420000e+01,  1.4810000e+01,  1.4280000e+01,  1.4400000e+01,
         7.1031973e-04,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4310000e+01,  1.4380000e+01,  1.4010000e+01,  1.4060000e+01,
         6.6552311e-04,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4080000e+01,  1.4150000e+01,  1.3840000e+01,  1.4070000e+01,
         1.2892298e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4000000e+01,  1.4360000e+01,  1.3950000e+01,  1.4330000e+01,
         1.6691163e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4360000e+01,  1.4920000e+01,  1.4350000e+01,  1.4800000e+01,
         1.5086494e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4800000e+01,  1.4930000e+01,  1.4590000e+01,  1.4900000e+01,
         1.2261327e-03,  1.0000000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.5030000e+01,  1.5380000e+01,  1.4880000e+01,  1.4900000e+01,
         3.2474287e-03,  1.0005641e+04, -5.0600000e+02, -7.5268999e+03,
         0.0000000e+00,  0.0000000e+00]], dtype=float32)) does not match expected `time_step_spec`: TimeStep(step_type=ArraySpec(shape=(), dtype=dtype('int32'), name='step_type'), reward=ArraySpec(shape=(), dtype=dtype('float32'), name='reward'), discount=BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0), observation=BoundedArraySpec(shape=(16, 10), dtype=dtype('float32'), name='observation', minimum=0.0, maximum=3.4028234663852886e+38))`

**Comment by mcmah309** [comment]
I have this same issue. How did you resolve it?
