### ISSUE TITLE
ActionRepeat wrapper's step() method skips the first time step of each trajectory

### ISSUE THREAD

**Issue by alexlee-gk** [tensorflow/agents#205]
Should the break condition also be triggered when the time step is the first one in the episode? I.e. the condition should be `time_step.is_first() or time_step.is_last()` instead of just the latter. The reason for this is that if the call to `step()` is effectively a `reset()`, it's desirable to return the very first time step with `step_type=StepType.FIRST`. Otherwise, the dummy 0th action would be repeatedly applied (undesired since the 0th action is often a dummy value and it should be ignored) and the trajectories would be missing time steps with `step_type=StepType.FIRST` (this causes streaming metrics to be computed incorrectly, among other things).

The line of the condition is this one:
https://github.com/tensorflow/agents/blob/master/tf_agents/environments/wrappers.py#L202

**Comment by kbanoop** [comment]
Thanks for pointing out the issue! Would you like to contribute a PR?

**Comment by alexlee-gk** [comment]
Sure, I made it part of #204. Thanks!
