### ISSUE TITLE
Problem when running DQN and Reinforce Colab notebooks

### ISSUE THREAD

**Issue by alexacgomes** [tensorflow/agents#210]
Hi,

I cannot run DQN/Reinforce colab notebooks. I get the following error after running the second cell.

"---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-2-af038be80e9a> in <module>()
     11 import tensorflow as tf
     12 
---> 13 from tf_agents.agents.dqn import dqn_agent
     14 from tf_agents.drivers import dynamic_step_driver
     15 from tf_agents.environments import suite_gym

12 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/pyct/common_transformers/anf.py in AnfTransformer()
    150       gast.Is, gast.IsNot, gast.In, gast.NotIn,
    151       # Other leaf nodes that don't make sense standalone.
--> 152       gast.expr_context, gast.Ellipsis,
    153   )
    154 

AttributeError: module 'gast' has no attribute 'Ellipsis'"

Any ideas how can I solve this?

Thank you.

**Comment by IgnacioRoldan** [comment]
I solved it installing gast. You can add the next line in the setup:

!pip install 'gast==0.2.2'
