### ISSUE TITLE
module 'gast' has no attribute 'Ellipsis'

### ISSUE THREAD

**Issue by ankurharitosh** [tensorflow/agents#211]
I'm running the setup cell after installing the libraries but this error is being shown. What can I do?

AttributeError                            Traceback (most recent call last)
<ipython-input-2-5cb0abb1126b> in <module>()
     13 import tensorflow as tf
     14 
---> 15 from tf_agents.agents.reinforce import reinforce_agent
     16 from tf_agents.drivers import dynamic_step_driver
     17 from tf_agents.environments import suite_gym

12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/pyct/common_transformers/anf.py in AnfTransformer()
    150       gast.Is, gast.IsNot, gast.In, gast.NotIn,
    151       # Other leaf nodes that don't make sense standalone.
--> 152       gast.expr_context, gast.Ellipsis,
    153   )
    154 

AttributeError: module 'gast' has no attribute 'Ellipsis'

**Comment by oars** [comment]
Try the following: `pip install tf-nightly==1.15.0.dev20190821 \ tf-estimator-nightly==1.14.0.dev2019091701 \ gast==0.2.2`

I'll update the colabs.

**Comment by ankurharitosh** [comment]
Thank you so much. It is now working.
