### ISSUE TITLE
TF-Agents Environments Tutorial.ipynb has random_uniform error

### ISSUE THREAD

**Issue by maochaokuo** [tensorflow/agents#213]
running
TF-Agents Environments Tutorial.ipynb
from google colab will get the following error:
AttributeError: 'module' object has no attribute 'random_uniform'

at Whole Episodes paragraph, line:
action = tf.random_uniform([1], 0, 2, dtype=tf.int32)

![random_uniform-error](https://user-images.githubusercontent.com/6857537/66267502-1fd5f500-e864-11e9-8c25-e4e4ad1c0d5b.png)

**Comment by sguada** [comment]
Which version of TF do you have installed?

**Comment by maochaokuo** [comment]
hi, the problem comes from the Github and/or Google colab, so you may just run it to see the problem:
Github:
[Github 2_environments_tutorial.ipynb](https://github.com/tensorflow/agents/blob/master/tf_agents/colabs/2_environments_tutorial.ipynb)
Google Colab:
[Google Colab 2_environments_tutorial.ipynb](https://colab.research.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/2_environments_tutorial.ipynb)

From the very top, you may see:
pip install tf-nightly

This should be the tf version.

**Comment by seungjaeryanlee** [comment]
[According to the TF document](https://www.tensorflow.org/api_docs/python/tf/random/uniform), it seems like the line should be changed to `tf.random.uniform`. I verified that it works on Colab after making the change.

![11](https://user-images.githubusercontent.com/6107926/66369107-0074c000-e969-11e9-9c92-72198b339f5e.png)

Should I make a PR?

**Comment by maochaokuo** [comment]
OK, understood. This is part of the tutorial. It will be great if you may update it. Thanks

**Comment by mitra-tabatabaei** [comment]
Using tf.random.normal instead of tf.random_normal should execute successfully.
