### ISSUE TITLE
Method copy for weights of Network

### ISSUE THREAD

**Issue by zzong2006** [tensorflow/agents#215]
I'm trying to implement meta-learning algorithm **MAML** by using tf-agent.

Just started looking around the tf-agent library, I found network.   
Network supports `copy` function. But it's only shallow without weights.
(I read the warning message "Network layer weights are *never* copied." but expected it at least will keep the number/structures of layers and nodes)

I used copy function but it was not satisfying.

Define Network first, 
```
class ActionNet(network.Network):
    def __init__(self, input_tensor_spec, output_tensor_spec):
        super(ActionNet, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name='ActionNet')
        self._output_tensor_spec = output_tensor_spec
        self._layers = [
            tf.keras.layers.Dense(
                action_spec.shape.num_elements(), activation=tf.nn.tanh),
        ]
    def call(self, observations, step_type, network_state):
        del step_type
        output = tf.cast(observations, dtype=tf.float32)
        for layer in self.layers:
            output = layer(output)
        actions = tf.reshape(output, [-1] + self._output_tensor_spec.shape.as_list())
        # Scale and shift actions to the correct range if necessary.
        return actions, network_state
```
Initiate `ActionNet` Network
```
action_net = ActionNet(input_tensor_spec, action_spec)
```
It has the weights and bias according to the single `keras.layers.core.Dense` .
```
action_net.get_weights()
->
[array([[ 0.4108224 ,  0.6797581 ,  0.4383297 ],
        [ 0.21604276,  0.05170751,  0.00158906],
        [ 0.7237488 , -0.24879843,  0.9208518 ],
        [ 0.01156223,  0.0433327 , -0.5863462 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]
```
But after copy the network, copied network shows nothing
```
z = action_net.copy()
z.get_weights()
-> []
z.set_weights(action_net.get_weights())
->
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-21d1478264d6>", line 1, in <module>
    z.set_weights(action_net.get_weights())
  File "/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", 
line 1327, in set_weights
    str(weights)[:50] + '...')
ValueError: You called `set_weights(weights)` on layer "ActionNet" with a  weight list of length 2, 
but the layer was expecting 0 weights. 
Provided weights: [array([[ 0.4108224 ,  0.6797581 ,  0.4383297 ], ...
```
Considering the comments written below the `class _NetworkMeta`, I should save some args into `_saved_kwargs` to copy the network's values to another one.

> We mainly use this class to capture all args to `__init__` of all `Network`
  instances, and store them in `instance._saved_kwargs`.  This in turn is
  used by the `instance.copy` method.

But still don't know how to do that. It would be much helpful make other tutorial colab files for showing the copy/train parameters of network.

**Comment by sguada** [comment]
Networks don't build their variables until they are called or explicit call to `create_variables()`.
Try the following:
```
z = action_net.copy()
z.create_variables()
z.set_weights(action_net.get_weights())
```

**Comment by zzong2006** [comment]
It works for me. Thanks.
