### ISSUE TITLE
Parallel training fails silently

### ISSUE THREAD

**Issue by therhappy** [tensorflow/agents#219]
Hello!

First of all thanks for this library. And also for reading this!

I am trying to run a training with several instances of my custom environment in parallel. This work is based on the [DDPG example](https://github.com/tensorflow/agents/tree/master/tf_agents/agents/ddpg/examples/v2).
The aforementioned environment runs fine when I set num_parallel_environments to 1. However, when I try to increase this, I come to an infinite wait.

This issue is the same as referenced by @Taxel in https://github.com/tensorflow/agents/issues/191#issuecomment-534109659_ but since they were commenting on a closed issue and it has not been reopened I took the liberty of opening a new one.

## Plaftorm 
Windows 10 / Python 3.7 / tf-nightly-gpu >= v2. 

## Details 
After logging 'Spawing all processes' the script comes to an infinite wait. 
Please find here a 'manual traceback' (although @Taxel provides a more legible traceback in https://github.com/tensorflow/agents/issues/191#issuecomment-534109659_ ) 
 
In **main.py** :
```
if num_parallel_environments > 1:
      tf_env = tf_py_environment.TFPyEnvironment(
          parallel_py_environment.ParallelPyEnvironment(
              [lambda : env_load_fn(env_name,max_episode_steps=1)] * num_parallel_environments))
```
 
In **__init__** of _ParallelPyEnvironment_
`self.start()`
 
In **start** of _process_:
self._popen = self._Popen(self)
 
In **SpawnProcess**:
`            return Popen(process_obj)`
 
In **__init__** of _Popen_:
```
            try:
                reduction.dump(prep_data, to_child)
                reduction.dump(process_obj, to_child)  
```
 
In __reduce_method_ of **multiprocessing/reduction.py**:
```
    204         return getattr, (m.__class__, m.__func__.__name__)
    205     else:
-> 206         return getattr, (m.__self__, m.__func__.__name__)
```

In __getattr__ of **parallel_py_environment.py** :
```
    264     self._conn.send((self._ACCESS, name))
-> 265     return self._receive()
```

In _\_receive_ of **parallel_py_environment.py** : 
```
  def _receive(self):
    """Wait for a message from the worker process and return its payload.
    Raises:
      Exception: An exception was raised inside the worker process.
      KeyError: The reveived message is of an unknown type.
    Returns:
      Payload object of the message.
    """
->    message, payload = self._conn.recv()

```
In **connection** :
 ```
       def _recv_bytes(self, maxsize=None):
            if self._got_empty_message:
                self._got_empty_message = False
                return io.BytesIO()
            else:
                bsize = 128 if maxsize is None else min(maxsize, 128)
                try:
                    ov, err = _winapi.ReadFile(self._handle, bsize,
                                                overlapped=True)
                    try:
                        if err == _winapi.ERROR_IO_PENDING:
                            waitres = _winapi.WaitForMultipleObjects(
                                [ov.event], False, INFINITE)
                            assert waitres == WAIT_OBJECT_0
```

I am at this time trying to assert if I can run parallel default (gym) environments but it seems this happens everytime (hence I did not specify in the issue title I was using a custom env).

I appreciate any input on how to get past this difficulty!

**Comment by corypaik** [comment]
I'm having the same issue on windows and can confirm the problem persists with default gym environments even though it runs on Mac with no changes to the code. Also as a side note, I've been running up to 64 environments with OpenAI vec_env wrappers on windows, so I'm not too sure where the error is coming from.

**Comment by gomes-eric** [comment]
I have this same issue in Windows 10 64bits.

**Comment by corypaik** [comment]
I found a relatively simple solution to this drawing from the OpenAI Baselines implementation if anyone is in need of a quick fix. It seems that something with the implementation of `ProcessPyEnvironment._worker()` as a class method was the root of the issue. I'm no expert, but from what I found searching through related issues on other projects, is that implementing multiprocessing can differ on mac/linux vs. windows so this could be a related issue. Again, not sure if this "breaks" anything I'm not seeing, but so far it has worked great for me and the code runs on mac, linux, and windows :). Here are the changes that need to be made to the `parallel_py_env.py` file:

1. Add CloudpickleWrapper() implementation from [here](https://github.com/openai/baselines/blob/665b888eeb688396894455a0d94febc4f712e0c0/baselines/common/vec_env/vec_env.py#L190) somewhere into the file (at the bottom works):
```python
class CloudpickleWrapper(object):
  """ Title: OpenAI Baselines CloudpickleWrapper source code
  Author: Dhariwal et al.
  Date: 2017
  Availability: https://github.com/openai/baselines/blob/665b888eeb688396894455a0d94febc4f712e0c0/baselines/common/vec_env/vec_env.py#L190
  Added By: Cory Paik (https://github.com/corypaik)

  Uses cloudpickle to serialize contents (otherwise multiprocessing tries to use pickle)
  """

  def __init__(self, x):
    self.x = x

  def __getstate__(self):
    import cloudpickle
    return cloudpickle.dumps(self.x)

  def __setstate__(self, ob):
    import pickle
    self.x = pickle.loads(ob)
```
2. Change the call to `multiprocessing.Process()` in `ProcessPyEnvironment.start()`
```python
self._process = multiprocessing.Process(
        target=self._worker,
        args=(conn, self._conn, CloudpickleWrapper(self._env_constructor), self._flatten))
```
3. I found that `ProcessPyEnvironment._worker()` couldn't work without be defined either outside  `ProcessPyEnvironment` or as a static method (which is what I went with). Here is the implementation: 
```python
  @staticmethod
  def _worker(conn, parent, env_constructor, flatten=False):
    """The process waits for actions and sends back environment results.

    Args:
      conn: Connection for communication to the main process.
      env_constructor: env_constructor for the OpenAI Gym environment.
      flatten: Boolean, whether to assume flattened actions and time_steps
        during communication to avoid overhead.

    Raises:
      KeyError: When receiving a message of unknown type.
    """
    _READY = 1
    _ACCESS = 2
    _CALL = 3
    _RESULT = 4
    _EXCEPTION = 5
    _CLOSE = 6

    parent.close()

    try:
      env = env_constructor.x()
      action_spec = env.action_spec()
      conn.send(_READY)  # Ready.
      while True:
        try:
          # Only block for short times to have keyboard exceptions be raised.
          if not conn.poll(0.1):
            continue
          message, payload = conn.recv()
        except (EOFError, KeyboardInterrupt):
          break
        if message == _ACCESS:
          name = payload
          result = getattr(env, name)
          conn.send((_RESULT, result))
          continue
        if message == _CALL:
          name, args, kwargs = payload
          if flatten and name == 'step':
            args = [tf.nest.pack_sequence_as(action_spec, args[0])]
          result = getattr(env, name)(*args, **kwargs)
          if flatten and name in ['step', 'reset']:
            result = tf.nest.flatten(result)
          conn.send((_RESULT, result))
          continue
        if message == _CLOSE:
          assert payload is None
          env.close()
          break
        raise KeyError('Received message of unknown type {}'.format(message))
    except Exception:  # pylint: disable=broad-except
      etype, evalue, tb = sys.exc_info()
      stacktrace = ''.join(traceback.format_exception(etype, evalue, tb))
      message = 'Error in environment process: {}'.format(stacktrace)
      logging.error(message)
      conn.send((_EXCEPTION, stacktrace))
    finally:
      conn.close()
```

I hope this helps! I'd be happy to answer any questions if that bit was confusing (and please let me know if these changes are breaking something I'm not seeing).

**Comment by andreas-repp** [comment]
I get the same problem. I can reproduce this on Windows 10 64 bit. This problem also occurs when running the [PPO example](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py). Reducing the `num_parallel_environments` parameter to does not help as well. 

I'm running today's nightly builds of tensorflow (tf-nightly) and tf-agents-nightly.

*EDIT*: The solution of @corypaik works for me.

**Comment by SebastienKeroack** [comment]
The solution of @corypaik no longer works.
tensorflow==2.1.0, tf-agents==0.3.0

**Comment by HadiSDev** [comment]
@corypaik I am also having the issue with windows 10, but I where should step 1 and 2 go in my code?

**Comment by craigdrayton** [comment]
Hey @corypaik, thanks for the workaround you posted above. I'm new to this - how might I apply your workaround to the PPO example provided in the tf_agents repo? https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval_clip_agent.py

**Comment by tfboyd** [comment]
Closing due to age of the issue. I will note that the distributed example with SAC does work with multiple actors.  I have given it a try in in the cloud on a single machine. https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/distributed/examples/sac
