### ISSUE TITLE
Post trained model Rewards

### ISSUE THREAD

**Issue by marconardelli** [tensorflow/agents#221]
Hello, 
I have a complex system that takes hours of training to arrive to the best solution.
This is due to the fact that the reward calculation of each step must do some complex check on multiple variables.
My idea is, once I have a trained model, is it possible to cut this portion of code and return always a reward value of 0?

**Comment by kuanghuei** [comment]
It seems like avoiding reward computation should probably be handled in your environment implementation.

**Comment by oars** [comment]
If you are deploying the trained policy and don't need to do any more training you can definitely change your environment to only return 0 rewards.

The policies do not use the reward for evaluation, it is only used by agents during training.
