### ISSUE TITLE
Why using replay_buffer.clear() in PPO? And a bug without it

### ISSUE THREAD

**Issue by Rendok** [tensorflow/agents#227]
Hi,

There is a PPO code example in https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py
where each iteration the training is made of the steps:

```python
collect_driver.run()
trajectories = replay_buffer.gather_all()
tf_agent.train(experience=trajectories)
replay_buffer.clear()
```
There is already a question about `replay_buffer.gather_all()`. My question is, **why do we clear the buffer each iteration?** It violates the idea of experience replay buffer, which is to infuse new trajectories while gradually deleting old.

I tried to delete this line but on a third iteration of training the buffer makes a batch of the shape `(None, H, W, C)` instead of `(All time steps, H, W, C)`. It happens when the number of collected timesteps is still less than the buffer capacity. However with `replay_buffer.clear()` doesn't happen. **Is it normal?**

**Comment by kuanghuei** [comment]
PPO is an on-policy algorithm. The replay buffer doesn't really store the agent's experience from previous iterations. Technically PPO can be implemented without replay buffer. We use it to cache  trajectories for connivence here.
