### ISSUE TITLE
save replay buffer

### ISSUE THREAD

**Issue by ChrisProgramming2018** [tensorflow/agents#228]
Hello,
I could not find out which data structure is used save the trajectories in the replay buffer
So if I continue training I can load the buffer with the old buffer content 

Thank you for your help

**Comment by ebrevdo** [comment]
Hi; the replay buffer subclasses `tf.Module`, so you should be able to save and load it using `tf.train.Checkpoint`:

```python
rb = tf_uniform_replay_buffer.TFUniformReplayBuffer(tf.TensorSpec([], tf.float32), 1)
...
checkpointed = tf.train.Checkpoint(rb=rb)
checkpointed.save('/tmp/blah')
rb.clear()  # reset RB
checkpointed.restore('/tmp/blah-1')  # assuming checkpoint was to /tmp/blah-1
rb.get_next()  # should return data that was in RB before checkpointing
```

Note you can create an empty RB, associated it with a Checkpoint object, and restore into it.
