### ISSUE TITLE
MaskedCategorical distribution example?

### ISSUE THREAD

**Issue by justindujardin** [tensorflow/agents#23]
I have an existing RL agent that I'd like to re-express with tf_agents, so I can test out a number of different algorithms that I'd struggle to implement myself. Thanks for this work! 👏 

My environment has an action-space where not all actions are valid at all timesteps. It looks like [MaskedCategorical](https://github.com/tensorflow/agents/blob/master/tf_agents/distributions/masked.py) class is capable of supporting this use-case, but there are no examples of its use within the larger library. 

I'm currently working with the [sac/examples/v2/train_eval.py](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/sac/examples/v2/train_eval.py) script and a custom environment. The training runs as expected, but I (unsurprisingly) receive invalid actions.

Can someone point me in the right direction?

**Comment by sguada** [comment]
This is meant to be used with QNetworks, not sure it would work with the actor in SAC.

Take a look at [masked_test](https://github.com/tensorflow/agents/blob/master/tf_agents/distributions/masked_test.py)

You would need to pass the boolean mask to the distribution for each time_step.

**Comment by justindujardin** [comment]
> This is meant to be used with QNetworks, not sure it would work with the actor in SAC.

@sguada That's good information, thanks.

I reviewed the masked_test file before opening this issue. It shows how to use the distribution directly, but not in the context of any of the components that tf_agents exposes.

It seems MaskedCategorical is not what I want for limiting to valid actions. I will close this issue, but if you have thoughts on another approach for masking actions in SAC I'd be interested to hear them.

**Comment by sguada** [comment]
I'm not sure what your environment looks like, but one option would be to create an [PyEnvironmentBaseWrapper](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/wrappers.py#L40) that will have access to what actions are available and filter out the rest.

However it may make learning more challenging.
