### ISSUE TITLE
TF agents & TF 2.0 contrib dependency for current pip package.

### ISSUE THREAD

**Issue by jun-bun** [tensorflow/agents#230]
Versions:
tf-agents 0.2.0rc2
tensorflow 2.0.0

Does not work unless tensorflow/agents/tf_agents folder is imported as module.
current pip version of tf_agents still uses tf.contrib but is missing in tensorflow 2.0.0

**Comment by youngalou** [comment]
+1 for this. Current pip module needs to be updated.

**Comment by ebrevdo** [comment]
@oars @sguada could you push a new pip?

**Comment by sguada** [comment]
While we push a new version you can `pip install tf-agents-nightly` to get a version that works with TF 2.0

**Comment by anandijain** [comment]
I'm having some issues trying to import modules using `tf-agents-nightly`.

Specifically, I can't seem to:
`from tf_agents.environments.tf_wrappers import TFPyEnvironment`

But I think something else is off because none of my tf_agents imports from non-nightly are able to import.

Is there any expected update on this?

Thanks!

**Comment by michael20at** [comment]
Trying to get TF agents running on windows (with winpython) and tensorflow 2, updated pip to newest version, installed tf-agents-nightly, but still get the contrib is missing error. Any idea how to solve this? 

How would I import tensorflow/agents/tf_agents folder as module, as suggested in the first post?

**Comment by anandijain** [comment]
I'm getting some different errors when using `pip install tf-agents==0.3.0rc0` which was published to pypi yesterday.
I think that this solved the contrib errors though 
@michael20at

**Comment by sguada** [comment]
Please open a different issue for other errors.
Re-open this one if you still have contrib troubles with the new release 0.3.0rc0
