### ISSUE TITLE
Does this lib provide fully parallel ability?

### ISSUE THREAD

**Issue by codelast** [tensorflow/agents#233]
Hi everyone, I'm new to this lib, and I want to ask that, does this library provide the parallelism ability like another RL lib [rlpyt](https://github.com/astooke/rlpyt) does? 

[rlpyt](https://github.com/astooke/rlpyt) can:
> Run experiments fully parallelized, with options for parallel sampling and/or multi-GPU optimization.

Thank you.

**Comment by egonina** [comment]
We have an internal API for doing distributed data collection and training that we plan on open sourcing soon.
