### ISSUE TITLE
Using tf_agents with Habitat environment

### ISSUE THREAD

**Issue by robodhruv** [tensorflow/agents#234]
I am trying to use tf_agents with Habitat RL_Env (which subclasses gym.Env). What is the right way to do this: register as a gym env and then load it, or wrap it inside a tensorflow environment manually?

I am able to register it as a gym environment but when trying `suite_gym.load`, I get
`The gym space <habitat.core.spaces.EmptySpace object at 0x7fae46241b50> is currently not supported.`
Is this a dead end?

**Comment by kbanoop** [comment]
Yes you could register as a suite or just wrap the GymEnv instance using the GymWrapper which will convert it to our PyEnvironment.

Not sure what an EmptySpace in Habitat means, but this is the function which converts GymSpaces to our format and you could try to define a conversion there:
https://github.com/tensorflow/agents/blob/3541bfe5e5d0a837ae5e92c4f3f99f88ba853732/tf_agents/environments/gym_wrapper.py#L34

**Comment by oars** [comment]
It seems habitat defines their own spaces:  https://github.com/facebookresearch/habitat-api/blob/6be49a17bde08798c2ec05a5d2c25cfbbe4b442a/habitat/core/spaces.py

The best way for you to integrate this would be to fork the gym_wrapper and modify `_spec_from_gym_space` as Anoop suggested.

**Comment by robodhruv** [comment]
Was able to create a wrapper to convert Habitat spaces to gym spaces and it interfaces fine. Thanks!
