### ISSUE TITLE
How to define actor network yielding action of joint distribution

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/agents#247]
when an actor network outputs action which is composed of several decisions following different distribution. how should I define the actor network?

I want to use tfd.JointDistributionSequential to join several distributions. but I find network.DistributionNetwork asks for output specification of the actor network. the output specification need input param shape of tfd.JointDistributionSequential which doesn't exist.

If I assign None to the input param shape for output sepcification. when I create TFUniformReplayBuffer, it will complain about None type error during initialization.

please help, Thx!

**Comment by egonina** [comment]
I'm not sure if we support different distribution specs in the networks/replay_buffers. @oars @sguada what do you think?

**Comment by tfboyd** [comment]
Closing stale issues/questions.
