### ISSUE TITLE
network.create_variables() clogs all GPU memory

### ISSUE THREAD

**Issue by robodhruv** [tensorflow/agents#250]
On calling network.create_variables() for my agent (using a DDPG agent), my GPU memory gets used 100% instantly and never clears up.
I can control it by using a virtual memory cap, but I need memory for other computation downstream (CNN etc.) and the memory cap ensures there is no memory left for anything else.

Why might this be happening and how do I get around this?

**Comment by egonina** [comment]
how big are your variables/layers that you are creating?

**Comment by robodhruv** [comment]
I create a custom tf_agent (outline shown below) using actor and critic networks from DDPG agent and the networks are 2-layer feedforward FC on low-dim states. It's unlikely that the network is causing the trouble.

On executing linewise in a notebook, it is the `for net in net_list: net.create_variables()` step that causes the memory to fill up.

```
class UvfAgent(tf_agent.TFAgent):
    """A UVF Agent."""

    def __init__(
            self,
            time_step_spec,
            action_spec,
            conv_layer_params=None,
            fc_layer_params=(256, 256),
            critic_conv_layer_params=None,
            critic_fc_layer_params=(256,),
            ou_stddev=1.0,
            ou_damping=1.0,
            target_update_tau=0.05,
            target_update_period=5,
            max_episode_steps=None,
            ensemble_size=3,
            combine_ensemble_method='min',
            use_distributional_rl=True):
        """Creates a Uvf Agent.

        Args:
          time_step_spec: A `TimeStep` spec of the expected time_steps.
          action_spec: A nest of BoundedTensorSpec representing the actions.
          ou_stddev: Standard deviation for the Ornstein-Uhlenbeck (OU) noise added
            in the default collect policy.
          ou_damping: Damping factor for the OU noise added in the default collect
            policy.
          target_update_tau: Factor for soft update of the target networks.
          target_update_period: Period for soft update of the target networks.
          max_episode_steps: Int indicating number of steps in an episode. Used for
            determining the number of bins for distributional RL.
          ensemble_size: (int) Number of models in ensemble of critics.
          combine_ensemble_method: (str) At test time, how to combine the distances
            predicted by each member of the ensemble. Options are 'mean', 'min',
            and 'td3'. The 'td3' option is pessimistic w.r.t. the pdf, and then
            takes computes the corresponding distance. The 'min' option takes the
            minimum q values, corresponding to taking the maximum predicted
            distance. Note that we never aggregate predictions during training.
          use_distributional_rl: (bool) Whether to use distributional RL.
        """
        tf.Module.__init__(self, name='UvfAgent')

        assert max_episode_steps is not None
        self._max_episode_steps = max_episode_steps
        self._ensemble_size = ensemble_size
        self._use_distributional_rl = use_distributional_rl

        # Create the actor
        self._actor_network = GoalConditionedActorNetwork(
            time_step_spec.observation, action_spec, conv_layer_params, fc_layer_params)
        self._target_actor_network = self._actor_network.copy(
            name='TargetActorNetwork')

        # Create a prototypical critic, which we will copy to create the
        # ensemble.
        critic_net_input_specs = (time_step_spec.observation, action_spec)
        critic_network = GoalConditionedCriticNetwork(
            critic_net_input_specs,
            output_dim=max_episode_steps if use_distributional_rl else None,
            observation_conv_layer_params=critic_conv_layer_params,
            observation_fc_layer_params=critic_fc_layer_params,
            action_fc_layer_params=None,
            joint_fc_layer_params=(256,),
        )
        self._critic_network_list = []
        self._target_critic_network_list = []
        for ensemble_index in range(self._ensemble_size):
            self._critic_network_list.append(
                critic_network.copy(name='CriticNetwork%d' % ensemble_index))
            self._target_critic_network_list.append(
                critic_network.copy(
                    name='TargetCriticNetwork%d' %
                    ensemble_index))

        # Create variables for each net.
        net_list = [
            self._actor_network, self._target_actor_network
        ] + self._critic_network_list + self._target_critic_network_list
        for net in net_list:
            net.create_variables()

        self._actor_optimizer = tf.optimizers.Adam(
            learning_rate=3e-4)
        self._critic_optimizer = tf.optimizers.Adam(
            learning_rate=3e-4)

        self._ou_stddev = ou_stddev
        self._ou_damping = ou_damping
        self._target_update_tau = target_update_tau
        self._target_update_period = target_update_period

        self._update_target = self._get_target_updater(
            target_update_tau, target_update_period)

        policy = actor_policy.ActorPolicy(
            time_step_spec=time_step_spec, action_spec=action_spec,
            actor_network=self._actor_network, clip=True)
        collect_policy = actor_policy.ActorPolicy(
            time_step_spec=time_step_spec, action_spec=action_spec,
            actor_network=self._actor_network, clip=False)
        collect_policy = ou_noise_policy.OUNoisePolicy(
            collect_policy,
            ou_stddev=self._ou_stddev,
            ou_damping=self._ou_damping,
            clip=True)

        super(UvfAgent, self).__init__(
            time_step_spec,
            action_spec,
            policy,
            collect_policy,
            train_sequence_length=2)
```

**Comment by egonina** [comment]
can you print the specs of all the layers in the networks you're creating in that loop? it seems likely that one or more of the layers is configured to be very large that is filling up GPU memory.

**Comment by sguada** [comment]
In general TensorFlow would use all the GPU memory by default. 

See https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

**Comment by robodhruv** [comment]
@egonina  what do you mean by specs? Is there a particular function that can get me these specs?

@sguada it seems to do that only at this step and no free memory available for future network initializations. I've used GPUOptions to limit the memory but that just means I don't get memory for other operations later on. For e.g. I get this when using a Conv2D later, likely because cuDNN ran out of memory.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/14254187/69082139-59b62180-09f4-11ea-93cb-9aec4aaf5d57.png">

**Comment by egonina** [comment]
you can look at input and output shapes of the layers in the networks: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#input_shape

**Comment by robodhruv** [comment]
Looking at the input/output spec, I get this error:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/14254187/69104751-3e600c00-0a1e-11ea-9b9e-a0f398a3676a.png">


`layer.input_shape` on the FC layers just shows the layers, as expected:
```

InputSpec(min_ndim=1)
InputSpec(min_ndim=2, axes={-1: 10})
InputSpec(min_ndim=2, axes={-1: 256})
InputSpec(min_ndim=2, axes={-1: 256})
InputSpec(min_ndim=1)
InputSpec(min_ndim=2, axes={-1: 10})
```

**Comment by sguada** [comment]
When you create the Variables print their sizes, so you know how much space are the taking. Example

```
total_size = 0
for net in net_list:
        net.create_variables()
        for var in net.variables:
           total_size += var.shape.size
```

**Comment by robodhruv** [comment]
`var.shape` is TensorShape and does not have an attribute size.
However, just printing out `var.shape` as suggested gives:

```
(10, 256)
(256,)
(256, 256)
(256,)
(256, 1)
(1,)
(10, 256)
(256,)
(256, 256)
(256,)
(256, 1)
(1,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
(10, 256)
(256,)
(257, 256)
(256,)
(256, 50)
(50,)
```

**Comment by sguada** [comment]
Sorry, `var.shape.num_elements()` should work.
Can you also print their dtypes, just to make sure they are float32.
If they are tf.float32 then their size should be total num_elements * 4 bytes.

**Comment by robodhruv** [comment]
Yeah, the total num_elements is 628014 of tf.float32 each. It is definitely not the network parameters...

**Comment by robodhruv** [comment]
@egonina @sguada An update.
This observation is not specific to DDPG. I was able to replicate this using the DQN_Tutorial notebook on `Cartpole-v0`.

While it works fine on Colab and the memory management is as expected, running it on my local machine blows up GPU:0 memory to 100%, attached is the output of `nvidia-smi` before and after calling the agent from the tutorial notebook.
<img width="443" alt="Untitled" src="https://user-images.githubusercontent.com/14254187/69199123-f1e30200-0aeb-11ea-889c-213f4bc0b916.png">

What may be going wrong here?

**Comment by sguada** [comment]
As I mention, as soon as TF start using the GPU it reserve all the available memory of the GPU, that doesn't mean is using all of it in that moment.

**Comment by robodhruv** [comment]
Thanks, @sguada.

However,
1. This does not happen on Colab. For example, here is the same output on a Colab instance:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/14254187/69199409-b85ec680-0aec-11ea-92ae-8b8726980014.png">

2. Because this takes up all memory, using a CNN downstream throws me the following error: 
![](https://user-images.githubusercontent.com/14254187/69082139-59b62180-09f4-11ea-93cb-9aec4aaf5d57.png)

Why is the behavior different in (1) and how may I circumvent (2)?

**Comment by egonina** [comment]
The error in (2) may be unrelated to the GPU memory issue, check out https://github.com/tensorflow/tensorflow/issues/24828 and https://github.com/tensorflow/tensorflow/issues/28326. Potentially due to mismatch between cuda and cudnn versions.

**Comment by robodhruv** [comment]
Thanks a lot, @egonina 
Following https://github.com/tensorflow/tensorflow/issues/24828#issue-397816192 was useful and (2) is resolved by maintaining consistency across cudnn and tf.

I still find the behavior of (1) a little weird. Especially since it behaves differently on Colab v/s local machine. Why might this be happening?

**Comment by egonina** [comment]
Yea, I'm not sure either. Could have something to do with the difference in tensorflow runtime backing colab vs your direct setup. Is 67MB about the size of variables you expect to be allocated?

**Comment by robodhruv** [comment]
Slightly overestimated, but yes.
I can explicitly cap memory_limit but that does not seem like the right way to do it...

**Comment by sguada** [comment]
I suppose the Colab is configured to allow memory growth.

```
# Tensorflow
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)
```

**Comment by ebrevdo** [comment]
As per Sergio: this is an issue with TF - not TF Agents.  In TF2, the solution is documented [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).
