### ISSUE TITLE
EpsilonGreedyPolicy Error

### ISSUE THREAD

**Issue by bartmaciszewski** [tensorflow/agents#253]
Hi All, I am trying to use a DQN agent with a custom Gym environment wrapped in TfPyEnvironment that has a Discrete action space (e.g. 1, 2, 3, 4, 5, ...) and using an observation_and_action_constraint_splitter function to restrict valid actions depending on the state.

So far so good and running an initial evaluation runs fine however I get the following error when training:
`
...
  File "C:\Anaconda\envs\tensorflow_2\lib\site-packages\tf_agents\policies\epsilon_greedy_policy.py", line 102, in _action
    random_action.action)
...
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation Select of type Select must have the same size and shape.  Input 0: [1] != input 2: [] [Op:Select]
`
This is the line that's failing:
`action = tf.compat.v1.where(cond, greedy_action.action, random_action.action)`

I managed to trace it back and it seems that the GreedPolicy is returning a Tensor shape=(1) while RandomTFPolicy is returning a scalar shape=().  I managed to work around this by modifying line in RandomTFPolicy to recast a scalar action to a shape=(1) tensor and it seems to work fine:

Before line 80 in RandomTFPolicy:
```
      action_ = tf.cast(masked_categorical.sample() + self.action_spec.minimum,
                        self.action_spec.dtype)
```
After:
```
      action_ = tf.reshape(tf.cast(masked_categorical.sample() + self.action_spec.minimum,
                        self.action_spec.dtype),[1])
```

Is this a bug or am I doing something wrong?  Any thoughts on how to better work around this in my code?

**Comment by jeroenherczeg** [comment]
Had the same problem, this also worked for me.

**Comment by bartmaciszewski** [comment]
Given the number of people that have this issue I’m beginning to think this is indeed a bug.  Anyone interested in working on this with me?

**Comment by jsrhoades** [comment]
I'm hitting a problem with observation_and_action_constraint_splitter in a Python environment. It is a imple TicTacToe game, in which I want to prevent the agent from making illegal moves (moves to occupied spots):

train_py_envx = TictacEnv()
train_env = tf_py_environment.TFPyEnvironment(train_py_envx)

For the agent I provide the following setup code:
# sort of works, but sometimes there is no numpy attribute

def check_valid_move(obs):
    try:
        pobs = np.array(obs.numpy() == 0,dtype=np.int32)
        constr = tf.convert_to_tensor(pobs,dtype=tf.int32)
    except AttributeError:
        print(obs)
        # this seems wrong but why?
        constr = tf.constant(np.ones(obs.shape),dtype=tf.int32)
    except:
        raise
    return obs,constr

agent = dqn_agent.DqnAgent(
    train_env.time_step_spec(),
    train_env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    observation_and_action_constraint_splitter=check_valid_move,
    td_errors_loss_fn=common.element_wise_squared_loss,
    train_step_counter=train_step_counter)

agent.initialize()

This almost works, I get a few AttributeError exceptions at startu;, but after that all is well for hundred-thousands of iterations. The exception printouts are like this:

my action generator: illegal move who,move,board: 1 1 [1 1 4 1 4 4 1 0 4]
my splitter function :Tensor("Squeeze_3:0", shape=(64, 9), dtype=int32)

Any thoughts? Also I'm new to this group, where should I be asking such questions?

**Comment by jsrhoades** [comment]
Oh, I see. Squeeze_3:0 is a tensor within a session. Thus, I must provide a tensor op for the mask. My function is

@tf.function
check_valid_move(obs):
  mask = tf.equal(obs,0) # disallow moves to occupied spots
  return(obs,mask)

and it all just works beautifully.

**Comment by tfboyd** [comment]
Closing due to age and lack of recent activity.  If the issue still exists, please open a new issue and reference this one.
