### ISSUE TITLE
DQN Agent: Should training=True be passed to q_network.__call__?

### ISSUE THREAD

**Issue by mhe500** [tensorflow/agents#254]
Regarding:
https://github.com/tensorflow/agents/blob/b6d0fac4fe6dee630d0f4a14118acf48217bd292/tf_agents/agents/dqn/dqn_agent.py#L512

Should training=True be passed to the Q-network, so that it can subsequently pass it to the encoding network (which can pass it to pre-processing layers, combiner layer, post-processing layers, etc.)?

Also, I believe it would be correct that the target_q_network would be called with training=False.

I noticed this because I have a custom Q network, but never receive training=True.

mhe

**Comment by kbanoop** [comment]
Thanks for raising the issue! We haven't added support for the training flag in DQN or QNetwork yet. We added it to SAC here: https://github.com/tensorflow/agents/commit/e2a0fb41fa25c958fef05a0df651e74c715f7dd6#diff-64bc214264f68e3811d618b67fb8b9ab

Would you like to contribute a PR supporting it in DQN?

**Comment by mhe500** [comment]
Hi @kbanoop. Sure I'd be glad to. Let me review the changes I made to ensure they look right using what was done in SAC.

There are a few related subtle things  that I encountered related to D-DQN that go beyond just passing training=true that I had to change and I want to ensure I'm confident are correct. For example, the q_network ends up being invoked multiple time in D-DQN, so layer losses need to be captured right after the first invocation.

Will submit a PR in next few days. Thanks.

**Comment by kbanoop** [comment]
That sounds great, thanks Michael!

**Comment by mhe500** [comment]
Hi @kbanoop. See here: https://github.com/tensorflow/agents/pull/269.

**Comment by tfboyd** [comment]
Looks like this has been added to all of the agents now.  @mhe500 , Thank you for bringing this up and sorry your PR was not accepted; the change was needed.
