### ISSUE TITLE
Issue with test ddpg 

### ISSUE THREAD

**Issue by vedantammihir** [tensorflow/agents#259]
When I try to run the example DDPG test and eval scripts, I get the following issue:
module 'tensorflow' has no attribute 'enable_resource_variables'

If I change this line to:
tf.compat.v1.enable_resource_variables()

Then I get the following error:

RuntimeError: dataset.make_initializable_iterator is not supported when eager execution is enabled. Use `for element in dataset` instead.
  In call to configurable 'train_eval' (<function train_eval at 0x7f10910917a0>)

I am trying to avoid making too many changes to the provided script, but I had to change the environment due to not having mujoco:
    env_name="Pendulum-v0",
    env_load_fn=suite_gym.load,

**Comment by kuanghuei** [comment]
Which version of tensorflow do you use?

**Comment by jdossgollin** [comment]
I'm having the same problem! From a `pip freeze` I get
```
tf-agents-nightly==0.2.0.dev20191130
tf-estimator-nightly==2.0.0.dev2019113009
tf-nightly==2.1.0.dev20191130
tfp-nightly==0.9.0.dev20191130
```

**Comment by kuanghuei** [comment]
I think it's probably because you are using tf2 but running the v1 example (enable_resource_variables only exists in the v1 example)? I guess either running v2 examples or pinning tf version to 1.15 should work. Let me know if this solves the issue for you.

**Comment by ebrevdo** [comment]
As @kuanghuei said; you should be instead running the examples from [this directory](https://github.com/tensorflow/agents/tree/master/tf_agents/agents/ddpg/examples/v2).  If those still pose a problem, please reopen this issue.
