### ISSUE TITLE
TFPyEnvironment does not call the actual env._reset()

### ISSUE THREAD

**Issue by gokhansolak** [tensorflow/agents#261]
I created a custom environment that runs a custom Mujoco session in it. I exposed some custom methods from this environment to get custom attributes, e.g. the sim time. I don't want these attributes to be part of the observation and be used by the agent, but use this for another purpose.  Following the REINFORCE agent tutorial, I created a TFPyEnvironment wrapper with this environment passed.

After running ```tf_env.reset(); tf_env.step()```, I query env indirectly to access this attribute ```tf_env.pyenv.envs[0].get_my_attrb()```. However, it tells me that such attributes does not exist. (It works fine without the TFPyEnvironment wrapper)

Further examining it by putting a print statement in the original environment's __reset()_ method reveals that this method is actually not called during ```tf_env.reset(); tf_env.step()```. I suspect that TFPyEnvironment wrapper is not meant for custom environments or there are some patterns to follow in my PyEnvironment design, but I could not find it in the colabs or the md files under the docs folder. 

Is there a way to have custom attributes in a PyEnvironment and access them through a TFPyEnvironment wrapper? Why doesn't tf_env.reset() call the actual env._reset()?

Thank you in advance.

**Comment by sguada** [comment]
Not sure how are you creating the TFEnv and the PyEnv, and how are you passing one to the other.

Also not clear if you are using TF 2.x or TF 1.15, since one is Eager by default but no the other.

But the following should work:

```
py_env = MyCustomEnv()
tf_env = TFPyEnvironment(py_env)
tf_env.reset()
time_step = tf_env.step(action)
py_env.my_attribute
```

**Comment by gokhansolak** [comment]
Thank you for your response. 

My TF version was 1.x. The code you provided gave the same error (the attribute is not found).

After upgrading to TF 2.0, it started to work as I want.
