### ISSUE TITLE
[Question] call() in ddpg critic network

### ISSUE THREAD

**Issue by junhyeokahn** [tensorflow/agents#262]
I have a question about [call()](https://github.com/tensorflow/agents/blob/0d14c7431cb5ea1dce597e5047ba1ea3fc8ddd37/tf_agents/agents/ddpg/critic_network.py#L145) in ```critic_network.py``` in ddpg example.

In the bellman update, isn't value function at the terminal state are usually 0?
So I was thinking that when the ```step_type``` equals to 2, the call function should return zero.

**Comment by ebrevdo** [comment]
@kbanoop would know best; I believe he wrote this code.

**Comment by kbanoop** [comment]
Good question, but step_type=2/LAST could mean either it's a terminal state or it could also happen when an episode is terminated early. In the latter case, the value is not 0.

This is currently handled using time_step.discount which is 0 for terminal states:
https://github.com/tensorflow/agents/blob/1c4f2a0dd0abf3795a221dfc8a1771cff0e6ebb9/tf_agents/agents/ddpg/ddpg_agent.py#L311

But we are considering splitting step_type.LAST into step_type.TERMINATION and step_type.TRUNCATION, so we could do what you suggested.

Closing for now, please feel free to reopen if you have more questions.
