### ISSUE TITLE
How do I adjust ddpg example to fit my environment?

### ISSUE THREAD

**Issue by mauricerad** [tensorflow/agents#263]
I want to adjust this [example](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ddpg/examples/v2/train_eval.py) to BipedalWalker-v2 but the performance is very unsatisfactory.

In fact, the agent does not seem to improve much at all over time. The losses just increase over time and video shows he tries differing strategies but does not significantly improve.

Thanks in advance!

These are my input params:

def train_eval(
    root_dir,
    env_name='BipedalWalker-v2',
    eval_env_name=None,
    env_load_fn=suite_mujoco.load,
    num_iterations=2000000,
    actor_fc_layers=(400, 300),
    critic_obs_fc_layers=(400,),
    critic_action_fc_layers=None,
    critic_joint_fc_layers=(300,),
    # Params for collect
    initial_collect_steps=1000,
    collect_steps_per_iteration=1,
    num_parallel_environments=1,
    replay_buffer_capacity=100000,
    ou_stddev=0.2, #0.2
    ou_damping=0.15, #0.15
    # Params for target update
    target_update_tau=0.05, #0.05
    target_update_period=5,
    # Params for train
    train_steps_per_iteration=1,
    batch_size=64,
    actor_learning_rate=1e-4,
    critic_learning_rate=1e-3,
    dqda_clipping=None,
    td_errors_loss_fn=tf.compat.v1.losses.mean_squared_error, #tf.compat.v1.losses.huber_loss potential problem? MSE?
    gamma=0.995, #0.995
    reward_scale_factor=1.0,
    gradient_clipping=None,
    use_tf_functions=True,
    # Params for eval
    num_eval_episodes=10,
    eval_interval=10000,
    # Params for checkpoints, summaries, and logging
    log_interval=1000,
    summary_interval=1000,
    video_interval=100000,
    summaries_flush_secs=10,
    debug_summaries=False,
    summarize_grads_and_vars=False,
    eval_metrics_callback=None
    ):

**Comment by ebrevdo** [comment]
@oars do you know who would be able to help with this?

@mauricerad do you have a git repo showing your setup?  or are you just checking out tf_agents and modifying the existing ddpg train_eval example?

**Comment by ebrevdo** [comment]
Assigning Oscar to triage.  Perhaps Sam would be able to help with this?

**Comment by mauricerad** [comment]
@ebrevdo 
I'm just checking it out, don't have a git repo. Thanks for your reply!

**Comment by ebrevdo** [comment]
Were you able to resolve this issue?

**Comment by mauricerad** [comment]
Sadly not yet, I have further worked on my code though, I added you as a collaborator to view my code if you would like.

**Comment by mauricerad** [comment]
[This should link you to my depository.](https://github.com/mauricerad/DDPG)
Thanks for the help so far!
