### ISSUE TITLE
ParallelPyEnvironments do not work on Windows

### ISSUE THREAD

**Issue by NeoExtended** [tensorflow/agents#264]
Today I was trying to create a PPO agents with a ParallelPyEnvironment. While the example under agent/ppo works well on linux the creation of child processes for the parallel environment fails under windows. 
I tried to debug the problem and it seems that the child process creation under Windows calls the modified __getattr__ method, which then blocks forever, because it calls the receive method on an empty pipe.
I am not really sure how to create a simple workaround so I opened this issue for now.

**Comment by ebrevdo** [comment]
What kind of environment are you working in?  Is it compute heavy?  If not, you can try BatchedPyEnvironment for now.

**Comment by ebrevdo** [comment]
Unfortunately I'm not sure we have many dev boxes for testing on Windows.  Have you had any experience with python subprocess pipes in windows, specifically know any gotchas to look out for when it comes to race conditions, opening pipes, etc?

**Comment by NeoExtended** [comment]
I am currently working with the BreakoutNoFrameskip-v4 environment because I started a few experiments with DQN last week and wanted to compare the results to PPO training. I also plan on using a custom environment in the future, but that won't be heavier than Breakout. 
The BatchedPyEnvironment seems to work for now, though im now running into a different problem later on =(. Maybe you can suggest some parameters how many parallel environments are realistic? Also I wanted to have shared convolutional layers between the actor and value net and do not really know how that should work. (Sorry for leaving the scope of this issue here. I'm just new to reinforcement learning and try to understand how everything works for now.)   
Unfortunately I don't have much experience with multiprocessing on windows either. It seems that the forking of the process somehow triggers the `__getattr__` method early, but i don't know why or what should be returned in that case. I tried the same code on a Linux machine and everything worked fine there, so its definetly a Windows related problem.

**Comment by JCMiles** [comment]
Hi, don't know if this can help but I was able to run 8 parallel custom environments on Windows x64  by following the workaround suggested by corypaik here: https://github.com/tensorflow/agents/issues/219

**Comment by NeoExtended** [comment]
Thank you very much, thats exactly the same issue! The solution works as well - great 👍 .

**Comment by NeoExtended** [comment]
Is it best to close the issue, since it is a duplicate now?

**Comment by kbanoop** [comment]
That sounds good, let me close the issue.
