### ISSUE TITLE
Clarification on defining discrete, nominal actions

### ISSUE THREAD

**Issue by matthew-hsr** [tensorflow/agents#265]
Hi! I am transitioning from keras-rl to tf_agents and would really appreciate some clarifications on defining discrete action specs.

I am buliding a custom environment in which the 9 possible actions are discrete and nominal (i.e. not ordinal) and I hope to run DQN on it. Does setting the action spec as an integer as follows assume any ordinal relationship?

`self._action_spec = array_spec.BoundedArraySpec(
            shape=(), dtype=np.int32, minimum=0, 
            maximum=8, name='action')`
            
If that's the case, can I define the action space to be some one-hot encoded matrix as follows? How could I enforce the requirement that there must only be one 1 and eight 0s?

`self._action_spec = array_spec.BoundedArraySpec(
            shape=((3, 3)), dtype=np.int32, minimum=0, 
            maximum=1, name='action')`
            
Thanks in advance!

**Comment by sguada** [comment]
`self._action_spec = array_spec.BoundedArraySpec( shape=(), dtype=np.int32, minimum=0, maximum=8, name='action')` is the right way to define discrete or nominal actions, they are assumed independent.

**Comment by ebrevdo** [comment]
Please reopen if there is still confusion.

**Comment by matthew-hsr** [comment]
Thanks a lot!
