### ISSUE TITLE
A novice question about shape

### ISSUE THREAD

**Issue by matthew-hsr** [tensorflow/agents#266]
Hello! I encountered a shape mismatch error when trying to run `1_dqn_tutorial.ipynb` on my own environment. I defined the observation_spec to be `observation=TensorShape([3, 3, 3])`, but it seems like the random_policy added two extra dimensions, making it `observation=TensorShape([1, 1, 3, 3, 3])`

How may I remedy this mismatch? Below is the code I ran and the error generated.

Thanks in advance!

`random_policy = random_tf_policy.RandomTFPolicy(train_env.time_step_spec(),
                                                train_env.action_spec())`
`random_policy.action(time_step)`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-229-6b48927ed1bd> in <module>
----> 1 random_policy.action(time_step)

~\AppData\Roaming\Python\Python37\site-packages\tf_agents\policies\tf_policy.py in action(self, time_step, policy_state, seed)
    276     if self._automatic_state_reset:
    277       policy_state = self._maybe_reset_state(time_step, policy_state)
--> 278     step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)
    279 
    280     def clip_action(action, action_spec):

~\AppData\Roaming\Python\Python37\site-packages\tf_agents\utils\common.py in with_check_resource_vars(*fn_args, **fn_kwargs)
    129         # We're either in eager mode or in tf.function mode (no in-between); so
    130         # autodep-like behavior is already expected of fn.
--> 131         return fn(*fn_args, **fn_kwargs)
    132       if not resource_variables_enabled():
    133         raise RuntimeError(MISSING_RESOURCE_VARIABLES_ERROR)

~\AppData\Roaming\Python\Python37\site-packages\tf_agents\policies\random_tf_policy.py in _action(self, time_step, policy_state, seed)
     87       policy_info = tensor_spec.sample_spec_nest(self._info_spec)
     88     else:
---> 89       outer_dims = nest_utils.get_outer_shape(time_step, self._time_step_spec)
     90 
     91       action_ = tensor_spec.sample_spec_nest(

~\AppData\Roaming\Python\Python37\site-packages\tf_agents\utils\nest_utils.py in get_outer_shape(nested_tensor, spec)
    390   num_outer_dims = (len(first_tensor.shape) - len(first_spec.shape))
    391   if not is_batched_nested_tensors(
--> 392       nested_tensor, spec, num_outer_dims=num_outer_dims):
    393     return []
    394 

~\AppData\Roaming\Python\Python37\site-packages\tf_agents\utils\nest_utils.py in is_batched_nested_tensors(tensors, specs, num_outer_dims)
    142       'And spec_shapes:\n   %s' %
    143       (num_outer_dims, tf.nest.pack_sequence_as(tensors, tensor_shapes),
--> 144        tf.nest.pack_sequence_as(specs, spec_shapes)))
    145 
    146 

ValueError: Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1.
Saw tensor_shapes:
   TimeStep(step_type=TensorShape([1]), reward=TensorShape([1]), discount=TensorShape([1]), observation=TensorShape([1, 1, 3, 3, 3]))
And spec_shapes:
   TimeStep(step_type=TensorShape([]), reward=TensorShape([]), discount=TensorShape([]), observation=TensorShape([3, 3, 3]))

**Comment by sguada** [comment]
The shape in the TensorSpec represents the shape of the observations without any batch or time dimension.
In this case seems to be an error due to having 2 extra dimensions, instead of just the batch dimension.

Could print the following `train_env.time_step_spec()`, `train_env.action_spec()` and `time_step`?

**Comment by Queeq** [comment]
I have similar problem (also in the code based on 1_dqn_tutorial). In my case traceback is like this:

```
<cut>
  File "/Users/queeq/repos/wat/wat/models/rl.py", line 144, in step_data
    action_step = policy.action(time_step)
  File "/Users/queeq/repos/wat/venv/lib/python3.7/site-packages/tf_agents/policies/tf_policy.py", line 278, in action
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)
  File "/Users/queeq/repos/wat/venv/lib/python3.7/site-packages/tf_agents/utils/common.py", line 131, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "/Users/queeq/repos/wat/venv/lib/python3.7/site-packages/tf_agents/policies/random_tf_policy.py", line 89, in _action
    outer_dims = nest_utils.get_outer_shape(time_step, self._time_step_spec)
  File "/Users/queeq/repos/wat/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 392, in get_outer_shape
    nested_tensor, spec, num_outer_dims=num_outer_dims):
  File "/Users/queeq/repos/wat/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 144, in is_batched_nested_tensors
    tf.nest.pack_sequence_as(specs, spec_shapes)))
ValueError: Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1.
Saw tensor_shapes:
   TimeStep(step_type=TensorShape([1]), reward=TensorShape([1]), discount=TensorShape([1]), observation=TensorShape([1, 16, 8]))
And spec_shapes:
   TimeStep(step_type=TensorShape([]), reward=TensorShape([]), discount=TensorShape([]), observation=TensorShape([16, 7]))
```

The requested `print()` results are this:
```
TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation=BoundedTensorSpec(shape=(16, 7), dtype=tf.float32, name='observation', minimum=array(0., dtype=float32), maximum=array(3.4028235e+38, dtype=float32)))
BoundedTensorSpec(shape=(), dtype=tf.int64, name='action', minimum=array(0), maximum=array(8))
TimeStep(step_type=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, reward=<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, discount=<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, observation=<tf.Tensor: shape=(1, 16, 8), dtype=float32, numpy=
array([[[-1.6920043e-02, -1.6680712e-02, -1.6445067e-02, -1.6525082e-02,
         -6.8540297e-02,  1.2200000e+00,  1.8434329e-02,  3.6057547e-02],
<cut>
        [-2.0232581e-02, -2.0358507e-02, -1.9853242e-02, -2.0298900e-02,
         -9.0636358e-02, -1.6000000e-01,  3.0374503e-01, -2.9954997e-01]]],
      dtype=float32)>)
```

**Comment by Queeq** [comment]
I think I narrowed down the place where one additional dimension gets added. I convert gym environment to TF one like this:
```
from tf_agents.environments import tf_py_environment, suite_gym
tfenv = tf_py_environment.TFPyEnvironment(suite_gym.wrap_env(env))
```

When we do `time_step = env.current_time_step()`, it calls `tf_agents.environments.tf_py_environment.TFPyEnvironment._current_time_step()`, which operates on `self._time_step` that is set by `self._env.reset()`. Not sure what's going on there, but `self._time_step` gets shapes in question set when
```
tf.numpy_function(
          _isolated_current_time_step_py,
          [],  # No inputs.
          self._time_step_dtypes,
          name='current_time_step_py_func')
```
is called.

**Comment by Queeq** [comment]
Digging deeper of what's happening when `_isolated_current_time_step_py()` is called. Here's the stack trace:
```
batch_nested_array, nest_utils.py:482
_reset, batched_py_environment.py:130
reset, py_environment.py:141
_current_time_step_py, tf_py_environment.py:221
_execute, tf_py_environment.py:195
_isolated_current_time_step_py, tf_py_environment.py:225
py_func_common, script_ops.py:488
numpy_function, script_ops.py:591
_current_time_step, tf_py_environment.py:232
wrapper, api.py:292
current_time_step, tf_environment.py:187
step_data, rl.py:143
_fill_buffer, rl.py:140
__init__, rl.py:128
<module>, main.py:85
```
This is how `tf_agents.utils.nest_utils.batch_nested_array()` looks like:
```python
def batch_nested_array(nested_array):
  return tf.nest.map_structure(lambda x: np.expand_dims(x, 0), nested_array)
```
`nested_array` at this point is this:
```
TimeStep(step_type=array(0, dtype=int32), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([[ 1.9072577e-01,  1.9009688e-01,  1.9171205e-01,  1.9074497e-01,
        -3.7446010e-01, -4.0000001e-01, -2.9617187e-01, -3.1588808e-01],
<cut>
       [ 1.9589201e-01,  1.9661075e-01,  1.9689099e-01,  1.9610648e-01,
         1.8412291e+00,  4.1999999e-01, -2.4788415e-01,  4.4457493e+00]],
      dtype=float32))
```
So its shape is still correct. But then `np.expand_dims()` adds additional dimension and `batch_nested_array()` returns `TimeStep` with expanded arrays.

**Comment by Queeq** [comment]
I am terribly sorry, but it turns out my problem was due to my custom environment spitting observation in the wrong shape ([16, 8] instead of [16, 7]), and this is why it failed here. One additional dimension does not cause any problems. I'll keep my messages above though, maybe they'll help troubleshooting your problem.

**Comment by rohitderaj** [comment]
Hey,
I would appreciate it a lot if you could help me out. I am stuck in a similar situation.
My  custom environment spec action_spec and observation_spec are as follows:
 
 self._action_spec = array_spec.BoundedArraySpec(shape=(), dtype=np.int64, minimum=0, maximum=2, name='action')   self._observation_spec = array_spec.BoundedArraySpec(shape=(3,), dtype=np.float32, minimum=[-15, -15, 0],
                                                             maximum=[15, 15, 2 * np.pi], name='observation') 

I initialize my observation as  np.array[0,-6,0] which is a (3,) shaped array that fits the specs, but just like everyone already stated the array to tensors conversion adds additional dims. 

the error that I am getting is:

ValueError: Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1.
Saw tensor_shapes:
   [TensorShape([1]), TensorShape([1, 1, 3]), TensorShape([1, 1]), TensorShape([1]), TensorShape([1]), TensorShape([1])]
And spec_shapes:
   [TensorShape([]), TensorShape([3]), TensorShape([]), TensorShape([]), TensorShape([]), TensorShape([])]

Not sure where my error is.

Thanks in advance
