### ISSUE TITLE
Can we expect a release any time soon ?

### ISSUE THREAD

**Issue by christianhidber** [tensorflow/agents#267]
We are currently using tf-agents for prototype-style client project. Results are promising and we would love to head towards production. Can we expect an "official" tf-agents release any time soon ? From our experience clients are not at ease to go to any form of production with a "nightly-build". Currently that's the only thing that's preventing us to go ahead.

**Comment by sguada** [comment]
Definitely, we are working hard to get it out today or tomorrow. Check it at https://github.com/tensorflow/agents/tree/r0.3.0

**Comment by christianhidber** [comment]
Fantastic!
