### ISSUE TITLE
Training TF-agents using custom OpenAI Gym environments

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/agents#27]
I created a custom Gym environment. I was wondering if it would possible to use TF-agents with my custom environment? Could you point me to documentation if this feature is available?

**Comment by PeterZhizhin** [comment]
Have you tried `tf_agents.environments.gym_wrapper`?

**Comment by sibyjackgrove** [comment]
No, haven't tried that. Is there any example Colab notebook showing how to use it?

**Comment by oars** [comment]
You can look at the [suite_gym.py](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/suite_gym.py) to see how the wrapper is used.

If you register your environment with `gym` such that `gym.make('YourCustomEnv`) works, then you can load it through `suite_gym.load('YourCustomEnv`)` and it will apply the `gym_wrapper` @PeterZhizhin referenced.

**Comment by sibyjackgrove** [comment]
Thanks for the solution, @oars I tried it using suite_gym.load('YourCustomEnv') and it works. The only thing I had to do extra was to add `import gym_YourCustomEnv` before using `suite_gym.load()`.
I was also able to convert my environment to the TensorFlow environment using `tf_py_environment.TFPyEnvironment(env)`.
