### ISSUE TITLE
Can the call to 'tf.compat.v1.enable_v2_behavior()' be avoided ?

### ISSUE THREAD

**Issue by christianhidber** [tensorflow/agents#271]
Is there a way to use tfagents without having to call 'tf.compat.v1.enable_v2_behavior()' ? 
If not, are there plans to get rid of it ?

[it interfers with other packages we are using]

**Comment by oars** [comment]
If you run in 1.15 and want to use eager mode that is required. If you install TF2.0 then it is not required, but it is there in the examples for compatibility with different versions.

**Comment by christianhidber** [comment]
Thanks. That actually helped a lot to identify the root cause (another package was calling tf.compat.v1.disable_eager_execution()).
