### ISSUE TITLE
is TFUniformReplayBuffer thread safe?

### ISSUE THREAD

**Issue by wsun66** [tensorflow/agents#273]
I am planning to spawn a new thread (process) to collect data from environment during training. Is the replaybuffer thread safe?

**Comment by kbanoop** [comment]
Not sure about your exact use case, but the uniform replay buffer uses a critical section to allow parallel reads and writes:

https://github.com/tensorflow/agents/blob/45022b764dde8ab351dc737da7c5b0888d656782/tf_agents/replay_buffers/tf_uniform_replay_buffer.py#L154

**Comment by wsun66** [comment]
Thanks, Kbanoop.
Collecting experiences from our environment is pretty slow. I am trying to parallelize traing SAC agent and collecting experiences from environment. Hope it will speed up training. But I am concerned if the replaybuffer is thread safe. If Critical section allows parallel reads and writes, then my solution should be fine. Thanks,

**Comment by sguada** [comment]
Have you tried using ParallelEnvironment?

**Comment by wsun66** [comment]
No, I have not. I am going to give a try. Thanks, Sguada!
