### ISSUE TITLE
Wrapping a loaded policy model with PyTFPolicy

### ISSUE THREAD

**Issue by gokhansolak** [tensorflow/agents#274]
I load a TFPolicy model that I saved using a PolicySaver, and wrap it with PyTFPolicy so that I can use it with numpy types:

```
loaded_policy = PyTFPolicy(tf.saved_model.load(args.policy))
```
It complains that "Policy should implement tf_policy.Base". Apparently, `tf.saved_model.load(args.policy)` does not return a TFPolicy, although the one I saved was a TFPolicy (specifically a GreedyPolicy). Loaded object is a `saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject`. How can I convert it to a policy? 

If it is not possible, what is the best way to cast numpy time steps into TF time steps? (As is done by the TFPyEnvironment wrapper) Maybe then I can use SavedModel's concrete functions without a policy wrapper.

Thank you.

**Comment by gokhansolak** [comment]
Actually this doesn't only happen for a loaded policy but also any GreedyPolicy.

When I follow the SAC minitaur tutorial and add these lines following the creation of eval_policy:
```
# existing code:
eval_policy = greedy_policy.GreedyPolicy(tf_agent.policy)
collect_policy = tf_agent.collect_policy

# added code:
saver = PolicySaver(eval_policy, batch_size=1)

# test saving py_tf_policy
from tf_agents.policies.py_tf_policy import PyTFPolicy
saver_test = PolicySaver(PyTFPolicy(eval_policy), batch_size=1)
saver_test.save('py_tf_policy_test')
```

It will give the same error at the creation of PyTFPolicy: "TypeError: policy is not a TFPolicy." 

That is unexpected because GreedyPolicy extends tf_policy.Base. 

_Edit: Error occurs at the creation of PolicySaver, not PyTFPolicy._

**Comment by gokhansolak** [comment]
I tried to save the policy as a Py policy so that I can load it as it is, but it doesn't work because PolicySaver expects a TFPolicy. 

Is there are way to save/load a py policy?

**Comment by sguada** [comment]
There a two options relax the check in PyTFPolicy or just use the loaded TFPolicy directly if you are using TF 2.0, since it should work with numpy inputs too.

**Comment by gokhansolak** [comment]
I tried it by giving np.zeros of desired size, since I was using FlattenEnvironment:
```
>>> policy_state = loaded_policy.get_initial_state()
>>> policy_state
()
>>> time_step = ts.transition(np.zeros(19), reward=0, discount=1.0)
>>> loaded_policy.action(time_step, policy_state)
```
But fails with the error:
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * TimeStep(step_type=<tf.Tensor 'time_step:0' shape=() dtype=int32>, reward=<tf.Tensor 'time_step_1:0' shape=() dtype=float32>, discount=<tf.Tensor 'time_step_2:0' shape=() dtype=float32>, observation=<tf.Tensor 'time_step_3:0' shape=(19,) dtype=float64>)
    * ()
  Keyword arguments: {}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (2 total):
    * TimeStep(step_type=TensorSpec(shape=(1,), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(1,), dtype=tf.float32, name='reward'), discount=TensorSpec(shape=(1,), dtype=tf.float32, name='discount'), observation=TensorSpec(shape=(1, 19), dtype=tf.float64, name='observation'))
    * ()
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * TimeStep(step_type=TensorSpec(shape=(1,), dtype=tf.int32, name='time_step/step_type'), reward=TensorSpec(shape=(1,), dtype=tf.float32, name='time_step/reward'), discount=TensorSpec(shape=(1,), dtype=tf.float32, name='time_step/discount'), observation=TensorSpec(shape=(1, 19), dtype=tf.float64, name='time_step/observation'))
    * ()
  Keyword arguments: {}
```
I will try relaxing PyTFPolicy.

I use TF 2, and tf-agents nightly.

**Comment by ebrevdo** [comment]
It's expecting batched inputs with batch_size 1.  Try passing reward=[0], discount=[1.0] and (i think) np.zeros((1, 19)) as inputs.

**Comment by gokhansolak** [comment]
It worked, thank you.

In summary, the solution is saving the policy as a TFPolicy, then load it as it is and use with batched numpy inputs:
```
>>> loaded_policy = tf.saved_model.load('policy_19823')
>>> policy_state = loaded_policy.get_initial_state()
>>> time_step = ts.transition(np.zeros((1, 19)), reward=[0], discount=[1.0])
>>> loaded_policy.action(time_step, policy_state)
PolicyStep(action=<tf.Tensor: id=1285, shape=(1, 3), dtype=float32, numpy=array([[-0.19553825, -0.05113029, -0.23740204]], dtype=float32)>, state=(), info=())
```
