### ISSUE TITLE
Issue with using the combination of TimeLimit wrapper, ParallelPyEnvironment and TfPyEnvironment.

### ISSUE THREAD

**Issue by mch5048** [tensorflow/agents#279]
Hi, I'm really enjoying this wonderful API in doing my research.

Currently, I'm building a parallelized learning system based on the custom PythonEnvironment.

Let my custom environment as CustomEnv, then what I'm doing is like below.

'
ctor = functools.partial(CustomEnv, args)

py_env = ParallelPyEnvironment(
[ctor] * num_of_parallel_envs)

py_env = wrappers.TimeLimit(py_env)

tf_Env = TFPyEnvironment(py_env)
'

What I'm curious about is that if the number of env is N, then all the data acquired from 

the environment is batched and have shape of (N, ...).

But, this causes some minor errors in TimeLimit wrapper in the line cited below.

https://github.com/tensorflow/agents/blob/bc0d8625755d7999219d37a8c29c87af7e692ab6/tf_agents/environments/wrappers.py#L111

This is because time.step.is_last() is a list of Bools, which isn't compatible with if statement.

So, I'm doubtful if I'm doing wrong with the order of wrapping with the environment.

Is there any solution for this?

Thanks in advance and Happy New Year!

**Comment by leroidauphin** [comment]
Do you see the same problem if you wrap each instance of your CustomEnv in the TimeLimit, before batching them together using the ParallelPyEnvironment?

**Comment by mch5048** [comment]
@leroidauphin Thank you for the suggestions. I tried to do as you mentioned, but couldn't come up with the way how I can implement in code. Since parallelpyenv wrapper requires the constructor of the env class, could you give me some hints to acquire the callable of timelimit wrapped custom environments ?
Thanks in advance!
