### ISSUE TITLE
MultiDiscrete spaces support

### ISSUE THREAD

**Issue by PeterZhizhin** [tensorflow/agents#28]
Hello. Thank you for an amazing product, I am experimenting with this right now.

I would like to know, why `MultiDiscrete` spaces for Gym wrappers are not supported. I don't see any reasons why it should be difficult to support the space. It should be similar to a tuple of discrete spaces which you already support.

Could you please provide some clarification?

**Comment by oars** [comment]
Simply need coverage of the space. We haven't had an env that required adding that. It should be a simple mapping of the space to specs which could be added to `_spec_from_gym_space` in the `gym_wrapper` module.
