### ISSUE TITLE
dqn_tutorial - initial_collect_steps is defined to be 1000 but not used anywhere...

### ISSUE THREAD

**Issue by guyk1971** [tensorflow/agents#281]
The call to collect_data in Data Collection (section 1.8) should have been:
`collect_data(train_env, random_policy, replay_buffer, initial_collect_steps)` 
right ?

**Comment by ebrevdo** [comment]
Thanks for catching this.  @adammichaelwood could you send a fix?

i guess we also need to set `initial_collect_steps` to `100` so the tutorial stays consistent.

**Comment by guyk1971** [comment]
Sure, I'll send a fix. Pull request, right ?
Thanks

**Comment by tfboyd** [comment]
fixed
