### ISSUE TITLE
Problem when running dqn on FrozenLake 

### ISSUE THREAD

**Issue by guyk1971** [tensorflow/agents#283]
Hi,
First, Great Work on TF Agents !! :)
I encountered a problem on running train_eval and also the dqn_tutorial colab when changing the environment to FrozenLake .
The code that I tried : 
```
example_environment = tf_py_environment.TFPyEnvironment(suite_gym.load('FrozenLake-v0'))
example_policy = random_tf_policy.RandomTFPolicy(example_environment.time_step_spec(),
                                                example_environment.action_spec())
time_step = example_environment.reset()
action_step=example_policy.action(time_step)
time_step=example_environment.step(action_step.action)
```
I got the following error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-9173aae14ed4> in <module>
----> 1 time_step=example_environment.step(action_step.action)

~/workspace/study/remote/agents/tf_agents/environments/tf_environment.py in step(self, action)
    230           corresponding to `observation_spec()`.
    231     """
--> 232         return self._step(action)
    233 
    234     def render(self):

~/anaconda3/envs/rltf20/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    290   def wrapper(*args, **kwargs):
    291     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 292       return func(*args, **kwargs)
    293 
    294   if inspect.isfunction(func) or inspect.ismethod(func):

.... (for clarity, I removed parts of the message)

~/anaconda3/envs/rltf20/lib/python3.6/site-packages/gym/envs/toy_text/discrete.py in step(self, a)
     52 
     53     def step(self, a):
---> 54         transitions = self.P[self.s][a]
     55         i = categorical_sample([t[0] for t in transitions], self.np_random)
     56         p, s, r, d= transitions[i]

**TypeError: unhashable type: 'numpy.ndarray'**
I work with tensorflow 2.0

Keep up the great work ! a very useful library !

**Comment by guyk1971** [comment]
**Update** : after spending some time debugging it, it turns out that FrozenLake uses the action as a key to a dictionary of transitions. since 'action' is numpy scalar (e.g. array(2) ) it is not hashable and cant be used as index.
as a temporary solution, I have added the following line in `gym_wrapper.GymWrapper._step(action)` method:
```
def _step(self,action):
    .... 
    action = np.asscalar(action) if self._action_is_discrete else action
    # and from here continue as in the original file
    observation, reward, self._done, self._info = self._gym_env.step(action)     
    ....
```
I have tested it on various environments and it seems to be working well so far... 
if its invalid fix (or should be done in a different way) let me know.
else, not sure if there arent any additional implications of this fix (otherwise I'd put pull request).

Thanks a lot for this great framework !

**Comment by kuanghuei** [comment]
Thanks for raising this! The proposed fix looks like the right thing to do. Would you mind to do a pull request so we can review it?

**Comment by guyk1971** [comment]
Hi, Kuang-Huei
sure, I'll do it.

Thanks and keep up the great work on TFAgents !
Guy

**Comment by guyk1971** [comment]
Hi, Kuang-Huei
Can you pls guide me how to open the pull request ?

I have already got a fork of tf-agent in my account but I admit wasnt that
organized when making the fix. the commit that include my fix was done to
master that already includes some additional draft files that I'm using.
so I cant propose the master branch of my fork for the pull request.

Given that, what are my options to do pull request to TF-Agents ?

Thanks,
Guy

**Comment by kuanghuei** [comment]
This should be a Google or stackoverflow question but:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by guyk1971** [comment]
Thanks. I've already done it.

בתאריך יום ג׳, 21 בינו׳ 2020, 21:00, מאת Kuang-Huei Lee ‏<
notifications@github.com>:

**Comment by ebrevdo** [comment]
Great; were you able to submit the PR?  If so, we can close this bug.

**Comment by guyk1971** [comment]
yes, I have submitted it.  I guess you need to verify the fix and merge.
Thanks,

Guy

**Comment by tfboyd** [comment]
Looks like the PR was not created and I don't see a link to the commit in the users repo.  This was over a year ago at this point.  I am closing it for now.  I am sorry we did not get this resolved.
