### ISSUE TITLE
we need install x11-utils for tutorials/1_dqn_tutorial.ipynb

### ISSUE THREAD

**Issue by clockzhong** [tensorflow/agents#290]
Hi, 

When I run the tutorials/1_dqn_tutorial.ipynb in colab(https://colab.research.google.com/), I found it always report errors that: no xdpyinfo found.

After I installled x11-utils in it, it works. So please change the first section of 1_dqn_tutorial.ipynb from:
```
# Note: If you haven't installed the following dependencies, run:
!apt-get install -y xvfb
!pip install 'gym==0.10.11'
!pip install 'imageio==2.4.0'
!pip install PILLOW
!pip install 'pyglet==1.3.2'
!pip install pyvirtualdisplay
!pip install --upgrade tensorflow_probability
!pip install tf-agents
try:
  %tensorflow_version 2.x
except:
  pass

```
To:
```
# Note: If you haven't installed the following dependencies, run:
!apt-get install x11-utils
!apt-get install -y xvfb
!pip install 'gym==0.10.11'
!pip install 'imageio==2.4.0'
!pip install PILLOW
!pip install 'pyglet==1.3.2'
!pip install pyvirtualdisplay
!pip install --upgrade tensorflow_probability
!pip install tf-agents
try:
  %tensorflow_version 2.x
except:
  pass

```

**Comment by ebrevdo** [comment]
@adammichaelwood ptal.

**Comment by clockzhong** [comment]
6_reinforce_tutorial.ipynb also have same problem, and could be resolved with the same solution, adding one line for env setup:
!apt-get install x11-utils

**Comment by clockzhong** [comment]
With latest version codes, we still face the warning log in colab env:
"xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!"
But the following codes could work very well, I don't know the exact reason, but this issue still could be considered as fixed, I believe.

**Comment by ebrevdo** [comment]
thanks!
