### ISSUE TITLE
Somthing wrong in tutorials/4_drivers_tutorial.ipynb

### ISSUE THREAD

**Issue by clockzhong** [tensorflow/agents#291]
When I execute it in colab, with both python2&python3, it report the following errors:

```
AttributeErrorTraceback (most recent call last)
<ipython-input-5-829a4093e8a4> in <module>()
      7 
      8 
----> 9 num_episodes = tf_metrics.NumberOfEpisodes()
     10 env_steps = tf_metrics.EnvironmentSteps()
     11 observers = [num_episodes, env_steps]

10 frames
/tensorflow-2.1.0/python2.7/tensorflow_core/python/ops/resource_variable_ops.pyc in _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name, graph_mode, initial_value)
    166     handle_data = cpp_shape_inference_pb2.CppShapeInferenceResult.HandleData()
    167     handle_data.is_set = True
--> 168     handle_data.shape_and_type.append(
    169         cpp_shape_inference_pb2.CppShapeInferenceResult.HandleShapeAndType(
    170             shape=shape.as_proto(), dtype=dtype.as_datatype_enum))

AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
```

**Comment by clockzhong** [comment]
tutorials/5_replay_buffers_tutorial.ipynb also have problems.
```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-456065d0248c> in <module>()
     11     tf_env.action_spec(),
     12     q_network=q_net,
---> 13     optimizer=tf.compat.v1.train.AdamOptimizer(0.001))
     14 
     15 replay_buffer_capacity = 1000

6 frames
/usr/local/lib/python3.6/dist-packages/tf_agents/specs/tensor_spec.py in sample_spec_nest(structure, seed, outer_dims)
    292       contains a `SparseTensorSpec`.
    293   """
--> 294   seed_stream = tfp.util.SeedStream(seed=seed, salt="sample_spec_nest")
    295 
    296   def sample_fn(spec):

AttributeError: module 'tensorflow_probability.python.util' has no attribute 'SeedStream'
  In call to configurable 'DqnAgent' (<function DqnAgent.__init__ at 0x7f09cc7ef9d8>)

```

It seems the tenserflow2.x' driver module has been updated and those tutorials haven't catch up them

**Comment by ebrevdo** [comment]
What version of tensorflow_probability do you have installed?  @kbanoop can you take a look at the metrics issue?

**Comment by clockzhong** [comment]
@ebrevdo 
It should be 0.7.0 as I print it this way:
```
import tensorflow_probability as tfp
print(tfp.__version__)
0.7.0
```
This should be the latest official released version, because I run this tutorial in google's colab environment: https://colab.research.google.com/

**Comment by clockzhong** [comment]
6_reinforce_tutorial.ipynb also have similar problem, after running the following section codes:


```
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)

train_step_counter = tf.compat.v2.Variable(0)

tf_agent = reinforce_agent.ReinforceAgent(
    train_env.time_step_spec(),
    train_env.action_spec(),
    actor_network=actor_net,
    optimizer=optimizer,
    normalize_returns=True,
    train_step_counter=train_step_counter)
tf_agent.initialize()

```
We'll get the following errors:




```
AttributeError                            Traceback (most recent call last)
<ipython-input-13-efa000aaccb1> in <module>()
      9     optimizer=optimizer,
     10     normalize_returns=True,
---> 11     train_step_counter=train_step_counter)
     12 tf_agent.initialize()

6 frames
/usr/local/lib/python3.6/dist-packages/tf_agents/specs/tensor_spec.py in sample_spec_nest(structure, seed, outer_dims)
    292       contains a `SparseTensorSpec`.
    293   """
--> 294   seed_stream = tfp.util.SeedStream(seed=seed, salt="sample_spec_nest")
    295 
    296   def sample_fn(spec):

AttributeError: module 'tensorflow_probability.python.util' has no attribute 'SeedStream'
  In call to configurable 'ReinforceAgent' (<function ReinforceAgent.__init__ at 0x7fe698e46bf8>)`

```

**Comment by clockzhong** [comment]
@kbanoop 
According to the error logs I've reported, it seems they are two different issues about modules version mismatch:
1. 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
2. AttributeError: module 'tensorflow_probability.python.util' has no attribute 'SeedStream'
  In call to configurable 'DqnAgent' (<function DqnAgent.__init__ at 0x7f09cc7ef9d8>)

Should we trace them in this one issue or divide it to two issues to trace?

**Comment by clockzhong** [comment]
After Google's release of tensorflow_probability was upgraded from 0.7.0 to 0.9.0, the 2nd issue was fixed already, it's confirmed in colab.
I'll check the status of the 1 issue, it's about protobuf's version.

**Comment by clockzhong** [comment]
I've tried to verify the 1st error:
'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
with 4_drivers_tutorial.ipynb, and found it's also fixed, I couldn't duplicate it now. It seems the line code:
`!pip install --upgrade tensorflow-probability`
fixed two issues. Can I close this issue?

**Comment by kbanoop** [comment]
Yes it seems like this commit fixed the issue: https://github.com/tensorflow/agents/commit/cdb234491c3ef3762084e1d44cf81e7bd11855b0

I think we should make a release that installs the correct tfp version rather than upgrade. But closing the issue for now.
