### ISSUE TITLE
suite_gym.load() default for max_episode_steps

### ISSUE THREAD

**Issue by nataliedurgin** [tensorflow/agents#293]
Re: https://github.com/tensorflow/agents/issues/137, perhaps the `suite_gym.load()` default for `max_episode_steps` should be `0` instead of `None` as well to fully eradicate this bug? 
 
When using `suite_gym.load()` on a custom gym environment, for which no `max_episode_steps` is set, I am still getting this `TypeError`. 

This works:  `suite_gym.load('registered-custom-env', max_episode_steps=0)`
This does not:  `suite_gym.load('registered-custom-env')`

This is not surprising, since `suite_gym.load()` is calling `wrap_env()` and in that call, we propagate `max_episode_steps=None` which overrides the new `wrap_env()` default, `max_episode_steps=0` that has been corrected thus far in this ticket (https://github.com/tensorflow/agents/issues/137). 

See:
- https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L35
- https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L72

This does not seem to be a problem for many of the canonical gym environments, because `max_episode_steps` is set. E.g.

- `gym.spec('CartPole-v0').max_episode_steps` --> 200
- `gym.spec('CartPole-v1').max_episode_steps` --> 500

One might argue that `None` is a more intuitive default for max_episode_steps than 0. In which case, perhaps the comparison should just be `if max_episode_steps:` instead of, 

https://github.com/tensorflow/agents/blob/2b75de602bd27665b9288250a774c32b01dbf8f3/tf_agents/environments/suite_gym.py#L125

But I defer to those who understand the implications better than I do.

**Comment by kbanoop** [comment]
Thanks for raising this, I believe you are right. None seems like a more reasonable default to me, so I will try to send a PR to change the comparison as you suggest.
