### ISSUE TITLE
Error in EncodingNetwork when specifying only 1 convolution layer

### ISSUE THREAD

**Issue by marconardelli** [tensorflow/agents#296]
Encoding network returns an error when you specify only one convolution layer:

```
      for config in conv_layer_params:
        if len(config) == 4:
          (filters, kernel_size, strides, dilation_rate) = config
        elif len(config) == 3:
          (filters, kernel_size, strides) = config
          dilation_rate = (1, 1) if conv_type == '2d' else (1,)
        else:
          raise ValueError(
              'only 3 or 4 elements permitted in conv_layer_params tuples')
```
in this portion of code the for loop takes the argument of the single layer and returns an error because is not possible to return the len of an integer.

**Comment by oars** [comment]
The argument is expected to be an iterable, as described in the Args section a list of conv layer parameters.

Closing as WAI.
