### ISSUE TITLE
Training PPO in non-episodic environments

### ISSUE THREAD

**Issue by PeterZhizhin** [tensorflow/agents#30]
After reviewing PPOAgent code, I have found the following piece of code:
```python
    valid_mask = ppo_utils.make_timestep_mask(next_time_steps)

    if weights is None:
      weights = valid_mask
    else:
      weights *= valid_mask

....

    value_preds, unused_policy_state = self._collect_policy.apply_value_network(
        time_steps.observation, time_steps.step_type, policy_state=policy_state)
    value_estimation_error = tf.math.squared_difference(returns, value_preds)
    value_estimation_error *= weights
```

This means that if an agent runs in a non-episodic environment (the environment never resets and can be run infinitely), the agent will never learn anything because `weights` will be always zero.

The agent can get some reward, but due to weight being zero, training will not happen.

This also makes it harder to train the agent with `DynamicStepDriver`. Only latest steps before reset will be used for training.

**Comment by Axel-CH** [comment]
Hi @PeterZhizzhin, thank you for your PR, I have the same issue. Could you add an exemple (gym or other env) of training with Training PPO in non-episodic environment ?

**Comment by DanielWicz** [comment]
> Hi @PeterZhizzhin, thank you for your PR, I have the same issue. Could you add an exemple (gym or other env) of training with Training PPO in non-episodic environment ?

Flatlat (http://flatland-rl-docs.s3-website.eu-central-1.amazonaws.com/index.html) is such an example. Nevertheless, there's a solution to this issue ?

**Comment by tfboyd** [comment]
Little cleanup and issue bankruptcy. Issue is ~2 years old. I am sorry that this did not end with a solution. If you find this issue in the future please open a new one and reference this one if desired.
