### ISSUE TITLE
Epsilon Decay in DQN

### ISSUE THREAD

**Issue by marconardelli** [tensorflow/agents#300]
Hello, I've created a custom epsilon_greedy_policy class that supports epsilon decay. I use the exact same class both for collect_policy and eval_policy, in particular I have made those changes:

```
  def _update_epsilon(self):
    step_no = self._current_step
    if step_no % self._decay_steps == 0:
        decay_perc = self._decay_percentage / 100
        self._epsilon = self._epsilon - (self._epsilon * decay_perc)
        if self._epsilon < 0.005:
            self._epsilon = 0.005

    print("Updated epsilon to {0}".format(self._epsilon))

  def _action(self, time_step, policy_state, seed):
    self._current_step += 1
    self._update_epsilon()
```

So basically every _decay_steps round of x episodes I update the epsilon value. 
While this works in eval, this doesn't work during training, if I set the starting epsilon_decay = 1.0, the train always return random actions. 

So I imagine that during training this part of code is never processed. 
Do you think there is a way to fix this or the way I tried to implement epsilon decay is wrong in the first place?

**Comment by leroidauphin** [comment]
It looks like the existing `EpsilonGreedyPolicy` already supports epsilon decay. The constructor parameter `epsilon` can be a `callable` which defines the decay schedule. The Categorical DQN example `train_eval_atari.py` includes an example of a polynomial decay schedule. Would the combination of the keras `PiecewiseConstantDecay` and the existing policy satisfy your requirements?

**Comment by oars** [comment]
Thanks for adding a pointer @leroidauphin!

@marconardelli The reason why your implementation doesn't work is that it relies on python variables to set what the value of epsilon will be. When the TF computation graph is built this is traced only once. 

You need to define epsilon and your step variables as tf.Variables. I assume if you avoid using the `tf.function` in the training (`use_tf_function` parameter in dqn/examples/v2/train_eval.py` for example) your code will probably work, but it will be slow.

**Comment by marconardelli** [comment]
thx @oars for the help, I will try to modify it accordingly
