### ISSUE TITLE
Gym Wrapper Converts MultiBinary Space to int8 Data Type Incompatible With Many TF Ops

### ISSUE THREAD

**Issue by decodyng** [tensorflow/agents#307]
In [this line](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/gym_wrapper.py#L97) of `gym_wrapper`, Gym environments with a MultiBinary space have that converted into a BoundedArraySpec with dtype of `np.int8`.  My guess is that this was done for efficiency reasons - obviously you don't need much precision to hold a binary value - but it has the unfortunate side effect of making many downstream Tensorflow operations break with the following error, since they don't support int8 as input. (Minimum is shown as an example, but in looking over the Tensorflow documentation, it seems that a majority of math operations similarly don't support int8). 

In our current code using gym_wrapper, we have to do a somewhat hacky and after-the-fact overriding of the inferred action space to be one with dtype np.int32, so that subsequent network operations succeed, but it seems better for the wrapper itself to output values in a more broadly compatible datatype, despite the efficiency cost in doing so. 

```Node:{{node Minimum}}
All kernels registered for op Minimum :
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF]
 [Op:Minimum]
```

**Comment by samfishman** [comment]
Thanks for the issue. I agree this is problematic - we don't tend to use MultiBinary spaces internally so we hadn't yet seen this. I'll push a fix today but in the meantime, you can use the `dtype_map` parameter when instantiating your environment: `dtype_map={gym.spaces.MultiBinary: np.int32}`.

**Comment by sguada** [comment]
Hi @decodyng you can pass `dtype_map = {gym.spaces.MultiBinary: np.int32}` to overwrite that.
