### ISSUE TITLE
PPOAgent without value network

### ISSUE THREAD

**Issue by Hkorb** [tensorflow/agents#308]
The ppoagent requires a value network, but default is None. First, therefore the default fails, second, the option to use the agent without a value network is useful as well. Of course one can define a "constant" as network, but that is especially for new users at least very unintuitive

**Comment by samfishman** [comment]
Hi @Hkorb, the value network is an important part of the PPO algorithm and removing it would significantly change the nature of the algorithm. If you are interested in setting something up like that, you would want to subclass the PPO agent.

The reason we don't provide a default value network is that it is very dependent on the domain you are applying the algorithm. For users that want a ready-to-use version, we have [the example script](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py).

That said PPOAgent should throw an error if `value_net` isn't provided. I'll leave this issue open to track that.
