### ISSUE TITLE
C51/Rainbow tutorial not working on Colab

### ISSUE THREAD

**Issue by caseyjconger** [tensorflow/agents#314]
Issue with xvfb on colab

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/easyprocess/__init__.py in start(self)
    230             self.popen = subprocess.Popen(
--> 231                 cmd, stdout=stdout, stderr=stderr, cwd=self.cwd, env=self.env,
    232             )

7 frames
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

During handling of the above exception, another exception occurred:

EasyProcessError                          Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/easyprocess/__init__.py in start(self)
    234             log.debug("OSError exception: %s", oserror)
    235             self.oserror = oserror
--> 236             raise EasyProcessError(self, "start error")
    237         self.is_started = True
    238         log.debug("process was started (pid=%s)", self.pid)

EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

**Comment by caseyjconger** [comment]
Maybe going off of an old version of the repo, but I found that just adding:

`!sudo apt-get update`

above the 

`!sudo apt-get install ...`

**Comment by clockzhong** [comment]
Yes, this issue's root cause should be in colab's management, not the tensorflow agents project. Its repos server updated,but the colab's hosts didn't do the update. This causes the xvfb installing fails.

**Comment by oars** [comment]
Thanks for the report, this is still useful to have as a reference! Will see if we can reach someone internal to get that done, otherwise we can add a note/update call in the colabs.

**Comment by tfboyd** [comment]
This is working at: https://www.tensorflow.org/agents/tutorials/9_c51_tutorial

and in our nightly tests with pure Jupiter Notebooks.
