### ISSUE TITLE
Different layers saved under the same name

### ISSUE THREAD

**Issue by yuchen-zhu** [tensorflow/agents#317]
When creating a q_network with multiple fully connected layers, all layers are saved under the same name. Printing out 'variables_to_train' in Dqn_agent._train gives this output:

'      dtype=float32)>, <tf.Variable 'QNetwork/EncodingNetwork/EncodingNetwork/dense/kernel:0' shape=(10, 15) dtype=float32, numpy=
...
 <tf.Variable 'QNetwork/EncodingNetwork/EncodingNetwork/dense/kernel:0' shape=(15, 20) dtype=float32, numpy=
array([[ 0.1729781 , -0.01916845,  0.45993644,  0.16150256, -0.17688678,'

Note that the shapes of the first and last layers are (10, 15) and (15, 20) respectively, i.e. they are different layers, but their names are the same, both being 'QNetwork/EncodingNetwork/EncodingNetwork/dense/kernel:0'

As a result when using summarize_grads_and_vars to visualise in tensorboard, only one plot is shown for all encoding kernel/bias weights.

Morally it also makes more sense that different layers are saved under different names. 

This could be achieved by for example editing the for loop block at line 266 of tf_agents/networks/encoding_networks.py to be:
'      for i, (num_units, dropout_params, weight_decay) in enumerate(zip(
                fc_layer_params, dropout_layer_params, weight_decay_params)):
        kernal_regularizer = None
        if weight_decay is not None:
            kernal_regularizer = tf.keras.regularizers.l2(weight_decay)
        layers.append(
            tf.keras.layers.Dense(
                num_units,
                activation=activation_fn,
                kernel_initializer=kernel_initializer,
                kernel_regularizer=kernal_regularizer,
                dtype=dtype,
                name=f'{name}/dense_{i}'))' 
where we added layer index i and let name be dependent on that. 

The printing output now looks like:
'  ... <tf.Variable 'QNetwork/EncodingNetwork/EncodingNetwork/dense_1/kernel:0' shape=(10, 15) dtype=float32, numpy=
array([[ 7.48026669e-02, -5.38740039e-01, -5.95409870e-01,
        ...
 <tf.Variable 'QNetwork/EncodingNetwork/EncodingNetwork/dense_2/kernel:0' shape=(15, 20) dtype=float32, numpy=
array([[-0.07656678, -0.2728299 ,  0.09025683, -0.43406826, -0.2609655 ,
'

**Comment by oars** [comment]
Thanks for noting this! Overall in TF 2.x variable names are not generally useful (no more collections, etc.), but clearly they matter for the summaries.

Feel free to submit a PR for this, otherwise we'll try to find some time to make this kind of change next week.

**Comment by oars** [comment]
Looking more into this, I think 2d0dcaa555980779af13 fixed this.

Please give a newer nightly a try. Feel free to re-open if it's still an issue for you.
