### ISSUE TITLE
policy.action MEMORY LEAK

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#319]
I have an issue where using a policies actions may be introducing a memory leak. I am currently training an environment which consists of a "master" snake (the snake that is being trained) and an "enemy" snake which has a fixed policy in the environment. During the update phase, I need to predict the next action of the enemy snake: I do so as follows

`
TS = ts.TimeStep(...)
`
`
enemy_action_step = self.ENEMY_POLICY.action(TS)
`
`
enemy_action = enemy_action_step.action.numpy()[0]
`
`
self.move_snake(enemy_action, 'enemy')
`

During training, my memory uses increases ever so slightly (but over 10 million iterations it can go up as much as 10 gigabytes). When I replace the code with 

`
TS = ts.TimeStep(...)
`
`
self.move_snake(0, 'enemy')
`

I get no such memory leak (enemy just always moves to the right). Is it possible that 

`
enemy_action_step = self.ENEMY_POLICY.action(TS)
`

is somehow leaking memory during training? The only other thing I could think of is it may possibly be grabbed by the replay buffer somehow (?) but it seems like it would be silly if the replay buffer grabbed any old action completed during training.

**Comment by oars** [comment]
What kind of policy do you have for `self.ENEMY_POLICY`? From your snippet there's not much that points towards the RB being involved.

**Comment by lukepolson** [comment]
Currently I'm just using a Random policy defined as follows:

`
initial_enemy_policy = RandomTFPolicy(tf_env.time_step_spec(),
                                        tf_env.action_spec())
`

where tf_env is another copy of the environment (a trick used to get the right environment specs). For clarification, I start by making an environment "tf_env" where the enemy_policy is set to None, then I get the initial enemy policy as above, and then I create a new "tf_env" where I input the enemy policy (I call the new environment "tf_env" as well).

**Comment by lukepolson** [comment]
I am creating a random policy as follows:

First make blank copy of env and tf_env
`
env = SnakeEnv(..., ENEMY_POLICY=None)
`
`
tf_env = tf_py_environment.TFPyEnvironment(env)
`

Use the specs of tf_env to create the random policy
`
initial_enemy_policy = RandomTFPolicy(tf_env.time_step_spec(), tf_env.action_spec())
`

Then redefine the env and tf_env variables using the random policy above.
`
env = SnakeEnv(... ENEMY_POLICY=initial_enemy_policy)
`
`
tf_env = tf_py_environment.TFPyEnvironment(env)
`

**Comment by leroidauphin** [comment]
Is it possible that this issue is related to https://github.com/tensorflow/tensorflow/issues/36164?

**Comment by lukepolson** [comment]
I believe it was, cheers!
