### ISSUE TITLE
TF-Agents 0.3.0 compatibility with TensorFlow 2.1.0

### ISSUE THREAD

**Issue by fgervais** [tensorflow/agents#321]
The readme says:

> Note: TF-Agents 0.3.0 is not compatible with TensorFlow 2.1.0 unless the nightly
release of `TensorFlow Probability` is installed: `pip install tfp-nightly`

But this commit dates back `18 Dec 2019`.

On `18 Dec 2019`, tfp-nightly was version `0.9.0.dev20191218`.

Since TensorFlow Probability 0.9 is stable now, I assume that the readme comment is obsolete. Is it?

**Comment by tfboyd** [comment]
That is very possible.  As far as being compatible and tested with TensorFlow 2.1.0.  I have version 0.4.0 in RC with not expectation that this will not be come official in 1-2 weeks.  Here is the upload on pypi. 

It was tested with:
tensorboard==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
tensorflow-probability==0.9.0

I would not normally list my gast version but in this case:
gast==0.2.2

Be careful you need to have gast 2.2 and if you do a --force-reinstall or anything else that triggers an install of the latest gast you will get 3.x and will get errors about missing properties during autograph in some instances.  

https://pypi.org/project/tf-agents/0.4.0rc0/

**Comment by tfboyd** [comment]
Looking at the readme and I was the one that did the 0.3 release I think your assumption is true; given the dates and probability now on 0.9.0.  I cannot remember the exact context of why I added the message. I doubt 2.1 was final when I was pushing out that release.  

TF 2.2 should be out soon and I hope to finish up 0.4 and then roll right into TF-Agents 0.5.0 and verify it with TF 2.2 as soon as it is final.  But things beyond my control may delay me.  0.4.0 taking this long was my fault.

**Comment by tfboyd** [comment]
Remove the wording from the README.  The wording might show up on the new tensorflow.org tf-agents sub-site and I will clean that up with the 0.4.0 release.

**Comment by tfboyd** [comment]
Marking fixed since I updated the README and start the RC.  I hope that seems fair.
