### ISSUE TITLE
How to use agents/tf_agents/bandits/agents/mixture_agent.py? is there any example?

### ISSUE THREAD

**Issue by lucifer2288** [tensorflow/agents#322]
How to use /bandits/agents/mixture_agent? Thank you.

**Comment by bartokg** [comment]
The examples tf_agents/bandits/agents/examples/v2/train_eval_stationary_linear.py and tf_agents/bandits/agents/examples/v2/train_eval_wheel.py have just been updated to use the exp3_mixture_agent. If you would like to understand how to create a new subclass of mixture_agent, have a look at how it's done in tf_agents/bandits/agents/exp3_mixture_agent.py.

**Comment by lucifer2288** [comment]
> The examples tf_agents/bandits/agents/examples/v2/train_eval_stationary_linear.py and tf_agents/bandits/agents/examples/v2/train_eval_wheel.py have just been updated to use the exp3_mixture_agent. If you would like to understand how to create a new subclass of mixture_agent, have a look at how it's done in tf_agents/bandits/agents/exp3_mixture_agent.py.

Thank you very much!!
