### ISSUE TITLE
Does DynamicStepDriver take a Reference of the tf_env?

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#323]
If I use

`
collect_driver = DynamicStepDriver( tf_env, ...) 
`

Does this take in a reference of the tf_env? For example, in the middle of the training loop, could I use

`
tf_env.pyenv.envs[0].change_rewards()
`

or would it not be affected in the Dynamic Step Driver? (i.e. only a copy was passed to the dynamic step driver, not an actual reference to the tf_env).

**Comment by kuanghuei** [comment]
Yes. Everything in python that is not a primitive is a reference. env is passed in the parent class constructor https://github.com/tensorflow/agents/blob/master/tf_agents/drivers/driver.py
