### ISSUE TITLE
Possible flaws in PPO implementation

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#324]
Current implementation of PPO may contains some flaws. We notice that it is nearly impossible to train a policy that uses deep net such as ResNet (18, 34) as a preprocessing layers. Or similar experience works with the the PP02 implementation of openai baseline.

According to this paper https://openreview.net/pdf?id=r1etN1rtPB there are some important optimization not mentioned in the paper but present in baseline implementation. One of them is value clipping.

Currently here is what we have in TF-Agents PPO's for the value estimation

```
value_preds, _ = self._collect_policy.apply_value_network(
        time_steps.observation,
        time_steps.step_type,
        value_state=value_state,
        training=training)
value_estimation_error = tf.math.squared_difference(returns, value_preds)
value_estimation_error *= weights
```

Instead here is the [baseline version](https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/ppo2/model.py#L67)

```
# Clip the value to reduce variability during Critic training
# Get the predicted value
vpred = train_model.vf
vpredclipped = OLDVPRED + tf.clip_by_value(train_model.vf - OLDVPRED, - CLIPRANGE, CLIPRANGE)
# Unclipped value
vf_losses1 = tf.square(vpred - R)
# Clipped value
vf_losses2 = tf.square(vpredclipped - R)

vf_loss = .5 * tf.reduce_mean(tf.maximum(vf_losses1, vf_losses2))
```

This difference may clearly explain why we failed to train an agents that uses deep nets. 

Having this option with TF-Agent PPO would be interesting.

**Comment by summer-yue** [comment]
Thank you for raising this issue. I agree that it'd be a great idea to have value clipping in TF-Agents' PPO. Would you like to help contribute this feature? This will probably to be the fastest way to get this feature out. Alternatively, I can add this to my list of todos. Thanks!

**Comment by OnTheRicky** [comment]
Hasn't this been added? So should be closed?

**Comment by summer-yue** [comment]
I think this is still open. I haven't got time to work on this yet. Might get to this in the next 2 weeks or so.

**Comment by summer-yue** [comment]
This was added earlier today.
