### ISSUE TITLE
Multiple activation function for ActorDistributionNetwork

### ISSUE THREAD

**Issue by sdfzz** [tensorflow/agents#327]
Dear all,

I'm trying to use ActorDistributionNetwork function to create an actor network which consists of multiple fully connected layers. 

I can do it by setting 'fc_layer_params' argument of 'ActorDistributionNetwork' function. However, What I want is to be able to assign different activation functions to each layer. 

For example, I want to create 3 fully connected layers, and use relu as the activation function for the first two layers while use tanh for the last layer. 

Is this possible? It seems like this is not possible in current tf-agent version. 

Any help would be greatly appreciated

Regards,

Steve

**Comment by oars** [comment]
You can define your own networks to do whatever you want. The only requirements are that they handle the observations for the environment you are using, and that the outputs of the network match the expectations for the agent (Easiest way to do this is to copy the last layer of the example networks.)

Take a look at the networks colab for more details. There we show how to use the encoding network, you could create multiple instances of that with different activation_fns, or you could create your own layers: https://github.com/tensorflow/agents/blob/master/docs/tutorials/8_networks_tutorial.ipynb

**Comment by sdfzz** [comment]
Thank you!!
