### ISSUE TITLE
Multiple OBservation with Actor Critic

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#330]
I'm training a game that includes an image of a board and the health  as two separate observations. This has worked fine with the DQN since I can use a preprocessing combiner to combine these.

Now I want to use an actor critic network but the critic network can't support more than 1 observation. What is the solution?

**Comment by v-sivak** [comment]
You can use FlattenObservationsWrapper from environments/wrappers, but they only have it for python environments so far.

**Comment by lukepolson** [comment]
I see. So I suppose there's no (direct) support for using a CNN in this case (for the image of the board) since the observation needs to be flattened before being put into the critic network. Is there a reason for this? Ideally, shouldn't one be able to use a preprocessing layers for a critic network?

**Comment by oars** [comment]
Take a look at [8_networks_tutorial.ipynb](https://github.com/tensorflow/agents/blob/master/docs/tutorials/8_networks_tutorial.ipynb). You can define whatever critic you want which can support multiple inputs.

**Comment by lukepolson** [comment]
So one can simply override the __init__ and call methods of the critic network? I see... I'll get to it. Thanks for the help! :)
