### ISSUE TITLE
Question about Collect Driver and Parallel Environment

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#335]
Suppose I have an environment creator:

    def get_Snake_Env():
        return MyEnv()

Then create 16 parallel environments using a parallel py environment:

`tf_env=tf_py_environment.TFPyEnvironment(parallel_py_environment.ParallelPyEnvironment([get_Snake_Env]*int(n_envs)))`

Now I create a collect driver:

    collect_driver = DynamicStepDriver(
        tf_env,
        agent.collect_policy, 
        observers=[replay_buffer.add_batch] + train_metrics,
        num_steps=n_steps_per_update) 

_**Is num_steps the number of steps taken by all of the parallel environments combined, or is the number of steps taken by each parallel py environment?**_

**Comment by JCMiles** [comment]
is the sum of all the parallel envs. the same is valide for episodes if you use DynamicEpisodeDriver.

**Comment by lukepolson** [comment]
@JCMiles Thank you for the speedy response. So how then should the epsilon greedy policy, the "num_steps" parameter in the collect driver, and the "target_update_period" parameter in the DQN agent be updated as the number of parallel environments increases? For example, would

*1 Environment*: num_steps=1, target_update_period=20000
*10 Environments*: num_steps=10, target_update_period=200000

be a good adjustment? When I ran my agent with 10 parallel environments, the amount my agent learned **(per step)** massively decreased. What are the appropriate adjustments to the hyperparameters I mentioned?

**Comment by tfboyd** [comment]
Closing due to being stale.

**Comment by Yash271100** [comment]
I am trying to initiate parallel environments for multiprocessing. Although I am using a custom environment, I get the same error with a standard gym environment.

This is the minimal example code that is showing the same error as my custom environment:
`env1 = suite_gym.load("Taxi-v3")
def GetmyENV():
  return env1
parallel_py_env = ParallelPyEnvironment([GetmyENV]*int(4))`

It is showing this error:
`E0611 20:43:09.540677 140416971974464 parallel_py_environment.py:492] Error in environment process: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/parallel_py_environment.py", line 458, in _worker
    env = cloudpickle.loads(self._pickled_env_constructor)()
  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__
    return getattr(self._env, name)
  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__
    return getattr(self._env, name)
  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__
    return getattr(self._env, name)
  [Previous line repeated 941 more times]
RecursionError: maximum recursion depth exceeded

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-31-7a1314b24b78> in <cell line: 8>()
      6   return env1
      7   # tf_env=tf_py_environment.TFPyEnvironment(parallel_py_environment.ParallelPyEnvironment([get_Snake_Env]*int(n_envs)))
----> 8 parallel_py_env = ParallelPyEnvironment([GetmyENV]*int(200))

6 frames
/usr/local/lib/python3.10/dist-packages/tf_agents/environments/parallel_py_environment.py in wait_start(self)
    282       self._process.join(5)
    283       raise result
--> 284     assert result == self._READY, result
    285 
    286   def observation_spec(self) -> types.NestedArraySpec:

AssertionError: (5, 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/parallel_py_environment.py", line 458, in _worker\n    env = cloudpickle.loads(self._pickled_env_constructor)()\n  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__\n    return getattr(self._env, name)\n  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__\n    return getattr(self._env, name)\n  File "/usr/local/lib/python3.10/dist-packages/tf_agents/environments/wrappers.py", line 55, in __getattr__\n    return getattr(self._env, name)\n  [Previous line repeated 941 more times]\nRecursionError: maximum recursion depth exceeded\n')`

Please help me understand why this error is coming in my case.
