### ISSUE TITLE
Parallel Py Environment Performing Considerably Worse For More Environments

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#336]
Hi all. I understand I've posted quite a few questions but I image they'll be useful for future people who want to use this package.

I have a question about the performance of the ParallelPyEnvironment. To do benchmarks I created a parallelpyenvironment with one instance of my environment and another with 16 instances of my environment. These were done in  2 separate jobs. Namely, to create each environment, I used:

1. `tf_env = tf_py_environment.TFPyEnvironment(parallel_py_environment.ParallelPyEnvironment([Snake_Env_Par]*1))`
2. `tf_env= tf_py_environment.TFPyEnvironment(parallel_py_environment.ParallelPyEnvironment([Snake_Env_Par]*16))`

where "Snake_Env_Par" is a callable version of my environment (so I could add input parameters):

    class Snake_Env_Par(SnakeEnv):
        def __init__(self):
            super().__init__(param1, param2,...)

In each of the two jobs I kept *all parameters constant* except for the differing number of parallel environments. These were the noteworthy parameters I used for each trial
- *Replay Buffer*:
"max_length": 500000
- *Collect Driver:*
"num_steps":1
- *DQN Agent*:
"target_update_period": 20000

When I extracted instances from the replay buffer I used the ".as_dataset()" method with
"sample_batch_size": 64,
"num_steps": 2,
"num_parallel_calls":3,

The plot below is of 
x: tf_metrics.EnvironmentSteps(),
y: tf_metrics.AverageReturnMetric(batch_size="number of environments")

![image](https://user-images.githubusercontent.com/39573086/77604517-eeafb680-6ecf-11ea-947d-46c6d4586b08.png)

Note that I trained the one for 16 environments for longer (because I could). **Why would the parallel environment be doing this much worse**? In particular

- Do I need to modify the max length of the replay buffer when using 16 environments? Could this be an issue?
- Is the "sample_batch_size" extracting things in a bizarre way when the replay buffer is already seperated by 16 different batches in the 16 environment case?
- Do I need to modify the "target_update_period" in the DQN agent to account for the fact that there are now 16 environments?

**Comment by lukepolson** [comment]
Hello everyone. I have the solution about what happened here. I will soon write a detailed reply to this and then close and comment.  This should be useful to many people in the future.

**Comment by OnTheRicky** [comment]
> Hello everyone. I have the solution about what happened here. I will soon write a detailed reply to this and then close and comment. This should be useful to many people in the future.

Any update on this?

**Comment by ebrevdo** [comment]
Closing as stale.  @lukepolson if you did solve this, please feel free to reopen and comment.  In our tests, we do not see a performance/quality degradation with ParallelPyEnvironment and cannot reproduce the bug you're seeing without a more detailed example.
