### ISSUE TITLE
Question about Custom PYEnvironment regarding two  inputs

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#338]
Hi,

If I want to create a custom PYEnvironment, by the tutorials giving I can only see how to define 1 input, for example a picture or a scalar value, but what If I want both a picture and a value to be part of the observation?

**Comment by sguada** [comment]
Each environment can define their own set of observations, so you can use dict or a namedtuple. Example:
```
obs_spec = {'value': ArraySpec((), np.float32), 'image': ArraySpec((82, 82), np.int32)}
```
The key aspect is that then you need define your own network to handle both observations.

**Comment by HadiSDev** [comment]
@sguada So I can't use the normal Q-Network? I have to create my own?. I thought I could just use preprocessing_layers parameter to specify each input layer

**Comment by HadiSDev** [comment]
Hi again, So I found out that I could just use the preprocessing layer on the Q-Network to specify each input. Closing

**Comment by cserpell** [comment]
@HadiSDev would you please elaborate a little on how to do it? I don't find any documentation on how to use a complex observation state as input for a Q network.

**Comment by cserpell** [comment]
I see the answers are in #533 .
