### ISSUE TITLE
How does epsilon_greedy work for the DQN agent

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#339]
How does the parameter **epsilon_greedy** for the DQN agent work since we are not defining **minimum**, **decay** and **start** epsilon?

Normally you would have:
EPSILON_MAX = 1 # Max exploration rate
EPSILON_MIN = 0.1 # Min exploration rate
EPSILON_DECAY_STEPS = 2e5 # How many steps to decay from max exploration to min exploration

**Comment by marconardelli** [comment]
The EpsilonGreedyPolicy has not a decay by itself, you have to implement it in your training process.
What you have to do is to define a decay process using for instance a PolinomialDecay like this:

```
  global_step = tf.compat.v1.train.get_or_create_global_step()
  start_epsilon = 0.1
  n_of_steps = 10000
  end_epsilon = 0.0001
  epsilon = tf.compat.v1.train.polynomial_decay(
      start_epsilon,
      global_step,
      n_of_steps,
      end_learning_rate=end_epsilon)
```
Then you have to pass the epsilon parameter to the agent:

```
    tf_agent = dqn_agents.DqnAgent(
        tf_env.time_step_spec(),
        tf_env.action_spec(),
        q_network=q_net,
        epsilon_greedy=epsilon,
        n_step_update=n_step_update,
        target_update_tau=target_update_tau,
        target_update_period=target_update_period,
        optimizer=tf.compat.v1.train.AdamOptimizer(learning_rate=decay_lr),
        td_errors_loss_fn=common.element_wise_huber_loss,
        gamma=gamma,
        reward_scale_factor=reward_scale_factor,
        gradient_clipping=gradient_clipping,
        use_decay=True,
        debug_summaries=debug_summaries,
        summarize_grads_and_vars=summarize_grads_and_vars,
        train_step_counter=global_step
    )
```

**Comment by HadiSDev** [comment]
Alright thanks :)

**Comment by iansmps** [comment]
> 

This is exactly what I need, but I am using tensorflow 2.11. Does anyone know how to do something like this in tensorflow version 2.11?
