### ISSUE TITLE
Incompatibilty of Tensorflow version 1.15 with tf-agents version 0.3.0

### ISSUE THREAD

**Issue by anaghagireesan** [tensorflow/agents#340]
Hi,
I am using Tensorflow 1.15 and on installing tf-agents 0.3.0, I still get incompatibility error while using td3 (saying Requirement of tensorflow  probability> 2.1). Shouldn't that work fine with tensorflow 1.15 as per the documentation?

Thanks!

**Comment by tfboyd** [comment]
It should, I will try to give this a try today and check back.  The downside is my environment might be totally different, but I will see what happens and maybe we get lucky.  You also may have moved on as 6 days is a long time for an install issue. On the plus side it will give us a data pont oin 0.3.0 and maybe update the README if I learn something.

I realize there is likely a reason you are using TF 1.15.  That said today I release 0.4.0 which is compatible with TF 2.1.  Also a warning that if you install via pypi you will now be getting TF-Agents 0.4.0.   Use this to keep using 0.3.0  `pip install tf-agents==0.3.0`

**Comment by ffbskt** [comment]
Still not work in my pc. (But in colab is ok)
'from tf_agents import specs'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/denis/anaconda3/envs/tf2/lib/python3.6/site-packages/tf_agents/specs/__init__.py", line 20, in <module>
    from tf_agents.specs.distribution_spec import DistributionSpec
  File "/home/denis/anaconda3/envs/tf2/lib/python3.6/site-packages/tf_agents/specs/distribution_spec.py", line 22, in <module>
    import tensorflow_probability as tfp
  File "/home/denis/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/denis/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.1; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.

**Comment by tfboyd** [comment]
It may seem obvious to you.  The fix is to run:

`pip install tensorflow-probability==0.8.0`

I did a fresh install on a docker image with TF 1.15.0 Docker as the base.  
I am looking into how tf-agents installs tensorflow-probability. Should not take long; and I wanted to get this update out ASAP. I do not know if we want to lock the versions for all the libraries.  tf.proability might be an exception.  At a minimum I will update the README since many people might stay on TF 1.15 for a while for various reasons.  

I tested by running your import and also a full run of cartpoleV2 just to have some basic end-to-end.

**Comment by tfboyd** [comment]
We do greater than or equal on the tensorflow-probability.  I am not sure we want to change it right now to lock to an exact version.  If this is a problem for future releases that decision may change.  I am also going to ask the team to verify my off the cuff conclusion.  I will close this when I update the README.md .

From setup.py

```python
tfp_package_name = 'tensorflow-probability>={}'.format(REQUIRED_TFP_VERSION)
```

**Comment by anaghagireesan** [comment]
Yes, tensorflow probability was the issue. Everything works fine after installing tensorflow probability compatible with tensorflow 1.15. 
Thanks a lot!

**Comment by tfboyd** [comment]
Readme is updated.  I forgot to close this.
