### ISSUE TITLE
Custom tf metrics for game variables?

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#344]
Is it possible to create a custom tf_metric like the AverageReturnMetric, but instead count game variables and not reward? For example ammo, health packs, armor etc.

**Comment by kuanghuei** [comment]
As long as those things are in your observation, I don't see any problem of doing that. Just pass metric observers to the driver, e.g.  https://github.com/tensorflow/agents/blob/master/tf_agents/eval/metric_utils.py#L123

**Comment by HadiSDev** [comment]
@kuanghuei What if they are not in the observation?
