### ISSUE TITLE
Linking API documentation in the README

### ISSUE THREAD

**Issue by Syakyr** [tensorflow/agents#350]
I have been relying on the API documentation in `tf_agents/docs/python` to use the module better, up until recently that I've found that the documentation is removed in 6a227494648ca25ca8188ef5cc646b40f1c9d841. I would recommend adding the API documentation link (https://www.tensorflow.org/agents/api_docs/python/tf_agents) in the README for future reference.

**Comment by tfboyd** [comment]
Sorry about that. PR is being approved that provides the link in the first paragraph and then again under the stable release section.

**Comment by tfboyd** [comment]
Done

**Comment by Syakyr** [comment]
I saw the link. I would suggest that the link should be placed below the Tutorial header though, so it would be like a natural progression of understanding the package better. Otherwise, thanks!
