### ISSUE TITLE
PPO value clipping seems to have no effect

### ISSUE THREAD

**Issue by leroidauphin** [tensorflow/agents#352]
The `PPOAgent` includes the option to use value clipping. This is included in the baselines implementation (https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/ppo2/model.py#L67) and is described in https://openreview.net/pdf?id=r1etN1rtPB as a useful optimisation to improve the performance of the algorithm.

However, it appears that the implementation of value clipping in TF-Agents has no effect. The value network is used to predict the values of the same observations from the trajectory twice - `value_pred` on line 867 and again `old_value_preds` on line 875. The value clipping then clips the difference between these two values, but for a deterministic model that is always equal to zero.

As such, the `clipped_value_estimation_error` (line 885) is always equal to the `value_estimation_error` (line 872).

**Comment by summer-yue** [comment]
Hey thanks for raising this, good catch. Looks like a bug. I'll rolling out a fix right now.

**Comment by summer-yue** [comment]
Just submitted the fix to use the cached value prediction instead. Thanks for reporting this!
