### ISSUE TITLE
Speeding up Prediction Time of a Policy

### ISSUE THREAD

**Issue by lukepolson** [tensorflow/agents#354]
I currently have a policy which can make predictions on a 33x33 game image in about 0.002 seconds. The neural network has about 1 million parameters. Is there a way to speed up the "policy.action" method? Based on the speed during training, the policy must be executing "policy.action" at a much quicker speed than 0.002 seconds.

**Comment by summer-yue** [comment]
Can you please provide some context on which policy you're using? I'm assuming you're already using graph mode?

**Comment by tfboyd** [comment]
Closing due to being stale.
