### ISSUE TITLE
Function copy(self) not defined in class policies.py_policy.PyPolicy

### ISSUE THREAD

**Issue by jonabaa** [tensorflow/agents#355]
The tutorial "3_policies_tutorial.ipynb" explains that the interface for Python policies defines a method "copy(self)" that is supposed to return a copy of the policy. However I cannot see that this method is defined in the abstract class policies.py_policy.PyPolicy. Neither does any of the policies I'm using that inherits policies.py_policy.PyPolicy implement this function. Will this function be implemented in the future? It would be nice to have the ability to get a copy of the policy without necessarily saving to disk as you can do with Checkpointer and PolicySaver.

**Comment by summer-yue** [comment]
Thanks for the raising this! The copy(self) function in the Colab is outdated and is from an early version of TF Agents. I have removed it after seeing your comment.

We don't currently have any plans of implementing the copy function in all the polices. It is not easy to do, and can get very tricky when we have shared variables between networks come into play.
