### ISSUE TITLE
Do the metrics in the `tf_metrics`-module support batching by design?

### ISSUE THREAD

**Issue by hohl** [tensorflow/agents#356]
I'm building an experiment upon the [REINFORCE v2 sample](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/reinforce/examples/v2/train_eval.py) with a custom recurrent actor network and custom Python-based environment. Both are implemented to support batching. The `train_eval` is mostly unchanged (besides the usage of the custom environment and network, of course). However, the execution fails with (also see: [full traceback](https://gist.github.com/hohl/7926ea33527db9e6abc3fe7fa7f7332e)):

```
ValueError: in user code:

    ${VENV_PATH}/lib/python3.7/site-packages/tf_agents/metrics/tf_metrics.py:161 call  *
        self._return_accumulator.assign(
    ${VENV_PATH}/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:846 assign  **
        self._shape.assert_is_compatible_with(value_tensor.shape)
    ${VENV_PATH}/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (1,) and (32,) are incompatible

```

The error message seems to be related to batch processing, as 32 was the batch size I used while running the script, but besides that the error message does not give me much hints about what is failing. Thus, I tried to nail the problem down by using some breakpoints and uncommenting parts of the code, which led me to the conclusion that it might be related to the processing of metrics. Replacing the following lines of the `train_eval.py` with an empty list removes the issue:

```
       train_metrics = [
            tf_metrics.NumberOfEpisodes(),
            tf_metrics.EnvironmentSteps(),
            tf_metrics.AverageReturnMetric(),
            tf_metrics.AverageEpisodeLengthMetric(),
        ]
```

Using only one of the above metrics also does result in the same error message as above. So I am wondering: **are these metrics supposed to be used with batches?** Are there any tests or examples which have been run with batches instead of single samples? Do you have any other hints about what could possible have went wrong in my setup?

**Comment by summer-yue** [comment]
Have you tried

```
train_metrics = [
            tf_metrics.NumberOfEpisodes(batch_size=32),
            tf_metrics.EnvironmentSteps(batch_size=32),
            tf_metrics.AverageReturnMetric(batch_size=32),
            tf_metrics.AverageEpisodeLengthMetric(batch_size=32),
        ]
```

I think the default batch size is 1 in those metrics.

**Comment by hohl** [comment]
I did check the arguments of `__init__`, but did not find anything like a batch size (see [source](https://github.com/tensorflow/agents/blob/master/tf_agents/metrics/tf_metrics.py#L109)):

```python
(...)
class NumberOfEpisodes(tf_metric.TFStepMetric):
  """Counts the number of episodes in the environment."""

  def __init__(self, name='NumberOfEpisodes', prefix='Metrics', dtype=tf.int64):
(...)
```

However, I just checked again and figured out that some metrics do have a `batch_size` argument: `AverageReturnMetric` and `AverageEpisodeLengthMetric` have a `batch_size` argument in the constructor, while `NumberOfEpisodes` and `EnvironmentSteps` do not have such a parameter.

**Comment by hohl** [comment]
Anyhow, that did not fix the issue, but I found the cause of my issue: it was not related to the metrics after all, but debugging them helped. 

The issue arises from the trajectories or more specifically the trajectories generated through the `ts.transition` and `ts.termination` helpers. The `tf.restart` helper has support for batch sizes, but the other two helpers do not support batch size. You can see that when looking at their source code, where you should find a TODO note stating exactly that. So, for me, manually creating the `ts.TimeStep`-instances did fix the issue.

**Comment by hohl** [comment]
Anyhow, that did not fix the issue, but setting the batch size might have been necessary. 

As the source of `AverageReturnMetric` shows, the shape of `_return_accumulator` is set according to the passed `batch_size`:

```python
(...)
  def __init__(self,
               name='AverageReturn',
               prefix='Metrics',
               dtype=tf.float32,
               batch_size=1,
               buffer_size=10):
    super(AverageReturnMetric, self).__init__(name=name, prefix=prefix)
    self._buffer = TFDeque(buffer_size, dtype)
    self._dtype = dtype
    self._return_accumulator = common.create_variable(
        initial_value=0, dtype=dtype, shape=(batch_size,), name='Accumulator')

  @common.function(autograph=True)
  def call(self, trajectory):
    # Zero out batch indices where a new episode is starting.
    self._return_accumulator.assign(
        tf.where(trajectory.is_first(), tf.zeros_like(self._return_accumulator),
                 self._return_accumulator))

    # Update accumulator with received rewards.
    self._return_accumulator.assign_add(trajectory.reward)
(...)
```

...but the execution fails at exactly that `self._return_accumulator.assign(...)` line in `call`. So I guess it must be related to the shape `trajectory`, but that should be fine too as it is delivered batched from my environment.

The shape of the trajectory according to the debugger is:

```python
Trajectory(step_type=<tf.Tensor 'trajectory:0' shape=(32,) dtype=int32>, observation=<tf.Tensor 'trajectory_1:0' shape=(32, 16000) dtype=int64>, action=<tf.Tensor 'trajectory_2:0' shape=(32,) dtype=float32>, policy_info=(), next_step_type=<tf.Tensor 'trajectory_3:0' shape=(32,) dtype=int32>, reward=<tf.Tensor 'trajectory_4:0' shape=(32,) dtype=float32>, discount=<tf.Tensor 'trajectory_5:0' shape=(32,) dtype=float32>)
```

Any ideas?

**Comment by summer-yue** [comment]
Your trajectory shape looked good to me, and if you set the batch size to 32, that shouldn't have caused an issue. Do you mind copying the error message here? It's hard to debug without it.

Could you also look into what "self._return_accumulator" looks like before the assign_add, if that's the line that's erring out.

**Comment by hohl** [comment]
Tying to post the shape of `self._return_accumulator` made me find the mistake myself, as the shape was still `<tf.Variable 'Accumulator:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>`. I missed, that in the above sample, metric classes were instantiated twice (once as `train_metrics` and `eval_metrics`) and I only added the `batch_size` parameter to one of them not the other.

Thank you very much for your help!
