### ISSUE TITLE
PPOAgent._train increments the train_step_counter by num_epochs rather than 1

### ISSUE THREAD

**Issue by leroidauphin** [tensorflow/agents#357]
The docstring for the `TFAgent_train` method states that:
`This method *must* increment self.train_step_counter exactly once.`

The `PPOAgent._train` method increments ` self.train_step_counter` by `self._num_epochs`. This is because the counter in incremented (by one) by the optimizer `apply_gradients` method inside the loop which repeats `self._num_epochs` times: 
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/ppo_agent.py#L777

**Comment by summer-yue** [comment]
Thanks for the contribution! I responded in the PR, copying it here just in case:

"I have a high level question. We are actually moving away from using epoch_num inside of ppo_agent.train, and handle epochs with tf.Data pipelines outside of the agent. Given that, is there still added benefit in separating train_step_counter and global step here?"

**Comment by summer-yue** [comment]
Resolved. See the PR for more detailed discussions.
