### ISSUE TITLE
Intel-tensorflow with TF-Agents not working

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#359]
When using Intel-Tensorflow 2.1.0 on Linux and using a Q-RNN network with preprocessing layers like:
```
q_net = q_rnn_network.QRnnNetwork(
            tf_env.observation_spec(),
            tf_env.action_spec(),
            input_fc_layer_params=input_fc_layer_params,
            lstm_size=lstm_size,
            output_fc_layer_params=output_fc_layer_params,
            preprocessing_layers = tf.keras.models.Sequential(
            [tf.keras.layers.Conv2D(32, 5, 3, activation=tf.keras.activations.elu),
             tf.keras.layers.Conv2D(64, 4, 2, activation=tf.keras.activations.elu),
             tf.keras.layers.Conv2D(64, 3, 2, activation=tf.keras.activations.elu),
             tf.keras.layers.Flatten()]))
```

I get:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must provide as many biases as the last dimension of the input tensor: [64] vs. [0,84,84,3] [Op:BiasAdd] name: QRnnNetwork/EncodingNetwork/sequential/conv2d/BiasAdd/

**Comment by summer-yue** [comment]
Could you please add more information on the environment you're using, and what you set for input_fc_layer_params, lstm_size and output_fc_layer_params? Thanks!

**Comment by HadiSDev** [comment]
Environment: python 3.7.7 on Linux server
input_fc_layer_params = None,
lstm_size= (256,)
output_fc_layer_params = (256,)

**Comment by summer-yue** [comment]
You had "input_fc_layer_params = None, " with an extra comma in the end. So input_fc_layer_params is actually (None, ) which evaluates to `True`. This leads the network to parse through input_fc_layer_params as values.

Let me know if this works after you remove the comma.

**Comment by HadiSDev** [comment]
Oh sorry it is input_fc_layer_params = None without comma. I just mistakenly used it as a sentence seperator:)

**Comment by summer-yue** [comment]
What did you use as `tf_env`? When I reproduced your code with Cartpole locally it didn't complain.

**Comment by HadiSDev** [comment]
I used a custom made env for the Vizdoom RL framework:

```
class DoomEnvironmentBasic(py_environment.PyEnvironment):

    def get_info(self):
        pass

    def __init__(self):
        super().__init__()

        self._game = self.configure_doom()
        self._num_actions = self._game.get_available_buttons_size()

        self._action_spec = array_spec.BoundedArraySpec(shape=(), dtype=np.int32, minimum=0,
                                                        maximum=self._num_actions - 1, name='action')
        self._observation_spec = array_spec.BoundedArraySpec(shape=(84, 84, 3), dtype=np.float32, minimum=0, maximum=1,
                                                             name='observation')

    @staticmethod
    def configure_doom(config_name="../Scenarios/basic.cfg"):
        game = DoomGame()
        directory = os.path.dirname(os.path.realpath(__file__))
        game.load_config(os.path.join(directory, config_name))
        game.set_mode(Mode.PLAYER)
        game.init()
        return game

    def action_spec(self):
        return self._action_spec

    def observation_spec(self):
        return self._observation_spec

    def _reset(self):
        self._game.new_episode()
        return time_step.restart(self.get_screen_buffer_preprocessed())

    def _step(self, action):
        if self._game.is_episode_finished():
            # The last action ended the episode. Ignore the current action and start a new episode.
            return self.reset()

        # construct one hot encoded action as required by ViZDoom
        one_hot = [0] * self._num_actions
        one_hot[action] = 1

        # execute action and receive reward
        reward = self._game.make_action(one_hot)

        # return transition depending on game state
        if self._game.is_episode_finished():
            return time_step.termination(self.get_screen_buffer_preprocessed(), reward)
        else:
            return time_step.transition(self.get_screen_buffer_preprocessed(), reward)

    def render(self, mode='rgb_array'):
        """ Return image for rendering. """
        return self.get_screen_buffer_frame()

    def get_screen_buffer_preprocessed(self):
        """
		Preprocess frame for agent by:
		- cutout interesting square part of screen
		- downsample cutout to 84x84 (same as used for atari games)
		- normalize images to interval [0,1]
		"""
        frame = self.get_screen_buffer_frame()
        cutout = frame[10:-10, 30:-30]
        resized = cv2.resize(cutout, (84, 84))
        return np.divide(resized, 255, dtype=np.float32)

    def get_screen_buffer_frame(self):
        """ Get current screen buffer or an empty screen buffer if episode is finished"""
        if self._game.is_episode_finished():
            return np.zeros((120, 160, 3), dtype=np.float32)
        else:
            return self._game.get_state().screen_buffer
```

**Comment by HadiSDev** [comment]
I forgot to say that the code works in normal Tensorflow 2.1.0

**Comment by tfboyd** [comment]
@HadiSDev 

I am going to try to repro and then escalate to intel. It has been a year or so since I worked with Intel even remotely close and I thought their TF builds just added some MKL-DNN which should have zero impact on the API.

**If you can send me a github repo with the code to run, it would save me some work** and make it more likely I can escalate. I know it seems easy.

I am not an RL expert; and my goal is to run it with TF 2.1 and then the intel build; verify; then escalate to my Intel contacts. Putting together a sample with your snippets takes me more time that I want to admit.  :-)  Ok I Just admitted it takes me too long.  

Thanks.

**Comment by HadiSDev** [comment]
Hi @tfboyd 

as far as I can see from the error, testing with an environment which is has the specs:

```
self._action_spec = array_spec.BoundedArraySpec(shape=(), dtype=np.int32, minimum=0,
                                                        maximum=self._num_actions - 1, name='action')
        self._observation_spec = array_spec.BoundedArraySpec(shape=(84, 84, 3), dtype=np.float32, minimum=0, maximum=1,
                                                             name='observation')
```

It should be enough.

Then use random numpy arrays in the step function :)

**Comment by tfboyd** [comment]
A link to working code with repro would be better.  I am going to have to
setup a branch with the example. The goal here is to reproduce it and
package it for Intel.  We normally do a unit test, but running a command
after a basic git clone is good as well.

If I find a bigger time block to setup an example and then test I will come
back. Testing is maybe 30-60min.  Setting up an example from scratch will
take me 2-3x that plus unknowns.

**Comment by kteavery** [comment]
Any updates on this thread?

**Comment by HadiSDev** [comment]
I think I am going to close this since my project is finished and don't need a fix anymore.

**Comment by Kaushal1011** [comment]
I am working on a similar project where i have a custom environment and I am using a DQNAgent. I get the same error with tensorflow-cpu but tensorflow-gpu seems to work fine. Any Updates?
