### ISSUE TITLE
1_dqn_tutorial.ipynb compute_avg_return should be in batch

### ISSUE THREAD

**Issue by jimmy6** [tensorflow/agents#361]
1_dqn_tutorial.ipynb compute_avg_return method should be in batch.

**Comment by summer-yue** [comment]
Can you please elaborate the issue you ran into? Is this a request to add a batched version of compute_avg_return in the existing Colab?

**Comment by jimmy6** [comment]
Yes! I want a batched version of compute_avg_return

**Comment by tfboyd** [comment]
Closing due to age and lack of recent activity. If the issue still exists, please open a new issue and reference this one.
