### ISSUE TITLE
Question: Is the replay buffer a priority replay buffer?

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#362]
Hi
I just want to be sure that the TFUniform Replay buffer is priorities. My assumption is yes, but I can't really confirm it from the API docs.
Thanks in advance

**Comment by summer-yue** [comment]
+kbanoop

I didn't think TFUniformReplayBuffer is prioritized (My impression was sampling from there is entirely uniform). I'm not super sure about this, so I tagged a colleague of mine who knows more.

If you elaborate a bit more on your use case, we can probably give a recommendation on which replay buffer to use.

**Comment by HadiSDev** [comment]
Well I don't have a lot of RAM, so I want to make sure that the replay experience I select is the one with the highest lost. I wan't to avoid selecting the easy experiences to predict and keep the hard ones

**Comment by kbanoop** [comment]
Unfortunately the TFUniformReplayBuffer doesn't support priorities. We are working on another replay buffer which will support it, but AFAIK it will be open sourced only towards the end of this month @ebrevdo

**Comment by ebrevdo** [comment]
Yep; something's gonna be available soon.

**Comment by summer-yue** [comment]
Closing this since the question has been addressed. Please feel free to re-open if you have follow-up questions. Will update here when the replay buffer with priorities becomes available.

**Comment by mcmah309** [comment]
Any update on the prioritized replay buffer release?
