### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by v-sivak** [tensorflow/agents#364]
Hi! 

It looks like either 'nest_utils.get_outer_shape' or 'common.replicate' might have a bug on batched dictionary actions. 

An example: I am creating a policy which is supposed to output zero action

```
class IdlePolicy(fixed_policy.FixedPolicy):

    def __init__(self, time_step_spec, action_spec):
        zero_action = tensor_spec.zero_spec_nest(action_spec)
        super(IdlePolicy, self).__init__(zero_action, time_step_spec, action_spec)
```

with 'action_spec'
```
{'alpha': TensorSpec(shape=(1, 2), dtype=tf.float32, name=None),
 'beta': TensorSpec(shape=(1, 2), dtype=tf.float32, name=None),
 'phi': TensorSpec(shape=(1, 1), dtype=tf.float32, name=None)}
```
and 'time_step_spec'

`TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation={'alpha': TensorSpec(shape=(1, 2), dtype=tf.float32, name=None), 'beta': TensorSpec(shape=(1, 2), dtype=tf.float32, name=None), 'phi': TensorSpec(shape=(1, 1), dtype=tf.float32, name=None), 'msmt': TensorSpec(shape=(1, 1), dtype=tf.float32, name=None)})`

Now create a time_step with batch size 10 and take action:
```
time_step = tensor_spec.zero_spec_nest(time_step_spec, outer_dims=(10,))
policy.action(time_step)
```
It throws this error:
```
Traceback (most recent call last):

  File "<ipython-input-83-50f99c7e90ea>", line 1, in <module>
    policy.action(time_step)

  File "C:\Users\qulab\Anaconda3\envs\tf-agents\lib\site-packages\tf_agents\policies\tf_policy.py", line 279, in action
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)

  File "C:\Users\qulab\Anaconda3\envs\tf-agents\lib\site-packages\tf_agents\utils\common.py", line 154, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)

  File "C:\Users\qulab\Anaconda3\envs\tf-agents\lib\site-packages\tf_agents\policies\fixed_policy.py", line 68, in _action
    action = common.replicate(self._action_value, outer_shape)

  File "C:\Users\qulab\Anaconda3\envs\tf-agents\lib\site-packages\tf_agents\utils\common.py", line 992, in replicate
    tensor_ndims = len(tensor.shape)

AttributeError: 'dict' object has no attribute 'shape'
```

This is tf-agents 0.4.0
The same approach works fine if I don't use a dictionary and simply flatten everything into one tensor.
Am I doing something wrong here?

**Comment by ormandi** [comment]
Sorry, for the late response. Taking a look, but here is a preliminary question:

Are you sure that `time_step` looks good after the call `time_step = tensor_spec.zero_spec_nest(time_step_spec, outer_dims=(10,))`?

**Comment by v-sivak** [comment]
Yes time_step looks good.

**Comment by ormandi** [comment]
Thanks. How do you exactly create the `policy`? Or even better, could you please put together a runnable minimal repro showing how the components are instantiated, how some sample data is created?

**Comment by ormandi** [comment]
Ah, please ignore what I wrote above, I think I was able to reproduce it with this using:

```
from tf_agents.trajectories import time_step as ts

class IdlePolicy(fixed_policy.FixedPolicy):
  def __init__(self, time_step_spec, action_spec):
    zero_action = tensor_spec.zero_spec_nest(action_spec)
    super(IdlePolicy, self).__init__(zero_action, time_step_spec, action_spec)

def repro():
  action_spec = {
    'alpha': tensor_spec.TensorSpec(shape=(1, 2), dtype=tf.float32, name=None),
    'beta': tensor_spec.TensorSpec(shape=(1, 2), dtype=tf.float32, name=None),
    'phi': tensor_spec.TensorSpec(shape=(1, 1), dtype=tf.float32, name=None)}
  time_step_spec = ts.time_step_spec(action_spec)

  policy = IdlePolicy(time_step_spec, action_spec)
  time_step = tensor_spec.zero_spec_nest(time_step_spec, outer_dims=(10,))
  policy.action(time_step)

repro()
```

Can you please confirm if this the right repro (just to make sure that I'm on the right track)?

Btw, in your `time_step_spec` there is an extra field `'msmt': TensorSpec(shape=(1, 1), dtype=tf.float32, name=None)`. I assume that it is not critical. It doesn't seem to affect the error at all.

**Comment by v-sivak** [comment]
Yes this reproduces the same error. It's true -- in the `time_step_spec` that I have provided there is this additional field `'msmt'` because I am combining the action with it and feeding this as observation into my agent. I agree that this shouldn't affect the error.

**Comment by ormandi** [comment]
Thanks again for reporting this.

Yes, this seems to be an issue in `fixed_policy.FixedPolicy`. It uses `common.replicate` on nested structures, but `common.replicate` doesn't support this. Adding a small utility function to `fixed_policy.FixedPolicy` which calls `common.replicate` respecting the nested structure of the action will handles it. Working on it please bear with me.

**Comment by v-sivak** [comment]
Great, thank you very much for looking into this!
