### ISSUE TITLE
Where can I set a random seed in order to obtain the same actions, states and rewards?

### ISSUE THREAD

**Issue by cris4414** [tensorflow/agents#366]
I need to run my TF_agents code multiple times and to obtain the same set of actions, states and rewards and I cannot figure out where and how to set a random seed. 
Firstly, I have a collect driver function that collects me data and I'm thinking maybe a random seed should be set in here initially:

    def _init_collect_driver(self):
        self.return_observer = AverageReturnMetric(buffer_size=nr_training_steps)
        self.nr_steps_observer = AverageEpisodeLengthMetric(buffer_size=nr_training_steps)
        self.collect_driver = DynamicEpisodeDriver(
            env=self.train_env,
            policy=self.collect_policy,
            observers=[self.replay_buffer.add_batch, self.return_observer, self.nr_steps_observer],
            num_episodes=collect_episodes_per_step)

Secondly, I think I need to set up a seed in the place where the actions are generated, and I found that they are generated in this function from tf_policy.py:

  def action(self, time_step, policy_state=(), seed = None):
   
    if self._enable_functions and getattr(self, '_action_fn', None) is None:
      raise RuntimeError(
          'Cannot find _action_fn.  Did %s.__init__ call super?' %
          type(self).__name__)
    if self._enable_functions:
      action_fn = self._action_fn
    else:
      action_fn = self._action

    tf.nest.assert_same_structure(time_step, self._time_step_spec)
    tf.nest.assert_same_structure(policy_state, self._policy_state_spec)

    if self._automatic_state_reset:
      policy_state = self._maybe_reset_state(time_step, policy_state)
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=12)

    def clip_action(action, action_spec):
      if isinstance(action_spec, tensor_spec.BoundedTensorSpec):
        return common.clip_to_spec(action, action_spec)
      return action

    if self._clip:
      clipped_actions = tf.nest.map_structure(clip_action, step.action,
                                              self._action_spec)
      step = step._replace(action=clipped_actions)

    tf.nest.assert_same_structure(step, self._policy_step_spec)

    def compare_to_spec(value, spec):
      return value.dtype.is_compatible_with(spec.dtype)

    compatibility = tf.nest.flatten(
        tf.nest.map_structure(compare_to_spec, step.action, self.action_spec))

    if not all(compatibility):
      get_dtype = lambda x: x.dtype
      action_dtypes = tf.nest.map_structure(get_dtype, step.action)
      spec_dtypes = tf.nest.map_structure(get_dtype, self.action_spec)

      raise TypeError('Policy produced an action with a dtype that doesn\'t '
                      'match its action_spec. Got action: %s with '
                      'action_spec: %s' % (action_dtypes, spec_dtypes))

    return step

 The above function is aparently implemented by this function:

  def _action(self, time_step, policy_state, seed):
    seed_stream = tfp.util.SeedStream(seed, salt='ppo_policy')
    distribution_step = self._distribution(time_step, policy_state)
    actions = tf.nest.map_structure(
        lambda d: reparameterized_sampling.sample(d, seed=seed_stream()),
        distribution_step.action)
    info = distribution_step.info
    if self.emit_log_probability:
      try:
        log_probability = tf.nest.map_structure(lambda a, d: d.log_prob(a),
                                                actions,
                                                distribution_step.action)
        info = policy_step.set_log_probability(info, log_probability)
      except:
        raise TypeError('%s does not support emitting log-probabilities.' %
                        type(self).__name__)
    return distribution_step._replace(action=actions, info=info)

I mention that I tried to set the seed parameter to a value, but I still don t obtain identical actions from different runs. What should I do to obtain identical results?

Thank you

**Comment by ormandi** [comment]
May I ask that why you want to do this if you don't mind? Is it for testing purpose?

What is the actual policy that you are using here (the one containing the method `_action`)?

**Comment by cris4414** [comment]
Yes, it's for testing purpose.
_action is contained in py_policy

**Comment by ormandi** [comment]
Thank you for your response, and sorry for the delay on this.

If you need the environment to be deterministic, then you're probably better off using a dedicated test environment e.g. [`CountingEnv`](https://github.com/tensorflow/agents/blob/a39f922d5546ffe9cb23a93a3c8c8afa85d9c253/tf_agents/environments/test_envs.py#L33). On the other hand, if you need the the policy to be fixed, you probably want to take a look into [`FixedPolicy`](https://github.com/tensorflow/agents/blob/a39f922d5546ffe9cb23a93a3c8c8afa85d9c253/tf_agents/policies/fixed_policy.py#L33).

**Comment by cris4414** [comment]
Thank you. 
I will have a look into these

**Comment by ormandi** [comment]
Thank you. Please feel free to reopen this if anything related comes up.

**Comment by cris4414** [comment]
I ve looked into what you sent to me. I see that FixedPolicy requires me to give to it a tensor with actions, as well as action_spec and observation_spec. This is not what I want.

I want to have reproducible results in my experiments, which means that, for multiple runs I want the policy to randomly choose points, but for the same points to pick the same actions for all the runs.

**Comment by dthsptctr** [comment]
I have the same problem. @cris4414 did you find any solution?

**Comment by cris4414** [comment]
No, I didn t

**Comment by bbeniamin** [comment]
@dthsptctr if you just want to produce identical experiments it should be enough to fix your random seeds. Make sure that besides the tensorflow* random seed, you also fix the seeds in python's and numpy's random modules and anything else that might introduce randomness in your environment.

*note: if you use a GPU for training it might not be possible to have 100% identical results

**Comment by dthsptctr** [comment]
Thanks

But I was already using the following random seeds:

random.seed(0)
tf.random.set_seed(0)
np.random.seed(0)
tf.compat.v1.set_random_seed(0)
tf.experimental.numpy.random.seed(0)

but this didn't work.
(I am using a CPU for training.)
