### ISSUE TITLE
tensorflow environment

### ISSUE THREAD

**Issue by mouadouad** [tensorflow/agents#373]
I am new to q learning and I have a game pretty similar to the cartpole game in openAI , written in python , so I wanted to apply for it the tutorial in tensorflow documentation but I didn't know how to convert my game to a proper environment so that tensorflow agents could work. Thank you!

**Comment by ormandi** [comment]
Thank you so much for your question. 

I may start with https://github.com/tensorflow/agents/blob/master/docs/tutorials/2_environments_tutorial.ipynb
Please see the section "Creating your own Python Environment".

**Comment by mouadouad** [comment]
Thank you so much for your answer, but I already tried doing that and I get an error in time_step_spec().
Thank you again!

**Comment by kbanoop** [comment]
Can you please elaborate on the error? And paste some code if possible?

Thanks!

**Comment by ayansengupta17** [comment]
TimeStep is a named tuple of step_type, reward, discount, observation. While you create your own environment, you give some structure to your observation space and action space. Check that they are correct throughout the code.
For example:
```
self._observation_spec = array_spec.BoundedArraySpec(
        shape=(1,), dtype=np.int32, minimum=0, name='observation')
```

So here observation spec is 1-D array, 1 element long, in one row containg only integers whose minimum values is 0. But later if your observation is a float or shapes don't match, then you will have an  time_step_spec() error. So check your shapes first. See if you need (1,) or () in shape, or dtype is different. These are the common errors one face while writing their first environment.

**Comment by mouadouad** [comment]
Thank you so much for your answers, I really appreciate it. Sorry for being late for my answer, I had to prepare my exams. 
I will gladly try your recommandations. And hopefully it would work.
Thank you again!

**Comment by tfboyd** [comment]
Closing due to being stale.
