### ISSUE TITLE
Questions about input of policy.action

### ISSUE THREAD

**Issue by dvdhfnr** [tensorflow/agents#378]
The documentation of the policies contains the following statement:

> In TF-Agents, observations from the environment are contained in a named tuple TimeStep('step_type', 'discount', 'reward', 'observation'), and policies map timesteps to actions or distributions over actions. Most policies use timestep.observation, some policies use timestep.step_type (e.g. to reset the state at the beginning of an episode in stateful policies), but timestep.discount and timestep.reward are usually ignored.

We are currently writing a new policy, and we are wonder why the input to the action method is the _complete_ timestep structure and not only the observation (+ step_type). Is there any policy that requires the discount and reward to decide for a new action, or is there another non-obvious reason?

**Comment by DylanCope** [comment]
It helps to dive into the source to answer this question. If we take a look at the implementation of the action method:

https://github.com/tensorflow/agents/blob/d25419cad91b3d46d65b15d74a68dacfe68747f1/tf_agents/policies/tf_policy.py#L260

We see that there is a call to another method, `_maybe_reset_state`:

https://github.com/tensorflow/agents/blob/d25419cad91b3d46d65b15d74a68dacfe68747f1/tf_agents/policies/tf_policy.py#L241

This method uses other information from the time step object, such as whether or not it is the first time step.

Another reason is that some policies require the `step_type`, for instance, DQNs:

https://github.com/tensorflow/agents/blob/d25419cad91b3d46d65b15d74a68dacfe68747f1/tf_agents/policies/q_policy.py#L123

**Comment by dvdhfnr** [comment]
Hi DylanCope,

Thanks for your answer.

`step_type` and `policy_state` are totally understandable and fine.

I mainly refer to the data inside the `time_step` structure.
a) The `observation` and `step_type` are needed. That is fine.
b) But why do we need the `discount` and the `reward` as input for the `action` method?

**Comment by kbanoop** [comment]
Agree this is a little awkward, it was done initially so that it is easy to pass the `time_step` obtained from the environment directly to `policy.action(time_step)`

`discount` and `reward` are usually unused by the policy.

**Comment by dvdhfnr** [comment]
Ok, thanks a lot for your answer!
