### ISSUE TITLE
Info about non scalar rewards implementation

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#383]
I will try to simplify my question with a general example maybe usefull also for other users:

Lets's say we have an agent monitoring 3 different rooms.
In every room we can have 1 or more sensors (e.g tempearature ...)
Assume just one to make this example easy.

so my observation is something like this

	observation = {
		sensor1: [....],
		sensor2: [....],
        	... 
		sensorN: [....]
		}

The policy output is a tensor with shape (9,)  that is rehaped by an external module to a tensor with shape (3,3) that represent the 3 predicted values to control a specific device placed in each room to manage it.

In a previous SAC agent version I had a single scalar reward composed by the sum of each single reward from each sensor.

	reward_spec = TensorSpec(shape=[], dtype=tf.float32, name='reward')
	reward = sum(reward_sensor1 + reward_sensor1 + .... reward_sensorN)

Now, based on this 2 papers:

http://www.cs.ucr.edu/~cshelton/papers/docs/nips00-mrl.pdf
https://arxiv.org/abs/2005.07541

I would like to implement a more sophisticated reward signal that should be able to tell to the agent the specific reward obtained from each specific sensor avoiding to sum up them and than maybe loosing usefull info.

Basically I will end up with 2 rewards for each sensor at every time step and my reward will have spec:
 
	num_of_sensors = num_of_rooms * sensors_per_room

	reward_spec = {
        	step_reward: TensorSpec(shape=(num_of_sensors,), dtype=tf.float32, name='r1'),
		goal_reward: TensorSpec(shape=(num_of_sensors,), dtype=tf.float32, name='r2'),
		}

 (the names step_reward, and goal_reward are here just for pure presentation purpose).

 for each sensor the desired relation between action and reward is represented by this schema:
 [SENSOR] >> [ACTION (3,)] >> [REWARD (2,)]

I saw that you are currently working on enabling non scalar rewards, so my question is with the next release 0.5.0 it will be possible to implement this type of rewards in the SAC agent just by changing the reward spec and the output reward from the environement, or more deep changes will be necessary? or maybe is already possible to implement this?
thx

**Comment by sguada** [comment]
So allowing non-scalar rewards is only part of the puzzle, SAC as most RL algorithms are designed for only scalar rewards. So you still need to convert to a single scalar at some point or use use a multi-agent algorithm.
