### ISSUE TITLE
Remove imports from `__future__`

### ISSUE THREAD

**Issue by leroidauphin** [tensorflow/agents#398]
The Python standard library includes a module called `__future__`, which contains function definitions which document (among other things) when breaking changes were introduced into the Python language. This module was of particular value around the Python 2/Python 3 boundary.

The TF-Agents project no longer supports Python 2, and includes code which is only valid in Python 3. Given that there is no longer official support for Python 2, it is now possible to remove most if not all of the import statements from the `__future__` module.

**Comment by tfboyd** [comment]
This is totally logical. Unfortunately, we have a couple teams still using Python2 internally our internal build system works a bit differently than most and they cannot really pin to a specific "release" like an external user as a temp solution. My educated guess is we can remove __future__ in 2021.

**Comment by tfboyd** [comment]
This has started to happen and all new code is PY3 only.  I am going to close this as we are not actively watching this issue and future will get removed over time.
