### ISSUE TITLE
Extending Replay Buffer to prioritise certain trajectories 

### ISSUE THREAD

**Issue by RossKohler** [tensorflow/agents#401]
Could someone provide me advice on how I could extend the ReplayBuffer class found here https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/replay_buffer.py to prioritise sampling trajectories with a metric such as those with higher rewards? Is there any documentation or examples that can help me? Is extending the ReplayBuffer class the correct way to achieve this? 

Thanks!

**Comment by summer-yue** [comment]
We are working on open sourcing our new replay buffer using Reverb(https://github.com/deepmind/reverb) that supports your use case. We are looking at a July release. Stay tuned :)

**Comment by RossKohler** [comment]
Looking forward to it! thanks @summer-yue 🥳

**Comment by summer-yue** [comment]
Check out the newly open sourced Reverb Replay Buffer (https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/reverb_replay_buffer.py) that supports priorities! :D
