### ISSUE TITLE
Is there a way to keep Replay Buffer on disc rather than in RAM?

### ISSUE THREAD

**Issue by fedor-chervinskii** [tensorflow/agents#402]
Basically, save the episodes on disc, maybe indexing it properly (tf-records?) and then loading batches from storage (in parallel to training)? Or is there other way how we can manage Replay Buffer with images that do not fit into RAM?

**Comment by oars** [comment]
Take a look at: https://github.com/tensorflow/agents/blob/master/tf_agents/utils/example_encoding_dataset.py

You can save data to disk when doing data collection and then use dataset tools to train from it.

**Comment by dtransposed** [comment]
Hey @oars thank your for your help. It is so great that the solution has already been implemented. I have followed your advice and successfully implemented the functionality.
However, I still have three questions related to the "write-to-disk" replay buffer properties:

1. In the code you have provided, I fail to see some argument, which will allow me to constrain the size of the replay buffer, like we normally do when calling `tf_uniform_replay_buffer.TFUniformReplayBuffer`. Have I missed something, or is it not implemented yet? If the latter is true, do you have any idea how one may go about tackling this problem?

2. I have modified the structure of `agents/tf_agents/agents/td3/examples/v2/train_eval.py` so the experience is saved to the disk and then fetched during training. So roughly, the code looks like:

a) The setup
```
observer = TFRecordObserver(...)
observer = common.function(observer)
collect_driver = dynamic_episode_driver.DynamicEpisodeDriver(tf_env, collect_policy, [observer])
```

b) Initializing the "pipe" for reading outside the "training loop" and then fetching the data as needed (using iterator):
```
dataset = load_tfrecord_dataset(...).batch(batch_size)
iterator = iter(dataset)
while True:
    time_step, policy_state = collect_driver.run(time_step=time_step, policy_state=policy_state)
    for _ in range(updates_per_episode):
        experience = next(iterator)
        train_loss = tf_agent.train(experience)
```
c) Initializing the "pipe" for reading inside the "training loop"
```
while True:
    time_step, policy_state = collect_driver.run(time_step=time_step, policy_state=policy_state)
    dataset = load_tfrecord_dataset(...).batch(batch_size)
    iterator = iter(dataset)
    for _ in range(updates_per_episode):
        experience = next(iterator)
        train_loss = tf_agent.train(experience)
```

So when running the combination of a) + c), I get the desired behaviour and the model trains as expected. 
However, the intuitive way would be a) + b), to initialise `dataset` and `iterator` outside the training loop and then fetching data one element at the time inside the training loop. While the former approach is working, the latter gives me an error:
```
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 346895670
```
Could you elaborate on the proper way of reading the TFRecords in the training loop?

3. Given that this functionality of reading to- and from- disk has been implemented, have you guys thought of implementing the training routine which is not sequential, as currently done, i.e.
```
for _ in range(number):
    gather data
    train
```
but having two separate processes, call them sampler and trainer, where sampler interacts with the world, gathers the data and dumps them to disk. The trainer would fetch the experience, train the model, and occasionally send the "fresh" weights to the sampler (so the data distribution slowly evolves and approaches the most optimal states). I suspect this could have many advantages, such as faster training speed for instance.

Maybe there are some snippets in the codebase that could possibly help me with implementing such a training routine?
