### ISSUE TITLE
Do we have a plan to develop a GAIL agent?

### ISSUE THREAD

**Issue by tanliboy** [tensorflow/agents#405]
I noticed that we are developing the `BehavioralCloningAgent`. Do we have a plan to develop [GAIL](https://arxiv.org/abs/1606.03476) agent as well?

**Comment by ebrevdo** [comment]
Not at this time; though we are looking into other offline-friendly variants like BRAC and CQL.  We're not keeping a tracking issue for that though.  For now you can find some external codebases using tf-agents, like [BRAC](https://github.com/google-research/google-research/tree/master/behavior_regularized_offline_rl).

**Comment by ebrevdo** [comment]
(we are looking at imitation learning too, just not GAIL)
