### ISSUE TITLE
EncodingNetwork breaks with only one preprocessing layer.

### ISSUE THREAD

**Issue by youngalou** [tensorflow/agents#41]
Currently the EncodingNetwork class cannot accept a single preprocessing layer.

When `preprocessing_layers` are passed as an attribute to the `EncodingNetwork` class the outputs of the preprocessing layers are stored in a list `states`. 
`states` is passed to the `preprocessing_combiner` layer, which reduces `states` to a single tensor.
This tensor is then passed to the `_postprocessing_layers`.

The issue arises when passing a single preprocessing layer.
Because we only have one preprocessing layer, we do not need a preprocessing combiner. But, without a `preprocessing_combiner` layer, `states` is passed to `_postprocessing_layers` as a list which causes an error.

I propose adding an elif to the `call` function as follows:
```
if self._preprocessing_layers is None:
      processed = observation
elif len(self._preprocessing_layers) == 1:
      processed = self._preprocessing_layers[0](observation)
else:
      processed = []
      for obs, layer in zip(
          nest.flatten_up_to(self.input_tensor_spec, observation),
          self._preprocessing_layers):
        processed.append(layer(obs))
```

**Comment by sguada** [comment]
Another solution would be to pass a lambda layer as a preprocessing_combiner

`tf.keras.layer.Lambda(lambda x: x[0])`

**Comment by eito-fis** [comment]
Is there a scenario in which one would use a `preprocessing_combiner` with one `preprocessing_layer`? It feels unintuitive to pass a combiner that does nothing when we have only one layer.

**Comment by sguada** [comment]
We could change the code when only one `preprocessing_layer` is passed and `preprocessing_combiner is None` to default just unpack the list.

**Comment by tfboyd** [comment]
Little cleanup and issue bankruptcy. Issue is ~2 years old. I am sorry that this did not end with a solution. If you find this issue in the future please open a new one and reference this one if desired.
