### ISSUE TITLE
Creating a dataset of trajectories using dm-reverb.

### ISSUE THREAD

**Issue by dtransposed** [tensorflow/agents#410]
First of all I wanted to thank you guys so much for this repository and @oars for the help so far.
As suggested in my previous issue #404 but also #408 or #401, you are planning to incorporate Deepmind's Reverb framework for data management. This is why I am hoping that you could help me with my small issue.

As suggested by @oars in #404, I have started playing with Reverb to alleviate one of my current pains and I love it. However, there is one problem I cannot solve and perhaps you are already past figuring it out.

I am trying to use reverb's client and server framework to serve as replay buffer for my td3 tf-agent.

1. I set the server and keep it running in the background.
2. I slightly modify your `https://github.com/tensorflow/agents/blob/master/tf_agents/drivers/dynamic_step_driver.py` by basically adding the following line of code:
```
with tf.control_dependencies([tf.group(observer_ops + transition_observer_ops)]): # Line 149
        time_step, next_time_step, policy_state = tf.nest.map_structure(tf.identity, (time_step, next_time_step, policy_state))
        client.insert((time_step, next_time_step), {'my_table': 1.0}) # Additional line of code
```
This means my client inserts a sample (current_SARS, next_SARS) in the server's table while the driver is running. This sample could be later on reshaped into (B, 2, ... ) Trajectory required by `tf_agent.train()` method.

3. Now this is where things get rocky. As suggested in reverb's tutorials, I am creating dataset out of the collected experience:
```
dataset = tf_client.dataset(
            table='my_table',
            dtypes= ?,
            shapes=? )
```
I have been naively specifying types and shapes as:
```
dtypes = ((tf.int32, tf.float32, tf.float32, {'inp1': (tf.uint8, tf.uint8, tf.uint8, tf.uint8),
                                                                     'inp2': (tf.float32, tf.float32)}),
                  (tf.int32, tf.float32, tf.float32, {'inp1': (tf.uint8, tf.uint8, tf.uint8, tf.uint8),
                                                                     'inp2': (tf.float32, tf.float32)}))

shapes = ((1,1,1, {'inp1': (1, H,W,C), 'inp2':(1,X)}),
                  (1,1,1, {'inp2': (1, H,W,C), 'inp2':(1,X)}))
```
Since that's what the Trajectory object contains (step, reward, discount, observation). My observation in this case is a dict with two keys (two inputs). This returns a `ReplayDataset` object as expected. But then attempting to use this object in any way (e.g. calling `.take()` or `sample()`), it gives me Error: signal 11: followed by a bunch of confusing Tensorflow error messages and crashes the code.

If have tried to run exactly same code using simpler data structures (basically inserting tf tensors in point 2 instead of tuple of trajectories) and then the code runs properly (I can fetch samples from the dataset). So the key is understanding how to construct `types` and `shapes` argument, so that they are being properly understood by the `tf_client.dataset()`. Perhaps you have already struggled with similar problem?

**Comment by summer-yue** [comment]
I haven't seen the segfault you described, but here's how we set the dtypes and shapes:

```
self.data_spec = agent.collect_data_spec  // set in the constructor of the ReverbRB

# Before calling client.dataset 
get_dtype = lambda x: tf.as_dtype(x.dtype)
get_shape = lambda x: (sequence_length,) + x.shape
shapes = tf.nest.map_structure(get_shape, self.data_spec)
dtypes = tf.nest.map_structure(get_dtype, self.data_spec)

dataset = client.dataset(
        table,
        dtypes,
        shapes,
        ......
    )
```

If that didn't help, you could try making a small example that reproduces this problem, and file an issue for the Reverb folks.

**Comment by dtransposed** [comment]
Hey @summer-yue!
Thanks for your help. I have tried to reproduce the problem using minimal example. Could you take a look?
https://github.com/dtransposed/TF-Agents_reverb_investigation/blob/master/investigation.ipynb

Edit: Perhaps I should also check my environment? Because dm requires TF 2.3 (nightly), I am also using current TF-Agents nightly release. This could also be a possible source of some trouble I suspect.

**Comment by summer-yue** [comment]
There is a typo in your example: **shapes=dtypes** 

```
dataset = training_client.dataset(
        table='my_table',
        dtypes=dtypes,
        shapes=dtypes)
```

**Comment by dtransposed** [comment]
Oh, that's embarrassing! Sorry for this. Just changed the typo and the minimal example is running smoothly, thank you so much! I think we can close!
