### ISSUE TITLE
'TensorSpec' object has no attribute 'maximum'  In call to configurable 'DdpgAgent'

### ISSUE THREAD

**Issue by mcmah309** [tensorflow/agents#411]
I am trying to declare a ddpg agent. When I run this code:

`input=tf.TensorSpec((1,100,35), dtype=tf.dtypes.float32, name=None)
out=tf.TensorSpec((1,), dtype=tf.dtypes.float32, name=None)
#input=array_spec.BoundedArraySpec((1,100,35), dtype=np.float32, name=None, minimum=0,maximum=1)
#out=array_spec.BoundedArraySpec((1,), dtype=np.float32, name=None, minimum=0,maximum=96)

actor=agents.ddpg.actor_network.ActorNetwork(input, out)
actor_target=agents.ddpg.actor_network.ActorNetwork(input, out)

critic=agents.ddpg.critic_network.CriticNetwork((input, out))
critic_target=agents.ddpg.critic_network.CriticNetwork((input,out))

new_agent=agents.DdpgAgent(
    time_step_spec=train_env.time_step_spec(),
    action_spec=train_env.action_spec(),
    actor_network=actor,
    critic_network=critic,
    target_actor_network=actor_target,
    target_critic_network=critic_target)`

I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-262-45691c184e55> in <module>()
     16     critic_network=critic,
     17     target_actor_network=actor_target,
---> 18     target_critic_network=critic_target)

13 frames
/usr/local/lib/python3.6/dist-packages/tf_agents/utils/common.py in <lambda>(spec)
    537   """Get the center and magnitude of the ranges in action spec."""
    538   action_means = tf.nest.map_structure(
--> 539       lambda spec: (spec.maximum + spec.minimum) / 2.0, action_spec)
    540   action_magnitudes = tf.nest.map_structure(
    541       lambda spec: (spec.maximum - spec.minimum) / 2.0, action_spec)

AttributeError: 'TensorSpec' object has no attribute 'maximum'
  In call to configurable 'DdpgAgent' (<function DdpgAgent.__init__ at 0x7f37c16f8bf8>)

I tried using what I have in comments but it still does not work. Any suggestions?

**Comment by sguada** [comment]
I think you need to use 

```
input=tensor_spec.BoundedTensorSpec((1,100,35), dtype=tf.float32, name=None, minimum=0,maximum=1)
out=tensor_spec.BoundedTensorSpec((1,), dtype=tf.float32, name=None, minimum=0,maximum=96)
```

Also make sure that `train_env.action_spec()` returns `BoundedSpecs`

**Comment by mcmah309** [comment]
Thank you that fixed it. I thought there had to be a bounded tensor spec but I could not find any mention of it on the tensorflow specs page. Here is where its located for anyone wondering `from tensorflow.python.framework import  tensor_spec` . Is there a way to discretize the action space in tensorflow?

**Comment by sguada** [comment]
you can also use `from tf_agents.specs import tensor_spec`

You can wrap the PyEnvironment with [`ActionDiscretizeWrapper`](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/wrappers.py#L332)

**Comment by mcmah309** [comment]
When you say `BoundedSpecs` do you mean `BoundedArraySpec`? I do not see it in the docs either.
I was thinking more so for the agent, because I am getting this error with the changes you suggested to the code above and I'm not sure how to resolve it. My environment is already discretized.

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-356-75d73a536e0d> in <module>()
     18     critic_network=critic,
     19     target_actor_network=actor_target,
---> 20     target_critic_network=critic_target)
     21 
     22 #does work because of continous action space

8 frames
/usr/local/lib/python3.6/dist-packages/tf_agents/policies/ou_noise_policy.py in _validate_action_spec(action_spec)
     51     def _validate_action_spec(action_spec):
     52       if not tensor_spec.is_continuous(action_spec):
---> 53         raise ValueError('OU Noise is applicable only to continuous actions.')
     54 
     55     tf.nest.map_structure(_validate_action_spec, wrapped_policy.action_spec)

ValueError: OU Noise is applicable only to continuous actions.
  In call to configurable 'DdpgAgent' (<function DdpgAgent.__init__ at 0x7f37c16f8bf8>)`

**Comment by sguada** [comment]
Sorry DDPGAgent only works for continuous and bounded action spaces, aka they are defined as as bounded range of floats `[-1.0, 1.0]` and not discretize space .

Yeah for environments I meant `BoundedArraySpec`

**Comment by mcmah309** [comment]
Okay thank you for the help!
