### ISSUE TITLE
Citing in LaTeX leads to error and may have bad formatting

### ISSUE THREAD

**Issue by tdavchev** [tensorflow/agents#421]
Current bibtex reference provided in Readme uses commas in author listing. 

LaTeX interprets all comma separated names as first names which leads to using only author initials (see attached screen). This does not comply with some paper formatting conventions. Further, it may also result in: 'Error in .bib entry, “Too many commas”' error. 

**Fix**: the provided referencing should list authors using `and` as opposed to `,` in LaTeX .

<img width="364" alt="Screenshot 2020-07-14 at 14 14 00" src="https://user-images.githubusercontent.com/2574005/87429864-518ea000-c5dc-11ea-9f18-db64be7728bf.png">

**Comment by tdavchev** [comment]
<img width="369" alt="Screenshot 2020-07-14 at 14 15 57" src="https://user-images.githubusercontent.com/2574005/87430079-9581a500-c5dc-11ea-9ecb-c28f1affca18.png">

referencing with author listing using `and`

**Comment by kbanoop** [comment]
Thanks for the suggestion!
