### ISSUE TITLE
why always num_steps = 2 while extracting dataset from replay buffer

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/agents#428]
can anyone please explain me the significance of num_steps = 2 in the following snippet
```bash
replay_buffer.as_dataset(
    batch_size = 16,
    num_steps = 2,
)
```
I am watching that everyone is using num_steps = 2.

**Comment by ayansengupta17** [comment]
Usually RL Agent needs both the current and next observation to compute the loss, so this code snippet samples two adjacent rows for each item in the batch by setting num_steps=2. So basically it sampling batches of 16 element, each with 2 timesteps.
