### ISSUE TITLE
Unable to use GPU with tf-agents

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/agents#431]
Running this simple code takes same time on GPU and CPU, here is the link to colab
https://gist.github.com/saahiluppal/9c9501c92cc2c3e66ba957793b122d8c

Am i doing something wrong? Because as far as i know, tensorflow automatically runs on gpu if available.
Can anyone take a look?

**Comment by wookayin** [comment]
Looks like CUDA-related logs are not appearing. I think the tensorflow package installed does not have GPU enabled. You may find the following APIs useful:

```
tf.test.is_built_with_gpu_support()
tf.test.is_gpu_available()
```

**Comment by saahiluppal** [comment]
getting True for both the instructions. 

It's weird, this new snippet is faster on cpu rather on cuda
you can find the new gist here.
https://gist.github.com/saahiluppal/9b93c149bae236606be044af3e48d7cf

Thanks

**Comment by saahiluppal** [comment]
Everything seems right, i guess *drivers* are taking time to complete loops or something.

**Comment by kbanoop** [comment]
Its possible that GPU may not be much faster than CPU, or could be even slower (assuming things are actually running on GPUs). Sometimes when you have e.g. small networks, there is not much speed up from using a GPU and there is extra overhead from copying data back and forth in memory
