### ISSUE TITLE
Why do we need to fill the replay buffer with random actions before the main loop?

### ISSUE THREAD

**Issue by peidaqi** [tensorflow/agents#435]
It seems for the framework to work, we have to pre-fill the replay buffer with some random actions before we enter the main loop - or it will report a "TFUniformReplayBuffer is empty" error.

But I don't quite understand why this is the case? In the main loop, the program logic will first call "collect_step", and wouldn't that fill the replay buffer?

Also what is this magic number "steps=100"? It appears in every sample code and seems to have nothing to do with the size of the replay buffer? I tried "1" and it seems to work fine. Is it just an arbitrary number?

(from official sample - Train a Deep DQN Network)
```
collect_data(train_env, random_policy, replay_buffer, steps=100)
...
for _ in range(num_iterations):
  for _ in range(collect_steps_per_iteration):
    collect_step(train_env, agent.collect_policy, replay_buffer)

  experience, unused_info = next(iterator)

```

**Comment by kuanghuei** [comment]
Most of the RL algorithms have an initial exploration phase. Many of them perform random exploration although it could be other strategy. I think this is probably described in the DQN paper. Consider the number of initial steps a hyper-param. Feel free to re-open if this doesn't answer your question.
