### ISSUE TITLE
Can I use tensorflow 1.14.0 to load tf-agent model file for prediction?

### ISSUE THREAD

**Issue by gsdt** [tensorflow/agents#438]
I would like to train an agent using tf-agent (latest version) and save completed model in a local file. After that, I want to use tensorflow 1.14.0 load this model file and using later. How can I do this?

**Comment by kuanghuei** [comment]
I think you can try that as you normally train and load checkpoints with the same tf version as long as you use the same TF-Agent version? Note that there's no guarantee as tf properties also change over time. Please feel free to reopen if this doesn't answer the question.
