### ISSUE TITLE
Action space conversion from OpenAI environment causes exception

### ISSUE THREAD

**Issue by alek5k** [tensorflow/agents#441]
Tensorflow version: 1.15.0
TF-Agents version: 0.3.0

I am generating a PyEnvironment using an OpenAI environment:

`train_env = tf_agents.environments.gym_wrapper.GymWrapper(env)`

My action space in my openAI environment is:
```
    @property
    def action_space(self):
        num_actions = self.action_space_resolver.get_total_num_actions()
        return spaces.Discrete(num_actions)
```

When I try to run the code to instantiate a DQN agent as per the code below:
```
q_net = q_network.QNetwork(
    train_env.observation_spec(),
    train_env.action_spec(),
    fc_layer_params=fc_layer_params)

agent = dqn_agent.DqnAgent(
    train_env.time_step_spec(),
    train_env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=common.element_wise_squared_loss,
    train_step_counter=train_step_counter)
```
I get the following exception shown below. Ive also provided the data inside `action_spec`:
![image](https://user-images.githubusercontent.com/20435565/89378797-f1e96780-d737-11ea-8581-76e6cb2095bf.png)

Note that len(flat_action_spec) == 1, and flat_action_spec[0].shape is an empty tuple.

**Comment by kuanghuei** [comment]
Hi that happens with python spec. Can you try wrapping with tf_py_environment and see if that solves the issue?
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v2/train_eval.py#L145

**Comment by alek5k** [comment]
Thanks, that worked. In case people are searching, here is my solution:
```python
from tf_agents.environments import gym_wrapper
from tf_agents.environments import tf_py_environment

env = MyOpenAIEnv()
py_env = gym_wrapper.GymWrapper(env)
tf_py_env = tf_py_environment.TFPyEnvironment(py_env)

# use tf_py_env
```
