### ISSUE TITLE
Cannot convert saved_model to onnx

### ISSUE THREAD

**Issue by Fax3D** [tensorflow/agents#444]
Hi,

after saving a model with `tf.saved_model.save`, i need to convert it to onnx format using tf2onnx, but i got the error:
`ValueError: make_sure failure: No signatures found in model. Try --concrete_function instead.`

What's wrong with my model?

Attached there's my python script using TF 2.3.0
[test.py.txt](https://github.com/tensorflow/agents/files/5074517/test.py.txt)

Thanks!

**Comment by kuanghuei** [comment]
It seems to me that this question should be asked on stackoverflow or, if it is a bug, on tf2onnx repo? We don't really have too much context to be able to help with this question.
