### ISSUE TITLE
v0.6.0 tag doesn't exist, breaks documentation

### ISSUE THREAD

**Issue by camille-ryan** [tensorflow/agents#445]
Documentation at https://www.tensorflow.org/agents/api_docs/python/tf_agents is for the current release version, v0.6.0

A r.0.6.0 branch exists, but no tag for it. The "view source on GitHub" links at the documentation point to v0.6.0, which doesn't exist, so all of those links are broken. 

For example, https://github.com/tensorflow/agents/blob/v0.6.0/tf_agents/trajectories/time_step.py#L42-L84

**Comment by tfboyd** [comment]
That is my bad Adding it today I missed the final step. A little embarrassing as I also documented the steps and wrote the tool to make it easier.  I will ping back when fixed.

**Comment by tfboyd** [comment]
Fixed and checked your link.
