### ISSUE TITLE
You are expected to return reward for *next* timestep?

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/agents#447]
I'm going through the C51 colab and see that the bulk of where you fit the agent into an environment is in the collect_step method

```
def collect_step(environment, policy):
    time_step = environment.current_time_step()
    action_step = policy.action(time_step)
    next_time_step = environment.step(action_step.action)
    traj = trajectory.from_transition(time_step, action_step, next_time_step)

    # Add trajectory to the replay buffer
    replay_buffer.add_batch(traj)
```

I see in the documentation that it seems like the values for reward and discount from *next* time step are used to create the trajectory. Are the values for current time step simply just unused place holders then?

**Comment by breadbread1984** [comment]
so is the time step a tuple of (r_{t-1}, o_t) or (r_t, o_t)?
