### ISSUE TITLE
How to wrap a loaded policy as greedy?

### ISSUE THREAD

**Issue by XirenZhou** [tensorflow/agents#448]
I trained an agent and save its policy using:
`
tf_policy_saver = policy_saver.PolicySaver(tf_agent.policy)
tf_policy_saver.save(policy_dir)
`
And I load it by `tf.saved_model.load(policy_dir)`.
When trying to wrap it as greedy: `deterministic_policy = greedy_policy.GreedyPolicy(policy)`, it throws:
`
AttributeError: '_UserObject' object has no attribute 'time_step_spec'
In call to configurable 'GreedyPolicy' (<class 'tf_agents.policies.greedy_policy.GreedyPolicy'>)
`
Apparently the loaded object with the high level api `tf.saved_model.load()` is a `_UserObject` instead of a policy object. So how can I conduct the greedy wrapping other than retraining the entire agent and saving its greedy version?

**Comment by kbanoop** [comment]
Can you try loading with SavedModelPyTFEagerPolicy(path, ..., load_specs_from_pbtxt=True)

https://github.com/tensorflow/agents/blob/ad98ff51d4a1d1e1d4ac91a09ee7fe135db8971b/tf_agents/policies/py_tf_eager_policy.py#L102

Closing for now, please reopen if this does not resolve the issue.
