### ISSUE TITLE
#Actor-Learner Some suggestions

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#449]
It's a great idea to have this API that uses the same concept as ACME. Ideally TF-Agent and ACME should be inter-operable.

For the naming `Actor` corresponds more to `EnvrionmentLoop` in ACME. For me `ActorLoop` is more suitable than `Actor`.

In the Learner you use object `Trigger` why not using `Callback`  to keep the same terminology as Keras. Somehow, `Learner` is the `Model` counter part of Keras so having abstraction consistant across the TF ecosystem will help user to get started rapidly.

**Comment by tfboyd** [comment]
I have no idea if this suggestion was taken, but the people that were working on the learner were tagged as Assignees.  Closing because this is now over a year old with not recent comments. I do appreciate the insightful comment on the API. Thank you.
