### ISSUE TITLE
Are there any plans/did I miss possible implementation of Deep Convolutional Q-Learning agents (Doom and other video games?)

### ISSUE THREAD

**Issue by TimbusCalin** [tensorflow/agents#450]

**Comment by camille-ryan** [comment]
Is this what you're looking for? 

https://www.tensorflow.org/agents/api_docs/python/tf_agents/agents/DqnAgent

**Comment by sguada** [comment]
See example for Atari here https://github.com/tensorflow/agents/blob/v0.6.0/tf_agents/agents/categorical_dqn/examples/train_eval_atari.py
