### ISSUE TITLE
What is time_step actually used for?

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/agents#456]
I see in call() for encoding network time_step is deleted because it is unused. I'm trying to find where in the code time_step is used and what it actually means. For my problem, time_step doesn't really matter so i'd prefer to not use it.

**Comment by wookayin** [comment]
> I see in call() for encoding network time_step is deleted because it is unused

Would you please provide a specific pointer to this? `time_step` seems to refer to `TimeStep` object which basically contains all information observed in one step of environment interaction. See also: [API docs](https://www.tensorflow.org/agents/api_docs/python/tf_agents/trajectories/time_step/TimeStep)

**Comment by ben-arnao** [comment]
@wookayin I think I mean step type actually. First, mind, last.

**Comment by summer-yue** [comment]
We care about the step type in some agent. For example, in PPO, in order to perform advantage calculation on the episode level, we need to know when the episode ends. Step type gives us this information. It's possible that in particular cases that this information is not necessary.

**Comment by summer-yue** [comment]
Please let us know if you have any followup questions. If not I will close this in a week.

**Comment by ben-arnao** [comment]
I think i understand now. Thanks for the explanation!
