### ISSUE TITLE
ReplayBuffer add_batch gets "The two structures do not match" error

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/agents#458]
I collect episode for ppo without dynamic episode driver due to some limitations of my application. when I add batch with ReplayBuffer's add_batch I get the following error message. 

>    self.replay_buffer.add_batch(trajectory.from_transition(self.last_ts, self.history['action'][-1], ts));
  File "/root/opt/vnpy/lib/python3.8/site-packages/tf_agents/replay_buffers/replay_buffer.py", line 83, in add_batch
    return self._add_batch(items)
  File "/root/opt/vnpy/lib/python3.8/site-packages/tf_agents/replay_buffers/tf_uniform_replay_buffer.py", line 193, in _add_batch
    nest_utils.assert_same_structure(items, self._data_spec)
  File "/root/opt/vnpy/lib/python3.8/site-packages/tf_agents/utils/nest_utils.py", line 113, in assert_same_structure
    raise exception('{}:\n  {}\nvs.\n  {}'.format(message, str1, str2))
TypeError: The two structures do not match:
  Trajectory(step_type=., observation=., action=., policy_info=(), next_step_type=., reward=., discount=.)
vs.
  Trajectory(step_type=., observation=., action=., policy_info=DictWrapper({'dist_params': DictWrapper({'logits': .})}), next_step_type=., reward=., discount=.)

I add batch following the code of dynamic episode driver. I add a constructed trajectory by

```python
self.replay_buffer.add_batch(trajectory.from_transition(self.last_ts, self.history['action'][-1], ts));
```

where self.last_ts and ts are manually constructured TimeStep objects. self.history['action'] is a PolicyStep object returned by tf_agent.policy.action() function. 

How can I give the policy_info which the error refers. thx

**Comment by yangshaoqing1996** [comment]
Maybe you can try do not use  "random_tf_policy.RandomTFPolicy(" to collect data.
