### ISSUE TITLE
what does TimeStep store

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/agents#459]
is TimeStep a tuple of (r_{t-1}, o_t) or (r_t, o_t)?

**Comment by tagomatech** [comment]
If this helps, you can see the definition of the [TimeStep](https://github.com/tensorflow/agents/blob/e74176c4ffb1695314c6dbe98d5f372e67ca82ca/tf_agents/trajectories/time_step.py#L42) class.
If you need an example of use, you can refer to the [DQN](https://www.tensorflow.org/agents/tutorials/1_dqn_tutorial) tutorial. It reads:

> The environment.step method takes an action in the environment and returns a **TimeStep tuple containing the next observation of the environment and the reward for the action**.
> 
> The time_step_spec() method returns the specification for the TimeStep tuple. Its observation attribute shows the shape of observations, the data types, and the ranges of allowed values. The reward attribute shows the same details for the reward.

**Comment by breadbread1984** [comment]
got it. thx
