### ISSUE TITLE
checkpointer can't load checkpoint

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/agents#461]
I save checkpoint with checkpointer. but when I load the checkpoint files, checkpointer complains that 

>OSError: SavedModel file does not exists at: checkpoints/policy/{saved_model.pbtxt|saved_model.pb}

it seems the checkpointer outputs file in checkpoint format and inputs saved model format. what is the right way to use it to resume training without problem?

**Comment by summer-yue** [comment]
Could you paste the code of how you saved the checkpoint files, as well as how you loaded it here? There are a few different versions of check pointers available.

**Comment by breadbread1984** [comment]
I create a checkpointer object and resume the context before training with the following code. 

```python
checkpointer = Checkpointer(
  ckpt_dir = 'checkpoints/policy',
  max_to_keep = 1,
  agent = agent,
  policy = agent.policy,
  global_step = tf.compat.v1.train.get_or_create_global_step()
);
checkpointer.initialize_or_restore();
```

**Comment by breadbread1984** [comment]
found the problem, thx

**Comment by summer-yue** [comment]
Could you update here with the problem you have found? That way it'd help other people who has the same issue :)

**Comment by breadbread1984** [comment]
I was stucked by a silly problem which is not worth mentioning. the above code can load checkpoint without problem. :-P
