### ISSUE TITLE
Can we save a replay buffer?

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/agents#462]
Is there any way to save a replay buffer to persistent storage to be loaded back up later?

**Comment by ormandi** [comment]
Thank you for your question.

Assuming that you are using Reverb replay buffer (https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/replay_buffer.py), you can perform checkpointing using the API provided by Reverb. More on this: https://github.com/deepmind/reverb#checkpointing

**Comment by oars** [comment]
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v2/train_eval.py#L215

For the uniform replay.
