### ISSUE TITLE
tf_summaries only supports tf.summary.scalar

### ISSUE THREAD

**Issue by erm96** [tensorflow/agents#465]
Hi,

I have a question regarding tf_summaries, is it intended to only support scalars?

I would like to log a custom metric that is a string but i am getting 
`UnimplementedError: Cast string to float is not supported [Op:Cast]` 
since the line 
`tf.compat.v2.summary.scalar(name=tag, data=result, step=train_step` 
in  tf_metric.tf_summaries tries to convert it  to a float.

Did I overlook another way to log my custom string metric?

Appreciate any help with this and thank you for your work.

**Comment by ormandi** [comment]
Thank you for the comment.

I think `tf.summary.text` should do the work: https://www.tensorflow.org/api_docs/python/tf/summary/text

Btw, there is summary support for more complex data (e.g. [histogram](https://www.tensorflow.org/api_docs/python/tf/summary/histogram), [images](https://www.tensorflow.org/api_docs/python/tf/summary/image), or [audio](https://www.tensorflow.org/api_docs/python/tf/summary/audio)) in TF.

**Comment by erm96** [comment]
Hey, thanks for the quick response.
Yes I am in general aware of the different summary supports from `tf.summary`.

My problem is that the class `TFStepMetric` in `tf_metric.py` in `TF Agents` only supports scalars/histograms and not text.
(https://github.com/tensorflow/agents/blob/4db8de39092d83ed9dab698ff253f5a4fce7024b/tf_agents/metrics/tf_metric.py)
