### ISSUE TITLE
Some bugs in experimental.example.ppo.train_eval_lib.py

### ISSUE THREAD

**Issue by lucifer2288** [tensorflow/agents#468]
line 38 & 39 : 
from tf_agents.google.replay_buffers import reverb_replay_buffer
from tf_agents.google.replay_buffers import reverb_utils

from tf_agents.google?

line 208 &212 : 
_ReverbAddTrajectoryObserver ?

allow_multi_episode_sequences ?

**Comment by summer-yue** [comment]
Just saw this. I thought I updated this but maybe it didn't go through. I'll look today.

**Comment by summer-yue** [comment]
Just submitted a fix! Thanks for reporting this issue! https://github.com/tensorflow/agents/commit/545507d1e15a7b828b44784641fb1469dfcdd3ad
