### ISSUE TITLE
Is there anyway to pre-compute states?

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/agents#470]
Is there any way to pre-compute states for your environment?

For my particular problem, it's pretty easy to pre-compute states. Instead of having to step through the environment and predict with a batch_size of 1, if I could utilize my GPU and pre-compute with large batches this would greatly increase the efficiency. Then the states could be easily fetched by a few keys/indexes.

**Comment by kuanghuei** [comment]
Agents can be agnostic of how the states being generated. You can specify observation spec to match the pre-compute states, and feed the pre-compute states to agents. You can also just store keys in rb, and replace the observation with the precomputed ones whenever you fetch trajectory from rb. Feel free to reopen if this doesn't answer your question.

**Comment by ben-arnao** [comment]
Is there an easy way to then use your policy to make predictions in batches
so you can cache them and access within your environment?

**Comment by kuanghuei** [comment]
tf-agents policy does support batches. An additional outer dimension not specified in spec is treated as batch dimension.
