### ISSUE TITLE
Create facade classes to make TF Agents more simpler to use

### ISSUE THREAD

**Issue by iirekm** [tensorflow/agents#472]
Currently in order to use TF Agents I basically have to copy & paste & modify examples (eg those from https://github.com/tensorflow/agents/tree/master/docs/tutorials ). Unfortunately those examples are too long to adapt them to other use cases:
- **very beginner-unfriendly** - I tried to adapt TF Agents to my use case and I gave up because of the complexity, and unfortunately I won't use TF Agents for my project for now. :-(
- very hard to understand and maintain code
- very bug-prone
- hard to preserve backwards compatibility when so many implementation details are accessed directly by end users

'Facade' classes or methods are necessary to solve this complexity.

For example Stable Baselines does it as:
```python
model = DQN('MlpPolicy', env, learning_rate=1e-3, prioritized_replay=True, verbose=1)
model.learn(total_timesteps=int(2e5))
```
( https://stable-baselines.readthedocs.io/en/master/guide/examples.html )

Similarly OpenAI do in their learning resources:
```
spinup.ddpg_tf1(env_fn, actor_critic=<function mlp_actor_critic>, ac_kwargs={}, seed=0, steps_per_epoch=4000, epochs=100, replay_size=1000000, gamma=0.99, polyak=0.995, pi_lr=0.001, q_lr=0.001, batch_size=100, start_steps=10000, update_after=1000, update_every=50, act_noise=0.1, num_test_episodes=10, max_ep_len=1000, logger_kwargs={}, save_freq=1)
```
( https://spinningup.openai.com/en/latest/algorithms/ddpg.html#documentation-tensorflow-version )

**Comment by kuanghuei** [comment]
Thanks for your suggestion. 

Please check the new [actor/learner API](https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/train) ([SAC tutorial](https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial)), which might be closer to what you're looking for. Should be easier to start with.

My belief is that one-line model.fit() is a "magic" that looks **easy** at the first glance but actually makes things **harder**. It only works perfectly for the simplest use-cases. It seems unlikely that TF-Agents will do things that way.

**Comment by iirekm** [comment]
if you make everything configurable like `xxxx = Xxxx(param1=..., param2=...); xxxx.fit()`, then both beginners and more advanced users who need to override something are happy, just like done in sklearn / Keras / Stable Baselines.
This gives faster project start, easier backwards compatibility (less details revealed), and when something doesn't work, I can blame only my `paramN=...`, I can temporarily comment them ouyt, don't have to carefully review all code line by line.
