### ISSUE TITLE
Why do we have to implement the observation_spec and action_spec in PyEnvironment but in TFEnvironment we can simply pass them to the superclass constructor?

### ISSUE THREAD

**Issue by guachoperez** [tensorflow/agents#474]
When subclassing PyEnvironment, we have to implement the observation_spec and action_spec methods. When subclassing TFEnvironment, we pass time_step_spec and action_spec to the superclass constructor. For consistency, could we not pass these specifications to the PyEnvironment superclass when subclassing as well?

**Comment by tfboyd** [comment]
Closing due to age and lack of recent activity. If the issue still exists, please open a new issue and reference this one.
