### ISSUE TITLE
[Question] How to use preprocessing_layers when concatenating blocks 

### ISSUE THREAD

**Issue by signalprime** [tensorflow/agents#481]
Hi everyone, I am trying to build the **EncodingNetwork** using the **preprocessing_layers** argument.  It works great, but how can we use a more complicated sequence like a convnet that concatenates blocks without using Keras' Functional API.  I've tried scripts to flatten a nested model, subclassing layers to represent blocks, etc. A layer is only built if it has an input, but not specifying inputs seems to cause errors when concatenating layer outputs... for example of B and C when their inputs are both layer A. 

How could we accomplish this within the Agents framework?  [Reference to requirement for layers not built](https://github.com/tensorflow/agents/blob/v0.6.0/tf_agents/networks/encoding_network.py#L137)

For a code example, I've referenced an implementation of the Squeeze network [here](https://github.com/daviddexter/keras_squeezenet2/blob/master/keras_squeezenet_tf2/squeezenet.py) which has a block called a "fire module".

Everything is normal with the first few layers:

```
    snet = tf.keras.Sequential()
    snet.add( Convolution2D(64, (3, 3), strides=(2, 2), padding='valid', name='conv1') )
    snet.add( Activation('relu', name='relu_conv1') )
    snet.add( MaxPooling2D(pool_size=(3, 3), strides=(2, 2), name='pool1') )
```

Now we need to add the fire module which has the concatenate.  
```
    args = {'squeeze':16,'expand':64}
    s_id = 'fire2/'
    
    first.add( tf.keras.layers.Conv2D(args['squeeze'], (1, 1), padding='valid', name=s_id + sq1x1, activation='relu') )
    left = copy.copy(first)
    left.add( tf.keras.layers.Conv2D(args['expand'], (1, 1), padding='valid', name=s_id + exp1x1, activation='relu') )
    right = copy.copy(first)
    right.add( tf.keras.layers.Conv2D(args['expand'], (3, 3), padding='same', name=s_id + exp3x3, activation='relu') )

    # This next line fails due to layers not containing a shape
    layer_concat = concatenate([left.layers[-1],right.layers[-1]],axis=channel_axis, name=s_id + 'concat')
    first.add( layer_concat )
```

Finally for thoroughness, here's [the link](https://stackoverflow.com/a/58232963/12310450) and code for flattening a nested model
```
def flatten_model(model_nested):
    def get_layers(layers):
        layers_flat = []
        for layer in layers:
            try:
                layers_flat.extend(get_layers(layer.layers))
            except AttributeError:
                layers_flat.append(layer)
        return layers_flat

    model_flat = tf.keras.models.Sequential(
        get_layers(model_nested.layers)
    )
    return model_flat

```

Thanks so much in advance for any ideas

**Comment by kuanghuei** [comment]
Sorry I'm a little confused. Aren't you supposed to concat layer outputs instead of concat layers? Can you provide the error message?

**Comment by signalprime** [comment]
Thanks friend, you're correct.  I must have copied the wrong cell, here is a copy that runs until the next to last line defining the concatenate layer, where it raises the AttributeError, that Layer "fire2/expand3x3" has no inbound nodes... refereing to the layer output of the Right branch .  Wondering how to accomplish this design while abiding by the Sequential API requirements of the EncodingNetwork.  Thanks again
 
```
import copy
from tensorflow.python.keras.layers import VersionAwareLayers
layers = VersionAwareLayers()

first = tf.keras.models.Sequential()
first.add(layers.Convolution2D(64, (3, 3), strides=(2, 2), padding='valid', name='conv1'))
first.add(layers.Activation('relu', name='relu_conv1') )
first.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(2, 2), name='pool1'))

# Fire Module
first.add( layers.Conv2D(16, (1, 1), padding='valid', name='fire2/squeeze1x1', activation='relu') )

# Left Branch    
left = copy.copy(first)
left.add( layers.Conv2D(64, (1, 1), padding='valid', name='fire2/expand1x1', activation='relu') )

# Right Branch
right = copy.copy(first)
right.add( layers.Conv2D(64, (3, 3), padding='same', name='fire2/expand3x3', activation='relu') )

# Merge and append to the Sequental Model
model_concat = layers.concatenate([left.layers[-1].output, right.layers[-1].output], axis=3, name='fire2/concat')
first.add(model_concat)
```

**Comment by kuanghuei** [comment]
I think there might be a way if you want to use keras Sequential API. It seems easier if you don't use Sequential. Just call tf.concat in forward pass. I think this is a tf.keras question and should probably be asked on stackoverflow or the tf repo instead of here. Closing it for now. Please feel free to reopen if I misunderstood. Thanks.
