### ISSUE TITLE
Additional GPUs appear to degrade performance

### ISSUE THREAD

**Issue by signalprime** [tensorflow/agents#483]
Hi all, [Tutorial #7 - SAC minitaur](https://github.com/tensorflow/agents/blob/master/docs/tutorials/7_SAC_minitaur_tutorial.ipynb) demonstrates the distributed training strategy API for multiple GPUs and TPUs.  

I ran speed tests using 1 to 4 GPUs and found that was performance degraded with each added GPU.  I wonder why?  Please don't laugh at the speeds ;) they're older cards. 

tensorflow==2.3.0 , tf_agents==0.7.0

With 1 GPU,  iteration time varied between 63 and 75 secs.
With 2 GPUs, iteration time varied between 72 and 94 secs.
With 3 GPUs, iteration time varied between 93 and 104 secs.
With 4 GPUs, iteration time varied between  110 and 160 secs.

Here's the basic code for using just 1 GPU, added at the top of the file, and the iteration loop with a timer:

```
import os, time
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="1"
```

And the training cell
```
start_time = time.time()
for _ in range(num_iterations):
  # Training.
  collect_actor.run()
  loss_info = agent_learner.run(iterations=1)

  # Evaluating.
  step = agent_learner.train_step_numpy

  if eval_interval and step % eval_interval == 0:
    metrics = get_eval_metrics()
    log_eval_metrics(step, metrics)
    returns.append(metrics["AverageReturn"])

  if log_interval and step % log_interval == 0:
    print('step = {0}: loss = {1}, seconds: {2}'.format(step, loss_info.loss.numpy(), time.time() - start_time))
    start_time = time.time()
```

**Comment by kuanghuei** [comment]
Sometimes when you have small networks like this case, GPU could be slower than CPU, and multi-GPU can be slower than single GPU because of extra overhead from copying data back and forth in memory through data bus. The SAC-minitaur tutorial is a demo. Multi-GPU isn't necessarily faster for this task.
