### ISSUE TITLE
Change initial state observation values

### ISSUE THREAD

**Issue by alekrul** [tensorflow/agents#484]
I'm learning RL with tensor flow and `tf_agents` and right now i'm working with the cart-pole env from `suite_gym` in a `tf_py_environment`.

I have this initial time step that i got from `time_step = eval_env.reset():`

```
TimeStep(step_type=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, reward=<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, discount=<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, observation=<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.01901868, -0.01773789,  0.03148418, -0.01060838]],
      dtype=float32)>)

```
And i would like to change the initial values of the numpy array of the observation tf.Tensor. Is there anyway to do this?

I was looking in the py_environment class and there is a method not implemented yet called `set_state()`, i think i can do this in the future.

**Comment by ebrevdo** [comment]
TimeStep is a NamedTuple, you should be able to do surgery via `time_step = time_step._replace(observation=tf.constant(...))`
