### ISSUE TITLE
Atari Examples in v2?

### ISSUE THREAD

**Issue by jeffheaton** [tensorflow/agents#487]
Are there any examples of using TF-Agents with Atari?  Just an end-to-end "Hello World" Breakout game would be very helpful.  There used to be:

```
tf_agents/agents/dqn/examples/v1/train_eval_atari.py
```

But it was dropped back in June 2020 when all the v1 examples were removed.  I did have a V2 [example ](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_12_04_atari.ipynb)of my own working great, for a deep learning class I teach, but recent changes in TF-Agents included some breaking changes.  I based my v2 example on the TF-Agents example above.

The primary issue is that the Atari observation space for an image is utf8, but the QNet needs float32 divided by 255.  There seem to be quite a few new checks added that throw errors now like:

```
ValueError: <tf_agents.networks.encoding_network.EncodingNetwork object at 0x7f902e3a8630>: Inconsistent dtypes or shapes between inputs and input_tensor_spec.
dtypes:
<dtype: 'float32'>
vs.
<dtype: 'uint8'>.
shapes:
(1, 84, 84, 4)
vs.
(84, 84, 4).
In call to configurable 'DqnAgent' (<class 'tf_agents.agents.dqn.dqn_agent.DqnAgent'>)
```

This used to work.  The dimension issue raised above does not seem to be an issue, because of batching.  If I just change the type of the observation, with something like:

```
observation_spec = BoundedTensorSpec(
    shape = observation_spec.shape,   
    dtype = np.float32,
    name =  observation_spec.name,
    minimum = observation_spec.minimum,
    maximum = observation_spec.maximum)
```
It gets me past the initialization of the  DqnAgent just fine.  But then I run into other problems where the observation spec seems to be cached by many of the various wrappers that are in play in TF-Agents.  Still working on that.

But I also wonder if I am missing something basic.  Are there any plans to provide an Atari example, similar to what you had for v1?  It would be really helpful to see how this sort of example is "intended" to be implemented in TF-Agents.  

The root problem seems to be that the low level environment observation is uint8, but having a QNet expecting floating point is wrecking havoc with the various checks. I am following the approach that the original TF-Agents v1 example used, but I am not sure that makes sense anymore with all the recent TF-Agents refactoring.

**Comment by summer-yue** [comment]
Same root as https://github.com/tensorflow/agents/issues/486

`assert_matching_dtypes_and_inner_shapes` that was added back in June seems to be breaking DQN Atari. Eugene, could you take a look?

**Comment by jeffheaton** [comment]
@summer-yue Agreed, same issue.  **However, it would also be nice if your resurrected your Atari example.**

**Comment by summer-yue** [comment]
The old Atari example I believe is in TF1 which we have moved away from. I will work on a DQN Atari example based on the new infra with the simpler actor/learner framework. Will need to ensure that it replicates the papers so might need to take some time to be available in OSS. I will aim for by the end of the year.

**Comment by summer-yue** [comment]
The new Atari example is open sourced now (https://github.com/tensorflow/agents/commit/635af30a6365ec963823d4623f14df25fcefaadd) reproducing "human-level control through deep reinforcement learning" (Mnih 15) thank you for your patience!

**Comment by cosmir17** [comment]
@summer-yue Thank you for the examples. I(and we are) am really thankful.
I have a quick question.

I have the following specs for my custom environment. I feed an image numpy array for each episode.
```
self._action_spec = array_spec.BoundedArraySpec(shape=(), dtype=np.int32, minimum=0, maximum=5, name='action')
    self._observation_spec = array_spec.BoundedArraySpec(shape=(70, 70, 1), dtype=np.float32, name='observation')
```

The following is how I configured my network and agent.
```
fc_layer_params = (560, 60)
conv_layer_params = [(70, (8, 8), 4), (140, (4, 4), 2), (280, (3, 3), 1)]

q_net = q_network.QNetwork(
    nimble_quest_env.observation_spec(),
    nimble_quest_env.action_spec(),
    conv_layer_params=conv_layer_params,
    fc_layer_params=fc_layer_params)

optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)
# global_step = tf.compat.v1.train.get_or_create_global_step()
global_step = tf.compat.v1.train.get_global_step()

#########################################################################
agent = dqn_agent.DdqnAgent(
    nimble_quest_env.time_step_spec(),
    nimble_quest_env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=common.element_wise_squared_loss,
    train_step_counter=global_step
)

agent.initialize()
```

I saw your examples where you set the q-network manually. 
Can I ask if my code is a valid setting for q-network and agent, please?

**Comment by summer-yue** [comment]
@cosmir17 q_network.QNetwork is still a valid way to set QNetwork. In the example I used TF Keras for the networks to demonstrate the new feature we launched recently (We now support Keras networks in TF-Agents not just the TF-Agents classes - many folks are more familiar with Keras networks so this simplifies the interface for them).

**Comment by cosmir17** [comment]
I see. Thank you, @summer-yue
