### ISSUE TITLE
@abc.abstractmethod

### ISSUE THREAD

**Issue by Bhaney44** [tensorflow/agents#49]
I have never seen this syntax before. I was reading the TensorFlow Environments code and came across  `@abc.abstractmethod` in the following context:

```
  @abc.abstractmethod
  def _reset(self):
    """Returns the current `TimeStep` after resetting the Environment."""

  @abc.abstractmethod
  def _current_time_step(self):
    """Returns the current `TimeStep`."""
```

What is the purpose and meaning of this syntax? Thanks!

**Comment by sguada** [comment]
It just mark a method as abstract, what means any subclass has to implement it.
https://docs.python.org/3/library/abc.html#abc.abstractmethod

**Comment by Bhaney44** [comment]
Thanks!
