### ISSUE TITLE
Dead links in Bandits intro

### ISSUE THREAD

**Issue by Denbergvanthijs** [tensorflow/agents#492]
The Google colab link at the bottom of [this notebook](https://github.com/tensorflow/agents/blob/master/docs/tutorials/intro_bandit.ipynb) is dead.

The same link can be found at the top of [this README](https://github.com/tensorflow/agents/blob/master/tf_agents/bandits/README.md).

Kind regards,
Thijs

**Comment by bartokg** [comment]
Thanks a lot for raising our attention! The fix will be in asap.
