### ISSUE TITLE
Differences between gamma in agent and discount in transition

### ISSUE THREAD

**Issue by tphanson** [tensorflow/agents#499]
As the title, could you provide a clear explanation about differences between `gamma` in `tf_agents.agents` and `discount` in transitions in `tf_agents.trajectories`? I'm really confused about it.

**Comment by sguada** [comment]
The main difference is that the one in the Agent refers to the discount used by the algorithm to discount future rewards. The one inside trajectories is used to stop using future rewards when the episode ends or is truncated.

**Comment by ghost** [comment]
@sguada that makes sense. Thank you.

**Comment by maxima120** [comment]
> The one inside trajectories is used to stop using future rewards when the episode ends or is truncated.

how do you use it in your code? all the examples I could find simply pass [1.0]
