### ISSUE TITLE
Time Step Spec Mismatch

### ISSUE THREAD

**Issue by lamhoson** [tensorflow/agents#504]
Any know what's wrong or how to fix this?

Given `time_step`: TimeStep(step_type=array(0), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([[0., 0.]])) does not match expected `time_step_spec`: TimeStep(step_type=ArraySpec(shape=(), dtype=dtype('int32'), name='step_type'), reward=ArraySpec(shape=(), dtype=dtype('float32'), name='reward'), discount=BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0), observation=BoundedArraySpec(shape=(2,), dtype=dtype('float64'), name='[profit, weekday]', minimum=[0. 0.], maximum=[1.79769313e+308 5.00000000e+000]))

From:
    def __init__(self): 
        self._action_spec = array_spec.BoundedArraySpec( 
            shape=(), dtype=np.float64, 
            minimum=-30, maximum=+30, name='trade')

        self._observation_spec = array_spec.BoundedArraySpec(shape=(2,), dtype=np.float64,
            minimum=[0,0], maximum=[sys.float_info.max, weekday['SAT']],
            name='[profit, weekday]')

**Comment by lamhoson** [comment]
![image](https://user-images.githubusercontent.com/34258914/97525299-694e3080-19e1-11eb-86f3-cb7be8566a77.png)

**Comment by Error-Message123** [comment]
Was this issue solved and if so how?

**Comment by lamhoson** [comment]
Yes. Thanks.

**Comment by Shinwazu** [comment]
How did you solve the issue? I have the same error!!!
