### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by PeterZhizhin** [tensorflow/agents#51]
Some RL libraries add performance benchmarks on Atari or MoJoCo. Some also have comparisons between typical algorithms with different implementations.
See this for an example: https://github.com/ray-project/rl-experiments

The performance benchmarks will make it more compelling for someone outside Google to use the library. If you had them, someone wouldn't need to do the benchmarks themselves. They wouldn't need to invest time learning the library before getting the performance numbers. It will make even more sense after you have distributed training (as discussed in #14). It will be hard for someone to set up distributed training infra just to make benchmarks.

Moreover, I've personally tried RLlib because of their comparison charts :-)

Also, a TF-Agents performance benchmark would make it easier for you and everyone else to profile the code and find bottlenecks.

I would have made the comparisons myself, if I had had a GPU at home. Testing on cloud would cost me money to make the comparisons. And I don't want to spend anything on this.

**Comment by kbanoop** [comment]
Definitely agree, and we are actually working on this. But we dont have a planned release date yet. 

We are first trying to develop some general training/eval infrastructure common across agents, and once we do that we can run these studies in a more unified manner and we can publish results that are easy to reproduce.

**Comment by karanchahal** [comment]
Good plan ! @kbanoop I wish you guys all the best. This is such exciting stuff !

**Comment by tfboyd** [comment]
I am closing this and we have started do do a much better job in this area. Not where it needs to be.  Here is our new [SAC "readme"](https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/examples/sac) and we are about to launch the new PPO "readme" with similar data.  More envs, e.g. not mujoco is also in the works.  I expect DQN will be after PPO and some distributed collect info.  

I am also closing some issues that are over 1 year old and not Feature Requests.
