### ISSUE TITLE
Custom envirnoment - sample_spec ?

### ISSUE THREAD

**Issue by lamhoson** [tensorflow/agents#510]
Do i need to specify sample_spec in addition to action_spec for a new custom env created to use tf-agent's SAC agent ?

**Comment by ayansengupta17** [comment]
As far as I remember I only defined observation_spec and action spec for my custom environment when I was using SAC agent.

**Comment by lamhoson** [comment]
Thank you for your input!  However, i always get a mismatch error below for both SAC and Reinforce agents.

Any ideas of the reason to trigger the mismatch?


ValueError: Inputs to NormalProjectionNetwork must match the sample_spec.dtype.
  In call to configurable 'ReinforceAgent' (<function ReinforceAgent.__init__ at 0x000001F4D04744C8>)

**Comment by lamhoson** [comment]
Fyi, the mismatch case in SAC:

![image](https://user-images.githubusercontent.com/34258914/98530589-16fef080-22ba-11eb-9e88-70a9dde473bc.png)

**Comment by tfboyd** [comment]
@oars  is responding on PR 508.  Closing this as a duplicate.
