### ISSUE TITLE
Access Environment attributes

### ISSUE THREAD

**Issue by benalcazardiego** [tensorflow/agents#511]
Hello.

I defined my own environment in python and then converted it to tensorflow using tf_py_environment.TFPyEnvironment. However, I need to access attributes and methods different from the standard functions like "myenv.attribute1" during the main code execution. Is this possible? I could not find the attributes listed.

Thank you

**Comment by kbanoop** [comment]
Hi,

There are a couple of options: 
- Access it through this [function](https://github.com/tensorflow/agents/blob/448ac9c64033055c8b52e6206eac4523ee419809/tf_agents/environments/tf_py_environment.py#L180)
- Access it through the wrapped py environment [property](https://github.com/tensorflow/agents/blob/448ac9c64033055c8b52e6206eac4523ee419809/tf_agents/environments/tf_py_environment.py#L208)

Btw with TF2/eager mode, there is not much need for converting PyEnvs to TF. e.g. see this [example](https://github.com/tensorflow/agents/blob/master/tf_agents/experimental/examples/sac/haarnoja18/sac_train_eval.py).
