### ISSUE TITLE
How can I change the experience storage policy

### ISSUE THREAD

**Issue by HuPeng-Valer** [tensorflow/agents#513]
I want to add trajectory to the replay buffer based on the value of the action and part of the observation,but I used tf_py_environment and TFUniformReplayBuffer , the eager tensor can't be compared with constants and I dont know how to modify the replaybuffer.add_batch,how can I do that?

**Comment by kbanoop** [comment]
Can you clarify what you meant by eager tensors cant be compared with constants?

Also please checkout the [Reverb Replay Buffer](https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/reverb_replay_buffer.py), which will be our main replay buffer moving forward.
