### ISSUE TITLE
Normalizing the states required ?

### ISSUE THREAD

**Issue by biplavc** [tensorflow/agents#516]
The states in my environment are a combination of two observations (i.e. concatenation of two lists), one of which is represented by an integer (shape =  [20\*1]) while the other lists is the probability (shape = [22\*1]) which makes the overall state a list of shape [22\*1]. In such a case, do I need to normalize the first 20 elements or the state as a whole can be used as the way it is?

**Comment by kbanoop** [comment]
Either is possible with TF-Agents. States can be arbitrary nested objects such as a list, dict or nests of these. But you may have to define your own custom network that can process these.
