### ISSUE TITLE
Toggling Agents/Policies

### ISSUE THREAD

**Issue by touramaline** [tensorflow/agents#517]
I've been trying to figure out how to interface policy switching with the built-in bandit algorithms for a contextual bandit algorithm that has a cycling piecewise environment that is consistent for each of the pieces and switches between pieces at predictable times. 

Was the library designed in mind with the prebuilt agents having the ability to toggle and train policies? Or is it mean to be that each agent should only settle on one policy?

**Comment by bartokg** [comment]
In general, agent classes can only work with their designated policy classes. That is, a LinUCB agent can only train and serve a LinUCB policy.

However, nothing stops you from instantiating 2 (or more) agents for one problem. You can decide based on your piecewise environment schedule, which agent you want to get involved. you could even decide whether you want all agents to be trained on each other's output: you can use agent1.policy.action() but then on the resulting trajectory you can run both agent1.train() and agent2.train().
