### ISSUE TITLE
How can I get "sample_info" through tf_agents.experimental.train.learner?

### ISSUE THREAD

**Issue by Dongwon-Son** [tensorflow/agents#522]
Hello,
I am trying to implement PER(Prioritized Experience Replay) with Reverb and experimental.train.actor & learner, as guided in SAC.
As in title, how can I get "sample_info" (contains priorities and probabilities which are necessary for PER) through learner.run?

FYI,
I found that 'sample_info' is generated from iterator, but not entered to train function of agents instance in function 'single_train_step'.

**Comment by sguada** [comment]
You will need to write your own Learner, since in addition to access the sample_info you also need to update the priorities afterwards.
