### ISSUE TITLE
Is the LSTM’s hidden state  zeroed at the start of each update?

### ISSUE THREAD

**Issue by WangMengqi32C** [tensorflow/agents#525]
Dear all,

I am new to tf-agent, I want to know whether the LSTM’s hidden state is zeroed at the start of each update when I use dqn agent with LSTM. Can anybody tell me how does the tf-agent manage that?

Thank you in advance!
Mengqi

**Comment by kbanoop** [comment]
Hi Mengqi,

Please see this for how the state resetting is handled in TF-Agents: https://github.com/tensorflow/agents/blob/f1cae020ba06548b97eb06c146fe540c29497b59/tf_agents/keras_layers/dynamic_unroll_layer.py#L245

Closing for now, feel free to reopen if you have more questions.
