### ISSUE TITLE
Question: why is a replay buffer required for on-policy RL algos like PPO-clip for tf-agents?

### ISSUE THREAD

**Issue by SurferZergy** [tensorflow/agents#528]
I think I never seen a replay buffer used for on-policy algos like the PPO-clipping (I understand TRPO might used it), is it really used? or can we eliminate the need for it?

**Comment by kuanghuei** [comment]
RB is not required. Just a way to cache on-policy experience. You don't have to use it with TF-Agents PPO.

**Comment by SurferZergy** [comment]
https://www.tensorflow.org/agents/api_docs/python/tf_agents/agents/ppo/ppo_clip_agent/PPOClipAgent
it looks like "experience" is required? or is the idea just to pass an empty experience?
