### ISSUE TITLE
Nested network with PPO Usage (NestMap)

### ISSUE THREAD

**Issue by Axel-CH** [tensorflow/agents#531]
Hello,
i'm using the PPO algorythm with preprocessing layers and combiner.

As I have various issue with the preprocessing layers due to their complexity,  [details here](https://github.com/tensorflow/agents/issues/443)

I want to use the new way to declare complex networks that you added recently called "NestMap".

As this feature is recent, it seem that the doc and exemples are not yet present.

**I saw this [exemple](https://github.com/tensorflow/agents/blob/367abe3596d3efde92857d43f8d9642895383e1b/tf_agents/networks/nest_map_test.py#L73) creating a custom sequential network using NestMap but I did not figured out yet how to implement it with PPO.**

Bellow the part of code that I would like to replace:

> 

            actor_net = actor_distribution_rnn_network.ActorDistributionRnnNetwork(
                tf_env.observation_spec(),
                tf_env.action_spec(),
                preprocessing_layers=preprocessing_layers,
                preprocessing_combiner=preprocessing_combiner,
                conv_layer_params=None, #space['conv_layer_params'],    
                input_fc_layer_params=actor_fc_layers,
                output_fc_layer_params=None,
                lstm_size=(space['lstm_size'],), # Default 40
                activation_fn=activation_fn
                )
            value_net = value_rnn_network.ValueRnnNetwork(
                tf_env.observation_spec(),
                preprocessing_layers=preprocessing_layers,
                preprocessing_combiner=preprocessing_combiner,
                conv_layer_params=None,
                input_fc_layer_params=value_fc_layers,
                output_fc_layer_params=None,
                lstm_size=(space['lstm_size'],),
                activation_fn=activation_fn)`

Bellow you will see the structure of my preprocessing layers:

```
            preprocessing_layers = {
                'a': tf.keras.models.Sequential(list_of_layers['a']),
                'b': tf.keras.models.Sequential(list_of_layers['b']),
                'c': tf.keras.models.Sequential(list_of_layers['c']),
                'd': tf.keras.models.Sequential(list_of_layers['d']),
                'e': tf.keras.models.Sequential(list_of_layers['e']),
                'f': tf.keras.models.Sequential(list_of_layers['f']),
                'g': tf.keras.models.Sequential(list_of_layers['g']),
                'h': tf.keras.models.Sequential(list_of_layers['h']),
                'i': tf.keras.models.Sequential(list_of_layers['i']),
                'j': tf.keras.models.Sequential(list_of_layers['j']),
            }
```

Observation space:
`Dict(a:Box(16, 5), b:Box(16, 20), c:Box(16, 6), d:Box(16, 6), e:Box(16, 22), f:Box(16, 22), g:Box(16, 22), h:Box(16, 22), i:Box(16, 22), j:Box(16, 22))`

Observation shape:
`{'a': (16, 5), 'b': (16, 20), 'c': (16, 6), 'd': (16, 6), 'e': (16, 22), 'f': (16, 22), 'g': (16, 22), 'h': (16, 22), 'i': (16, 22), 'j': (16, 22)}`

Thank you for your Help

**Comment by kbanoop** [comment]
Sorry for the late reply. Please take a look at this [DDPG example](https://github.com/tensorflow/agents/blob/117b83882c71d74881a80163ec1ff3c2e2eb4fe3/tf_agents/agents/ddpg/examples/v2/train_eval.py#L319) showing how to create a custom network using NestMap.

Closing for now, please reopen if you have more questions.
