### ISSUE TITLE
Does tf-agents support DQN agents with multiple inputs?

### ISSUE THREAD

**Issue by FMalerba** [tensorflow/agents#533]
Simple example:
```

observation_spec = {'image_obs': array_spec.ArraySpec(shape=(100, 100, 3), dtype=np.float32),    # rgb image
                    'other_obs': array_spec.ArraySpec(shape=(20,), dtype=np.float32)}

```
network to be passed as preprocessing network:
```
image_input = Input(shape=(100, 100, 3))
other_input = Input(shape=(20,))

x = Conv2D(256, (3, 3), activation='relu')(image_input)
x = Dropout(0.2)(x)
x = Conv2D(256, (3, 3), activation='relu')(x)
x = Dropout(0.2)(x)
x = Flatten()(x)
x = Concatenate()([x, other_input])
```

and `x` should be the input to the Qnetwork's postprocessing layers.

My understanding by looking at `encoding_network.py` is that this is not currently possible because all the layers in `self._flat_preprocessing_layers` get fed the same input. Am I missing something?

This seems like an important feature to have in general since it is common to have an image input to pass through some convolutional layers and then other inputs that shouldn't.

**Comment by kbanoop** [comment]
Sorry for the late reply. This can be done in multiple ways:

1. Use preprocessing layers as you mentioned. See e.g. this [test](https://github.com/tensorflow/agents/blob/117b83882c71d74881a80163ec1ff3c2e2eb4fe3/tf_agents/networks/encoding_network_test.py#L328).  

2. Write your own custom network. e.g. the [DDPG example](https://github.com/tensorflow/agents/blob/117b83882c71d74881a80163ec1ff3c2e2eb4fe3/tf_agents/agents/ddpg/examples/v2/train_eval.py#L319) shows how to take in observation and action as separate inputs and combine them together later. 

Closing for now, please feel free to reopen if you have more questions.

**Comment by Abner77** [comment]
But how you define the observation spec with multiple inputs? This is possible en keras-rl where the api assigns each observation spec (multiple bound array spec) to each input defined in the q-network. 
I don't have a preprocessing network trained, cause I need that process to be done by the own q-network..... How can I do this? Thanks in advance.

**Comment by FMalerba** [comment]
You define the observation spec similarly to how I did. In my case I used a dict to clearly differentiate between the inputs by assigning names to them (the dict keys), but in principle you could use also a list or tuple of array specs if you prefer.

When it comes to building your QNetwork you just create a variable preprocessing_layers that matches the structure of your obs_spec (in my case it would be a dict with the same keys) and contains the preprocessing parts of your model that match each input in the obs_spec.

I do not believe that you can feed multiple inputs to your QNetwork without using preprocessing_layers, but also this is not a limitation really. I think you are misunderstanding the fact that preprocessing layers must be pre-trained; they do not. If you have multiple inputs that all need to just be concatenated then you could do that in your environment directly and not have a nested observation spec (dict/list/tuple/ecc.).

If instead you have something like
```
            model 
           /      \
          /        \
         /          \
sub_model_1        sub_model_2
```
Then you should define something like:

```
obs_spec = {"sub_model_1_obs": ...,
            "sub_model_2_obs": ...}
```
and
```
preprocessing_layers = {"sub_model_1_obs": Sequential(layers=[.....], name="sub_model_1"),
                        "sub_model_2_obs": Sequential(layers=[.....], name="sub_model_2")}
preprocessing_combiner = Concatenate(axis=-1)

q_net = q_network.QNetwork(obs_spec,
                           action_spec,
                           fc_layer_params=....,
                           ....
                           preprocessing_layers=preprocessing_layers,
                           preprocessing_combiner=preprocessing_combiner)
```

Note that the Sequential models defined in `preprocessing_layers` should not be already built; therefore, do not give them the initial `Input` layer, but start straight from whatever layer comes after. Also note that these Sequential models will in principle be trained as would be expected, if you want to avoid this (maybe you have pre-trained models), then you can just pass the relevant `trainable=False` flag to the layers contained in them.

If one of the sub_models is empty (like in my example in the issue where `other_obs` should not be processed prior to concatenation), then you can just assign an empty `Sequential(name="other_input_model")` to its obs.

**Comment by Abner77** [comment]
Could you put a complete sample. I was following the google tutorial and they don't use QNetwork, they use a standard Sequential model, so I don´t know exactly how that works. 
Thank you very much for the answer

**Comment by febinmathew** [comment]
@FMalerba Can you please show/Explain how you created the Agent to train from this QNetwork that you generate? For me, the  "DqnAgent" was converting "observation" dict object to "_DictWrapper" automatically and I could not train. Thanks in advance
