### ISSUE TITLE
is_bandit_env check in dynamic_step_driver fails for custom BanditPyEnvironments wrapped with TFPyEnvironment

### ISSUE THREAD

**Issue by MoritzErtelt** [tensorflow/agents#535]
Hey everyone,

I recently tried to use the dynamic_step_driver with a custom BanditPyEnvironment, 
which lead the driver (with `steps_per_loop=1` ) to never terminate. 
This is caused by the driver only counting steps that lead to a transition and not to an environment reset,
with the later being always the case for Bandit environments.
Normally this behavior is avoided with the `is_bandit_env` check in the `dynamic_step_driver`:
https://github.com/tensorflow/agents/blob/755b43c78bb50e36b1331acc9492be599997a47f/tf_agents/drivers/dynamic_step_driver.py#L35-L42

When a non-batched python environment gets wrapped with `TFPyEnvironment`, however, it gets transformed into an batched environment here:
https://github.com/tensorflow/agents/blob/755b43c78bb50e36b1331acc9492be599997a47f/tf_agents/environments/tf_py_environment.py#L146-L153

This then results in `env.pyenv` to return an `batched_py_environment.BatchedPyEnvironment` instead of an `bandit_py_environment.BanditPyEnvironment` and therefore is not catched by `is_bandit_env`.

One possible solution that works for me would be to slightly modify `is_bandit_env`:
```
def is_bandit_env(env): 
   actual_env = env 
   if isinstance(env, tf_py_environment.TFPyEnvironment): 
      if isinstance(env.pyenv, batched_py_environment.BatchedPyEnvironment):
        actual_env = env.pyenv.envs[0]
      else:
        actual_env = env.pyenv 
   is_bandit = ( 
       isinstance(actual_env, bandit_py_environment.BanditPyEnvironment) or 
       isinstance(actual_env, bandit_tf_environment.BanditTFEnvironment)) 
   return is_bandit 
```

Not sure if this is the most elegant solution though, but I could open a PR if you like me too.

Edit: This does not work for `ParallelPyEnvironment` though.

Best, 
Moritz

**Comment by tfboyd** [comment]
Assigned to bandits team to take a look including at the possible patch/solution.

**Comment by bartokg** [comment]
Thanks for the catch, this is indeed a bug. The main reason for this bug existing is that we always use batched environments for bandits, even when the batch size is 1. To avoid hitting this bug we might decide to enforce all bandit environments to be batched.

Can you please try if you set the `is_batched` function in your environment to return `True`, do you still have the problem? You also have to update all shapes to accommodate for the batch dimension.

**Comment by MoritzErtelt** [comment]
Hey, thanks for the quick response.
Yes, converting to a batched environment solves the problem for a simple example environment.
However, for my real environment having it batched in combination with using `ParallelPyEnvironment` requires fixing everything downstream in sometimes non-obvious ways, so I am not sure if enforcing batched environments is the most user friendly thing to do.
