### ISSUE TITLE
Problem in MSwindows10 due to pyvirtualdisplay incompatibility

### ISSUE THREAD

**Issue by TekpreXyz** [tensorflow/agents#538]
Tutorial issue
https://www.tensorflow.org/agents/tutorials/6_reinforce_tutorial
When try to import
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()
because pyvirtualdisplay not work in MSwindows10

**Comment by tfboyd** [comment]
Duplicate https://github.com/tensorflow/agents/issues/539
