### ISSUE TITLE
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()

### ISSUE THREAD

**Issue by TekpreXyz** [tensorflow/agents#539]
Tutorial issue
https://www.tensorflow.org/agents/tutorials/6_reinforce_tutorial
When try to import
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()
because pyvirtualdisplay not work in MSwindows10

**Comment by tfboyd** [comment]
I don't like closing issues this way but we are not supporting windows officially. If the package works that is great, but on our team we do not have a setup to debug or for continuous testing. If you know of a solution that works on linux and windows please submit a PR and we can validate it.
