### ISSUE TITLE
Add a folder for examples?

### ISSUE THREAD

**Issue by jionglearningzhang** [tensorflow/agents#54]
How about adding a folder for examples and tutorials like tensorflow/tensorflow/contrib/eager/python/examples?

**Comment by sguada** [comment]
Take a look at [Colabs/Tutorials ](https://github.com/tensorflow/agents/tree/master/tf_agents/colabs) and to examples under each Agent, e.g. [DQNAgent/examples](https://github.com/tensorflow/agents/tree/master/tf_agents/agents/dqn/examples/v2)

**Comment by kbanoop** [comment]
Closing this issue, please reopen if you have further questions.
