### ISSUE TITLE
`Distribution` policy_state

### ISSUE THREAD

**Issue by JacobFV** [tensorflow/agents#545]
The `tf_agents.policies.*.action` method accepts a recurrent `NestedTensor` `policy_state`. However, I want to recurrently biject and read from a `Distribution` state. Is there a way I can modify the `policy.action` method and signature to accept `tf_agents.typing.types.Distribution` objects? 

```python
  def action(self,
             time_step: ts.TimeStep,
             policy_state: types.NestedTensor = (), # <==== I want this to be a `tfp.distributions.Distribution`
             seed: Optional[types.Seed] = None) -> policy_step.PolicyStep:
```

**Comment by sguada** [comment]
I'm not sure I follow what you want to do, but would it be possible to pass the parameters of the Distribution as policy_state and reconstruct the Distribution inside of it?

**Comment by JacobFV** [comment]
No. I want to pass along a `TransformedDistribution`

**Comment by sguada** [comment]
Currently that is not possible, so you may need to create your own policy.
