### ISSUE TITLE
Current DQN example modified for a federated learning case ?

### ISSUE THREAD

**Issue by biplavc** [tensorflow/agents#546]
A simple implementation of Federated Learning based on this example [link](https://towardsdatascience.com/federated-learning-a-step-by-step-implementation-in-tensorflow-aac568283399) requires two `for `loops where the

-  outer loop is for the overall iteration of the global model (where the local models weights are averaged to obtain a global model) 

- an inner loop to train the local models.

Assuming the local models are identical in all respects (state, action, reward, state transition), can this modification be done in the tf agent DQN example ([link](https://github.com/tensorflow/agents/blob/master/docs/tutorials/1_dqn_tutorial.ipynb)) ?

**Comment by sguada** [comment]
I suppose is possible, I encourage you to copy the colab and implement it for your use case.
