### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ankdesh** [tensorflow/agents#55]
It would be a great help if the APIs and the parameters can be hosted on a site. Currently, we need to reach to the specific python files to understand the definition.

**Comment by sguada** [comment]
Thanks for your request, we are working on it. They should be public this week.

**Comment by ankdesh** [comment]
Thanks. Any updates?

**Comment by ankdesh** [comment]
Closing the issue. Will wait for it :)

**Comment by kbanoop** [comment]
Added some initial documentation here: https://github.com/tensorflow/agents/blob/master/tf_agents/docs/python/tf_agents.md

These get auto generated from the documentation in the code, and we will update it periodically. Some symbols need to be cleaned up though.
