### ISSUE TITLE
TypeError: function() got an unexpected keyword argument 'jit_compile'

### ISSUE THREAD

**Issue by jcatanza** [tensorflow/agents#553]
**Has anyone encountered this error, and found a workaround?**

Description of the problem: executing the following cell
============================
`from tf_agents.environments import suite_gym` <br>
`env = suite_gym.load("Breakout-v4")` <br>
`env`<br>
============================

Threw this error:
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-104-35ec520dce7d> in <module>()
----> 1 from tf_agents.environments import suite_gym
      2 
      3 env = suite_gym.load("Breakout-v4")
      4 env

18 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/internal/variadic_reduce.py in make_variadic_reduce(reducer, vjp_bwd, tangents_fn)
    120   # Top-level `tf.function` for XLA (closed-over by the returned reduce_fn).
    121   @implementation_selection.never_runs_functions_eagerly
--> 122   @tf.function(jit_compile=True)
    123   def _xla_reduce(operands, inits, axis):
    124     """JIT-ed wrapper for TF `xla.variadic_reduce(..., reducer)`."""

TypeError: function() got an unexpected keyword argument 'jit_compile'

**Comment by AntoninLagarrigue** [comment]
I have the exact same issue. I think i will just go pytorch, but i'm interested if you found a solution ?

**Comment by sguada** [comment]
It seems a problem with the version of tensorflow_probablity and TensorFlow. Can you check which versions do you have instaled?

**Comment by vinits5** [comment]
This is an issue with tensorflow_probability library. Check the version.
In my case, the version was '0.13.0-dev20210311'. I changed it to 0.12.0 and reinstalled the tf_agents. And it worked.

**Comment by morgandu** [comment]
I experienced the same issue. It went away after ```pip uninstall tensorflow``` and replaced with ```pip show tf-nightly```, would like to know if there is a better or other way.

**Comment by ebrevdo** [comment]
TF-Agents nightlies are tied to tf-nightlies; whereas TF-Agents versioned releases are each associated with a particular TF versioned release.
