### ISSUE TITLE
Initialize DQN with custom weights

### ISSUE THREAD

**Issue by ghost** [tensorflow/agents#558]
I have two model files, one a .h5 file for a TF network model and a policy for a separately trained DQN agent (I believe according to the policy saver routine from documentation it is stored as a .pb file). I need to now merge these two models and pre initialize the respective layers with these pre-trained weights to get a single DQN agent for a different experiment (transfer learning in some way). Is this possible to do with the DqnAgents method? Anyone has any suggestions to do this? Please recommend the right forum if this is not the place for this question.

**Comment by ebrevdo** [comment]
You'll have to use model surgery to do this, using `tf.saved_model.load`, modifying the associated object's tf.Variables in-place, and re-saving it using `tf.saved_model_save`.  The appropriate location to ask for more details is StackOverflow.
