### ISSUE TITLE
`epsilon_greedy` in class `DqnAgent` type hint should be optional

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [tensorflow/agents#565]
[`epsilon_greedy` in class `DqnAgent`](https://github.com/tensorflow/agents/blob/v0.7.1/tf_agents/agents/dqn/dqn_agent.py#L104) and [`CategoricalDqnAgent`](https://github.com/tensorflow/agents/blob/v0.7.1/tf_agents/agents/categorical_dqn/categorical_dqn_agent.py#L65) type hint should be optional like `boltzmann_temperature` since you check for `None` [here](https://github.com/tensorflow/agents/blob/v0.7.1/tf_agents/agents/dqn/dqn_agent.py#L220).

I think the docs could also be more explicit that `epsilon_greedy` and `boltzmann_temperature` are mutually exclusive.

Also, [`boltzmann_temperature` type hint](https://github.com/tensorflow/agents/blob/v0.7.1/tf_agents/agents/dqn/dqn_agent.py#L106) is an optional `types.Int` instead of `types.Float` or `types.FloatOrReturningFloat`.

**Comment by ebrevdo** [comment]
@kbanoop ping.
