### ISSUE TITLE
tf_agents.eval.metric_utils.eager_compute()  is very slow

### ISSUE THREAD

**Issue by Adaickalavan** [tensorflow/agents#567]
I wrote a reinforcement learning code using tf_agents at https://github.com/Adaickalavan/rl-tfagents/blob/main/tfagent_dqn.py. This code is very similar to the example code of https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v2/train_eval.py . 

My code has the following setup:
+ uses python3.7, nvidia driver: 450.80.02, cuda 11.0 
+ runs inside a docker container with tensorflow/tensorflow:2.4.0-gpu as base image
+ implements DQN to solve Breakout:v4 environment
+ uses multiple parallel environments for training and evaluation
+ the agent training loop is interleaved with evaluation
+ evaluation is performed as follows 
  ```python3.7
  metric_utils.eager_compute(eval_metrics, eval_tf_env, eval_policy, eval_num_episodes, train_step, eval_summary_writer, 'Metrics - Evaluation')
  ```

Problem:
+ The training runs fast and utilises up to 32% of the GPU. 
+ However, during the evaluation period, the GPU utilisation drops to 6% and the evaluation runs very slowly.

Questions:
+ Why is `metric_utils.eager_compute()` very slow and why does it not utilise the GPU?
+ How can I perform evaluation of the trained agent policy at a faster speed by utilising GPU?

**Comment by ebrevdo** [comment]
One possibility is that during evaluation you're constantly going back and forth with the CPU to run your environment, then sending this data back to GPU!  In contrast, when training we can send all the time frames to the GPU at once.

For this reason we recommend that for eval/data collection you use the CPU only.  The cost of copying data back and forth from GPU to CPU for each time step slows everything down.  It's only useful to use the GPU if you have an extremely complicated/large per-step model and the cost of doing compute on CPU overshadows the cost of CPU<->GPU transfer for each frame.

Let us know if that helps the speed.  I'll close for now, but please reopen if you feel this doesn't address your question!
