### ISSUE TITLE
Recommendation and best practice for pre-training and transfer learning ?

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#57]
Hi all,
We're looking for some recommendation to do pre-training and transfer learning with tf_agents. 
The idea is to perform pre-training on other task domain and use this pre-trained model as an encoder for an agent. For instance, the pre-training task is imagenet classification. 
Ideally, we would like to use the original Keras model definition for the encoder network since we have a fullstack of Tensorflow keras pipeline for the pre-training task and we don't want to recode everything to follow tf_agents network definitions. 
We know that tf_agents.Network derives from keras.Network and the question is : does using pre-trained model from keras will work out of the box when we want to use is as a sub-network in tf_agents ? if Not what is the best way to copy weight from keras pre-trained model ?
Below is the pseudo-code of what we would like to achieve:

```
# pre-training
keras_model = build_keras_model(...)
keras_model.fit(pre_train_dataset)

# tf_agents_netowks uses keras_model as an encoder
tf_agents_networks = build_tf_agent_network(keras_model, ...)

tf_agents = Agent(tf_agents_network)

...
tf_agents.train(...)
```

**Comment by sguada** [comment]
One simple way would be to create a Network wrapper that takes a keras_model and implements the tf_agents.Network API, most relevant are .copy() and .variables()

**Comment by sibyjackgrove** [comment]
@sguada I can help with this. I use the QNetwork class in `q_network.py` as a template to come up with below code. Sorry I am very new to this, but I would really like to help out.
Could you suggest how I can the correct the code. I don't uderstand where` .copy()` and `.variables(`) are be used. 

```
class CustomKerasNetwork(network.Network):
    """Creates custom network from Keras model."""
    def __init__(self,
                 input_tensor_spec,
                 action_spec,
                 keras_model,
                 name='CustomKerasNetwork'):
        super(CustomNetwork, self).__init__(input_tensor_spec=input_tensor_spec,
                                           state_spec=(),
                                           name=name)
        self._model = keras_model
        
    def call(self, observation, step_type=None, network_state=()):
        state, network_state = self._model(observation, step_type=step_type, network_state=network_state)
    
        return state, network_state  
```

**Comment by sguada** [comment]
You can start by creating a subclass of [tf_agents.networks.Network](https://github.com/tensorflow/agents/blob/master/tf_agents/networks/network.py#L91) which takes a tf.keras.Model as an additional input and implements the `variables()`, `copy()` and `call()` by forwarding appropriately to the tf.keras.Model.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if we need to track this actively or if you have further questions.

**Comment by XirenZhou** [comment]
> You can start by creating a subclass of [tf_agents.networks.Network](https://github.com/tensorflow/agents/blob/master/tf_agents/networks/network.py#L91) which takes a tf.keras.Model as an additional input and implements the `variables()`, `copy()` and `call()` by forwarding appropriately to the tf.keras.Model.

FYI, The following is a tested implementation which successfully runs with DQN agent (This is a simple wrapper which only deals with non-stateful models).
```
class MyNetwork(network.Network):
    '''
    This is a custom wrapper for a non-stateful pre-defined tensorflow model
    '''
    def __init__(self,
                 model,
                 input_spec = None,
                 name = None):
        '''

        :param model: a tf.keras model, can be Functional or Sequential.
                      stateful network is currently not supported within this subclass;
                      i.e., the input model is expected to not have any `tf.keras.layers.{RNN,LSTM,GRU,...}` layer.
        :param input_spec: (Optional.) A nest of `tf.TypeSpec` representing the input observations to the first layer.
        :param name: (Optional.) Network name.
        '''
        super(MyNetwork, self).__init__(input_tensor_spec=input_spec,
                                         state_spec=(),
                                         name=name)
        self.model = model

    def copy(self, **kwargs) -> 'MyNetwork':
        """Make a copy of a `MyNetwork` instance.
        **NOTE** The new instance will not share weights with the original - but it will start with the same weights.
        Args:
          **kwargs: Args to override when recreating this network. Commonly overridden args include 'name'.
        Returns:
          A copy of this network.
        Raises:
          RuntimeError: If not `tf.executing_eagerly()`; as this is required to
            be able to create deep copies of layers in `layers`.
        """
        new_kwargs = dict(self._saved_kwargs, **kwargs)
        if 'model' not in kwargs:
            new_model = tf.keras.models.clone_model(self.model)
            new_kwargs['model'] = new_model
        return type(self)(**new_kwargs)

    def call(self, inputs, **kwargs):
        # Only Networks are expected to know about step_type, network_state; not Keras models.
        model_kwargs = kwargs.copy()
        model_kwargs.pop('step_type', None)
        model_kwargs.pop('network_state', None)
        return self.model(inputs, **model_kwargs), ()
```
I think this point proposed by @jrabary is fairly valuable and deserves an official feature extension. In terms of making tf-agents more powerful, flexible and scalable as a popular RL library, I believe the support of pre-training & transfer learning is an inevitable topic.

**Comment by ghost** [comment]
> FYI, The following is a tested implementation which successfully runs with DQN agent (This is a simple wrapper which only deals with non-stateful models).

Could you please show an example for using this? It would be really helpful.
