### ISSUE TITLE
7 SAC Minitaur tutorial pybullet version mismatch

### ISSUE THREAD

**Issue by Mechanacor3** [tensorflow/agents#571]
The current pybullet version (3.0.9) is causing a version mismatch with 7_SAC_minitaur_tutorial.ipynb

Changing
```
!pip install pybullet
```
to the previous version
```
!pip install pybullet==3.0.8
```
fixes things.

**Comment by tfboyd** [comment]
I suspect an issue with pybullet.  They just released 3.1.0 on 08-MAR.  I tested https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial on the site and it looks good.  Last nights nightly runs also run the colabs and it also looked ok as well.  I think you got unlikely with either pybullet releasing something that was not ready or nighty builds that did not line up.  I think everything looks good now.  Feel free to reopen and ping me if not.
