### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_agents.agents'; 'tf_agents' is not a package

### ISSUE THREAD

**Issue by kapilrathore42** [tensorflow/agents#572]
when i download the tf_agents then everything with tf_agents give me that error i can reinstall but nothing works

**Comment by kapilrathore42** [comment]
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import abc
import tensorflow as tf
import numpy as np

from tf_agents.environments import py_environment
from tf_agents.environments import tf_environment
from tf_agents.environments import tf_py_environment
from tf_agents.environments import utils
from tf_agents.specs import array_spec
from tf_agents.environments import wrappers
from tf_agents.environments import suite_gym
from tf_agents.trajectories import time_step as ts

tf.compat.v1.enable_v2_behavior()
after run 
ModuleNotFoundError: No module named 'tf_agents.environments'; 'tf_agents' is not a package

**Comment by RayTsui** [comment]
Hi @kapilrathore42 , I noticed this ticket is closed, seems you've found the solution or where is the root cause. If you do not mind, can you please share it since I encounter this issue, thanks in advance.
