### ISSUE TITLE
Support for RandomPyPolicy parameters in validate_py_environment

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [tensorflow/agents#584]
[`validate_py_environment`](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/utils.py#L51) only accepts a `PyEnvironment` and the number of episodes as arguments. It would be nice to also support arguments to pass to the internal RandomPyPolicy. Specifically, I would like to pass an `observation_and_action_constraint_splitter` to ensure the policy only selects valid actions.

**Comment by kbanoop** [comment]
That sounds like a good idea. Would you like to submit a PR?

**Comment by AbhijeetKrishnan** [comment]
I would be glad to. Is there a style guide for contributors? Or a default code linter? The links in [agents/STYLE_GUIDE.md](https://github.com/AbhijeetKrishnan/agents/blob/master/STYLE_GUIDE.md) no longer work.

**Comment by kbanoop** [comment]
Awesome, thank you! A PR to update the broken links is on the way. In the meantime, they are:

https://www.tensorflow.org/community/contribute/code_style
https://www.tensorflow.org/community/contribute/docs_style

**Comment by AbhijeetKrishnan** [comment]
Any follow-up to this?

**Comment by oars** [comment]
This has now been merged. Thank you!
