### ISSUE TITLE
validate_py_environment doesn't check that reset() is called on episode termination

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [tensorflow/agents#585]
`PyEnvironment` objects assume that the `step()` method calls the `reset()` method if the episode has terminated. `validate_py_environment` only checks that the time_step_spec matches the returned time_step, and does not check if `reset()` is called during `step()` if the episode has ended.

This is difficult to debug when writing a custom environment. For example, my custom environment returns an error when `step()` is called after episode termination with a non-`None` action. I was trying to use `DynamicEpisodeDriver` to fill a replay buffer, and this error was repeatedly raised. Tracking down the issue with my environment not meeting the assumption regarding `reset()` was difficult.

This behavior can be seen by commenting out the following lines in the `CardGameEnv` class from the [TF-Agents Environments](https://www.tensorflow.org/agents/tutorials/2_environments_tutorial) tutorial.

```python
    if self._episode_ended:
        # The last action ended the episode. Ignore the current action and start
        # a new episode.
    return self.reset()
```

I would expect `validate_py_environment` to return an error, but it does not.

**Comment by sguada** [comment]
Thanks for raising the issue. I can think a couple of solutions, one is to add a parameter `auto_reset` to the base `PyEnvironment` class that makes explicit the handling of auto-reset, although it will be false by default. And then make sure that `validate_py_environment` checks if that auto reset happens when is `True`.

Would you like to do a PR to fix this?

**Comment by AbhijeetKrishnan** [comment]
That sounds like a clean way to implement it. I would be happy to submit a PR.

**Comment by AbhijeetKrishnan** [comment]
I believe a better way to solve this would be to modify [`environments/py_environment.py:200`](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/py_environment.py#L200) as follows -

```python
if self._current_time_step is None or self._current_time_step.is_last():
    return self.reset()
```

This would call `reset()` if the `_current_time_step` (which at this point in the function contains the *previous* time step) is of type `StepType.LAST`, indicating episode end. This change also seems to better reflect the assumptions made. Using `auto_reset` as a parameter seems to require making changes in a lot of other places. At least, one would have to check in `DynamicEpisodeDriver` that `auto_reset` is `True`.

The issue with implementing this is that I get a lot of errors when testing with `python setup.py test`. They are of the form `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`, and I cannot figure out yet why it appears, since `_current_time_step` should both be non-`None` at that point, and should be an object of `ts.TimeStep`.

From the test logs, this error seems to occur with batched and parallel environments, where I presume the time step returned by `step()` is a *list* of time steps. I'm not sure what the correct behaviour for `step()` should be if only some of these timesteps are episode terminations.

***

Here's the proposed test for the change in `py_environment_test.py` which breaks prior to the proposed change, and is fixed by it.

```python
def testResetOnEpisodeEnd(self):
    obs_spec = array_spec.BoundedArraySpec((1,), np.int32)
    action_spec = array_spec.BoundedArraySpec((1,), np.int32)

    random_env = random_py_environment.RandomPyEnvironment(
        observation_spec=obs_spec, action_spec=action_spec)

    def _step(action):
      return ts.termination(np.ones((1,)), 0.0)  # pytype: disable=wrong-arg-types

    random_env._step = _step

    random_env.reset()
    random_env.step(action=np.ones((1,))) # StepType.LAST
    random_env.step(action=np.ones((1,))) # should return StepType.FIRST
    current_time_step = random_env.current_time_step()
    self.assertTrue(current_time_step.is_first())
```

**Comment by sguada** [comment]
Will modify PyEnvironment to allow auto_reset, but keep it False by default to not change the default behavior.


```
if self._auto_reset and np.all(self._current_time_step.is_last()):
      return self.reset()
```

**Comment by AbhijeetKrishnan** [comment]
Any follow-up to this?
