### ISSUE TITLE
Loss is inf or nan : Tensor had NaN values

### ISSUE THREAD

**Issue by singagan** [tensorflow/agents#589]
Hi,
I am having the below issue. 
I have tried changing hyperparameter (learning rate), state normalization, checking for NANs, etc but is not working for me. Please could you help me with the below error message?

Thanks.

train_loss_in = tf_agent.train(experience)
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in call
result = self._call(*args, **kwds)
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
return self._stateless_fn(*args, **kwds) # pylint: disable=not-callable
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in call
return graph_function._call_flat(
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
return self._build_call_outputs(self._inference_function.call(
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
outputs = execute.execute(
File "/root/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Loss is inf or nan : Tensor had NaN values
[[node CheckNumerics (defined at /root/.local/lib/python3.8/site-packages/tf_agents/agents/dqn/dqn_agent.py:394) ]] [Op:__inference_train_565242]

Errors may have originated from an input operation.
Input Source operations connected to node CheckNumerics:
critic_loss/add (defined at /root/.local/lib/python3.8/site-packages/tf_agents/utils/common.py:1360)

Function call stack:
train

**Comment by singagan** [comment]
I was able to resolve the issue after debugging everything inside out. The problem was with one of the features in my state representation. Thanks!

**Comment by suresh-guttikonda** [comment]
hey i am having same problem, what do you mean by state feature representation. could you please give more details if possible.

**Comment by sguttikon** [comment]
> I was able to resolve the issue after debugging everything inside out. The problem was with one of the features in my state representation. Thanks!

@singagan hey i am having same problem, what do you mean by state feature representation. could you please give more details if possible.

**Comment by singagan** [comment]
@suresh-guttikonda not sure if you were able to get around your issue, but what I saw was one of the observations in my state representation was not properly normalized. However, after fixing that, everything worked well.

**Comment by sguttikon** [comment]
@sin

> @suresh-guttikonda not sure if you were able to get around your issue, but what I saw was one of the observations in my state representation was not properly normalized. However, after fixing that, everything worked well.

@singagan yes i was able to narrow down the issue when i use tf_functions to collect_driver, env.step() is returning nan value images. if i turn it off i am getting correct images from env.step().

Not sure if its issue with dynamic_step_driver. anyway, thank you

```
....
collect_driver = dynamic_step_driver.DynamicStepDriver(
            tf_env,
            collect_policy,
            observers=replay_observer + train_metrics,
            num_steps=collect_steps_per_iteration)
.....
if use_tf_functions:
            collect_driver.run = common.function(collect_driver.run)
```
