### ISSUE TITLE
Custom and generic PolicyInfo in PolicyStep

### ISSUE THREAD

**Issue by MichelangeloConserva** [tensorflow/agents#591]
Hello,

I designing a custom TFPolicy and I would like to transmit store information in the PolicyStep object. In more concrete terms I would like to return from the _distribution function the current object
```
policy_step.PolicyStep(
            distribution,
            self._policy_state,
            self._mask_distribution.sample(self._num_ensembles)
        )
```
where self._mask_distribution.sample(self._num_ensembles) is a tensor with the following TensorSpec
```
tf.TensorSpec(
            shape=[self._num_ensembles], dtype=tf.float32, name="mask_distribution"
        )
```
Looking at the source code it seems like the only current usage of PolicyInfo is for emitting log probabilities.

Am I missing something in the documentation?
Can you suggest a better way to transmit such information using the PolicyStep object?

Thanks.

Kind regards,
Michelangelo

**Comment by egonina** [comment]
PolicyInfo can be anything, the example we have is with log probabilities. You can include the mask distribution sample in policy info and return it as part of your policy action return value

**Comment by oars** [comment]
+1 to @egonina's comment. Feel free to re-open if you hit any issues with it.
