### ISSUE TITLE
Cannot allocate tf_uniform_replay_buffer to GPU -  No registered 'ResourceScatterUpdate' OpKernel for 'GPU' devices compatible with node

### ISSUE THREAD

**Issue by deeepwin** [tensorflow/agents#595]
I am trying to run the TFUniformReplayBuffer on the GPU based on the example outlined here:

[https://pathtopioneer.com/blog/2020/07/rl-3](https://pathtopioneer.com/blog/2020/07/rl-3)

When adding device='/device:CPU:0' to the initalisation of the replay buffer everything works. When specifying GPU device='/device:GPU:0', an error occurs. It appears there is no GPU op for ResourceScatterUpdate. But how can this be fixed?

```


import tensorflow as tf
from tf_agents.replay_buffers import tf_uniform_replay_buffer
import numpy as np

data_spec =  (
        tf.TensorSpec([1], tf.float32, 'action'),
        tf.TensorSpec([5], tf.float32, 'lidar'),
        tf.TensorSpec([3, 2], tf.float32, 'camera')
)

batch_size = 32
max_length = 1000

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec,
    batch_size=batch_size,
    max_length=max_length,
    device='/device:GPU:0') # when using device='/device:CPU:0') everything works

action = tf.constant(1 * np.ones(
    data_spec[0].shape.as_list(), dtype=np.float32))
lidar = tf.constant(
    2 * np.ones(data_spec[1].shape.as_list(), dtype=np.float32))
camera = tf.constant(
    3 * np.ones(data_spec[2].shape.as_list(), dtype=np.float32))

values = (action, lidar, camera)
values_batched = tf.nest.map_structure(lambda t: tf.stack([t] * batch_size),
                                       values)

replay_buffer.add_batch(values_batched)

# Convert the replay buffer to a tf.data.Dataset and iterate through it
dataset = replay_buffer.as_dataset(
    sample_batch_size=4)

iterator = iter(dataset)
print("Iterator trajectories:")
trajectories = []
for _ in range(3):
  t, _ = next(iterator)
  trajectories.append(t)

print(tf.nest.map_structure(lambda t: t.shape, trajectories))
```

I get the following error:

Exception has occurred: NotFoundError
No registered 'ResourceScatterUpdate' OpKernel for 'GPU' devices compatible with node {{node ResourceScatterUpdate}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: Tindices=DT_INT64, dtype=DT_INT64
	.  Registered:  device='CPU'; dtype in [DT_UINT64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT32]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT32]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_HALF]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_HALF]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_BOOL]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT64]
 [Op:ResourceScatterUpdate]
  File "C:\Users\Martin\Documents\GitHub\rl-investing\helper\replay.py", line 31, in <module>
    replay_buffer.add_batch(values_batched)

System is:

tensorboard                2.4.1
tensorflow                 2.4.1
tf-agents                  0.7.1

Same error when running code on Colab with GPU enabled.

**Comment by ebrevdo** [comment]
Adding GPU kernel support requires filing a bug with TensorFlow team since we don't maintain TensorFlow's kernels.  You can file this bug [here](https://www.github.com/tensorflow/tensorflow).  That said, I'm not convinced that this will speed up your training in any way.  You can reference this issue with TF team.

**Comment by deeepwin** [comment]
Reference is https://github.com/tensorflow/tensorflow/issues/48650#issue-863204097

I see a lot of memory copy between CPU and GPU with Tensorflow profiler in my RL project. Hence, I hope to gain speed when allocating replay buffer to GPU memory similar to this paper:

Deep In-GPU Experience Replay
https://arxiv.org/abs/1801.03138

But I guess I have to try. Thanks.

**Comment by ebrevdo** [comment]
This is during training or collection?

During collection, unless your model is really expensive/big, you will pay a cost for calling to the GPU for each step you take.  For smaller models you want your data collection model to sit on CPU.

Suppose you move your RB to GPU.  You will also have a memory copy CPU->GPU during data collection, so you'll pay the cost then instead of at training.

You may want to try both but I wouldn't expect it to be a panacea.

**Comment by deeepwin** [comment]
It is during training and collection The special case ist, that I run a train step after every step in the environment, instead of training at the end of an epsiode. This gives me better convergence. Increasing batch size and training at the end of the episode did not give good results.  I need mainy trainin steps. The CPU is spending a lot of time in the environment, as the huge time gap indicates in the attached chart. The model itself is fairly small with approximately 15000 parameters. Overall, I have a super low GPU utilization - but nice RTX 2080 Ti card.

The goal is to run training separate in a process on GPU with RB. Data collection will be on CPU's (12 core) with possibly several explorers similar using APE-X architectur. Data would need to be copied only once to RB through PCI and GPU can access RB directly from GPU memory. Versus today, where I have GPU Kernel allocations on every step.

Hope this makes sense, otherwise let me know if I could improve my approach. 

![grafik](https://user-images.githubusercontent.com/65670300/115500300-540bdd80-a271-11eb-938c-60f30b679d96.png)

**Comment by ebrevdo** [comment]
For a small model, wouldn't you need to use fairly large training batch
sizes to make it worthwhile to train on GPU?  Either way you probably want
to look at the Actor/Learner API which - while it doesn't use a GPU for the
RB - does use the Reverb replay buffer and would allow you to scale to
collecting data via multiple machines.  That would come in handy if your
environment is actually expensive.  If everything's on one machine then you
really do just kinda have to do the grid search of options to see which is
fastest.

**Comment by deeepwin** [comment]
Thanks for the hints. Indeed reverb is something to look into. The Actor/Learner API is too tf-agents specific for me at the moment. Maybe I'll later switch framework to tf-agents. I very much like it. It is the right way forward. But at the moment it requires too much code rework for me.

Regarding the batch size, yes it would be better to increase. But, it did not help in my case. There reason is most likely because I train on every step, I get new transitions too slowly that a larger batch size would help to converge the model quicker. Hence, in essence, I gain no speed.

**Comment by oars** [comment]
Given that we are not likely to deal with custom kernels for our internal replay buffer I'll be closing this issue. I understand moving to the Actor/Learner API would be a significant rework for you, but you might be able to consider using Reverb instead for your distributed data collection. You can use rate limiters there and then still scale the number of train steps you do per call into the GPU.
