### ISSUE TITLE
BoundedTensorSpec difficulties in PPOPolicy Initialisation

### ISSUE THREAD

**Issue by IanRDavies** [tensorflow/agents#605]
I have an implementation of PPO for a custom environment I have written. When initialising PPO I get an error which I have traced back to the [call to `tf_agents.distributions.utils. assert_specs_are_compatible`](https://github.com/tensorflow/agents/blob/29daabcc11b277a914f6b848d44c30b4aabbf659/tf_agents/agents/ppo/ppo_policy.py#L116) in the initialisation of PPOPolicy.

I believe this is due to the `ActorDistributionNetwork` resulting in an instance of `DistributionSpecV2` being passed to `assert_specs are compatible` which then takes the `event_spec` from the distribution spec which leads to the batch dimensions being dropped which then causes the error below. Bypassing this taking of the `event_spec` attribute resolves the issue and then the code runs without error.

```bash
ValueError: actor_network output spec does not match action spec:
TensorSpec(shape=(2,), dtype=tf.float32, name=None)
vs.
BoundedTensorSpec(shape=(1, 2), dtype=tf.float32, name='action/tuple_0', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32))
In call to configurable 'PPOPolicy' (<class 'tf_agents.agents.ppo.ppo_policy.PPOPolicy'>)
In call to configurable 'PPOAgent' (<class 'tf_agents.agents.ppo.ppo_agent.PPOAgent'>)
```

I have tried to build a minimal reproduction below based on my own code. This issue aims to distill the core issue that I have in some more complex code using a custom implementation of ActorDistributionNetwork.

```python
import tensorflow as tf
import numpy as np
import tf_agents
from tf_agents.agents.ppo import ppo_policy
from tf_agents.trajectories.time_step import TimeStep
from tf_agents.specs.tensor_spec import BoundedTensorSpec, TensorSpec
time_step_spec = TimeStep(
    TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
    TensorSpec(shape=(), dtype=tf.float32, name='reward'),
    BoundedTensorSpec(
        shape=(),
        dtype=tf.float32,
        name='discount',
        minimum=np.array(0., dtype=np.float32),
        maximum=np.array(1., dtype=np.float32)
    ),
    BoundedTensorSpec(
        shape=(1,),
        dtype=tf.float32,
        name='observation',
        minimum=np.array(0., dtype=np.float32),
        maximum=np.array(3.4028235e+38,
        dtype=np.float32)
    ),
)
observation_spec = BoundedTensorSpec(
    shape=(1,),
    dtype=tf.float32,
    name='observation',
    minimum=np.array(0., dtype=np.float32),
    maximum=np.array(3.4028235e+38, dtype=np.float32)
)
action_spec = BoundedTensorSpec(
    shape=(1, 2),
    dtype=tf.float32,
    name='action',
    minimum=np.array(0., dtype=np.float32),
    maximum=np.array(1., dtype=np.float32)
)
actor_network = tf_agents.networks.actor_distribution_network.ActorDistributionNetwork(
    input_tensor_spec=observation_spec, output_tensor_spec=action_spec
)
value_network = tf_agents.networks.value_network.ValueNetwork(
    observation_spec,
    fc_layer_params=(128, 64),
    activation_fn=tf.nn.tanh
)

ppo_policy.PPOPolicy(
        time_step_spec=time_step_spec,
        action_spec=action_spec,
        actor_network=actor_network,
        value_network=value_network,
        observation_normalizer=None,
        clip=False,
        collect=False
)
```

This error arose when updating the versions of TensorFlow and TF-Agents (to 2.4 and 0.7.1 respectively). 

It may simply be that I am misunderstanding the use of tensor specifications but I have failed to resolve this myslef.

**Versions**
tf-agents==0.7.1
tensorflow==2.4.0
tensorflow_probability==0.12.1
numpy==1.19.5

**Comment by ebrevdo** [comment]
The specs you pass to the networks and agents should not have any batch dimensions in their shapes.  Does everything work if you remove the `(1,)` prefix?  [sounds like that's the batch size 1 prefix?]

**Comment by IanRDavies** [comment]
Ah right, my bad. Your suggestion fixed the issue. I've refactored my custom env and networks in line with this.

Thanks for the quick reply and helping me to better understand the use of TensorSpecs.
