### ISSUE TITLE
BoundedArraySpec should convert its shape argument to a TensorShape by default

### ISSUE THREAD

**Issue by rschiewer** [tensorflow/agents#607]
I'm creating a `BoundedArraySpec` manually to put it into a `Trajectory` which is used as the data_spec for a `TFUniformReplayBuffer`. Whereas the [docs](https://www.tensorflow.org/agents/api_docs/python/tf_agents/specs/BoundedArraySpec) say it's fine to use any iterable for the shape argument, [here](https://github.com/tensorflow/agents/blob/3448c9e88fbe48d515c85ffab2b96e9f429a3b7d/tf_agents/replay_buffers/table.py#L59) it is implicitly assumed that `shape` is a `TensorShape` or a related class that supports the `as_list()` method.

Actually, every iterable provided for the `shape` Argument is converted to a tuple in the constructor. Thus, I don't see any way to create a `BoundedArraySpec` object that satisfies the requirements to use it as part of a `Trajectory` to initialize a `TFUniformReplayBuffer`.

**Comment by sguada** [comment]
`TFUniformReplayBuffer` requires `BoundedTensorSpec` not `BoundedArraySpec`, you can either directly create a `BoundedTensorSpec` or convert into by 
```
tensor_spec = tensor_spec.tensor_spec(array_spec)
```

**Comment by rschiewer** [comment]
I see, thanks for pointing that out. From stepping through the code with a debugger I found that when following the [Rainbow DQN example](https://www.tensorflow.org/agents/tutorials/9_c51_tutorial#training_the_agent), the resulting `TFUniformReplayBuffer` has `BoundedArraySpecs` for its contents. From that I concluded that those should be used, however I did not look it up in the docs.

Thanks again for your help!

**Comment by rschiewer** [comment]
Of course, I'll close the issue because it's actually solved. I have no idea why internally the `TFUniformReplayBuffer` can use `BoundedArraySpec` without the problem I encountered. All in all, when working with tf agents aside from the tutorials the documentation is still a bit slim for me.

**Comment by rschiewer** [comment]
Of course, I'll close the issue because it's actually solved. I have no idea why internally the `TFUniformReplayBuffer` can use `BoundedArraySpec` without the problem I encountered. All in all, when working with tf agents aside from the tutorials the documentation is still a bit slim for me.
