### ISSUE TITLE
Observation summary may cause OOM

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#61]
In some agent, for instance PPOAgent, when `debug_summaries` is enabled the summaries contain `observations` as well. This sometimes causes OOM error especially when the observation dimension is large (e.g image).
My suggestion is to add an additional flag `summarize_observation` to handle this case.
Below is the error message I got :  
```
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3145728,30] 
and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator 
GPU_0_bfc [Op:OneHot] name: epoch_9/observations/buckets/cond/cond/one_hot/
  In call to configurable 'train_eval' (<function train_eval at 0x7fe756fdf840>)
```

**Comment by egonina** [comment]
How would the observation be summarized with that flag turned on? An option to skip/summarize observation in the debug info sounds good for large observations. Also, it looks like the observation summary is created on the GPU, we should probably move the summary op to run on the CPU.

**Comment by sguada** [comment]
Sure we could add a flag for `summarize_observation` separated from `debug_summaries`. One note the observation seems a bit odd shape `[3145728,30]` for an image.

**Comment by jrabary** [comment]
@sguada to be honest, I'm not really sure anymore if the observation is the problem. I comment out every summaries and still have the OOM error. It's may be the same issue as https://github.com/tensorflow/agents/issues/20 .

**Comment by kbanoop** [comment]
Closing this issue, please reopen if we need to track this actively or if you have further questions.
