### ISSUE TITLE
GymWrapper miss reward_spec mapping

### ISSUE THREAD

**Issue by cmarlin** [tensorflow/agents#610]
The Gym environments provide a **reward_range** member with min-max reward value. This parameter could be forwarded to a reward_spec() member returning a BoundedArraySpec instead of ArraySpec from abstract PyEnvironment.

**Comment by sguada** [comment]
Contribution to the gym_wrapper to forward the information if available are welcome.

**Comment by cmarlin** [comment]
I have created a pull request
https://github.com/tensorflow/agents/pull/616
