### ISSUE TITLE
How is discount factor applied over multiple transitions?

### ISSUE THREAD

**Issue by ArmaanAS** [tensorflow/agents#613]
Using an episodic driver and a UniformReplayBuffer add_batch function as an observer, is the DQN agent's predefined discount factor applied to all the trajectory rewards added to the uniform replay buffer over an episode? Is this something I need to do manually for my environment, applying the discount factor?

**Comment by sguada** [comment]
The discount factor is used when computing the DQN loss. See [here](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/dqn_agent.py#L295) and [here](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/dqn_agent.py#L481)
