### ISSUE TITLE
Layer Sequential has arguments in `__init__` and therefore must override `get_config`.

### ISSUE THREAD

**Issue by kelia** [tensorflow/agents#614]
The documentation states, that one should use `tf_agents.networks.Sequential` instead of `tf.keras.layers.Sequential` (I assume this should say `tf.keras.models.Sequential`) when designing preprocessing layers for an `EncodingNetwork`. 

Below shows a code excerpt to create very simple preprocessing layers for an `EncodingNetwork`:
```
preproc_encoder_layers = tfa.networks.Sequential([
             tf.keras.layers.Flatten(),
             tf.keras.layers.Dense(64, activation=None),
             tf.keras.layers.LeakyReLU(alpha=0.2)
         ])

encoder = encoding_network.EncodingNetwork(
            self.observation_spec,
            preprocessing_layers=preproc_encoder_layers,
            ....
        )
```

This results in the following error:
```
NotImplementedError: Layer Sequential has arguments in `__init__` and therefore must override `get_config`.
In call to configurable 'EncodingNetwork' (<class 'tf_agents.networks.encoding_network.EncodingNetwork'>)
```

For clarification, my model trains successfully when replacing above preprocessing layers with `tf.keras.models.Sequential` preprocessing, i.e. this works
```
preproc_encoder_layers = tf.keras.models.Sequential([
             tf.keras.layers.Flatten(),
             tf.keras.layers.Dense(64, activation=None),
             tf.keras.layers.LeakyReLU(alpha=0.2)
         ])

encoder = encoding_network.EncodingNetwork(
            self.observation_spec,
            preprocessing_layers=preproc_encoder_layers,
            ...
       )
```

The reason I'd like to switch to the recommended `tf_agents.networks.Sequential` is that `tf.keras.models.Sequential` seems to have problems when used with `PolicySaver`, as also pointed out in the documentation. 

Unfortunately, I could not find an example that used `tf_agents.networks.Sequential` as preprocessing_layers of an `EncodingNetwork`. How should `tf_agents.networks.Sequential` be used as preprocessing_layers?

**Comment by ebrevdo** [comment]
We added `get_config` in ~January.  Are you using an older version of TF-Agents?  Try the nightly (in conjunction w/ tf-nightly and tfp-nightly?)

You should also be able to use `Sequential` to *replace* the `EncodingNetwork` completely.

**Comment by kelia** [comment]
I tested with `tf-agents-nightly         0.8.0.dev20210701`, getting the same error. However, replacing the `EncodingNetwork` completely resolved the issue. Thanks a lot!
