### ISSUE TITLE
auxiliary tasks with tf agents

### ISSUE THREAD

**Issue by npqst** [tensorflow/agents#618]
Hi! 

I'm wondering how best to add a second head to, for example a DQN Agent to train an auxiliary supervised task. So far the only work I've found with tf-agents uses [custom networks to adapt to multiple inputs](https://www.tensorflow.org/agents/tutorials/8_networks_tutorial), not outputs. 

Many thanks!

**Comment by kuanghuei** [comment]
Sorry for missing this. Please see https://github.com/google-research/pisac for an example. Let us know if you have further questions.
