### ISSUE TITLE
SAC for Car Control

### ISSUE THREAD

**Issue by Bhaney44** [tensorflow/agents#63]
**Problem: How to create a simulation where a SAC algorithm controls a car to navigate an environment.**

**Goal: Create a simulation where a SAC agent controls a car in an environment.**

Generally, I familiar with deep reinforcement learning frameworks and autonomous car control. I wrote a [paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3261275) on the topic and have read a lot about the subject matter. Some important papers: [paper 1](https://arxiv.org/pdf/1807.00412.pdf), [paper 2](https://web.stanford.edu/class/psych209/Readings/MnihEtAlHassibis15NatureControlDeepRL.pdf), [paper 3](https://arxiv.org/pdf/1704.02532.pdf), [paper 4](https://ai.google/research/pubs/pub46570), [paper 5](https://arxiv.org/abs/1801.01290). However, I am struggling to develop the code for my models. Below is a list of steps I am taking to try and solve the problem. I would really appreciate any help or advice.

Steps:

**1. Pick packages**

I want to use tf.agents [SAC](https://github.com/Bhaney44/agents/tree/master/tf_agents/agents/sac). However, I may also need a package to create an environment. 

_Issues:_
I am unsure how to integrate the SAC with an environment. My thought was to use OpenAI's [CarRacing-v0](https://gym.openai.com/envs/CarRacing-v0/), but there are so many problems with the environment because of the way in which the different packages are layered and the inconsistency of action and observation spaces is complex to resolve. Indeed, as written the CarRacing-v0 environment does not work. See Issue [1267](https://github.com/openai/gym/issues/1267) and Issue [120](https://github.com/openai/spinningup/issues/120).

I looked at other environment generators like [Donkey Car](http://docs.donkeycar.com/) and [Unity](https://blogs.unity3d.com/2018/11/14/airsim-on-unity-experiment-with-autonomous-vehicle-simulation/)- but generally, I would like to work with TensorFlow because it provides the ability to create both environments and agents. Further, TensorFlow seems to be the most simple, well-tested, and mathematically sound model. Another option would be to create a new environment from scratch with TensorFlow. 

**2. Pick interface** 

Generally, there are a lot of different interfaces I have been trying. For example, the command line, Spyder, and Idle.

_Issues:_
The packages are hard to find and correct. I don't know how these different interfaces interact with my machine, nor the relation between the files and the interface. So, I get a lot of packages not found and double loading errors, which makes it difficult to move forward.

**3. Write code to develop agent.**

To do this I need to map out the objects: agent and environment. I also need to map out the agents functions for perception of its environment and decision making. I think a 3D observation space makes the most sense, however a 2D space may also suffice. A convolutional neural network would likely be the best method of perception. Essentially, the SAC would be dueling CNNs with the actor acting as the agent in a [Markov Decision Process](https://en.wikipedia.org/wiki/Markov_decision_process).  The [SAC](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/sac/sac_agent.py) would be the method of decision making and the math is [here](https://spinningup.openai.com/en/latest/algorithms/sac.html).

_Issues:_
Writing the code from scratch is difficult because I do not understand how the code and math line up. However, I think TensorFlow will allow me to develop everything I need to solve the problem. But, I want to write the code in a more simplified way. So, there would need to be a critic function and actor function working to minimize loss or maximize reward. The reward would be defined by optimal driving metrics like lane follow and speed.

**4. Run code in environment.**

_Issues:_
Integrating the agent in the environment is difficult because there are a lot of dependencies and packages, which need to work in harmony to successfully execute the code.

**Moving Forward** 
One way of figuring out how to do this may be building a dataset and asking a [BERT](https://ai.googleblog.com/2018/11/open-sourcing-bert-state-of-art-pre.html) model for help. But, I am not sure how good BERT is yet. Any advice or suggestions would be greatly appreciated. Thanks.

I also thought about making this a project rather than an issue. However, I cannot figure out how the project tab works or how to start a new project.

**Comment by egonina** [comment]
I'm sorry you're having trouble getting started with tf-agents for your application. It sounds like the main issue is setting up the required packages for you to run the code and then extend it. Has the diff that @oars suggested with using the mujoco environment (#62) not worked? What happens when you run locally from the command line?

**Comment by Bhaney44** [comment]
Hi @egonina. Thanks for your time. When I run CarRacing-v0 from the command line with the following code:

`python -m spinup.run sac --exp_name Car4 --env CarRacing-v0 --epochs 20 --data_dir /Users/brianhaney/Desktop/Gym --dt `

I get a return error:

`ValueError: could not broadcast input array from shape (96,96,3) into shape (96)`

The problem is a disconnect in the action space and observation space in the CarRacing environment. I would like to try the Mujoco environment @oars mentioned, but I cannot afford Mujoco and my 30-day free trial has already expired.

**Comment by oars** [comment]
@Bhaney44 The example I proposed in #62 is to replace the example use of Mujoco and use the car racing environment directly.

**Comment by Bhaney44** [comment]
Oh, got it. I sincerely appreciate your help. However, based on our discussions I am unable to solve or advance the problem with TensorFlow. Generally, I think my confusion is the result of inefficiencies in communication resulting from my inability to understand how to apply your advice. So, I am still not sure where to start because I do not know how to change the observation space and action space, how to find the file, or if it is even possible to successfully run the CarRacing-v0 environment.  I also found a cool way to run simulations [here](https://selfdrivingcars.mit.edu/deeptraffic/). Thanks anyway.

**Comment by sguada** [comment]
The observation and action spaces are defined [here](https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py#L121)

**Comment by Bhaney44** [comment]
Thanks @sguada, I made a [repository](https://github.com/Bhaney44/CarrRacing) the project.
