### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.linalg.linear_operator' has no attribute 'make_composite_tensor'

### ISSUE THREAD

**Issue by FatemehJalalvand** [tensorflow/agents#633]
Hello,

When I run the following codes to import tf modules, I encounter this error: "AttributeError: module 'tensorflow.python.ops.linalg.linear_operator' has no attribute 'make_composite_tensor'". Could you please let me know how I can fix this problem?

from tf_agents.environments import random_py_environment
from tf_agents.environments import tf_py_environment
from tf_agents.networks import encoding_network
from tf_agents.networks import network
from tf_agents.networks import utils
from tf_agents.specs import array_spec
from tf_agents.utils import common as common_utils
from tf_agents.utils import nest_utils
from tf_agents.environments import random_py_environment

**Comment by nicolaspi** [comment]
It is probably a mismatch between your tensorflow (<=2.5.0) and tensorflow-probability (>=0.13.0) versions. Downgrade tensorflow-probability: `pip install tensorflow-probability==0.12.2`

**Comment by FatemehJalalvand** [comment]
> pip install tensorflow-probability==0.12.2

Thanks. I tried your code but it didn't work.

**Comment by sguada** [comment]
Which versions of TF, tfp and tf_agents do you have?
