### ISSUE TITLE
Problem in installation of "sudo apt-get update" and 'imageio==2.4.0'

### ISSUE THREAD

**Issue by FatemehJalalvand** [tensorflow/agents#635]
Hi,
 I want to install the followings to use reinforce agent from TF-agent:

sudo apt-get update
sudo apt-get install -y xvfb ffmpeg
pip install 'imageio==2.4.0'

But, I get syntax error: invalid syntax. How can I fix this problem? 
Thanks.

**Comment by kuanghuei** [comment]
Do you know which line gives this error?

**Comment by FatemehJalalvand** [comment]
> Do you know which line gives this error?

The first two lines I think.
I tried !pip install imageio==2.4.0 for the third line and it worked. But, this way does not work for the other two lines.

**Comment by kuanghuei** [comment]
These lines are not TF-Agents specific. The first 2 lines are just for installing linux packages and the third line is for installing a python lib. If the first two lines run into problems, it's probably your computer environment and I don't feel like I can give a quick answer. Please refer to stackoverflow for question like this.
