### ISSUE TITLE
Custom Signature with Policy Saver

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#642]
HI Team.

I have a custom tf.policy that basically extends ActorPolicy by adding a function that runs a monte carlo tree search using the output of policy.action as its input. Something like this.

		class CustomPolicy(tf_policy.TFPolicy):
			def __init__(self)
			def _action(self, time_step, policy_state, seed):
			def _distribution(self, time_step, policy_state):
			def mcts(self, time_step: ts.TimeStep, distribution_step):

The problem is that using policy_saver.PolicySaver only these signatures are saved ('action', 'get_initial_state', 'get_train_step', 'get_metadata'). So my question is: it is possible to include a custom function and having a callable signature directly  
once policy is loaded in production with tf.saved_model.load() ????

**Comment by oars** [comment]
Yes, you can use the `register_function` or `register_concrete_function` utilities on the saver.

https://github.com/tensorflow/agents/blob/master/tf_agents/policies/policy_saver.py#L527

See the tests for an example.

https://github.com/tensorflow/agents/blob/master/tf_agents/policies/policy_saver_test.py#L992

**Comment by JCMiles** [comment]
Hi, thx for the reply but how can I use those functions if I'm using PolicySavedModelTrigger?

During its init PolicySavedModelTrigger calls self_build_saver(policy) and I get the warning telling me the function I would like to register is untraced. So practically it is ok to ignore the warning and than register the function or I should do something before?

**Comment by oars** [comment]
The trigger has a `extra_concrete_functions` param where you can pass it.

Roughly you want something like:

```
mcts_fn = common.function(policy.mcts)
batched_time_step_tensor_spec = tensor_utils.add_outer_dim(time_step_tensor_spec)
batched_distribution_step = ...?
mcts_fn.get_concrete_function(batched_time_step_tensor_spec, batched_distribution_step)
saver_trigger = triggers.PolicySavedModelTrigger(
        saved_model_dir,
        agent,
        train_step,
        interval=policy_save_interval,
        extra_concrete_functions([(mcts, mcts_fn)]))
```

**Comment by JCMiles** [comment]
ok I had a older version of tf_agents ant that param was missing. 
just updated and works fine thx.
