### ISSUE TITLE
How can I run learner and actor in parallel

### ISSUE THREAD

**Issue by diskun00** [tensorflow/agents#648]
Hello guys, 

I found this cool API learner and actor very suitable for my problem. As my observation operation is a bit time-consuming, I think it will be much more efficient to run them simultaneously. The tutorial ( [SAC minitaur with the Actor-Learner API](https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial#training_the_agent) ) seems just split the learner and actor but still execute them sequentially. Since I'm not familiar with TensorFlow and TF-Agent, it would be really nice if somebody could share scripts to run those two components in parallel.

**Comment by sguada** [comment]
Take a look at the distributed example https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/distributed/examples/sac
