### ISSUE TITLE
Normalizing advantages in PPOAgent

### ISSUE THREAD

**Issue by cedavidyang** [tensorflow/agents#651]
When using PPOAgent, I want to train the agent with one batch of experience from one episode. However, the agent is not learning. I tried to trace the problem in `ppo_agent.py`. It turns out that in the `_train(...)` method, the following code will turn my advantages all to zeros, leading to no learning for the actor net:
```python
normalized_advantages = _normalize_advantages(advantages,
                                                  variance_epsilon=1e-8)
```
This is because the `_normalize_advantages` function uses a default `axes=(0,)`. After I override this function with the default `axes=(1,)`, the agent starts to learn. I wonder if this is a bug.

**Comment by sguada** [comment]
@summer-yue can you run a few comparisons with that change, it maybe a bug. It should normalize advantages across time and across batches.

**Comment by sguada** [comment]
@cedavidyang can you also try with `axes=(0,1)`?

**Comment by cedavidyang** [comment]
@sguada `axes=(0,1)` works as well. This will normalize across both dimensions (i.e., batch and time).

**Comment by summer-yue** [comment]
Thanks for reporting! Looks like a bug to me. Should use (0,1). Let me run a few experiments and see the impact of this, and report back.

**Comment by summer-yue** [comment]
Fixed this in https://github.com/tensorflow/agents/commit/c957dea0d736c11891999344dd2c0d9926f89ff3 thank you for catching the issue!
