### ISSUE TITLE
TensorNormalizer can't normalize date type tf.float64

### ISSUE THREAD

**Issue by diskun00** [tensorflow/agents#654]
Hi there,

First thanks for this great work!

I recently use StreamingNormalizer to normalize my observation tensor, but encounter some issues with type of tf.float64. After I check the source code,  there is some instruction for tf.float64, but it seems outdated as no dtype argument in _init function. 

https://github.com/tensorflow/agents/blob/188ea7958c2f809e745ef0503a3dea0ce7c78d4a/tf_agents/utils/tensor_normalizer.py#L47-L80

There is no problem with tf.float32, but I get the following error when use tf.float64
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Sub as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Sub]
```

the error could be reproduced by
```python
  tensor_normalizer = StreamingTensorNormalizer(tf.TensorSpec([], tf.float64))
  observation_list = np.array([1, 2, 3], dtype=np.float64)
  for i, o in enumerate(observation_list):
      print(f"{i}".center(30, "-"))
      mean, var = tensor_normalizer._get_mean_var_estimates()
      normalized_value = tensor_normalizer.normalize(o)
      tensor_normalizer.update(o)
      print(f"{i}".center(30, "-"))
```

**Comment by sguada** [comment]
Not sure why using np.array and automatic conversion to tf.Tensor fails, but if you change it to
`observation_list = tf.constant([1, 2, 3], dtype=np.float64)` it works.
