### ISSUE TITLE
How to get probability vector for all actions? 

### ISSUE THREAD

**Issue by Kage18** [tensorflow/agents#659]
I'm working on Multi-Armed-Bandit problem, using LinearUCBAgent and LinearThompsonSamplingAgent but they both return a single action for an observation. What I need is the probability for all the action which I can use for ranking.
Can someone suggest how to get some kind of score for each action which could be used for ranking.

**Comment by bartokg** [comment]
Hi Kage,
You can tell the agent (actually the policy) to populate this information in the policy info. Just pass the agent the following kwarg at initializiation:
```
from tf_agents.policies import utils as policy_utilities
...
emit_policy_info=(policy_utilities.InfoFields.PREDICTED_REWARDS_MEAN,)
```

You can see the reward predictions for all arms in the corresponding field of the policy info. If you are interested, you can also populate PREDICTED_REWARDS_OPTIMISTIC for LinUCB, and PREDICTED_REWARDS_SAMPLED for LinTS.

Hope this helps!
Gabor
