### ISSUE TITLE
tf_agents.train.Actor: run method doesn't actually run an episode on the first call

### ISSUE THREAD

**Issue by sikanrong** [tensorflow/agents#661]
I have the following situation:

```
    venv = BatchedPyEnvironment(envs=[ValidationEnv(**kwargs)])

    # Load the model from our model file
    saved_policy = tf.saved_model.load(load_path)
    train_step = tf.Variable(0., trainable=False)
    actor = Actor(venv, saved_policy, train_step=train_step, episodes_per_run=1)

    actor.run() # For some reason, first call to run does nothing, only second call works
    actor.run()
```

The second call to actor.run() works as expected. The first does nothing, as far as I can tell.

Also note that I can set `episodes_per_run=2`, which also seems to work

**Comment by sikanrong** [comment]
tensorflow 2.6.0
tf-agents 0.9.0

**Comment by sikanrong** [comment]
Two weeks and nothing? Man, `tf-agents` definitely feels like someone's "20% time" project...

**Comment by sguada** [comment]
Not sure we can help you with that little information.
I will recommend you to debug it and see what happens with the environment and whether is stepping correctly on it..

**Comment by sikanrong** [comment]
Thanks for your reply. I will try to condense the issue into a small git repository so that you may reproduce it easily. Will let you know when I do. Kudos.

Sorry for giving you guys shit for not responding to my issue 😂 (on the other hand, it worked.)

**Comment by sguada** [comment]
Just to be clear, we regularly take a look at issues on GitHub, but we have many other duties, so no critical issues take some time to review. Only critical bugs or issue affecting many users get prompt attention.

I recommend taking a look at our [code of conduct](https://github.com/tensorflow/agents/blob/master/CODE_OF_CONDUCT.md)., and specifically at "Examples of unacceptable behavior by participants". Next time will close directly the issue without any response.

**Comment by sikanrong** [comment]
Next time that what, exactly? 

A user of your open-source software points out that it doesn't do what it purports to do, and then has the utter _gall_ to call you out on zero response after 15 days? Sounds like you guys have a really pragmatic approach towards community management and issue handling. Sheesh.

Next time I run into issues with `tf-agents` I'll just save myself the trouble and be inwardly frustrated until I switch to pytorch, since this was such a bloody great experience.

**Comment by sguada** [comment]
If there was no response to your issue, you could just pinged "any updates" on the issue and/or provided more details about it to make it tractable, instead of, as you said:
 >  giving you guys shit for not responding to my issue
