### ISSUE TITLE
Error when using PPOActorNetwork with a discrete action space environment 

### ISSUE THREAD

**Issue by dorli** [tensorflow/agents#664]
Hi,
I’m trying to adopt the `PPOLearner` pipeline (base on the "schulman17" [example](https://github.com/tensorflow/agents/blob/29111f4ec0505b195830cc0644938ce3091540fe/tf_agents/experimental/examples/ppo/schulman17/train_eval_lib.py)) to my custom environment, which has a discrete action space, but using `PPOActorNetwork` cause the following error:
```python
ValueError: actor_network output spec does not match action spec:
TensorSpec(shape=(1,), dtype=tf.float32, name=None)
vs.
BoundedTensorSpec(shape=(1,), dtype=tf.int32, name='action', minimum=array(0, dtype=int32), maximum=array(4, dtype=int32))
  In call to configurable 'PPOPolicy' (<class 'tf_agents.agents.ppo.ppo_policy.PPOPolicy'>)
  In call to configurable 'PPOAgent' (<class 'tf_agents.agents.ppo.ppo_agent.PPOAgent'>)
  In call to configurable 'PPOClipAgent' (<class 'tf_agents.agents.ppo.ppo_clip_agent.PPOClipAgent'>)
```

I think a similar issue has been reported in[#656](https://github.com/tensorflow/agents/issues/656).

**Code to reproduce**:
```python
import numpy as np
import tensorflow as tf
from tf_agents.specs import array_spec, tensor_spec
from tf_agents.trajectories import time_step as ts
from tf_agents.agents.ppo import ppo_actor_network, ppo_clip_agent
from tf_agents.networks import value_network


action_spec = array_spec.BoundedArraySpec(shape=(1, ), dtype=np.int32, minimum=0, maximum=4, name='action')
observation_spec = array_spec.BoundedArraySpec(shape=(20,), dtype=np.int32, minimum=0, maximum=1, name='observation')

action_tensor_spec = tensor_spec.from_spec(action_spec)
observation_tensor_spec = tensor_spec.from_spec(observation_spec)
time_step_tensor_spec = ts.time_step_spec(observation_tensor_spec)

actor_net_builder = ppo_actor_network.PPOActorNetwork()
actor_net = actor_net_builder.create_sequential_actor_net((20, 20), action_tensor_spec)

value_net = value_network.ValueNetwork(observation_tensor_spec,fc_layer_params=(20, 20), kernel_initializer=tf.keras.initializers.Orthogonal())

agent = ppo_clip_agent.PPOClipAgent(
    time_step_tensor_spec, 
    action_tensor_spec,
    actor_net=actor_net,
    value_net=value_net)
```

TensorFlow Version: 2.6.0
TF-Agents : 0.9.0

**Comment by summer-yue** [comment]
Sorry about the delay. Thanks for reporting this with a simple and reproducible example.

So first of all, PPO does work with both continuous and discrete action spaces. In theory, it should work for your problem.

Looking closer, it looks likes your `action_spec` says you're working with a discrete action space.

In the `create_sequential_actor_net` helper function, we build a `tfp.distributions.MultivariateNormalDiag` to sample actions from. Note that distribution is continuous.

The error you see is complaining that we expect the actor output to be discrete, but we actually observe a continuous output.

To fix this, you want to modify the `create_sequential_actor_net` such that it generates a discrete distribution. Hope that helps.

**Comment by dorli** [comment]
Hi @summer-yue , thank you very much for the response.
I will try to follow what you wrote and reopen it if needed.

**Comment by sibyjackgrove** [comment]
> To fix this, you want to modify the `create_sequential_actor_net` such that it generates a discrete distribution. Hope that helps.

@dorli Were you able to do this? I don't see any documentation on how `create_sequential_actor_net` can be modified.
