### ISSUE TITLE
Call policy.variables() from a saved model freezes indefinitely

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#666]
By following the example at https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/distributed

when calling collect_policy.variables() from a saved model the script freezes indefinitely without giving any error
or warning on how to investigate what's going on.

        variables = {
            reverb_variable_container.POLICY_KEY: collect_policy.variables(),
            reverb_variable_container.TRAIN_STEP_KEY: train_step
        }

Any suggestion about it?
thx

**Comment by sguada** [comment]
Can you clarify how did you save your model? and that it can be restored correctly?

**Comment by JCMiles** [comment]
Sorry for the delay. I was hospitalized for a while. The problem was the incorrect setup of the reverb port. After fixing it the update collect_policy.variables() worked fine.
