### ISSUE TITLE
py_driver constructor, question  

### ISSUE THREAD

**Issue by idigitopia** [tensorflow/agents#67]
max_steps = max_steps or 0 
    max_episodes = max_episodes or 0
    if max_steps < 1 and max_episodes < 1:
      raise ValueError(
          'Either "max_steps" or "max_episodes" should be greater than 0.')
    super(PyDriver, self).__init__(env, policy, observers)
    self._max_steps = max_steps or np.inf
    self._max_episodes = max_episodes or np.inf 

is there a scenario where  the max_stes will be assigned np.inf ? 
I could not understand the logic behind it. 

Sorry if this is too basic. :)

**Comment by sguada** [comment]
So the logic behind it is two fold:
- You need to specify at least one parameter `max_steps` or `max_episodes` so if neither of them are specified then it would raise an error.
- If only one is specified then then the other would be converted to np.inf (so it won't be a limit)

Maybe the following boolean examples help:
```
None or 0 => 0
0 or np.inf => np.inf
```

A different way to write the code would be:
```
if max_steps is None and max_episodes is None:
 raise ValueError(
'Either "max_steps" or "max_episodes" should be greater than 0.')
if max_steps is None:
  max_steps = np.inf
if max_episodes is None:
  max_episodes = np.inf
self._max_steps = max_steps
self._max_episodes = max_episodes
```

**Comment by sguada** [comment]
Re-open if needed.
