### ISSUE TITLE
m1 Mac successfully install tf-agents, but failed to import it

### ISSUE THREAD

**Issue by SubaruSpirit** [tensorflow/agents#671]
After successful installation and running of tensorflow, I tried to install the tf-agents by 

```
pip install --user 'tf-agents[reverb]'
```
It did successfully install it but gives me a warning `WARNING: tf-agents 0.5.0 does not provide the extra 'reverb'`

Then I tried to import `from tf_agents.agents.dqn import dqn_agent`, and it gives me the below error message. Please help. Would be good to have a guide on how to install tf-agents on m1 after tensorflow.

```
ImportError: dlopen(/Users/username/.local/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/username/.local/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/username/.local/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by sguada** [comment]
Try `pip install --upgrade --user 'tf-agents[reverb]'`

**Comment by SubaruSpirit** [comment]
> Try `pip install --upgrade --user 'tf-agents[reverb]'`

I've tried that, and it won't upgrade the tf-agents, still at 0.5.0, I tried force it to install 0.9.0, but it will fail to import  as a separate issue.

**Comment by SubaruSpirit** [comment]
I've tried `pip install tf-agents`, which it will install the latest version 0.10.0, but it gives me the same error message when I try to import it.

**Comment by sguada** [comment]
Try installing `reverb` first by itself if `pip install tf-agents[reverb]` doesn't work.
