### ISSUE TITLE
Check replay buffer use, resize

### ISSUE THREAD

**Issue by Spiegel-Leser** [tensorflow/agents#683]
I'm wondering if bad performance of the agents might be because the buffer size is too small.

Is there a way to check the amount of buffer used?

Is there a way to resize (enlarge) the buffer?

Edit: I found that the buffer has 0 trainable_variables (Why?) and in non_trainable_variables the last id used is 1,350,249
```
[0] = <tf.Variable 'TFUniformReplayBuffer/last_id:0' shape=() dtype=int64, numpy=1350249>
```
with a capacity of 1,000,000. If all experience should be reused, the buffer IS too small. On the other hand the oldest data overwritten was from early training stages (2 days back), the agent was dumb and the experience has already been used for training. So I guess the buffer size is ok.

Still the questions asked are of interest.

**Comment by sguada** [comment]
The capacity control the size of the Buffer, you can adjust that depending of the problem.
