### ISSUE TITLE
DQN tutorial not fit for MountainCar

### ISSUE THREAD

**Issue by gzroy** [tensorflow/agents#686]
Hi, I have tried the DQN tutorial, it works well for the CartPole, but when I change to MountainCar, it could not work, even the loss is converge, but the average return for the evaluation still keep on -200. I have adjusted the model param, gamma, epsilon_greedy, but it still can't work. Does anyone successfully use the DQN to solve the MountainCar problem?

**Comment by sguada** [comment]
MountainCar is a challenging problem for DQN, since it requires very good exploration, which epsilon-greedy, which is typical in DQN cannot handle. You may need to try Bootstrapped-DQN or other algorithms that have better exploration capabilities. See https://github.com/deepmind/bsuite

**Comment by gzroy** [comment]
> 

Thanks sguada for your kindly reply! Yes you are right that MountainCar need more good exploration. I found a simple solution to solve that, just load the environment with unlimited steps setting, for example suite_gym.load(env_name, max_episode_step=0). The default setting will limit the episode step to 200, while set it to 0 could be unlimited.
