### ISSUE TITLE
What is your plan about the Agent design and TF 2.0 ?

### ISSUE THREAD

**Issue by jrabary** [tensorflow/agents#7]
Currently, most of the algorithm available in tf_agents work in graph mode and some can be run in eager mode as well. We are trying to run PPOAgent in eager mode because we found it easier for example to set the network phase #6. 
The problem is that it is not easy and error prone to maintain the graph and the eager mode at the same time. 
Since, TF 2.0 will be by default in eager mode. Is it necessary to maintain the graph mode in tf_agents ?

**Comment by sguada** [comment]
We are working on this, currently DQNAgent can run in Eager mode, have a prototype for PPOAgent. We'll share a roadmap shortly.

**Comment by karanchahal** [comment]
Can you create a github project to track issues ?

**Comment by ebrevdo** [comment]
This should be mostly done now.  @sguada ?

**Comment by sguada** [comment]
Yeah Now TF-Agents is fully compatible with TF 2.0
