### ISSUE TITLE
Is there any agent implemented that can work with MultiBinary action space?

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/agents#702]
All the available examples use environments that have either discrete or continuous action spaces. My problem requires the agent to use a multi-binary action space. Does tf_agents support that?

**Comment by kuanghuei** [comment]
I think you can just map it to 1-d discrete space, probably the easiest way to implement.

**Comment by sibyjackgrove** [comment]
@kuanghuei  Is there any actor-network currently available in TF agents that supports an1-D discrete space?

**Comment by sguada** [comment]
PPO https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/ppo_agent.py supports 1-D discrete spaces.

**Comment by sibyjackgrove** [comment]
@sguada Thanks for the update. I will try it out.

**Comment by sibyjackgrove** [comment]
@sguada I get the error  `actor_network output spec does not match action spec` when I try 1-D discrete action space with PPO agent. I have opened #720 with the details. Any suggestion to solve this would be highly appreciated.

**Comment by MiriamJo** [comment]
Is there a reason #705 was never merged? Currently working on an agent that would benefit from a hybrid action space (Box x Discrete)

**Comment by sibyjackgrove** [comment]
@MiriamJo Here is one solution to this issue. https://github.com/tensorflow/agents/issues/656#issuecomment-1286095054

**Comment by harmomyshoes** [comment]
Does this way create too many parameters weight on class categorical, if the action space is big in high dimensions?

> I think you can just map it to 1-d discrete space, probably the easiest way to implement.
