### ISSUE TITLE
time_step.restart doesn't respect the supplied reward_spec.dtype

### ISSUE THREAD

**Issue by kubistmi** [tensorflow/agents#704]
Hey everyone!

I've been trying to implement with custom TFEnvironment and realised the [`trajectories.time_step.restart`](https://github.com/tensorflow/agents/blob/4c8d922b75b9539f3b3606547ca416a658e9cb70/tf_agents/trajectories/time_step.py#L111) always returns rewards with `dtype=tf.float32`, even when provided a `reward_spec` with a different `dtype` (e.g.`tf.float64`). 
This leads to some confusing errors (that the `reward_spec` doesn't comply with `reward` returned by the environment).

A minimal example follows:
```python
import tf_agents.trajectories.time_step as ts
from tf_agents import specs

reward_spec = specs.TensorSpec(shape=[], dtype=tf.float64, name="reward")
timestep = ts.restart(tf.random.uniform((3,2)), 3, reward_spec)

# timestep.reward.dtype = tf.float32
# so the assert fails
assert timestep.reward.dtype == reward_spec.dtype
```

While I could use `tf.float32` in `reward_spec`, I haven't found about this anywhere in the documentation and I believe the fix is not very complex.

Additionally, the other `time_step` functions have similar problem:
- `termination` and `transition` will both fail while trying to run `tf.convert_to_tensor(r, dtype=tf.float32, name='reward')`
- `truncation` will handle this correctly and return reward with the same `dtype`
```python
# OK
ts.truncation(tf.random.uniform((3,2)), tf.random.uniform((3,), dtype=tf.float64))

# ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.34264197, 0.84577005, 0.37301366])>
ts.termination(tf.random.uniform((3,2)), tf.random.uniform((3,), dtype=tf.float64))
ts.transition(tf.random.uniform((3,2)), tf.random.uniform((3,), dtype=tf.float64))

```
#### Proposed fix:

The following `else` part of the `restart` function is the one that is supposed to work with `reward_spec`, but here it is using function `_as_float32_array()`, which always creates a `float32` array.
https://github.com/tensorflow/agents/blob/4c8d922b75b9539f3b3606547ca416a658e9cb70/tf_agents/trajectories/time_step.py#L160-L167

I would propose to extend the function `_as_float32_array()` as `_as_array()`:
```python
def _as_array(a, t=np.float32):
  r = np.asarray(a, dtype=t)
  if np.isnan(np.sum(r)):
    raise ValueError('Received a time_step input that converted to a nan array.'
                     ' Did you accidentally set some input value to None?.\n'
                     'Got:\n{}'.format(a))
  return r
```
With the default `t=np.float32` it could replace `_as_float32_array` in all cases, but it would allow us to inject the `reward_spec.dtype` when it is known:
```python
  if reward_spec is None:
    reward = tf.fill(shape, _as_array(0.0), name='reward')
  else:
    reward = tf.nest.map_structure(
        # pylint: disable=g-long-lambda
        lambda r: tf.fill(tf.concat([shape, r.shape], axis=-1),
                          _as_array(0.0, r.dtype.as_numpy_dtype),
                          name='reward'), reward_spec)
```

I am happy to open a PR, but wanted to discuss the proposed changes first.

Best regards,
Michal

**Comment by sguada** [comment]
Thanks Michal, it seems that you discovered a conner case that wasn't handle properly, please go ahead and create a PR.

**Comment by kubistmi** [comment]
Sure, I have opened the PR here #707

**Comment by kubistmi** [comment]
Since PR #707 was merged, I am closing this issue.
