### ISSUE TITLE
question about 3_policies_tutorial

### ISSUE THREAD

**Issue by robinsxdgi** [tensorflow/agents#719]
Hello, 

I have a question while reading the [3_policies_tutorial.ipynb](https://github.com/tensorflow/agents/blob/master/docs/tutorials/3_policies_tutorial.ipynb).

In TensorFlow Policies, Example 2: Actor Policy (as a screenshot below), where is this **action_spec** variable (highlighted in blue) defined? Is it inherited from its parent Class, **network.Network**, but if so which part in the parent class mentioned this action_spec? (I had a hard time finding where it comes from)

![action_spec](https://user-images.githubusercontent.com/44181296/156644841-7fe0cd10-8bb7-4962-ab4c-eb3006fabcf0.jpg)

Thanks

**Comment by kbanoop** [comment]
Thanks for raising this. It looks like a typo and should be output_tensor_spec instead of action_spec. It doesn't crash because there is an action_spec defined at the global level in other cells. Please feel free to submit a PR.
