### ISSUE TITLE
PPO: Unexpected output from `actor_network`.  Expected `Distribution` objects, but saw output spec: TensorSpec(...)

### ISSUE THREAD

**Issue by PeterDomanski** [tensorflow/agents#721]
I have a related issue. If I use the ActorDistributionNetwork in actor_distribution_network.py PPO works fine (due to the latest changes in "Fully align PPO sequential network setup with the legacy actor distribution"). However, if I want to use ActorDistributionRnnNetwork I get the following error: 

Unexpected output from `actor_network`.  Expected `Distribution` objects, but saw output spec: TensorSpec(shape=(1,), dtype=tf.float32, name=None)

Is it possible, that the same changes that were done for the ActorDistributionNetwork have to be done for the ActorDistributionRnnNetwork as well to align the new sequential network's output spec is with the specified action spec?

_Originally posted by @PeterDomanski in https://github.com/tensorflow/agents/issues/720#issuecomment-1066107637_

**Comment by sibyjackgrove** [comment]
@PeterDomanski Were you able to make 1D discrete action spaces work with ActorDistributionRnnNetwork? Please let me know.

**Comment by PeterDomanski** [comment]
> @PeterDomanski Were you able to make 1D discrete action spaces work with ActorDistributionRnnNetwork? Please let me know.

Yes with tf_agents.networks.actor_distribution_rnn_network.ActorDistributionRnnNetwork it works

**Comment by sibyjackgrove** [comment]
@PeterDomanski Could you please post the code snippet you are are using. Here is the action space I am trying to to get to work:
`BoundedArraySpec(shape=(5,), dtype=dtype('int32'), name='action', minimum=0, maximum=1)`

I tried both actor_distribution_rnn_network.ActorDistributionRnnNetwork and actor_distribution_network.ActorDistributionNetwork. But both are giving me the same error:
```
ValueError: actor_network output spec does not match action spec:
TensorSpec(shape=(), dtype=tf.int32, name=None)
vs.
BoundedTensorSpec(shape=(5,), dtype=tf.int32, name='action', minimum=array(0, dtype=int32), maximum=array(1, dtype=int32))
```
I am using version 0.12.0. My full code snippet is below:

```
USE_RNN = False

if USE_RNN:
    actor_net = actor_distribution_rnn_network.ActorDistributionRnnNetwork(eval_env.observation_spec(),eval_env.action_spec(),lstm_size=(80,))
    value_net = value_rnn_network.ValueRnnNetwork(eval_env.observation_spec())
    
else:
    actor_net = actor_distribution_network.ActorDistributionNetwork(eval_env.observation_spec(),eval_env.action_spec(),)
    value_net = value_network.ValueNetwork(eval_env.observation_spec())

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
tf_agent = ppo_clip_agent.PPOClipAgent(
        eval_env.time_step_spec(),
        eval_env.action_spec(),
        optimizer,
        actor_net=actor_net,
        value_net=value_net)
tf_agent.initialize()

```

**Comment by PeterDomanski** [comment]
> @PeterDomanski Could you please post the code snippet you are are using. Here is the action space I am trying to to get to work: `BoundedArraySpec(shape=(5,), dtype=dtype('int32'), name='action', minimum=0, maximum=1)`
> 
> I tried both actor_distribution_rnn_network.ActorDistributionRnnNetwork and actor_distribution_network.ActorDistributionNetwork. But both are giving me the same error:
> 
> ```
> ValueError: actor_network output spec does not match action spec:
> TensorSpec(shape=(), dtype=tf.int32, name=None)
> vs.
> BoundedTensorSpec(shape=(5,), dtype=tf.int32, name='action', minimum=array(0, dtype=int32), maximum=array(1, dtype=int32))
> ```
> 
> I am using version 0.12.0. My full code snippet is below:
> 
> ```
> USE_RNN = False
> 
> if USE_RNN:
>     actor_net = actor_distribution_rnn_network.ActorDistributionRnnNetwork(eval_env.observation_spec(),eval_env.action_spec(),lstm_size=(80,))
>     value_net = value_rnn_network.ValueRnnNetwork(eval_env.observation_spec())
>     
> else:
>     actor_net = actor_distribution_network.ActorDistributionNetwork(eval_env.observation_spec(),eval_env.action_spec(),)
>     value_net = value_network.ValueNetwork(eval_env.observation_spec())
> 
> optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
> tf_agent = ppo_clip_agent.PPOClipAgent(
>         eval_env.time_step_spec(),
>         eval_env.action_spec(),
>         optimizer,
>         actor_net=actor_net,
>         value_net=value_net)
> tf_agent.initialize()
> ```

actor_net = tf_agents.networks.actor_distribution_rnn_network.ActorDistributionRnnNetwork(
            observation_spec,
            action_spec,
            lstm_size=(40,)
        )
        value_net = value_rnn_network.ValueRnnNetwork(
            observation_spec,
        )
        agent = ppo_agent.PPOAgent(
            time_step_spec,
            action_spec,
            optimizer=tf.keras.optimizers.Adam(),
            actor_net=actor_net,
            value_net=value_net
        )

**Comment by sibyjackgrove** [comment]
@PeterDomanski Thanks. But could you show your `action_spec `specification? My code seems to be the same as what you are using.

**Comment by PeterDomanski** [comment]
> @PeterDomanski Thanks. But could you show your `action_spec `specification? My code seems to be the same as what you are using.

BoundedTensorSpec(shape=(1,), dtype=tf.float32, name='action', minimum=array(0., dtype=float32), maximum=array(5., dtype=float32))

**Comment by sibyjackgrove** [comment]
@PeterDomanski Ok, I see the difference. You are using the 1D box space. So your datatype is float. I am using the discrete space and my data type is an integer. The 1-D box space works for me as well but my application needs to use a discrete space. So this won't work for me. Thanks anyway.

**Comment by mhdtslm** [comment]
Hi everybody
i have same problem with a complex model:
class CustomActorNetwork(network.Network):
    def __init__(self, input_tensor_spec, output_tensor_spec, name='CustomActorNetwork'):
        super(CustomActorNetwork, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name=name)
        
        self.conv1 = Conv2D(filters=32, kernel_size=(3, 3), strides=(1, 1), activation='relu')
        self.pool1 = MaxPooling2D((2, 2))
        self.conv2 = Conv2D(filters=64, kernel_size=(3, 3), strides=(1, 1), activation='relu')
        self.pool2 = MaxPooling2D((2, 2))
        self.conv3 = Conv2D(filters=128, kernel_size=(3, 3), strides=(1, 1), activation='relu')
        self.pool3 = MaxPooling2D((2, 2))
        self.reshape = Reshape((-1, 128))
        self.lstm = LSTM(512, return_sequences=False, use_bias=True)
        self.batch_norm = BatchNormalization()
        self.dense1 = [Dense(128, activation='relu') for _ in range(4)]
        self.dense2 = [Dense(64, activation='relu') for _ in range(4)]
        self.out1 = Dense(3, activation='softmax')
        self.out2 = Dense(100, activation='softmax')
        self.out3 = Dense(100, activation='softmax')
        self.out4 = Dense(30, activation='softmax')

    def call(self, observation, step_type=None, network_state=(), training=False):
        x = self.conv1(observation)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = self.conv3(x)
        x = self.pool3(x)
        x = self.reshape(x)
        x = self.lstm(x)
        x = self.batch_norm(x)
        x_out1 = self.dense1[0](x)
        x_out1 = self.dense2[0](x_out1)
        out1_logits = self.position(x_out1)
        out1_dist = tfp.distributions.Categorical(logits=out1_logits).sample()
        xc = concatenate([out1_logits, x], axis=-1)
        x_out2 = self.dense1[1](xc)
        x_out2 = self.dense2[1](x_out2)
        out2_logits = self.up_band(x_out2)
        out2_dist = tfp.distributions.Categorical(logits=out2_logits).sample()
        x_out3 = self.dense1[2](xc)
        x_out3 = self.dense2[2](x_out3)
        out3_logits = self.down_band(x_out3)
        out3_dist = tfp.distributions.Categorical(logits=out3_logits).sample()
        xc2 = concatenate([xc, out2_logits, out3_logits], axis=-1)
        x_out4 = self.dense1[3](xc2)
        x_out4 = self.dense2[3](x_out4)
        out4_logits = self.volume(x_out4)
        out4_dist = tfp.distributions.Categorical(logits=out4_logits).sample()
        return tf.stack([out1_dist, out2_dist, out3_dist, out4_dist], axis=-1), network_state
        

and my error is :
        
        Exception has occurred: ValueError
Unexpected output from `actor_network`.  Expected `Distribution` objects, but saw output spec: TensorSpec(shape=(4,), dtype=tf.int32, name=None)
  In call to configurable 'PPOPolicy' (<class 'tf_agents.agents.ppo.ppo_policy.PPOPolicy'>)
  In call to configurable 'PPOAgent' (<class 'tf_agents.agents.ppo.ppo_agent.PPOAgent'>)
ValueError: Unexpected output from `actor_network`.  Expected `Distribution` objects, but saw output spec: TensorSpec(shape=(4,), dtype=tf.int32, name=None)


        can everybody help me?
