### ISSUE TITLE
Using PPO in colab doesn't work?

### ISSUE THREAD

**Issue by zafarali** [tensorflow/agents#73]
I can't make the PPO agent work in a colab. I basically took everything from the `train_eval.py` file and pasted it into a colab.

```
!pip install tf-nightly tfp-nightly tf-agents-nightly

from absl import logging

import tensorflow as tf

from collections import namedtuple
FakeFlags = namedtuple('FakeFlags', 'root_dir master env_name replay_buffer_capacity num_environment_steps num_parallel_environments num_epochs collect_episodes_per_iteration num_eval_episodes')

FLAGS = FakeFlags(
  # Default flags for easy porting. https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v1/train_eval.py
  './', '', 'CartPole-v1', 1001, 30, 10000000, 16, 16, 16
)

from tf_agents.environments import suite_gym
from tf_agents.agents.ppo.examples.v1 import train_eval

tf.compat.v1.enable_resource_variables()
logging.set_verbosity(logging.INFO)

  
train_eval.train_eval(
      FLAGS.root_dir,
      tf_master=FLAGS.master,
      env_load_fn=suite_gym.load,
      env_name=FLAGS.env_name,
      replay_buffer_capacity=FLAGS.replay_buffer_capacity,
      num_environment_steps=FLAGS.num_environment_steps,
      num_parallel_environments=FLAGS.num_parallel_environments,
      num_epochs=FLAGS.num_epochs,
      collect_episodes_per_iteration=FLAGS.collect_episodes_per_iteration,
      num_eval_episodes=FLAGS.num_eval_episodes,
    log_interval=1,
    use_rnns=False
)
```

I see nothing printed at all.

See https://colab.research.google.com/drive/14Vdpnv9BY4JpAOQveD_HHLV-_nB2ZgU6

Is there something I'm doing wrong?

**Comment by egonina** [comment]
In the colab link above I see an error "AttributeError: 'NumpyState' object has no attribute 'episode_return'", is that the error you're seeing or is that spurious?

**Comment by zafarali** [comment]
That's from a keyboard interrupt.

I just see the spinning thing and nothing happens:

![image](https://user-images.githubusercontent.com/6295292/55873870-c9128b80-5b5e-11e9-9093-6916c1eea073.png)

**Comment by egonina** [comment]
are you able to run one of the colab tutorials? for example this dqn one; https://colab.sandbox.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/1_dqn_tutorial.ipynb 

edit: and are you able to connect to the colab runtime? (upper right where it says "Connect")

**Comment by zafarali** [comment]
Yes. DQN works.

**Comment by egonina** [comment]
I'm able to reproduce not seeing any output. I think it's an issue with the logging library not displaying the output in colab notebook, see https://github.com/tensorflow/tensorflow/issues/3047 issue. Looking further into it to see if there's a workaround

**Comment by egonina** [comment]
oh, also i think you have an error in your FakeFlags:

from collections import namedtuple
FakeFlags = namedtuple('FakeFlags', 'root_dir master env_name replay_buffer_capacity num_environment_steps num_parallel_environments num_epochs collect_episodes_per_iteration num_eval_episodes')

FLAGS = FakeFlags(
  './', '', 'CartPole-v1', 1001, 30, 10000000, 16, 16, 16
)

num_parallel_environments is set to 10000000, that will for sure slow things down :)

**Comment by zafarali** [comment]
Yes! you are right. Sorry that was really embarassing.

I am now getting the error:
`RuntimeError: tf.placeholder() is not compatible with eager execution.`
Is this code eager or not?

**Comment by zafarali** [comment]
(I was under the assumption that using tf-nightly meant that everything was eager)

**Comment by sguada** [comment]
tf-nightly is the latest version of TF 1.x, which by default is Graph, but can also run in Eager mode.

The example you're using v1 is for Graph, for Eager use examples under v2

**Comment by zafarali** [comment]
Ok. I reset my colab environment and it works now.

Thank you all!
