### ISSUE TITLE
running tf-agent on historical data and off policy evaluation

### ISSUE THREAD

**Issue by chanansh** [tensorflow/agents#743]
Hi,
It's not clear for me from the documentation how to train using historical data (aka offline-RL or warm start CMAB) and how to conduct offline policy evaluation. Does TF-agents support it?

**Comment by chanansh** [comment]
see VW for reference - https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/tutorials/off_policy_evaluation.html

**Comment by sguada** [comment]
Take a look at CQL https://github.com/tensorflow/agents/tree/master/tf_agents/examples/cql_sac
