### ISSUE TITLE
Cannot import tf_agents, get TypeError: function() got an unexpected keyword argument 'reduce_retracing'

### ISSUE THREAD

**Issue by xivarri** [tensorflow/agents#746]
As of June 5, 
`import tf_agents` 
fails with
`TypeError: function() got an unexpected keyword argument 'reduce_retracing'`

**Comment by xivarri** [comment]
Specifically, the error is within 
`from tf_agents.policies import utils as policy_utilities`
and then

```
/usr/local/lib/python3.9/dist-packages/tf_agents/utils/common.py in function(*args, **kwargs)
    140   autograph = kwargs.pop('autograph', False)
    141   reduce_retracing = kwargs.pop('reduce_retracing', True)
--> 142   return tf.function(  # allow-tf-function
    143       *args,
    144       autograph=autograph,
```

**Comment by ghost** [comment]
dose anyone know how to solve this error ?

**Comment by alexandrehsd** [comment]
I'm getting the same error message when running `from tf_agents.environments import suite_gym`. I tried to downgrade tf_agents from v0.13.0 to v0.12.1 but the error message persisted.

**Comment by sguada** [comment]
Can you try upgrading `!pip install tf_agents[reverb]`?

Which version of TF do you have installed? The error seems related to a change in TF.

**Comment by ghost** [comment]
!pip install tf-agents[reverb]

this solved my problem

**Comment by alexandrehsd** [comment]
> Can you try upgrading `!pip install tf_agents[reverb]`?
> 
> Which version of TF do you have installed? The error seems related to a change in TF.

I was using TF 2.8, then upgraded to 2.9 while running `!pip install tf_agents[reverb]` (it forced TF to upgrade). Then things worked as expected.

**Comment by xivarri** [comment]
Thanks, that does work as a temp fix.
