### ISSUE TITLE
self.steps = common.create_variable('steps', 0)

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#75]
Hello team,
in the colab example on how to build a tf_environment
you use this line to create a variable

self.steps = common.create_variable('steps', 0)

it was working perfectly until I installed tf-agents on a new machine today
and now "create_variable" is disappeared. It has been moved in other place???

**Comment by oars** [comment]
`common.create_variable` is still there:
https://github.com/tensorflow/agents/blob/master/tf_agents/utils/common.py#L109

Mind sharing a full stack trace to take a look at?

**Comment by JCMiles** [comment]
from tf_agents.utils import common
from tf_agents.environments import tf_environment

class ExampleEnv(tf_environment.TFEnvironment):
    def __init__(self, cfg, scope):
        self.step_shape   = cfg.t_shape
        self.action_shape = cfg.a_shape
        self.observation_shape = cfg.o_shape
        self.seed = self._seed(cfg.seed)
        
        super(ExampleEnv, self).__init__(
            cfg.time_step_spec, cfg.action_spec, batch_size=1)  
        
    	......

        self.steps    = common.create_variable('steps', 0)
        self.episodes = common.create_variable('episodes', 0)
        self.resets   = common.create_variable('resets', 0)

eclipse is highlighting an import error with create_variable and also TFEnvironment

**Comment by sguada** [comment]
Not sure about which error is eclipse saying.
