### ISSUE TITLE
[GSoC] add new environments to agents

### ISSUE THREAD

**Issue by talregev** [tensorflow/agents#77]
I see this video:
https://www.youtube.com/watch?v=-TTziY7EmUA&t=222s
and I register for GSoC of tensor flow:
https://summerofcode.withgoogle.com/organizations/6137730124218368/

I want to add to agates new robotic environments: 
[gym-gazebo][1]
[gym-gazebo2][2]
[gym-webots][3]

How I get started? 

[1]:https://github.com/erlerobot/gym-gazebo
[2]:https://github.com/AcutronicRobotics/gym-gazebo2
[3]:https://github.com/talregev/gym-webots

**Comment by samfishman** [comment]
Hi,

Glad to hear you're excited about the project. We already support Gym environments so using these would just require importing them in your training script (e.g. agents/dqn/examples/v2/train_eval.py) and setting env_name to whatever you would like to load.

Please reopen this issue if you have trouble getting this to work.

**Comment by talregev** [comment]
It not part of gym, it a new libraries that use gym,  ros and robotic simulators such as gazebo and webots.
need to write a code for them.

**Comment by samfishman** [comment]
Yes, but it seems the environments are exposed via the Gym interface, right?
