### ISSUE TITLE
Distributed training like SEED RL

### ISSUE THREAD

**Issue by philstahlfeld** [tensorflow/agents#771]
I have an environment that runs a simulation at every step, which makes it computationally expensive. To speed up training, I'd like to try distributing my actors across a number of different machines. Basically, I'd like to try out an architecture like [SEED RL](https://github.com/google-research/seed_rl). AFAICT, TF Agents doesn't support this (yet). The closest thing that I can find is the [Actor Learner tutorial](https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial), but that relies on the current policy being shared in memory between the Actor and Learner, which wouldn't be possible when using distributed Learners. Does TF Agents support this type of training? Is there a plan to support this type of training? 

If there isn't support now or in the near future, I was thinking about building a prototype. I see two types of communication that need to happen:

1. The Actors need to communicate the trajectories back to the Learner
2. The Learner needs to communicate the policy back to the Actors

The first can be accomplished by using Reverb and the second can be accomplished through gRPC (like SEED RL). The machine hosting the Learner would start a gRPC server that has access to the current policy. The Learners would then use a policy that proxies calls to the Learner's gRPC server. Would this type of prototype be of interest to the TF Agents team?

**Comment by sguada** [comment]
See https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/distributed for more details and see https://github.com/google-research/circuit_training for an example using TF-Agents PPO distributed learning, with 100s of Actors collecting data in different machines while the Learner uses multiple GPUs to train the model.
