### ISSUE TITLE
Support / documentation for quantization-aware training

### ISSUE THREAD

**Issue by oveddan** [tensorflow/agents#78]
Is it possible to do [quantization-aware training](https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/contrib/quantize) using the agents reinforcement learning framework? If so these models could be deployed onto the coral edge tpu accelerators. If this is possible it would be great to see an example.

**Comment by samfishman** [comment]
It should be possible to follow the instructions in the README of that package as well as the TF lite documentation. We haven't looked at doing quantization ourselves, but I'd encourage you to give it a try if you're interested. You should start with just trying to apply quantization to one of the pre-existing example training scripts, like agents/dqn/examples/v1/train_eval.py. Feel free to comment here if you run into issues.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if we need to track this actively or if you have further questions.
