### ISSUE TITLE
DDPG Parallel environment example is broken

### ISSUE THREAD

**Issue by vittorione94** [tensorflow/agents#787]
Hello,

The DDPG example is broken when using parallel envs.

I'm referring to the example: https://github.com/tensorflow/agents/blob/868f276af35c376d5c122d82a7ea4b6780b22652/tf_agents/agents/ddpg/examples/v2/train_eval.py

When passing in input a higher number of parallel envs the first issue is that tf_agents.system.multiprocessing.enable_interactive_mode() is not included in main(). Once we include that line, an error with tf_metrics comes up:

File "/Users/vittorio/anaconda3/envs/tf-agents/lib/python3.10/site-packages/tf_agents/metrics/tf_metrics.py", line 176, in call  *
        self._return_accumulator.assign(

    ValueError: Cannot assign value to variable ' Accumulator:0': Shape mismatch.The variable shape (1,), and the assigned value shape (2,) are incompatible.

Any help with this would be highly appreciated :)

Best,
-Vittorio

**Comment by coreyleveen** [comment]
Have you tried passing a `batch_size` argument to your metrics? 
Like 
```python
tf_metrics.AverageReturnMetric(batch_size=batch_size)
```

**Comment by vittorione94** [comment]
Hi thanks for the reply! I think I managed to get it to work but setting batch_size=num_parallel_environments for tf_metrics.AverageReturnMetric and tf_metrics.AverageEpisodeLengthMetric.

**Comment by vittorione94** [comment]
Marking this as closed
