### ISSUE TITLE
[Bug] The first training step of PPO takes very long to complete

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#80]
The very first training step of PPO seems to take a very long time to complete (grow more than quadratically with respect to num_epochs).

For example, I modified the following code from
https://github.com/tensorflow/agents/blob/fbc111a069dba58843417d75b9acfe074170a991/tf_agents/agents/ppo/examples/v1/train_eval.py#L286-L288
to
```
start_time = time.time()
total_loss, _ = sess.run([train_op, summary_op])
train_time += time.time() - start_time
print('train:', time.time() - start_time)
```

If I ran `python train_eval.py --env_name CartPole-v0 --num_epochs 10 --root_dir  exp1`, I got:
```
train: 5.171086311340332
train: 0.03916430473327637
train: 0.036617279052734375
train: 0.03401970863342285
train: 0.03482651710510254
```

If I ran `python train_eval.py --env_name CartPole-v0 --num_epochs 20 --root_dir  exp2`, I got:
```
train: 24.23134732246399
train: 0.062247276306152344
train: 0.0605158805847168
train: 0.06485986709594727
train: 0.0675079822540283
```

If I ran `python train_eval.py --env_name CartPole-v0 --num_epochs 40 --root_dir  exp2`, I got:
```
train: 184.3827407360077
train: 0.24522662162780762
train: 0.24355483055114746
train: 0.2152266502380371
train: 0.2042083740234375
```

I think this prevents me from 
1) increasing num_epoch to a large value
2) use a more complicated network. e.g. when I use a larger CNN base network for feature extraction and a larger observation space, the first training step sometimes take thousands of seconds. 

Any help will be greatly appreciated. Thank you so much!

**Comment by ChengshuLi** [comment]
@oars @samfishman 
I am sorry for @ you guys directly. I have been struggling with this for a while and I am wondering whether there is any update on this issue. Thank you very much for your generous help!

**Comment by bayesian** [comment]
I ran into the same problem, it is because it is doing a full eval (default 30 episodes in a single process).. 

the fix is simply change one line to

if global_step_val % eval_interval == 0 and global_step_val > 0:

**Comment by ChengshuLi** [comment]
@bayesian I tried your method, but unfortunately it didn't work for me. I have even commented out everything about eval and still get the same slow runtime. I think it is the **train_op** that takes a long time, not the eval or compute_summaries step. Thank you for your suggestion.

**Comment by ChengshuLi** [comment]
Any updates on this issue?

**Comment by Veluga** [comment]
I've been running into the same issue while training a PPO agent. I've run @ChengshuLi 's setup from the OP and get very similar behaviour for an increase in the first training step time, even if the evaluation step is commented out.

**Comment by tfboyd** [comment]
Little cleanup and issue bankruptcy. Issue is ~2 years old. I am sorry that this did not end with a solution. If you find this issue in the future please open a new one and reference this one if desired.   I see the comment on April 6th.  I wonder if anyone was using the new PPO, which we use extensively internally and is very well tested.  https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/examples/ppo  Closing as the original issue is old.
