### ISSUE TITLE
Parallel Environment didn't speed up

### ISSUE THREAD

**Issue by JiahengHu** [tensorflow/agents#81]
I tried utilizing parallel environment in my code like this: 
```
num_parallel_environments = 5
train_env = tf_py_environment.TFPyEnvironment(
           parallel_py_environment.ParallelPyEnvironment(
               [lambda: MyEnv()] * num_parallel_environments, start_serially = False, flatten = True))
```
But now I have to spend 5 times more time to collect each step comparing to the single thread version. I am running this on google colab, am I doing something wrong?

**Comment by lukepolson** [comment]
What was the solution here?
