### ISSUE TITLE
PPO Schulman's example doesn't work

### ISSUE THREAD

**Issue by grizzlybearg** [tensorflow/agents#821]
Has anyone been able to make the PPO example given by this repo to work???

Two months of making modifications have ended up fruitless.

I've tried changing drivers, replay buffers, networks, learners, nothing seems to work.

It's somewhat disappointing because  the examples for other agents work. 

If anyone has had a successful mod made with tf 2.10 or 2.11, i'd appreciate if you shared your work with me

**Comment by egonina** [comment]
Hello, our team sorry to hear about you having trouble getting the PPO example to work. Can you share specifically what is not working and any errors that you get?
