### ISSUE TITLE
import error: No module named 'tensorflow.python.platform 

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#83]
Hello 
I've created a new conda env and I've installed tf-agents-nightly, tf-nightly and tfp-nightly
as described in the installation section.

but  when I try to 
import tensorflow as tf
I get this error "No module named 'tensorflow.python.platform"  cause  platform module
is absent in tf 1.14 nightly that is the current tensorflow version installed with command 
pip install --upgrade tf-nightly

what are the current versions to be installed of
tensorflow, tf-agents and tf-probability ?

**Comment by oars** [comment]
You can look at the sample colabs and double check versions there. Currently there's an issue with `tf-nightly`. See #84 

I just re-ran it with:

`tf-nightly==1.14.1-dev20190416`
`tfp-nightly==0.7.0-dev`
`tf-agents-nightly==0.2.0.dev20190415`

Feel free to re-open if you still hit issues.
