### ISSUE TITLE
Need help and willing to pay $$ to solve this problem - Please name your price!

### ISSUE THREAD

**Issue by Robertfu89** [tensorflow/agents#833]
I have a python code edited 3 years ago (2020). It called tensorflow in reinforcement learning and it worked in 2020. However, the code is not working any more. Somehow, when I am running the code in the Jupyter-notebook, I always get some errors. I am not able to identify the root cause. Likely, this is due to that tensorflow has updated and some functions have changed.  Here is the entire code as attached.

Please feel free to contact at robertfu89@gmail.com

Thank you!

Robert
[DQN-based Scheduling_3_15_23.txt](https://github.com/tensorflow/agents/files/11158887/DQN-based.Scheduling_3_15_23.txt)

**Comment by tfboyd** [comment]
Closed, not deleted or anything but not really an issue. I can only imagine how much has changed. I would likely start with a working DQN example with today's code and then modify it with your changes.  Having handled upgrades like and harder than this I can say it might be easy or it might be a pain depending on how exact it needs to be. 

Good luck.

**Comment by Robertfu89** [comment]
Hi, Toby,

Thanks for your suggestion.

Is it possible to run this code with the downgraded version of tensorflow
in 2020?

Robert
