### ISSUE TITLE
[Suggestion] Cross-pollinate project with project Ray

### ISSUE THREAD

**Issue by jarlva** [tensorflow/agents#85]
Hi All, [Ray](https://github.com/ray-project/ray) project is "high-performance distributed execution framework. Ray comes with libraries that accelerate deep learning and reinforcement learning development." In short it's a RL-friendly framework that speed-up training, much like dask but for RL. It's also compatible with TF 2.0
I believe that cooperation between the the two projects will rip lots of fruits. Thoughts?

**Comment by oars** [comment]
@ebrevdo has looked at Ray more in detail. Unfortunately the way we have to handle distributed workflows internally makes it hard to integrate with libraries like Ray.

I think there are however several fairly lightweight integrations the community could create. Like a Ray based parallel environment for example would be great.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if we need to track this actively or if you have further questions.
