### ISSUE TITLE
tf-agents pip is no longer available

### ISSUE THREAD

**Issue by wushaobo** [tensorflow/agents#9]
I think you have noticed that there is no release available now for tf-agents pip library to install. A number of other libraries have been broken by this issue including magenta, tensor2tensor, etc. Would you consider to fix it soon or what's the plan?

**Comment by sguada** [comment]
Need to pip install tf-agents-nightly.
There will  not be a stable version for a bit.

**Comment by wushaobo** [comment]
It was quite like a smoke test that anyone who used tf-agents suddenly gets broken then realizes the right name of this library has been updated.  No doubt they have strong Continuous Integration to warn their quick responding developers to fix it, but I just feel that a compatible way may be more graceful than hustle.

**Comment by sguada** [comment]
Sorry for the hustle, we will be more careful in the future.
