### ISSUE TITLE
Per-Arm Features guide/tutorial not in site table of contents

### ISSUE THREAD

**Issue by tottenjordan** [tensorflow/agents#903]
FYI - The [Tutorial on Multi-Armed Bandits with Per-Arm Features](https://www.tensorflow.org/agents/tutorials/per_arm_bandits_tutorial) is not visible when navigating the table of contents on the TF site

I found through Github at [agents/docs/tutorials/...](https://github.com/tensorflow/agents/blob/master/docs/tutorials/per_arm_bandits_tutorial.ipynb) and selecting ` View on TensorFlow.org`

**Comment by esonghori** [comment]
Thanks for bringing it up, I just sent out the fix. It will show up in the website soon.
