### ISSUE TITLE
Unable to import a lot of dependencies due to: AttributeError: module 'tensorflow.python.ops.linalg.linear_operator_util' has no attribute 'matmul_with_broadcast' 

### ISSUE THREAD

**Issue by DaveOuds** [tensorflow/agents#91]
Yesterdays commit on tf/probability (https://github.com/tensorflow/probability/commit/ceb73fe5ed418209469b0be5f3ff919cd5ecbba2) made me unable to import a lot of dependencies including the dqn agent and q-network. 

It seems that tf agents has a lot of dependencies (aka looks pretty urgent).

Output:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-8d71e029660c> in <module>
     32 # from tf_agents.environments import trajectory
     33 # from tf_agents.metrics import metric_utils
---> 34 from tf_agents.metrics import tf_metrics
     35 from tf_agents.policies import random_tf_policy
     36 from tf_agents.replay_buffers import tf_uniform_replay_buffer

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/metrics/tf_metrics.py in <module>
     24 import tensorflow as tf
     25 
---> 26 from tf_agents.metrics import py_metrics
     27 from tf_agents.metrics import tf_metric
     28 from tf_agents.metrics import tf_py_metric

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/metrics/py_metrics.py in <module>
     25 import six
     26 
---> 27 from tf_agents.metrics import py_metric
     28 from tf_agents.utils import nest_utils
     29 from tf_agents.utils import numpy_storage

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/metrics/py_metric.py in <module>
     27 import tensorflow as tf
     28 
---> 29 from tf_agents.metrics import tf_metric
     30 from tf_agents.utils import common
     31 

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/metrics/tf_metric.py in <module>
     21 
     22 import tensorflow as tf
---> 23 from tf_agents.utils import common
     24 
     25 

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/utils/common.py in <module>
     25 import tensorflow as tf
     26 
---> 27 from tf_agents.trajectories import time_step as ts
     28 from tf_agents.utils import nest_utils
     29 

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/trajectories/time_step.py in <module>
     26 import tensorflow as tf
     27 
---> 28 from tf_agents.specs import array_spec
     29 from tf_agents.specs import tensor_spec
     30 

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/specs/__init__.py in <module>
     17 from tf_agents.specs.array_spec import ArraySpec
     18 from tf_agents.specs.array_spec import BoundedArraySpec
---> 19 from tf_agents.specs.tensor_spec import BoundedTensorSpec
     20 from tf_agents.specs.tensor_spec import TensorSpec

~/Projects/training/training/lib/python3.6/site-packages/tf_agents/specs/tensor_spec.py in <module>
     22 import numpy as np
     23 import tensorflow as tf
---> 24 import tensorflow_probability as tfp
     25 
     26 from tf_agents.specs import array_spec

~/Projects/training/training/lib/python3.6/site-packages/tensorflow_probability/__init__.py in <module>
     76 
     77 # from tensorflow_probability.google import staging  # DisableOnExport
---> 78 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     79 from tensorflow_probability.python.version import __version__
     80 # pylint: enable=g-import-not-at-top

~/Projects/training/training/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py in <module>
     20 
     21 from tensorflow_probability.python import bijectors
---> 22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2
     24 from tensorflow_probability.python import glm

~/Projects/training/training/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py in <module>
     59 from tensorflow_probability.python.distributions.kumaraswamy import Kumaraswamy
     60 from tensorflow_probability.python.distributions.laplace import Laplace
---> 61 from tensorflow_probability.python.distributions.linear_gaussian_ssm import LinearGaussianStateSpaceModel
     62 from tensorflow_probability.python.distributions.lkj import LKJ
     63 from tensorflow_probability.python.distributions.logistic import Logistic

~/Projects/training/training/lib/python3.6/site-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py in <module>
     39 # need to use `matmul_with_broadcast` throughout to ensure we support
     40 # batching.
---> 41 _matmul = linear_operator_util.matmul_with_broadcast
     42 
     43 

AttributeError: module 'tensorflow.python.ops.linalg.linear_operator_util' has no attribute 'matmul_with_broadcast'

**Comment by sguada** [comment]
Can you try using `tensorflow-probability 0.6.0`?

**Comment by oars** [comment]
Remove the pinned version of tfp-nightly in setup.py. I'm cutting a new `tf-agents` nightly that should work. And pushing the change as soon as tests pass.

**Comment by ICDI0906** [comment]
> Remove the pinned version of tfp-nightly in setup.py. I'm cutting a new `tf-agents` nightly that should work. And pushing the change as soon as tests pass.
what do you actually mean?

**Comment by oars** [comment]
That comment was a workaround for tfp  breakage. No longer required.

**Comment by insysion** [comment]
> That comment was a workaround for tfp breakage. No longer required.

We're still seeing this issue. Why was the workaround no longer required?

**Comment by Gpasquini** [comment]
I am still having this issue too.

**Comment by insysion** [comment]
@Gpasquini We solved our problem by updating to tfp 0.7 so it was compatible with tf 1.14

**Comment by kleinli2020** [comment]
tfp version =0.7 tensorflow==1.15 solved this issue
