### ISSUE TITLE
What versions of tf and tf-probability am I supposed to use for the collab examples?

### ISSUE THREAD

**Issue by llucid-97** [tensorflow/agents#92]
I tried running the DQN collab example without any changes and I run into an error with tf-probability (traceback @ bottom)

I presume this is because the version of tf-nightly and/or tfp-nightly have changed since you made these notebooks? What version should I use to get these to work?

Collab Traceback
ImportErrorTraceback (most recent call last)
<ipython-input-4-d94cd7c61173> in <module>()
     13 import tensorflow as tf
     14 
---> 15 from tf_agents.agents.dqn import dqn_agent
     16 from tf_agents.drivers import dynamic_step_driver
     17 from tf_agents.environments import suite_gym

8 frames
/usr/local/lib/python2.7/dist-packages/tf_agents/agents/__init__.py in <module>()
     15 
     16 """Module importing all agents."""
---> 17 from tf_agents.agents.ddpg.ddpg_agent import DdpgAgent
     18 from tf_agents.agents.dqn.dqn_agent import DqnAgent
     19 from tf_agents.agents.ppo.ppo_agent import PPOAgent

/usr/local/lib/python2.7/dist-packages/tf_agents/agents/ddpg/ddpg_agent.py in <module>()
     28 import tensorflow as tf
     29 
---> 30 from tf_agents.agents import tf_agent
     31 from tf_agents.policies import actor_policy
     32 from tf_agents.policies import ou_noise_policy

/usr/local/lib/python2.7/dist-packages/tf_agents/agents/tf_agent.py in <module>()
     24 import tensorflow as tf
     25 
---> 26 from tf_agents.trajectories import trajectory
     27 from tf_agents.utils import common
     28 from tf_agents.utils import nest_utils

/usr/local/lib/python2.7/dist-packages/tf_agents/trajectories/trajectory.py in <module>()
     26 import tensorflow as tf
     27 from tf_agents.trajectories import policy_step
---> 28 from tf_agents.trajectories import time_step as ts
     29 from tf_agents.utils import nest_utils
     30 

/usr/local/lib/python2.7/dist-packages/tf_agents/trajectories/time_step.py in <module>()
     26 import tensorflow as tf
     27 
---> 28 from tf_agents.specs import array_spec
     29 from tf_agents.specs import tensor_spec
     30 

/usr/local/lib/python2.7/dist-packages/tf_agents/specs/__init__.py in <module>()
     17 from tf_agents.specs.array_spec import ArraySpec
     18 from tf_agents.specs.array_spec import BoundedArraySpec
---> 19 from tf_agents.specs.tensor_spec import BoundedTensorSpec
     20 from tf_agents.specs.tensor_spec import TensorSpec

/usr/local/lib/python2.7/dist-packages/tf_agents/specs/tensor_spec.py in <module>()
     22 import numpy as np
     23 import tensorflow as tf
---> 24 import tensorflow_probability as tfp
     25 
     26 from tf_agents.specs import array_spec

/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py in <module>()
     76 
     77 # from tensorflow_probability.google import staging  # DisableOnExport
---> 78 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     79 from tensorflow_probability.python.version import __version__
     80 # pylint: enable=g-import-not-at-top

/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/__init__.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 from tensorflow_probability.python import bijectors
     22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2

ImportError: cannot import name bijectors

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by sguada** [comment]
Can you try using `tensorflow-probability 0.6.0`?

**Comment by sibyjackgrove** [comment]
I am also getting the following error in the TensorFlow probability module when running the DQN tutorial.

> AttributeErrorTraceback (most recent call last)
> <ipython-input-1-d94cd7c61173> in <module>()
>      13 import tensorflow as tf
>      14 
> ---> 15 from tf_agents.agents.dqn import dqn_agent
>      16 from tf_agents.drivers import dynamic_step_driver
>      17 from tf_agents.environments import suite_gym
> 
> 10 frames
> /usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py in <module>()
>      39 # need to use `matmul_with_broadcast` throughout to ensure we support
>      40 # batching.
> ---> 41 _matmul = linear_operator_util.matmul_with_broadcast
>      42 
>      43 
> 
> AttributeError: 'module' object has no attribute 'matmul_with_broadcast'

**Comment by oars** [comment]
Remove the pinned version of tfp-nightly in setup.py. I'm cutting a new `tf-agents` nightly that should work.
