### ISSUE TITLE
[Question] Tune/speed up training?

### ISSUE THREAD

**Issue by jarlva** [tensorflow/agents#93]
Hey everyone!
Anyone knows how we can tune/optimize the network/parameters using existing tools, such as [Ray/Tune](https://ray.readthedocs.io/en/latest/tune.html) or [Google/Adanet](https://ai.googleblog.com/2018/10/introducing-adanet-fast-and-flexible.html) or any other way to get better/faster training?

**Comment by sguada** [comment]
If you are familiar with Ray/Tune you should be able to modify any of examples and provide parameters via Tune.

To change the fc_layer_params [here](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v1/train_eval_gym.py#L68)

**Comment by jarlva** [comment]
@sguada, I was not aware that it's possible to use Ray/Tune in Agents. Thanks.
