### ISSUE TITLE
[Suggestion] Add/improve support for multi-agent environments

### ISSUE THREAD

**Issue by Lorenzo-Giardi** [tensorflow/agents#94]
Hi everyone! 
I think that it would be awesome if TF-Agents could make it easier to train multiple RL agents on some common multi-agents environments, maybe with a simple function to load the environment like with Gym's ones.
Some interesting environments are provided by OpenAI in the library "Multi-Agent Particle Environment" (https://github.com/openai/multiagent-particle-envs), which have also been used for developing and testing the MADDPG algorithm (https://github.com/openai/maddpg), that would be very nice to have in TF-Agents too!

**Comment by sguada** [comment]
As far as the environment follows OpenAI Gym API and provides the appropriate observation and action specifications, it should work. It would be up to the user to define an Agent and Networks that can handle multiple observations and actions.

**Comment by Lorenzo-Giardi** [comment]
Thank you Sguada for your answer. I realized just now that I could use `suite_gym.wrap_env()`, which gives the  ValueError "The gym space [Box(4,)] is currently not supported.", but it can be solved by removing the squared brackets from the action and observation specifications (hopefully without bad consequences).
Any chance to see agents that can handle multiple observations and actions in the future? Furthermore, if it is of general interest, I think that it would be great to have a colab notebook on the topic of multi-agent RL, given that it is quite tricky and there is little documentation available elsewhere on the web.

**Comment by karishnu** [comment]
I was trying to get the multi agent particle environment working with tf-agents too. This should do the job.

https://github.com/karishnu/tf-agents-multi-particle-envs/commit/e6d5e45e02c37ecebd73c05fcb0556e3e2b79331

@sguada  Is there a chance it could be supported officially? I could make a PR.
