### ISSUE TITLE
environment not maximizing average return

### ISSUE THREAD

**Issue by quarterpastsix** [tensorflow/agents#96]

**Comment by mattinjersey** [comment]
how to access the average return

**Comment by quarterpastsix** [comment]
@mattinjersey most agent algorithm examples track them while training and you can call them later with tensorboard :o

**Comment by mattinjersey** [comment]
true in PPO agents we have:
eval_metrics = [
      tf_metrics.AverageReturnMetric(buffer_size=num_eval_episodes),
      tf_metrics.AverageEpisodeLengthMetric(buffer_size=num_eval_episodes)
  ]
But if I have the variable train_metrics, how to readout the AverageReturnMetric

**Comment by sguada** [comment]
You can add train_metrics to TensorBoard as is done in the PPO example [here](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py#L224)

In general Metrics have a `result()` method that would give you the value of the metric.

In general debugging Environments is tricky. I would recommend trying just a RandomPolicy to get a clear baseline, also enable all the debug_summaries that we provide, that would give you a lot more information about whether the agent is learning something or not.

**Comment by quarterpastsix** [comment]
thanks for that idea, i have a random policy and it does indeed act random, but the agent is really not doing any better, so i really think it might be a wrong algorithm i'm using or something else i cant think about

**Comment by kbanoop** [comment]
Closing the issue, please reopen if you need more help.
