### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by mattinjersey** [tensorflow/agents#98]
Hello I am using PPO Agent and it does not seem to properly record data in tensorboard. So when I open the tensorboard window I dont see anything. Thanks Matt

**Comment by kbanoop** [comment]
I noticed that in the example command, the train binary uses /tmp/ppo_example as the root directory whereas the tensorboard points to /tmp/ppo. 
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py#L21

If that didnt solve the issue, can you paste the exact commands you used here. Do you see this with other agents as well?

**Comment by sguada** [comment]
Re-open if this doesn't fix it.

**Comment by mattinjersey** [comment]
yes I think it is working. Was my mistake. Thanks Matt
